"""lingo_calls.py — Called It: the lines she picks before kick-off.

She takes three before the whistle, then watches the match hunting for her
moment. When it comes, the goal push that was going out anyway carries her line
back to her. So every entry here is **what she says out loud on the sofa** at
the instant the trigger fires. Not commentary, not a caption, not a fact: a
short thing a person actually says in a living room, sayable without reading it
off the screen.

Two rules do most of the work, both from CALLED_IT_CONTRACT.md:

1. **The trigger must be resolvable.** Only kickoff, goals, half-time and
   full-time push, so only those can resolve, and within a goal the feed gives
   us side, the scorer's `players.position`, penalty, own goal and minute and
   nothing else. There are no headers here, no corners, no crosses, no
   possession and nothing about how a goal was built, because API-Football's
   event `detail` is `Normal Goal | Penalty | Own Goal | Missed Penalty` and
   that is the whole of it. `validate_calls.py` holds the closed grammar.

2. **The line must be true given only what resolved.** The trigger rule is
   mechanical and the validator enforces it; this one is a human gate. "They've
   done us on the break" resolves fine off `goal/them/Attacker` and is still
   wrong half the time it fires, because we cannot see the break. A groan is
   safe, a mechanism is not.

`band` is how often the moment arrives, not how good the line is: an offer is
always one `banker`, one `likely` and one `longshot`, so a round of three can
never all miss. `when` comes from the Overheard tag vocabulary unchanged, which
is what makes a slip fixture-aware for free; the `opp-*` tags are read off the
matchup card, so a line about the other side's forwards is only dealt in a week
when the card says that is who they are. `termId` links a call to a Lingo term
she has already met, which is the point of the whole feature.

No club names and no living people, for the same reason as everywhere else in
My Turn: this file ships inside the binary and a name goes stale the week he is
sold.
"""

CALLS = [
    # ---------------------------------------------------------------- bankers
    # The large majority of matches. One of these is in every offer, which is
    # the rule that stops a round of three from all missing.
    dict(id="someone-scores",
         line="Told you there'd be a goal in this one.",
         trigger=dict(kind="goal", side="any", scorerRole="any"),
         band="banker", when=["any"],
         situation="If anybody scores, at either end of the pitch.",
         cue="Say it as the net moves, whoever got it. Almost every match hands you this one."),
    dict(id="first-half-goal",
         line="In before the break. That changes the afternoon.",
         trigger=dict(kind="goal", side="any", minuteTo=45),
         band="banker", when=["any"]),
    dict(id="second-half-goal",
         line="A game of two halves, this one.",
         trigger=dict(kind="goal", side="any", minuteFrom=46),
         band="banker", when=["any"], termId="game-of-two-halves"),
    dict(id="goal-inside-the-hour",
         line="A goal inside the hour. This one's alive.",
         trigger=dict(kind="goal", side="any", minuteTo=60),
         band="banker", when=["any"]),
    dict(id="we-score",
         line="Get in! I said we'd get one.",
         trigger=dict(kind="goal", side="us"),
         band="banker", when=["any"],
         situation="If we score, whoever gets it.",
         cue="Say it as it goes in, before he does. It lands because you got there first."),
    dict(id="they-score",
         line="And there it is. I knew we'd let one in.",
         trigger=dict(kind="goal", side="them"),
         band="banker", when=["any"]),
    dict(id="forward-scores",
         line="That's what they pay a striker for.",
         trigger=dict(kind="goal", side="any", scorerRole="Attacker"),
         band="banker", when=["any"], termId="striker",
         situation="If a striker scores, at either end.",
         cue="Strikers get the bulk of the goals. Say it flat, like the whole thing was expected."),
    # Same moments, different week. The fixture tags are what make the slip
    # sound like it knows who we're playing.
    dict(id="derby-they-score",
         line="Against this lot. The group chat will be brutal.",
         trigger=dict(kind="goal", side="them"),
         band="banker", when=["derby"], termId="group-chat"),
    dict(id="cup-we-score",
         line="One more of those and we're into the next round.",
         trigger=dict(kind="goal", side="us"),
         band="banker", when=["cup"]),
    dict(id="europe-we-score",
         line="A goal in Europe. This is why he stays up.",
         trigger=dict(kind="goal", side="us"),
         band="banker", when=["europe"]),
    dict(id="favourites-they-score",
         line="We were supposed to be walking this. Typical.",
         trigger=dict(kind="goal", side="them"),
         band="banker", when=["favourites", "opp-bad-form"]),
    dict(id="opp-clean-sheets-we-score",
         line="They don't concede many. We've cracked them.",
         trigger=dict(kind="goal", side="us"),
         band="banker", when=["opp-clean-sheets"]),
    dict(id="good-run-we-score",
         line="There it is again. The lads cannot stop scoring.",
         trigger=dict(kind="goal", side="us"),
         band="banker", when=["good-run"], termId="the-lads",
         situation="If we score again, the way we have been lately.",
         cue="For a week when we are scoring every game. It reads as calm rather than hopeful."),
    dict(id="bad-run-they-score",
         line="Same every week at the minute. We go again.",
         trigger=dict(kind="goal", side="them"),
         band="banker", when=["bad-run"], termId="we-go-again"),

    # ----------------------------------------------------------------- likely
    dict(id="late-goal",
         line="Squeaky bum time. Somebody's heart is about to go.",
         trigger=dict(kind="goal", side="any", minuteFrom=75),
         band="likely", when=["title", "run-in"], termId="squeaky-bum-time"),
    dict(id="we-score-first-half",
         line="Before the break. I'll have that all day.",
         trigger=dict(kind="goal", side="us", minuteTo=45),
         band="likely", when=["any", "favourites"]),
    dict(id="we-score-second-half",
         line="Whatever he said at half-time has worked.",
         trigger=dict(kind="goal", side="us", minuteFrom=46),
         band="likely", when=["any", "opp-clean-sheets"], termId="half-time"),
    dict(id="they-score-first-half",
         line="Conceding before the break. Thanks for that.",
         trigger=dict(kind="goal", side="them", minuteTo=45),
         band="likely", when=["any", "opp-good-form", "opp-close-range"]),
    dict(id="they-score-second-half",
         line="Second half and we've gone to sleep again.",
         trigger=dict(kind="goal", side="them", minuteFrom=46),
         band="likely", when=["any", "bad-run"]),
    dict(id="our-forward-scores",
         line="That's why he's up front. Man of the match.",
         trigger=dict(kind="goal", side="us", scorerRole="Attacker"),
         band="likely", when=["any", "good-run"], termId="man-of-the-match",
         situation="If one of our strikers is the one who scores.",
         cue="Narrower than any goal, so it is worth more when it lands. Say it before the replay."),
    dict(id="their-forward-scores",
         line="We've given him far too much space there.",
         trigger=dict(kind="goal", side="them", scorerRole="Attacker"),
         band="likely", when=["opp-counter", "opp-close-range"]),
    dict(id="our-midfielder-scores",
         line="From midfield as well. He'll dine out on that.",
         trigger=dict(kind="goal", side="us", scorerRole="Midfielder"),
         band="likely", when=["any", "opp-long-range"]),
    dict(id="their-midfielder-scores",
         line="A midfielder's done us. That's a sore one.",
         trigger=dict(kind="goal", side="them", scorerRole="Midfielder"),
         band="likely", when=["opp-long-range", "opp-counter"]),
    dict(id="midfielder-scores-any",
         line="A midfielder off the mark. He'll not get many.",
         trigger=dict(kind="goal", side="any", scorerRole="Midfielder"),
         band="likely", when=["any", "opp-long-range"]),
    dict(id="our-defender-scores",
         line="A defender! He'll not stop going on about this.",
         trigger=dict(kind="goal", side="us", scorerRole="Defender"),
         band="likely", when=["any", "opp-set-piece"]),
    dict(id="their-defender-scores",
         line="Their defender's scored. We were warned.",
         trigger=dict(kind="goal", side="them", scorerRole="Defender"),
         band="likely", when=["opp-set-piece", "opp-aerial"]),
    dict(id="defender-scores-any",
         line="A defender's scored. Nobody saw that coming.",
         trigger=dict(kind="goal", side="any", scorerRole="Defender"),
         band="likely", when=["any", "opp-set-piece", "opp-aerial"]),
    dict(id="halftime-level",
         line="Level at half-time. Anyone's game, this.",
         trigger=dict(kind="halftime", state="level"),
         band="likely", when=["any"], termId="half-time",
         situation="If it is level when the half-time whistle goes.",
         cue="Say it on the way to the kettle, not at the telly. Half of all matches are level here."),
    dict(id="halftime-ahead",
         line="Ahead at the break. Game management from here.",
         trigger=dict(kind="halftime", state="ahead"),
         band="likely", when=["any", "favourites"], termId="game-management"),
    dict(id="halftime-behind",
         line="Behind at the break. The gaffer won't be happy.",
         trigger=dict(kind="halftime", state="behind"),
         band="likely", when=["any", "underdog"], termId="the-gaffer"),
    dict(id="halftime-clean",
         line="Nothing in at the break. Half a clean sheet.",
         trigger=dict(kind="halftime", conceded=0),
         band="likely", when=["any", "opp-aerial", "opp-bad-form"], termId="clean-sheet",
         situation="If nobody has put one past us by half-time.",
         cue="Our end has stayed quiet. Say it at the break and it sounds like you rate the back four."),
    dict(id="halftime-ahead-clean",
         line="Ahead and nothing in. Backs to the wall now.",
         trigger=dict(kind="halftime", state="ahead", conceded=0),
         band="likely", when=["europe", "underdog", "opp-good-form"], termId="backs-to-the-wall"),
    dict(id="underdog-halftime-level",
         line="Level with this lot at half-time. I'll take that.",
         trigger=dict(kind="halftime", state="level"),
         band="likely", when=["europe", "underdog", "opp-good-form"], termId="half-time"),
    dict(id="fulltime-win",
         line="Get in. Three points and I called it.",
         trigger=dict(kind="fulltime", state="win"),
         band="likely", when=["any"], termId="points",
         situation="If we are in front when the final whistle goes.",
         cue="Say it once, at the whistle. Three points is the only thing he will remember by Monday."),
    dict(id="fulltime-draw",
         line="A point's a point. We've had worse afternoons.",
         trigger=dict(kind="fulltime", state="draw"),
         band="likely", when=["any"], termId="points"),
    dict(id="fulltime-loss",
         line="Nothing to say about that. We go again.",
         trigger=dict(kind="fulltime", state="loss"),
         band="likely", when=["any", "bad-run"], termId="we-go-again"),
    dict(id="fulltime-clean-sheet",
         line="Clean sheet. That's the bit that wins you things.",
         trigger=dict(kind="fulltime", cleanSheet=True),
         band="likely", when=["any", "opp-bad-form"], termId="clean-sheet"),
    dict(id="title-fulltime-win",
         line="Three points in the run-in. That's a title race.",
         trigger=dict(kind="fulltime", state="win"),
         band="likely", when=["title", "run-in"], termId="title-race"),
    dict(id="relegation-fulltime-win",
         line="Massive, that. Proper relegation battle points.",
         trigger=dict(kind="fulltime", state="win"),
         band="likely", when=["relegation", "run-in"], termId="relegation-battle"),
    dict(id="cup-fulltime-win",
         line="Through to the next round. The magic of the cup.",
         trigger=dict(kind="fulltime", state="win"),
         band="likely", when=["cup"], termId="the-magic-of-the-cup"),
    dict(id="they-score-late",
         line="Don't bottle this now. Please.",
         trigger=dict(kind="goal", side="them", minuteFrom=80),
         band="likely", when=["title", "relegation"], termId="bottle-it"),

    # -------------------------------------------------------------- longshots
    # The fun one. A penalty, an own goal, a late winner.
    dict(id="penalty-scored",
         line="A penalty, and it's in. I said there'd be one.",
         trigger=dict(kind="goal", side="any", penalty=True),
         band="longshot", when=["any"], termId="penalty",
         situation="If a penalty is given and it is scored.",
         cue="About one match in three has one. Say it as he places the ball, before it is taken."),
    dict(id="penalty-us",
         line="Penalty, and he's buried it. Never in doubt.",
         trigger=dict(kind="goal", side="us", penalty=True),
         band="longshot", when=["any", "favourites"], termId="penalty"),
    dict(id="penalty-them",
         line="A penalty against us. Of course there is.",
         trigger=dict(kind="goal", side="them", penalty=True),
         band="longshot", when=["any", "derby"], termId="penalty"),
    dict(id="penalty-late",
         line="A penalty, this late on. I can't watch.",
         trigger=dict(kind="goal", side="any", penalty=True, minuteFrom=75),
         band="longshot", when=["cup", "derby"], termId="penalty"),
    dict(id="own-goal-us",
         line="An own goal. We'll take them any way they come.",
         trigger=dict(kind="goal", side="us", ownGoal=True),
         band="longshot", when=["any"], termId="own-goal"),
    dict(id="own-goal-them",
         line="Own goal. You cannot legislate for that.",
         trigger=dict(kind="goal", side="them", ownGoal=True),
         band="longshot", when=["any", "bad-run"], termId="own-goal",
         situation="If one of ours puts it into his own net.",
         cue="Say it while he is still working out whose it was. Nobody ever calls this one."),
    dict(id="keeper-scores",
         line="The keeper's scored. The actual goalkeeper.",
         trigger=dict(kind="goal", side="any", scorerRole="Goalkeeper"),
         band="longshot", when=["any"]),
    dict(id="late-winner-us",
         line="Fergie time. I don't believe what I've just seen.",
         trigger=dict(kind="goal", side="us", minuteFrom=88),
         band="longshot", when=["any", "run-in"], termId="fergie-time",
         situation="If we score in the last couple of minutes.",
         cue="Rare enough that he remembers you called it. Say it standing up, because you will be."),
    dict(id="goal-added-time",
         line="Added time and it's gone in. Absolute scenes.",
         trigger=dict(kind="goal", side="any", minuteFrom=90),
         band="longshot", when=["any", "run-in"], termId="added-time"),
    dict(id="they-score-added-time",
         line="Added time. They've gone and nicked one.",
         trigger=dict(kind="goal", side="them", minuteFrom=90),
         band="longshot", when=["any", "bad-run", "opp-good-form"], termId="added-time"),
    dict(id="we-score-added-time",
         line="Added time and we've nicked it. Smash and grab.",
         trigger=dict(kind="goal", side="us", minuteFrom=90),
         band="longshot", when=["cup", "underdog"], termId="smash-and-grab"),
    dict(id="goal-in-first-ten",
         line="Inside ten minutes. We've not even sat down.",
         trigger=dict(kind="goal", side="any", minuteTo=10),
         band="longshot", when=["any"],
         situation="If a goal goes in inside the first ten minutes.",
         cue="Say it before the drinks are poured. Half the fun is that nobody has settled yet."),
    dict(id="they-score-first-ten",
         line="Inside ten minutes and we're behind already.",
         trigger=dict(kind="goal", side="them", minuteTo=10),
         band="longshot", when=["any", "underdog", "opp-good-form"]),
    dict(id="our-forward-early",
         line="Forward's got us going early. Dream start.",
         trigger=dict(kind="goal", side="us", scorerRole="Attacker", minuteTo=20),
         band="longshot", when=["any", "favourites"]),
    dict(id="their-forward-late",
         line="Their forward, this late on. That's cruel.",
         trigger=dict(kind="goal", side="them", scorerRole="Attacker", minuteFrom=75),
         band="longshot", when=["relegation", "opp-counter", "opp-close-range", "opp-good-form"]),
    dict(id="comeback-win",
         line="Behind at the break. Game of two halves, that.",
         trigger=dict(kind="fulltime", comeback=True),
         band="longshot", when=["any", "good-run"], termId="game-of-two-halves"),
    dict(id="win-to-nil",
         line="Won it, clean sheet. That's a proper afternoon.",
         trigger=dict(kind="fulltime", state="win", cleanSheet=True),
         band="longshot", when=["any", "opp-bad-form"], termId="clean-sheet"),
    dict(id="nil-nil",
         line="Nil-nil. Ninety minutes of my life, that.",
         trigger=dict(kind="fulltime", state="draw", cleanSheet=True),
         band="longshot", when=["any", "opp-clean-sheets"], termId="nil-nil"),
]
