import Foundation

struct ContentItem: Identifiable, Codable {
    let id: UUID
    let teamId: String
    let type: ContentType
    let headline: String
    let body: String
    let kickoffTime: Date?
    let emotionalContext: String?
    let publishedAt: Date

    // Raw talking points — decoded differently based on type
    private let talkingPointsRaw: TalkingPointsPayload

    // Everyone's talking about — cross-team feed
    let everyoneTalking: Bool
    let everyoneTalkingHeadline: String?
    let everyoneTalkingBody: String?
    let everyoneTalkingTalkingPoints: [String]?
    let worthKnowing: Bool

    // Immersive card fields
    let immersiveHeadline: String?
    let immersiveContext: String?
    let immersiveContextFallback: String?

    // Analogy review state
    let analogyReviewed: Bool
    let analogyApproved: Bool
    let analogyAutoPublished: Bool

    /// Teams referenced in the headline or body. Drives the team-crest
    /// header on ContentDetailView — 1 crest for 1 entry, 2 crests for
    /// 2 entries, no crests for 3+ entries OR nil (legacy rows). Optional
    /// so older items decoded from cache don't break. V2.0.
    let affectedTeamIds: [String]?

    /// Goal scorers + minutes for a post-game result article (075). Reuses the
    /// live-box Scorer shape. Nil for non-result items / legacy rows.
    let scorers: [LiveMatchBrief.Scorer]?

    /// Links this content_item to a specific upcoming fixture. When set,
    /// the iOS Calendar tab uses this to navigate from a fixture row to
    /// the preview's ContentDetailView. Format:
    /// `"<team_id>:<iso-date>:<opponent-slug>"`. Used by the V2.0 WC
    /// pre-tournament preview content. nil for normal feed items.
    /// See Lesson 78.
    let previewFixtureId: String?

    /// For a pre-match preview (`previewFixtureId != nil`), the one-line
    /// favourite verdict shown as a sub-header in the detail view, e.g.
    /// "Spain are the clear favourites" (mapped deterministically from FIFA
    /// ranks by the gd-wc-preview routine). For a result item it carries the
    /// scoreline. nil for ordinary news.
    let matchResult: String?
    /// API-Football league id of the competition this card is about (migration
    /// 094). Nil on rows written before 2026-09-08 and on cards that are not
    /// about one match; the badge then falls back to the card type alone.
    let leagueId: Int?

    /// The competition, when the card records one.
    var competition: Competition? { leagueId.flatMap(Competition.init(rawValue:)) }

    /// Badge label for a cup card: "LEAGUE CUP" says more than "MATCH DAY" on a
    /// Tuesday in September, which is the whole reason the column exists. Nil
    /// for the Premier League and the World Championship, where the card type
    /// is the more useful of the two, and for rows with no competition.
    var cupBadgeLabel: String? {
        guard let competition, competition.isCup else { return nil }
        return competition.badge
    }

    /// What she needs to KNOW, as opposed to `talkingPoints` (what she can
    /// SAY). Up to three levelled cards; levels 1-2 render above Things to
    /// say, level 3 ("To impress") sits behind a +. Migration 090. Nil on
    /// every row written before 2026-09-07 and on Edge-template rows — the
    /// section hides.
    let infoCards: [InfoCard]?

    enum ContentType: String, Codable {
        case news
        case matchday
        /// Weekly forward-look generated by gd-sunday-brief routine.
        /// T2+ gated client-side and server-side. V1.1 task C2.
        case sundayBrief = "sunday_brief"
        /// Pre-match starting XI brief — fires ~60min before kickoff.
        /// Generated by gd-starting-xi cloud routine, fired by
        /// match-watcher's STARTING_XI trigger. Same render path as
        /// news/matchday (push + feed card), no tier gating beyond T1+.
        /// V2.0.
        case startingXi = "starting_xi"
    }

    enum CodingKeys: String, CodingKey {
        case id
        case teamId = "team_id"
        case type
        case headline
        case body
        case talkingPointsRaw = "talking_points"
        case kickoffTime = "kickoff_time"
        case emotionalContext = "emotional_context"
        case publishedAt = "published_at"

        // Everyone's talking about
        case everyoneTalking = "everyone_talking"
        case everyoneTalkingHeadline = "everyone_talking_headline"
        case everyoneTalkingBody = "everyone_talking_body"
        case everyoneTalkingTalkingPoints = "everyone_talking_talking_points"
        case worthKnowing = "worth_knowing"

        // Immersive card
        case immersiveHeadline = "immersive_headline"
        case immersiveContext = "immersive_context"
        case immersiveContextFallback = "immersive_context_fallback"

        // Analogy review
        case analogyReviewed = "analogy_reviewed"
        case analogyApproved = "analogy_approved"
        case analogyAutoPublished = "analogy_auto_published"

        // V2.0 team-crest header
        case affectedTeamIds = "affected_team_ids"
        case scorers = "goal_events"

        // V2.0 WC pre-tournament preview linking — see previewFixtureId
        case previewFixtureId = "preview_fixture_id"
        case matchResult = "match_result"
        case leagueId = "league_id"
        case infoCards = "info_cards"
    }

    // Custom decoder for backward compatibility with cached items missing new fields
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(UUID.self, forKey: .id)
        teamId = try container.decode(String.self, forKey: .teamId)
        type = try container.decode(ContentType.self, forKey: .type)
        headline = try container.decode(String.self, forKey: .headline)
        body = try container.decode(String.self, forKey: .body)
        talkingPointsRaw = try container.decode(TalkingPointsPayload.self, forKey: .talkingPointsRaw)
        kickoffTime = try container.decodeIfPresent(Date.self, forKey: .kickoffTime)
        emotionalContext = try container.decodeIfPresent(String.self, forKey: .emotionalContext)
        publishedAt = try container.decode(Date.self, forKey: .publishedAt)

        // New fields — all default to false/nil for backward compatibility
        everyoneTalking = (try? container.decodeIfPresent(Bool.self, forKey: .everyoneTalking)) ?? false
        everyoneTalkingHeadline = try? container.decodeIfPresent(String.self, forKey: .everyoneTalkingHeadline)
        everyoneTalkingBody = try? container.decodeIfPresent(String.self, forKey: .everyoneTalkingBody)
        everyoneTalkingTalkingPoints = try? container.decodeIfPresent([String].self, forKey: .everyoneTalkingTalkingPoints)
        worthKnowing = (try? container.decodeIfPresent(Bool.self, forKey: .worthKnowing)) ?? false
        immersiveHeadline = try? container.decodeIfPresent(String.self, forKey: .immersiveHeadline)
        immersiveContext = try? container.decodeIfPresent(String.self, forKey: .immersiveContext)
        immersiveContextFallback = try? container.decodeIfPresent(String.self, forKey: .immersiveContextFallback)
        analogyReviewed = (try? container.decodeIfPresent(Bool.self, forKey: .analogyReviewed)) ?? false
        analogyApproved = (try? container.decodeIfPresent(Bool.self, forKey: .analogyApproved)) ?? false
        analogyAutoPublished = (try? container.decodeIfPresent(Bool.self, forKey: .analogyAutoPublished)) ?? false
        affectedTeamIds = try? container.decodeIfPresent([String].self, forKey: .affectedTeamIds)
        scorers = try? container.decodeIfPresent([LiveMatchBrief.Scorer].self, forKey: .scorers)
        previewFixtureId = try? container.decodeIfPresent(String.self, forKey: .previewFixtureId)
        matchResult = try? container.decodeIfPresent(String.self, forKey: .matchResult)
        leagueId = try? container.decodeIfPresent(Int.self, forKey: .leagueId)
        // Lenient: one malformed card must not take the item down. Decode the
        // array element by element and keep what parses.
        infoCards = (try? container.decodeIfPresent([LossyInfoCard].self, forKey: .infoCards))?
            .compactMap(\.card)
            .sorted { $0.level < $1.level }
    }

    /// The context/analogy line to display on the immersive card.
    /// The AI critic screens analogies before they reach the DB — if `immersive_context`
    /// is non-null, it has passed the critic (possibly after a rewrite). Show that.
    /// Only fall back to the factual line if no analogy survived review.
    var displayContext: String? {
        if let context = immersiveContext, !context.isEmpty {
            return context
        }
        return immersiveContextFallback
    }

    var regularTalkingPoints: [String] {
        switch talkingPointsRaw {
        case .simple(let points):
            return points
        case .matchday(let data):
            return data.regular
        }
    }

    var postMatchCheatSheet: PostMatchCheatSheet? {
        guard case .matchday(let data) = talkingPointsRaw else { return nil }
        return data.postMatch
    }

    var matchdayMetadata: MatchdayMetadata? {
        guard case .matchday(let data) = talkingPointsRaw else { return nil }
        return data.metadata
    }
}

// MARK: - Info cards (what she needs to know)

/// One levelled fact card. `level` 1 = the gist, 2 = the wider picture,
/// 3 = to impress. Neutral text — the sister voice lives in talking points.
struct InfoCard: Codable, Identifiable, Hashable {
    var id: Int { level }
    let level: Int
    let title: String?
    let text: String
    /// Level 3 may carry the match it is about, so the card can draw both
    /// crests and the kickoff instead of a picture we do not have.
    let fixture: InfoFixture?

    var isToImpress: Bool { level >= 3 }
}

struct InfoFixture: Codable, Hashable {
    let home: String
    let away: String
    let homeApiId: Int?
    let awayApiId: Int?
    let kickoff: Date?
    let competition: String?

    enum CodingKeys: String, CodingKey {
        case home, away, kickoff, competition
        case homeApiId = "home_api_id"
        case awayApiId = "away_api_id"
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        home = try c.decode(String.self, forKey: .home)
        away = try c.decode(String.self, forKey: .away)
        homeApiId = try? c.decodeIfPresent(Int.self, forKey: .homeApiId)
        awayApiId = try? c.decodeIfPresent(Int.self, forKey: .awayApiId)
        competition = try? c.decodeIfPresent(String.self, forKey: .competition)
        // The routine writes ISO 8601 with or without fractional seconds; the
        // item decoder's date strategy is not applied inside nested strings
        // decoded here, so parse by hand and tolerate a bad value.
        if let raw = try? c.decodeIfPresent(String.self, forKey: .kickoff) {
            let f1 = ISO8601DateFormatter(); f1.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
            let f2 = ISO8601DateFormatter(); f2.formatOptions = [.withInternetDateTime]
            kickoff = f1.date(from: raw) ?? f2.date(from: raw)
        } else {
            kickoff = try? c.decodeIfPresent(Date.self, forKey: .kickoff)
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(home, forKey: .home)
        try c.encode(away, forKey: .away)
        try c.encodeIfPresent(homeApiId, forKey: .homeApiId)
        try c.encodeIfPresent(awayApiId, forKey: .awayApiId)
        try c.encodeIfPresent(competition, forKey: .competition)
        if let kickoff {
            let f = ISO8601DateFormatter(); f.formatOptions = [.withInternetDateTime]
            try c.encode(f.string(from: kickoff), forKey: .kickoff)
        }
    }

    /// Crest URLs follow the same CDN shape as `Team.crestURL`.
    var homeCrestURL: URL? { homeApiId.flatMap { URL(string: "https://media.api-sports.io/football/teams/\($0).png") } }
    var awayCrestURL: URL? { awayApiId.flatMap { URL(string: "https://media.api-sports.io/football/teams/\($0).png") } }
}

/// Element-level lossy wrapper: a card that fails to decode becomes nil
/// instead of failing the whole array.
private struct LossyInfoCard: Decodable {
    let card: InfoCard?
    init(from decoder: Decoder) throws {
        card = try? InfoCard(from: decoder)
    }
}

// MARK: - Hashable conformance (id-based)
//
// SwiftUI's NavigationStack requires destination values to be Hashable. Two
// items with the same id are considered the same content; comparing other
// fields would cause spurious "different" results when the same item is
// loaded twice from different sources (cache vs API).
extension ContentItem: Hashable {
    static func == (lhs: ContentItem, rhs: ContentItem) -> Bool { lhs.id == rhs.id }
    func hash(into hasher: inout Hasher) { hasher.combine(id) }
}

// MARK: - Matchday Talking Points Types

struct MatchdayTalkingPoints: Codable {
    let regular: [String]
    let postMatch: PostMatchCheatSheet
    let metadata: MatchdayMetadata

    enum CodingKeys: String, CodingKey {
        case regular
        case postMatch = "post_match"
        case metadata
    }
}

struct PostMatchCheatSheet: Codable {
    let ifTheyWin: String
    let ifTheyLose: String

    enum CodingKeys: String, CodingKey {
        case ifTheyWin = "if_they_win"
        case ifTheyLose = "if_they_lose"
    }
}

struct MatchdayMetadata: Codable {
    let preMatchMood: String
    let rivalryLevel: String

    enum CodingKeys: String, CodingKey {
        case preMatchMood = "pre_match_mood"
        case rivalryLevel = "rivalry_level"
    }
}

// MARK: - Dual-format talking_points decoder

enum TalkingPointsPayload: Codable {
    case simple([String])
    case matchday(MatchdayTalkingPoints)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        // Try decoding as matchday structured object first
        if let matchdayData = try? container.decode(MatchdayTalkingPoints.self) {
            self = .matchday(matchdayData)
            return
        }
        // Fall back to simple string array
        if let simpleArray = try? container.decode([String].self) {
            self = .simple(simpleArray)
            return
        }
        self = .simple([])
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .simple(let array):
            try container.encode(array)
        case .matchday(let data):
            try container.encode(data)
        }
    }
}

// MARK: - Player Card & Team Page models

struct PlayerCard: Identifiable, Codable {
    var id: String { playerName }
    let teamId: String?
    let playerName: String
    let position: String
    let age: Int?
    let summary: String
    let vibe: String?
    let form: String?

    enum CodingKeys: String, CodingKey {
        case teamId = "team_id"
        case playerName = "player_name"
        case position
        case age
        case summary
        case vibe
        case form
    }

    /// Empty-summary placeholder for a player whose dossier hasn't been
    /// generated yet. `PlayerCardModal` reads `summary.isEmpty` to switch
    /// to the .empty rendering branch.
    static func stub(teamId: String, playerName: String, position: String) -> PlayerCard {
        PlayerCard(
            teamId: teamId,
            playerName: playerName,
            position: position,
            age: nil,
            summary: "",
            vibe: nil,
            form: nil
        )
    }
}

// MARK: - Team Page — Versioned JSONB schema (matches Supabase team_pages.content)

struct TeamPageContent: Codable {
    let schemaVersion: Int
    let cards: TeamPageCards

    enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case cards
    }
}

struct TeamPageCards: Codable {
    let basics: BasicsCard?
    let manager: ManagerCard?
    let onesToKnow: OnesToKnowCard?
    let rivalry: RivalryCard?
    let form: FormCard?
    let season: SeasonCard?
    let nextFixture: NextFixtureCard?

    // Redesign additions
    let mood: MoodCard?
    let thisWeek: ThisWeekCard?
    let rivalryIntensity: Double?
    let postMatch: TeamPostMatchCard?
    let freshnessText: String?

    // Calendar tab + Table tab on TeamPageView (Info / Calendar / Table)
    let upcomingFixtures: [UpcomingFixture]?
    /// Recent FINISHED fixtures with scores (E1) — powers the collapsible
    /// "last games" section in the Calendar tab. Newest first.
    let recentResults: [RecentResult]?
    let standings: StandingsCard?

    enum CodingKeys: String, CodingKey {
        case basics
        case manager
        case onesToKnow = "ones_to_know"
        case rivalry
        case form
        case season
        case nextFixture = "next_fixture"
        case mood
        case thisWeek = "this_week"
        case rivalryIntensity = "rivalry_intensity"
        case postMatch = "post_match"
        case freshnessText = "freshness_text"
        case upcomingFixtures = "upcoming_fixtures"
        case recentResults = "recent_results"
        case standings
    }
}

struct BasicsCard: Codable {
    let updatedAt: String?
    let nickname: String
    /// Optional. PL clubs always have one (hand-seeded). WC countries
    /// usually have a clear national home venue (Sweden → Friends Arena,
    /// England → Wembley) but some smaller WC nations rotate venues
    /// across qualifying; for those, the field is omitted and the
    /// expanded card hides the "Home ground" row.
    let stadium: String?
    let funFact: String
    let talkingPoint: String?
    /// The three facts that place a club at a glance (2026-09-07): how long
    /// they have been in the top flight, where they finished last season,
    /// and when they last won the league. Hand-maintained in
    /// `team_pages.cards.basics`; nil for WC countries and pre-rollout rows.
    let plSince: String?
    let lastSeason: String?
    let lastTitle: String?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case nickname
        case stadium
        case funFact = "fun_fact"
        case talkingPoint = "talking_point"
        case plSince = "pl_since"
        case lastSeason = "last_season"
        case lastTitle = "last_title"
    }
}

struct ManagerCard: Codable {
    let updatedAt: String?
    let name: String
    let summary: String
    let talkingPoint: String?
    /// Optional API-Football coach headshot URL. Populated by the
    /// team-page-generator routine from the `/coachs` endpoint data. Nil
    /// during the rollout window for teams not yet regenerated; MeetManagerView
    /// falls back to a generic person icon.
    let photoURL: String?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case name
        case summary
        case talkingPoint = "talking_point"
        case photoURL = "photo_url"
    }
}

struct OnesToKnowCard: Codable {
    let updatedAt: String?
    let players: [TopPlayer]
    let talkingPoint: String?
    /// The UPCOMING opponent's own key players (copied from their team page
    /// server-side, refreshed per fixture). Rendered in the same card under
    /// a clear "their side" header so it's unmistakably the away team, not
    /// his. Nil for non-WC teams / when the next opponent has no page.
    let opponent: OpponentSide?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case players
        case talkingPoint = "talking_point"
        case opponent
    }
}

/// The away side shown inside the focal team's "Ones to know" card.
struct OpponentSide: Codable {
    let teamName: String
    let venue: String?
    let players: [TopPlayer]

    enum CodingKeys: String, CodingKey {
        case teamName = "team_name"
        case venue
        case players
    }
}

struct TopPlayer: Codable, Identifiable {
    var id: String { name }
    let name: String
    let position: String
    let oneLiner: String?
    /// Optional headshot URL. Populated by the team-page-generator routine
    /// from API-Football's player metadata. Nil during rollout window until
    /// every team_page row has been regenerated; views fall back to initials.
    let photoURL: String?

    enum CodingKeys: String, CodingKey {
        case name
        case position
        case oneLiner = "one_liner"
        case photoURL = "photo_url"
    }
}

struct RivalryCard: Codable {
    let updatedAt: String?
    let text: String
    let talkingPoint: String?
    /// The rival's name for the card headline. Before this field the view
    /// split `text` on a dash and fell back to a 50-character truncation,
    /// which is how "Coventry's fiercest rivalry is with Birmingham City, the…"
    /// became a title.
    let rival: String?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case text
        case talkingPoint = "talking_point"
        case rival
    }
}

struct FormCard: Codable {
    let updatedAt: String?
    let leaguePosition: Int
    let leaguePositionLabel: String
    let recentForm: String
    let formSummary: String
    let talkingPoint: String?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case leaguePosition = "league_position"
        case leaguePositionLabel = "league_position_label"
        case recentForm = "recent_form"
        case formSummary = "form_summary"
        case talkingPoint = "talking_point"
    }
}

struct SeasonCard: Codable {
    let updatedAt: String?
    let summary: String
    let talkingPoint: String?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case summary
        case talkingPoint = "talking_point"
    }
}

struct NextFixtureCard: Codable {
    let updatedAt: String?
    let opponent: String
    let date: String
    let venue: String
    let preview: String
    let talkingPoint: String?
    /// "League Cup (Carabao Cup), last 32" — written by team-page-generator
    /// from the fixture's own league (2026-09-08). Nil for a Premier League
    /// game, where naming the competition tells the reader nothing, and on
    /// rows written before the cups were covered.
    let competition: String?
    let leagueId: Int?
    let round: String?
    /// Deterministic pre-game verdict from FIFA ranks (B2). nil when either
    /// side's strength_rank is unknown — render nothing in that case.
    let favorite: FavoriteVerdict?

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case opponent
        case date
        case venue
        case preview
        case talkingPoint = "talking_point"
        case favorite
        case competition
        case leagueId = "league_id"
        case round
    }

    /// The competition without the sponsor parenthetical, for the narrow chip
    /// on the collapsed card: "League Cup (Carabao Cup), last 32" is a sentence
    /// and truncated to "League Cup (Caraba…" in a chip. The full prose form
    /// still reads in the expanded card's preview line.
    var competitionShort: String? {
        guard let competition, !competition.isEmpty else { return nil }
        let stripped = competition.replacingOccurrences(
            of: " *\\([^)]*\\)", with: "", options: .regularExpression)
        return stripped.isEmpty ? nil : stripped
    }
}

/// Pre-game favorite verdict carried on the Coming-up card payload.
struct FavoriteVerdict: Codable {
    let tag: String    // "likely_win" | "even" | "likely_loss"
    let label: String  // "Likely win" | "Could go either way" | "Likely loss"
}

/// One recent FINISHED fixture with the score, from this team's perspective.
/// Powers the collapsible "last games" section (E1).
struct RecentResult: Codable, Identifiable {
    var id: String { "\(date)-\(opponent)" }
    let date: String
    let opponent: String
    let venue: String        // "home" | "away"
    let teamScore: Int
    let oppScore: Int

    enum CodingKeys: String, CodingKey {
        case date, opponent, venue
        case teamScore = "team_score"
        case oppScore = "opp_score"
    }

    /// W / D / L from this team's perspective.
    var outcome: String {
        if teamScore > oppScore { return "W" }
        if teamScore < oppScore { return "L" }
        return "D"
    }
}

// MARK: - Team Page — Calendar tab (upcoming fixtures with importance)

/// One upcoming fixture with a server-generated importance rating.
/// Powers the Calendar tab on TeamPageView. The importance dots + label
/// come from team-page-generator's Claude pass using standings + form
/// context — derbies and direct top-4 / relegation collisions go 4-5,
/// mid-table league games go 2-3, friendlies / dead-rubbers go 1.
struct UpcomingFixture: Codable, Identifiable, Equatable {
    var id: String { "\(date)-\(opponent)" }
    let date: String                  // ISO 8601 kickoff datetime
    let opponent: String
    let venue: String                 // "home" | "away"
    let importanceDots: Int           // 1-5
    let importanceLabel: String       // ≤30 chars, statement form
    /// Opponent's API-Football id, for the crest. Nil on rows written
    /// before team-page-generator started emitting it (2026-09-07); the
    /// view then tries to resolve a PL club by name and otherwise shows
    /// the shield fallback.
    let opponentApiId: Int?

    enum CodingKeys: String, CodingKey {
        case date, opponent, venue
        case importanceDots = "importance_dots"
        case importanceLabel = "importance_label"
        case opponentApiId = "opponent_api_id"
    }

    var opponentCrestURL: URL? {
        if let id = opponentApiId { return URL(string: "https://media.api-sports.io/football/teams/\(id).png") }
        return Team.allCases.first {
            $0.displayName.caseInsensitiveCompare(opponent) == .orderedSame
                || $0.shortName.caseInsensitiveCompare(opponent) == .orderedSame
        }?.crestURL
    }
}

// MARK: - Team Page — Table tab (standings)

/// One row of standings. Used by both PL (20-row league table) and WC
/// (4-row group table). Populated by team-page-generator's mechanical
/// post-Claude merge from api_football_standings raw_fetch_log — no LLM
/// judgment, purely deterministic table data.
struct StandingsEntry: Codable, Identifiable, Equatable {
    /// Stable id for SwiftUI. Prefer the API-Football team id (unique
    /// across the league/group); fall back to rank for legacy rows that
    /// lack the id. Don't use plain `rank` alone — would collide if we
    /// ever render multiple groups in a single ForEach.
    var id: Int { teamIdApiFootball ?? rank }
    let rank: Int
    let teamName: String
    let teamIdApiFootball: Int?
    let played: Int
    let won: Int
    let drawn: Int
    let lost: Int
    let gf: Int
    let ga: Int
    let gd: Int
    let points: Int

    enum CodingKeys: String, CodingKey {
        case rank, played, won, drawn, lost, gf, ga, gd, points
        case teamName = "team_name"
        case teamIdApiFootball = "team_id_api_football"
    }
}

/// Standings table card. `competitionLabel` is "Premier League" for PL
/// clubs and "Group A" / "Group B" / etc. for WC countries.
struct StandingsCard: Codable, Equatable {
    let updatedAt: String?
    let competitionLabel: String
    let entries: [StandingsEntry]

    enum CodingKeys: String, CodingKey {
        case updatedAt = "updated_at"
        case competitionLabel = "competition_label"
        case entries
    }
}

// MARK: - Team Page — New card types for redesign

struct MoodCard: Codable {
    let state: MoodState
    let text: String
    enum MoodState: String, Codable { case good, bad, neutral }
}

struct ThisWeekCard: Codable {
    let text: String
    let talkingPoint: String

    enum CodingKeys: String, CodingKey {
        case text
        case talkingPoint = "talking_point"
    }
}

struct TeamPostMatchCard: Codable {
    let state: TeamPostMatchState
    let text: String
    let talkingPoint: String
    let expiresAt: String
    enum TeamPostMatchState: String, Codable { case win, loss, draw }

    enum CodingKeys: String, CodingKey {
        case state, text
        case talkingPoint = "talking_point"
        case expiresAt = "expires_at"
    }
}

struct TeamPage: Codable {
    let teamId: String?
    let content: TeamPageContent

    enum CodingKeys: String, CodingKey {
        case teamId = "team_id"
        case content
    }
}

// MARK: - Team Page Cache

struct CachedTeamPage: Codable {
    let content: TeamPageContent
    let cachedAt: Date

    var isStale: Bool {
        Date().timeIntervalSince(cachedAt) > 24 * 60 * 60
    }
}

enum TeamPageCache {
    private static func key(for teamId: String) -> String {
        "teamPage_\(teamId)"
    }

    static func load(teamId: String) -> CachedTeamPage? {
        guard let data = UserDefaults.standard.data(forKey: key(for: teamId)) else { return nil }
        return try? JSONDecoder().decode(CachedTeamPage.self, from: data)
    }

    static func save(content: TeamPageContent, teamId: String) {
        let cached = CachedTeamPage(content: content, cachedAt: Date())
        if let data = try? JSONEncoder().encode(cached) {
            UserDefaults.standard.set(data, forKey: key(for: teamId))
        }
    }

    static func clear(teamId: String) {
        UserDefaults.standard.removeObject(forKey: key(for: teamId))
    }
}
