import Foundation

/// One rolling commentary card written during a live PL match. Generated by
/// the gd-live-brief cloud routine, triggered at HT and 75' by match-watcher.
/// iOS polls live-brief-current every 60s during a live window and renders
/// the latest brief as a LiveMatchCard at the top of the feed (T2+ only).
struct LiveMatchBrief: Codable, Identifiable, Equatable {
    let id: UUID
    let teamId: String
    let matchId: String
    let headline: String
    let body: String
    /// Match minute when the trigger fired. May be nil for synthetic /
    /// test rows; live rows always have it.
    let minute: Int?
    /// Trigger label: "HT" / "75" for v1; future "goal" / "redcard" / etc.
    /// Used for display ("HT" → "HALF TIME") and analytics. May be nil for
    /// legacy rows but should always be populated by the routine going
    /// forward.
    let triggerLabel: String?
    let generatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id, minute
        case teamId = "team_id"
        case matchId = "match_id"
        case headline, body
        case triggerLabel = "trigger_label"
        case generatedAt = "generated_at"
    }

    /// Display-friendly label for the card header.
    var displayTriggerLabel: String {
        guard let label = triggerLabel else { return "LIVE" }
        switch label {
        case "HT":  return "HALF TIME"
        case "FT":  return "FULL TIME"
        case "75":  return "75 MIN"
        default:    return label.uppercased()
        }
    }
}
