import Foundation

/// One rolling commentary card written during a live PL match. Generated by
/// the gd-live-brief cloud routine, triggered at HT and 75' by match-watcher.
/// iOS polls live-brief-current every 60s during a live window and renders
/// the latest brief as a LiveMatchCard at the top of the feed (T2+ only).
struct LiveMatchBrief: Codable, Identifiable, Equatable {
    let id: UUID
    let teamId: String
    let matchId: String
    let headline: String
    let body: String
    /// Match minute when the trigger fired. May be nil for synthetic /
    /// test rows; live rows always have it.
    let minute: Int?
    /// Trigger label: "HT" / "75" for v1; future "goal" / "redcard" / etc.
    /// Used for display ("HT" → "HALF TIME") and analytics. May be nil for
    /// legacy rows but should always be populated by the routine going
    /// forward.
    let triggerLabel: String?
    let generatedAt: Date
    /// Group standings table for the live box (WC group). Nil when unavailable.
    let standings: LiveStandings?
    /// Who scored and when, chronological. Nil/empty when no goals yet.
    let scorers: [Scorer]?

    enum CodingKeys: String, CodingKey {
        case id, minute, standings, scorers
        case teamId = "team_id"
        case matchId = "match_id"
        case headline, body
        case triggerLabel = "trigger_label"
        case generatedAt = "generated_at"
    }

    /// One goal in the live box. `minute` is the pre-formatted match minute
    /// ("47'" / "45+2'"); `player` is the scorer name (or "Own goal"); `team`
    /// is the scoring side's short name. `penalty` tags a spot-kick.
    struct Scorer: Codable, Equatable, Identifiable {
        let side: String
        let team: String
        let player: String
        let minute: String
        let penalty: Bool?
        /// Optional headshot URL string (API-Football CDN), key "photo".
        /// Nil for legacy rows / players without a photo on file — synthesized
        /// Codable's decodeIfPresent-for-Optional keeps this backward and
        /// forward compatible with rows that predate this field.
        let photo: String?
        var id: String { "\(side)-\(player)-\(minute)" }

        /// Convenience URL for AsyncImage call sites.
        var photoURL: URL? {
            guard let photo else { return nil }
            return URL(string: photo)
        }
    }

    /// The group table rendered under the live score, sourced deterministically
    /// from the team page's standings card by live-brief-current.
    struct LiveStandings: Codable, Equatable {
        let competitionLabel: String
        let entries: [Row]

        enum CodingKeys: String, CodingKey {
            case competitionLabel = "competition_label"
            case entries
        }

        struct Row: Codable, Equatable, Identifiable {
            let rank: Int
            let team: String
            let played: Int
            let won: Int
            let drawn: Int
            let lost: Int
            let gd: Int
            let points: Int
            var id: Int { rank }
        }
    }

    /// Display-friendly label for the card header.
    var displayTriggerLabel: String {
        guard let label = triggerLabel else { return "LIVE" }
        switch label {
        case "HT":  return "HALF TIME"
        case "FT":  return "FULL TIME"
        case "75":  return "75 MIN"
        default:    return label.uppercased()
        }
    }
}
