-- 011_push_text.sql
-- Add push_text: a separate, lock-screen-optimized text used as the APNs
-- push body. Decouples push from the feed headline.
--
-- Why we need it: the headline is the dominant card text in the immersive
-- feed (~140-180 chars, sentence-style, may carry parenthetical name
-- explanations). When that same string was also the push body, ~67% of
-- pushes truncated mid-word on the lock screen (audited 3 of 3 most-recent
-- routine items pre-launch; 2 of 3 broke the 160-char rule). For a
-- notification-driven app, the lock-screen line IS the product impression.
--
-- push_text is short (≤90 chars), punchy, designed to read complete on
-- one or two lines without truncation. Generated by the routine alongside
-- the headline. notification-sender prefers push_text when present, falls
-- back to headline for old rows that pre-date this column.
--
-- Backfill: not strictly needed. Old rows won't trigger pushes again, and
-- if they did, headline fallback still works.

ALTER TABLE content_items
ADD COLUMN push_text TEXT
CHECK (push_text IS NULL OR length(push_text) <= 100);

COMMENT ON COLUMN content_items.push_text IS
  'Lock-screen push notification body. ≤90 chars target, ≤100 hard limit. NULL for legacy rows; notification-sender falls back to headline.';
