-- 023_team_insider_items.sql
-- v1.1 Insider card (V1.1_FEATURE_BUNDLE.md task C1)
--
-- Niche stats, history, anecdotes, and oddities about his team that she can
-- use to outflank him in conversation. One new row per team per day,
-- generated by the gd-insider cloud routine (separate registration, see
-- claude.ai/code/routines). Tier-gated to T2+ on iOS.
--
-- Append-only model: each generation creates a new row with a fresh
-- published_at. The iOS client reads the most recent N rows per team. No
-- trimming for now — the table grows ~20 rows/day across all teams; we can
-- add a retention sweep later if needed.

CREATE TABLE team_insider_items (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id       TEXT NOT NULL REFERENCES teams(id),
    type          TEXT NOT NULL CHECK (type IN ('stat', 'anecdote', 'history', 'oddity')),
    title         TEXT NOT NULL,   -- one-line hook, sentence case
    body          TEXT NOT NULL,   -- the explanation / story body
    source_url    TEXT,            -- optional source link for fact-check trail
    published_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index serves the iOS read pattern: "give me this team's most recent N
-- insider items, newest first." Without this, large fan-out queries on
-- popular teams scan the whole table.
CREATE INDEX idx_team_insider_team_published
    ON team_insider_items (team_id, published_at DESC);

-- RLS: read-only public access via the anon/publishable key, writes only
-- via the service-role key. Matches team_pages / team_season_state.
ALTER TABLE team_insider_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "team_insider_items is publicly readable"
    ON team_insider_items
    FOR SELECT
    USING (true);

-- No pg_cron job here. Generation runs as the gd-insider cloud routine
-- (Claude Code, scheduled via claude.ai/code/routines, daily). Same pattern
-- as gd-season-state — we burned by Haiku-via-Edge-Function on A1 and
-- migrated to cloud routine + Sonnet + hard validators in the post script.
-- If we ever fall back to the Edge Function path, schedule the cron in a
-- follow-up migration using the get_cron_service_key() accessor pattern.
