-- 024_add_sunday_brief_type.sql
-- v1.1 Sunday Brief (V1.1_FEATURE_BUNDLE.md task C2)
--
-- Extends the content_items.type CHECK constraint to accept the new
-- 'sunday_brief' value. Sunday Briefs are forward-looking weekly recap +
-- preview cards generated by the gd-sunday-brief cloud routine every
-- Sunday morning. Live alongside news + matchday in the same table;
-- tier filtering (T2+ only) is enforced client-side in iOS and
-- server-side in notification-sender.
--
-- Idempotent: DROPS the existing check first so re-applying the
-- migration in dev doesn't trip an "already exists" error.

ALTER TABLE content_items DROP CONSTRAINT IF EXISTS content_items_type_check;
ALTER TABLE content_items ADD CONSTRAINT content_items_type_check
    CHECK (type IN ('news', 'matchday', 'sunday_brief'));
