// _shared/goal-push-copy.ts
//
// Copy pools for the WC live pushes (goal / half-time / full-time). Each
// event-and-perspective bucket holds 40 variants; goal-push.ts picks one at
// fire-time so the same line never repeats across a long tournament. Kept apart
// from goal-push.ts so the logic file stays readable and the copy is easy to
// edit in bulk.
//
// Placeholders, filled by goal-push.ts:
//   {flag}  scorer's flag emoji        (goal pools only)
//   {team}  scorer's short name        (goal pools); follower's own team (HT/FT)
//   {score} scoreline. GOAL pools: home-away (matches the title). HT/FT pools:
//           follower-first ("their team first"), e.g. a 0-2 trailer sees "0-2".
//   {home} {away}  short names         (GOAL_BOTH only)
//
// House rules baked into every line:
//   - NO em-dashes or en-dashes (campaign rule). Hyphens in "half-time" /
//     "full-time" and in scorelines are fine.
//   - Rendered worst-case (longest names + tag-flag + two-digit score) stays
//     <=90 chars. Enforced by the sweep in goal-push.test.ts.
//   - Voice: gf-to-bf older-sister, dry and warm. Scorer/win celebrates with a
//     varied "text him" nudge; conceder/loss is muted and kind; level/draw is
//     neutral; HT-behind is hopeful. Some lines carry no nudge so 40 never feel
//     formulaic.

// ============================================================
// GOAL pools. {flag}/{team} = the SCORER. {score} = home-away.
// ============================================================

export const GOAL_SCORED: readonly string[] = [
  "{flag} {team} score! {score}. He's buzzing, good moment to text him.",
  "Get in! {team} make it {score}. He'll be off his seat right now.",
  "{flag} Goal for {team}! {score}. Perfect time to send him a message.",
  "{team} score, {score}! He's celebrating. Drop him a quick text.",
  "Yes! {team} on the board, {score}. He loves that you're following this.",
  "{flag} {team} find the net! {score}. He's made up. Say something nice.",
  "Goal! {team} lead the way at {score}. Text him before the replay ends.",
  "{team} score! {score}. That's the one he wanted. He'll be grinning.",
  "Big moment, {team} go {score}! He's shouting at the telly. Join in.",
  "{flag} They've done it! {team} score, {score}. Good time to check in.",
  "Goal {team}! {score}. He's buzzing right now, send him a heart.",
  "{team} strike! {score} and he is loving life. Drop him a line.",
  "Get in there! {team} make it {score}. He'll want to talk about this.",
  "{flag} {team} score, {score}! Pure joy on his end. Text away.",
  "Goal! {team} edge ahead, {score}. He'll remember you asked.",
  "{team} score! {score}. He's celebrating like he scored it himself.",
  "{flag} What a moment, {team} go {score}! Send him a quick well done.",
  "{team} on the scoresheet, {score}! He's thrilled. Good time to message.",
  "Goal for {team}! {score}. He's punching the air. Drop him a text.",
  "{flag} {team} score! {score}. He's over the moon, say hi.",
  "They've scored! {team} lead {score}. He's glued to it, text him.",
  "{team} find a goal, {score}! He's buzzing. Perfect time to reach out.",
  "Goal! {team} make it {score}. He's having the best time right now.",
  "{flag} {team} score, {score}! He'll be telling everyone. Tell him too.",
  "Get in! {team} go {score}. He is delighted, send him something.",
  "{team} score! {score}. That'll have him grinning ear to ear.",
  "{flag} Goal, {team}! {score}. He's loving this. Good time to text.",
  "{team} strike, {score}! He'll be celebrating for a while yet.",
  "Goal! {team} ahead at {score}. He'll want to share this, beat him to it.",
  "{flag} {team} score, {score}! He is buzzing. Drop him a message.",
  "They've done it, {team} {score}! He's thrilled. Say something kind.",
  "Goal for {team}! {score}. He's on cloud nine, good time to check in.",
  "{flag} {team} net one, {score}! He'll be celebrating. Join him.",
  "{team} score! {score}. He couldn't be happier. Text him now.",
  "Get in! {team} make it {score}. He's living for this. Reach out.",
  "{flag} Goal! {team} go {score}. He's buzzing, send him a quick line.",
  "{team} score, {score}! He'll be beaming. Perfect time to message him.",
  "They've scored! {team} {score}. He is over the moon, text him.",
  "{flag} {team} find the net, {score}! He's made up. Say well played.",
  "Goal! {team} lead {score}. He's having a moment. Good time to text.",
];

export const GOAL_CONCEDED: readonly string[] = [
  "{flag} {team} score. {score}. He won't be happy, give him a minute.",
  "Tough one, {team} make it {score}. He'll be quiet for a bit.",
  "{team} have scored, {score}. Not his moment. Maybe leave him be.",
  "{flag} {team} go {score}. He'll be frustrated, a kind word helps.",
  "They've conceded. {team} {score}. He'll need a second, be gentle.",
  "{team} score, {score}. He's gutted. Now's a good time to be soft.",
  "{flag} Goal for {team}, {score}. Not what he wanted. Go easy on him.",
  "{team} make it {score}. He'll be muttering at the telly. Let him.",
  "Ouch, {team} score. {score}. He's deflated, a little support goes far.",
  "{flag} {team} on top, {score}. He'll be tense. Maybe just check in.",
  "They've gone behind. {team} {score}. He'll need a moment, be kind.",
  "{team} score, {score}. He's not loving this. A gentle text helps.",
  "{flag} {team} ahead now, {score}. He'll be stressed, go softly.",
  "Tough watch. {team} {score}. He'll be frustrated, give him space.",
  "{team} find a goal, {score}. He's quiet. Not the teasing time.",
  "{flag} {team} score, {score}. He'll be down. A kind word means a lot.",
  "Not great, {team} go {score}. He'll be on edge. Be patient with him.",
  "{team} have scored, {score}. He'll need a minute before he talks.",
  "{flag} {team} make it {score}. He's gutted, save the jokes for later.",
  "They've conceded again, {score}. Soft and supportive wins here.",
  "{team} score, {score}. He'll be sighing at the screen. Go gentle.",
  "{flag} {team} on the board, {score}. Not his night so far, be kind.",
  "Rough one, {team} {score}. He'll be frustrated, a little warmth helps.",
  "{team} score, {score}. He's deflated. Maybe just send a heart.",
  "{flag} {team} ahead, {score}. He'll be quiet. Don't poke the bear yet.",
  "They've gone behind, {score}. He'll need a sec. Be the calm one.",
  "{team} make it {score}. He's not happy, a gentle check-in lands well.",
  "{flag} Goal {team}, {score}. He'll be tense, keep it soft for now.",
  "Tough, {team} score {score}. He'll want a minute. Give it to him.",
  "{team} on top at {score}. He's frustrated. A kind message helps.",
  "{flag} {team} score, {score}. Not his moment. Be patient and warm.",
  "They've conceded, {score}. He'll be quiet, now's a time to be soft.",
  "{team} go {score}. He's gutted. Hold the teasing, send support.",
  "{flag} {team} make it {score}. He'll be on edge. Go easy tonight.",
  "Ouch. {team} score, {score}. He'll need a beat before he chats.",
  "{team} ahead, {score}. He's deflated. A gentle word does wonders.",
  "{flag} {team} score, {score}. Tough one for him. Be the kind voice.",
  "They've gone behind, {team} {score}. He'll be frustrated. Stay soft.",
  "{team} make it {score}. Not what he hoped. Check he's okay.",
  "{flag} {team} score, {score}. He's quiet now. A little warmth helps.",
];

export const GOAL_BOTH: readonly string[] = [
  "It's {score} between {home} and {away}. Goals flying in!",
  "End to end stuff, {home} and {away} at {score}. Chaos!",
  "{score}! {home} and {away} are trading goals. What a game.",
  "Both teams scoring, {score}. {home} vs {away} is wide open.",
  "Goals galore! {home} {score} {away}. This one's a thriller.",
  "{score} and counting. {home} and {away} can't stop scoring.",
  "What a match, {home} {score} {away}. Goals at both ends.",
  "It's {score}! {home} and {away} are putting on a show.",
  "Mad game. {home} {score} {away}. Neither side wants to defend.",
  "Goals flying in, {score}. {home} and {away} are going for it.",
  "{score}! End to end between {home} and {away}. Edge of your seat.",
  "Both nets bulging, {home} {score} {away}. Proper entertainment.",
  "It's basketball out there, {score}. {home} and {away} trading blows.",
  "{home} {score} {away} and the goals keep coming. What a watch.",
  "Wild one, {score}! {home} and {away} both finding the net.",
  "Goals everywhere, {home} {score} {away}. This game has it all.",
  "{score} already! {home} and {away} are not holding back.",
  "Trading goals, {home} {score} {away}. Hope his heart can take it.",
  "It's {score}! Defences optional in {home} vs {away}.",
  "Helter skelter, {home} {score} {away}. Goals at a rate of knots.",
  "{score} and rising. {home} and {away} are putting on a clinic.",
  "Both teams at it, {score}. {home} vs {away} is pure chaos.",
  "Goal fest! {home} {score} {away}. He'll be loving this one.",
  "It's {score}! {home} and {away} keep answering each other.",
  "What a spectacle, {home} {score} {away}. Goals galore.",
  "{score}! Neither {home} nor {away} can stop scoring tonight.",
  "End to end again, {home} {score} {away}. Breathless stuff.",
  "Goals raining down, {score}. {home} and {away} both on it.",
  "It's a shootout, {home} {score} {away}. Edge of the sofa time.",
  "{score} and open as you like. {home} vs {away} is bonkers.",
  "Both finding the net, {home} {score} {away}. Some game this.",
  "Goals, goals, goals. {home} {score} {away}. He's glued to it.",
  "It's {score}! {home} and {away} have thrown the script away.",
  "Frantic stuff, {home} {score} {away}. Goals flowing both ways.",
  "{score}! Toe to toe, {home} and {away}. What a contest.",
  "Both teams firing, {home} {score} {away}. Tell him not to blink.",
  "It's wild, {score}. {home} and {away} trading punches.",
  "Goals everywhere you look, {home} {score} {away}. Brilliant.",
  "{score} and end to end. {home} vs {away} is a proper watch.",
  "Madness, {home} {score} {away}. Both nets getting plenty of action.",
];

// ============================================================
// HALF-TIME pools. {score} = follower-first. {team} = follower's team.
// ============================================================

export const HT_AHEAD: readonly string[] = [
  "Up {score} at the break. He's enjoying this one.",
  "{score} ahead at half-time. He'll be pleased but won't relax yet.",
  "Leading {score} at the break. Half a game to go, he knows it.",
  "Half-time, up {score}. He'll be happy. Good moment to text him.",
  "{score} to the good at the break. He's smiling, say something nice.",
  "Ahead {score} at half. He'll be cautiously buzzing. Drop him a line.",
  "Up {score} at the whistle. He's in a good mood, text away.",
  "Half-time and he's {score} up. He'll take that, still 45 to play.",
  "{score} lead at the break. He's pleased. Worth a quick message.",
  "In front {score} at half. He'll be hopeful but nervy. Check in.",
  "Up {score} at the break. So far so good, he'll be quietly happy.",
  "Half-time, {score} ahead. He's enjoying it. Good time to say hi.",
  "{score} up at the interval. He'll be pleased. Send him a heart.",
  "Leading {score} at half. He knows it's not over, but he's smiling.",
  "Ahead {score} at the break. He'll be in good spirits, text him.",
  "Up {score} at half-time. He'll be happy, just don't jinx it.",
  "{score} to the good at half. He's enjoying the ride. Drop a line.",
  "Half-time, in front {score}. He'll be pleased as punch. Say hi.",
  "Up {score} at the break. He'll be cautiously optimistic. Check in.",
  "{score} ahead at half. He's having a good time. Good moment to text.",
  "Leading {score} at the whistle. He'll be smiling. Send him something.",
  "Half-time and {score} up. He'll be happy but watching the clock.",
  "In front {score} at the break. He's pleased. Worth a quick text.",
  "Up {score} at half. So far so good for him. Drop him a message.",
  "{score} lead at the interval. He'll be enjoying this. Say well done.",
  "Ahead {score} at half-time. He's in a good place. Text him.",
  "Up {score} at the break. He'll be quietly chuffed. Check in.",
  "Half-time, {score} in front. He'll take that. Good time to say hi.",
  "{score} up at the break. He's smiling at the telly. Drop him a line.",
  "Leading {score} at half. He'll be hopeful. Send him a quick text.",
  "In front {score} at the whistle. He's enjoying it. Say something kind.",
  "Up {score} at half-time. He'll be pleased. Just don't mention jinxes.",
  "{score} ahead at the break. He's having a good half. Text him.",
  "Half-time and he's {score} up. He'll be happy, 45 to hold on.",
  "Up {score} at half. He's in good spirits. Good moment to reach out.",
  "{score} to the good at the break. He'll be smiling. Send a heart.",
  "Leading {score} at half-time. He's enjoying this. Drop him a line.",
  "In front {score} at the break. He'll be pleased. A quick text works.",
  "Up {score} at half. He's cautiously buzzing. Say hi.",
  "{score} ahead at the interval. He'll take it. Good time to text.",
];

export const HT_BEHIND: readonly string[] = [
  "Down {score} at the break. Plenty of time left.",
  "{score} behind at half-time. Still 45 to turn it around.",
  "Trailing {score} at the break. He'll be hopeful for a comeback.",
  "Half-time, down {score}. Loads of football still to play, tell him.",
  "{score} behind at the break. He'll be frustrated but not done.",
  "Behind {score} at half. A whole half to fix it. Stay positive.",
  "Down {score} at the whistle. He'll want a response. Be encouraging.",
  "Half-time and {score} down. Comebacks happen. He knows it.",
  "{score} behind at the break. He'll be on edge, a kind word helps.",
  "Trailing {score} at half. Plenty of time, he'll be hoping. Check in.",
  "Down {score} at the break. He'll be tense but it's far from over.",
  "Half-time, behind {score}. Second halves are long. Keep him hopeful.",
  "{score} down at the interval. He'll be willing them on. Text him.",
  "Behind {score} at half. There's time yet. He'll cling to that.",
  "Down {score} at the break. He'll be frustrated. A little support helps.",
  "Half-time and {score} behind. Still all to play for. Tell him so.",
  "{score} down at half. He'll be hoping for a turnaround. Be kind.",
  "Trailing {score} at the break. Don't count them out. He won't.",
  "Down {score} at the whistle. He'll be quiet. Send some encouragement.",
  "{score} behind at half. Comeback territory. He'll be hoping. Check in.",
  "Behind {score} at the break. Long way to go, he knows it. Stay upbeat.",
  "Half-time, down {score}. He'll be tense. A hopeful word lands well.",
  "{score} down at the interval. He'll want a reaction. Cheer him on.",
  "Trailing {score} at half. Plenty left. He'll be on the edge. Text him.",
  "Down {score} at the break. Not over yet, and he'll feel it too.",
  "Half-time and {score} behind. He'll be frustrated. Keep it positive.",
  "{score} behind at half. A half to go. He'll be hoping. Be kind.",
  "Behind {score} at the break. He'll be willing a comeback. Cheer along.",
  "Down {score} at the whistle. Long way back, but possible. Tell him.",
  "{score} down at half. He'll be tense. A gentle text helps a lot.",
  "Trailing {score} at the break. He'll be hoping for more. Stay hopeful.",
  "Half-time, down {score}. Comebacks are made of this. He knows.",
  "{score} behind at the interval. He'll be on edge. Send him warmth.",
  "Behind {score} at half. Plenty of time, he'll say. Agree with him.",
  "Down {score} at the break. He'll be frustrated. Be the calm voice.",
  "Half-time and {score} down. Far from over. Keep him believing.",
  "{score} behind at half. He'll want a second-half push. Cheer along.",
  "Trailing {score} at the whistle. There's time. He'll be hoping. Check in.",
  "Down {score} at the break. He'll be quiet but hopeful. A kind word helps.",
  "{score} behind at half. Long way to go. He'll back them. So can you.",
];

export const HT_LEVEL: readonly string[] = [
  "Level {score} at the break. All to play for.",
  "{score} at half-time. Honours even so far.",
  "All square at the break, {score}. Game on for the second half.",
  "Half-time, {score}. Nicely poised, he'll be into this one.",
  "Level {score} at half. Everything still up for grabs.",
  "{score} at the break. Even contest, he'll be glued to it.",
  "All level at half-time, {score}. The second half will decide it.",
  "Tied {score} at the break. He'll be on the edge of his seat.",
  "{score} at half. Tight one, he'll be loving the tension.",
  "Level {score} at the whistle. Anyone's game from here.",
  "Half-time, all square at {score}. He'll be enjoying the battle.",
  "{score} at the break. Balanced as you like. Good time to check in.",
  "Level {score} at half. Everything to play for, he knows it.",
  "All square {score} at half-time. He'll be into the second half.",
  "Tied {score} at the break. A proper contest. Text him.",
  "{score} at half. Even stevens. He'll be enjoying this one.",
  "Level {score} at the interval. The second half is the decider.",
  "Half-time, {score}. Too close to call. He'll be hooked.",
  "All square at {score}. He'll be locked in. Drop him a line.",
  "Level {score} at the break. Game in the balance, he'll feel it.",
  "{score} at half-time. Nothing between them. He's into it.",
  "Tied {score} at half. He'll be glued. Good moment to say hi.",
  "All level {score} at the break. The second half will tell.",
  "{score} at the whistle. Evenly matched. He'll be enjoying it.",
  "Level {score} at half. Anyone's to win. He'll be on edge.",
  "Half-time, all square {score}. He'll be into every minute.",
  "{score} at the break. Tight contest. Worth a quick text.",
  "Tied {score} at half-time. He'll be hooked on this one.",
  "Level {score} at the interval. Everything still open.",
  "{score} at half. Balanced battle. He'll be loving it.",
  "All square at the break, {score}. The second half is everything.",
  "Level {score} at half. He'll be glued. Send him a line.",
  "{score} at half-time. Even contest, he's enjoying the watch.",
  "Tied {score} at the break. Too tight to call. He's into it.",
  "All level {score} at half. He'll be on the edge. Check in.",
  "{score} at the whistle. Nothing in it. He'll be hooked.",
  "Level {score} at the interval. Game on for the second half.",
  "Half-time, {score}. Poised nicely. He'll be enjoying this.",
  "{score} at half. Anyone's game. Good time to drop him a text.",
  "All square {score} at the break. He'll be locked in for more.",
];

// ============================================================
// FULL-TIME pools. {score} = follower-first. {team} = follower's team.
// ============================================================

export const FT_WIN: readonly string[] = [
  "Win! {score} at full-time. He'll be buzzing, good time to text him.",
  "Full-time, they win {score}! He'll be over the moon. Message him.",
  "Get in! {score} at the whistle. He'll be celebrating, text him.",
  "A win, {score}! He's made up. Say well played.",
  "Full-time {score}, a win! He'll be grinning ear to ear. Drop a line.",
  "They've won {score}! He'll be buzzing all night. Good time to reach out.",
  "Victory! {score} at full-time. He's delighted. Send him a heart.",
  "Win, {score}! He'll be on cloud nine. Perfect moment to message him.",
  "Full-time and they win {score}! He'll be thrilled. Text him now.",
  "Job done, {score}! He's loving life. Say something nice.",
  "They've done it, {score} win! He'll be celebrating. Drop him a text.",
  "Full-time {score}! What a result for him. He'll be buzzing.",
  "Win! {score} at the whistle. He'll be made up. Good time to say hi.",
  "Get in there! {score} victory. He's delighted, send him a message.",
  "Full-time, {score} and they win! He'll be beaming. Text away.",
  "They win {score}! He'll be over the moon all evening. Reach out.",
  "Victory, {score}! He's thrilled. Perfect time to drop him a line.",
  "Full-time win, {score}! He'll be celebrating. Say well played.",
  "Result! {score} at full-time. He's buzzing, good moment to text.",
  "They've won it, {score}! He'll be grinning. Send him a heart.",
  "Win! {score} on the day. He's made up. A great time to message.",
  "Full-time {score}, get in! He'll be loving this. Drop him a text.",
  "Victory {score}! He'll be on top of the world. Text him now.",
  "They win {score}! He's delighted. Perfect moment to say hi.",
  "Full-time and it's a win, {score}! He'll be buzzing. Reach out.",
  "Job done, {score} win! He'll be celebrating. Send him something.",
  "Get in! {score} at full-time. He's thrilled, good time to text him.",
  "They've won {score}! He'll be made up all night. Drop him a line.",
  "Win, {score}! He's over the moon. Perfect time to message him.",
  "Full-time {score}, a result! He'll be grinning. Say well played.",
  "Victory! {score} at the whistle. He's buzzing. Text him now.",
  "They win {score}! He'll be loving life. Good moment to reach out.",
  "Full-time win {score}! He's delighted. Send him a heart.",
  "Get in there, {score}! He'll be celebrating. Drop him a quick text.",
  "Result, {score}! He'll be on cloud nine. Perfect time to say hi.",
  "They've done it, {score}! He's thrilled. Good time to message him.",
  "Win! {score} at full-time. He'll be beaming. Text away.",
  "Full-time {score} and they win! He's buzzing. Reach out to him.",
  "Victory {score}! He'll be made up. A great moment to text.",
  "They win {score}! He's over the moon. Send him something nice.",
];

export const FT_LOSS: readonly string[] = [
  "Full-time, lost {score}. He'll need a minute on this one.",
  "Beaten {score} at the whistle. He'll be gutted, go easy on him.",
  "Full-time {score}, a defeat. He'll be quiet. Be gentle tonight.",
  "Lost {score} at full-time. He'll be down. A kind word helps.",
  "Defeat, {score}. He'll be frustrated. Maybe leave him be for a bit.",
  "Full-time and they've lost {score}. He'll need space. Be soft.",
  "Beaten {score}. He'll be deflated. Not the teasing time.",
  "Lost {score} at the whistle. He'll be sighing. Go easy on him.",
  "Full-time {score}, tough one. He'll be gutted. Send some warmth.",
  "Defeat {score}. He'll be quiet for a while. A gentle text lands well.",
  "They've lost {score}. He'll be frustrated. Be patient with him.",
  "Full-time, beaten {score}. Not his night. Just check he's okay.",
  "Lost {score}. He'll be down about it. A little support goes far.",
  "Full-time {score}, a loss. He'll need a beat. Be the kind voice.",
  "Beaten {score} at full-time. He'll be deflated. Go softly tonight.",
  "Defeat, {score}. He'll be muttering about it. Let him, then be kind.",
  "Lost {score} at the whistle. He'll be gutted. Hold the jokes.",
  "Full-time and it's a defeat, {score}. He'll be quiet. Be gentle.",
  "Beaten {score}. He'll need a minute before he talks. Give it to him.",
  "Lost {score}. Tough watch for him. A warm message helps.",
  "Full-time {score}, defeat. He'll be frustrated. Stay soft with him.",
  "They've lost {score}. He'll be down. Maybe just send a heart.",
  "Beaten {score} at full-time. Not what he wanted. Go easy.",
  "Defeat {score}. He'll be deflated. Now's a good time to be soft.",
  "Lost {score} at the whistle. He'll be gutted. Be patient tonight.",
  "Full-time, lost {score}. He'll need space. A kind word means a lot.",
  "Beaten {score}. He'll be sighing at the telly. Be gentle with him.",
  "Defeat, {score}. He'll be frustrated. Leave the teasing for later.",
  "Lost {score} at full-time. He'll be quiet. Send him some warmth.",
  "Full-time {score}, a loss. He'll be down. Be the calm one for him.",
  "They've lost {score}. Not his night. Maybe just check in gently.",
  "Beaten {score}. He'll need a moment. Be soft, he'll appreciate it.",
  "Defeat {score} at the whistle. He'll be gutted. Go easy on him.",
  "Lost {score}. He'll be frustrated. A little support helps right now.",
  "Full-time, beaten {score}. He'll be deflated. Keep it kind tonight.",
  "Defeat, {score}. He'll be quiet for a bit. A gentle text works.",
  "They've lost {score}. He'll be down about it. Be patient and warm.",
  "Lost {score} at full-time. Tough one for him. Send a kind word.",
  "Beaten {score}. He'll need a sec before he chats. Be gentle.",
  "Full-time {score}, defeat. He'll be gutted. A time to be soft.",
];

export const FT_DRAW: readonly string[] = [
  "Full-time, {score} draw. Honours even.",
  "It ends {score}. A point apiece, he'll take it or rue it.",
  "Full-time {score}, all square. A fair result, he'll say.",
  "Draw, {score} at the whistle. Even contest, even result.",
  "Full-time and it's {score}. Honours shared. He'll have thoughts.",
  "{score} draw at full-time. A point each. He'll be mulling it over.",
  "It finishes {score}. All square. He'll be philosophical about it.",
  "Full-time {score}, a draw. Nobody wins. Ask him how he feels.",
  "Drawn {score}. Even stevens at the whistle. He'll take a point.",
  "Full-time, all square {score}. Fair enough, he'll probably say.",
  "{score} at full-time, a draw. He'll have mixed feelings. Ask him.",
  "It ends level, {score}. Point shared. He'll be reflecting on it.",
  "Full-time draw, {score}. Honours even. Good time to check in.",
  "Drawn {score} at the whistle. He'll weigh it up. Ask his verdict.",
  "Full-time {score}. All square. A point gained or two dropped, ask him.",
  "It finishes {score}, a draw. He'll be chewing it over. Text him.",
  "Level at full-time, {score}. Honours shared. He'll have a view.",
  "{score} draw. Even result for an even game. He'll take it.",
  "Full-time, {score}. A point each. He'll be weighing the result.",
  "Drawn {score} at full-time. A fair shout, he'll say. Ask him.",
  "It ends {score}, all square. He'll be thoughtful about this one.",
  "Full-time draw {score}. Honours even. He'll have plenty to say.",
  "{score} at the whistle, a draw. Point apiece. Ask how he rates it.",
  "Level {score} at full-time. Shared spoils. He'll be reflecting.",
  "Full-time {score}, drawn. Nobody loses. Good moment to ask his take.",
  "It finishes all square, {score}. He'll mull it over. Drop him a line.",
  "Draw, {score}. Even game, even result. He'll take the point.",
  "Full-time, {score} draw. Honours shared. He'll have an opinion.",
  "{score} at full-time. All square. Ask if he's happy with it.",
  "Drawn {score}. A point each at the whistle. He'll weigh it up.",
  "Full-time {score}, level. A fair result, he'll agree. Text him.",
  "It ends {score}, a draw. He'll be philosophical. Ask his verdict.",
  "Level at full-time, {score}. Spoils shared. He'll have thoughts.",
  "Full-time draw, {score}. Honours even. He'll be chewing it over.",
  "{score} at the whistle, all square. A point. Ask how he feels.",
  "Drawn {score} at full-time. Even contest. He'll take the point.",
  "Full-time, {score}. A draw. Nobody wins. Good time to check in.",
  "It finishes {score}, level. He'll be reflecting. Drop him a text.",
  "Full-time {score}, all square. Honours shared. He'll have a take.",
  "Draw, {score} at the whistle. A point each. Ask him his verdict.",
];
