// _shared/goal-push-copy.ts
//
// Copy pools for the WC live pushes (goal / half-time / full-time). Each
// event-and-perspective bucket holds 40 variants; goal-push.ts picks one at
// fire-time so the same line never repeats across a long tournament. Kept apart
// from goal-push.ts so the logic file stays readable and the copy is easy to
// edit in bulk.
//
// Placeholders, filled by goal-push.ts:
//   {flag}  scorer's flag emoji        (goal pools only)
//   {team}  scorer's short name        (goal pools); follower's own team (HT/FT)
//   {score} scoreline. GOAL pools: home-away (matches the title). HT/FT pools:
//           follower-first ("their team first"), e.g. a 0-2 trailer sees "0-2".
//   {home} {away}  short names         (GOAL_BOTH only)
//
// House rules baked into every line:
//   - NO em-dashes or en-dashes (campaign rule). Hyphens in "half-time" /
//     "full-time" and in scorelines are fine.
//   - Rendered worst-case (longest names + tag-flag + two-digit score) stays
//     <=90 chars. Enforced by the sweep in goal-push.test.ts.
//   - Voice: gf-to-bf older-sister, dry and warm. Scorer/win celebrates with a
//     varied "text him" nudge; conceder/loss is muted and kind; level/draw is
//     neutral; HT-behind is hopeful. Some lines carry no nudge so 40 never feel
//     formulaic.

// ============================================================
// GOAL pools. {flag}/{team} = the SCORER. {score} = home-away.
// ============================================================

export const GOAL_SCORED: readonly string[] = [
  "{flag} {team} score! {score}. He's buzzing, good moment to text him.",
  "Get in! {team} make it {score}. He'll be off his seat right now.",
  "{flag} Goal for {team}! {score}. Perfect time to send him a message.",
  "{team} score, {score}! He's celebrating. Drop him a quick text.",
  "Yes! {team} on the board, {score}. He loves that you're following this.",
  "{flag} {team} find the net! {score}. He's made up. Say something nice.",
  "Goal! {team} lead the way at {score}. Text him before the replay ends.",
  "{team} score! {score}. That's the one he wanted. He'll be grinning.",
  "Big moment, {team} go {score}! He's shouting at the telly. Join in.",
  "{flag} They've done it! {team} score, {score}. Good time to check in.",
  "Goal {team}! {score}. He's buzzing right now, send him a heart.",
  "{team} strike! {score} and he is loving life. Drop him a line.",
  "Get in there! {team} make it {score}. He'll want to talk about this.",
  "{flag} {team} score, {score}! Pure joy on his end. Text away.",
  "Goal! {team} edge ahead, {score}. He'll remember you asked.",
  "{team} score! {score}. He's celebrating like he scored it himself.",
  "{flag} What a moment, {team} go {score}! Send him a quick well done.",
  "{team} on the scoresheet, {score}! He's thrilled. Good time to message.",
  "Goal for {team}! {score}. He's punching the air. Drop him a text.",
  "{flag} {team} score! {score}. He's over the moon, say hi.",
  "They've scored! {team} lead {score}. He's glued to it, text him.",
  "{team} find a goal, {score}! He's buzzing. Perfect time to reach out.",
  "Goal! {team} make it {score}. He's having the best time right now.",
  "{flag} {team} score, {score}! He'll be telling everyone. Tell him too.",
  "Get in! {team} go {score}. He is delighted, send him something.",
  "{team} score! {score}. That'll have him grinning ear to ear.",
  "{flag} Goal, {team}! {score}. He's loving this. Good time to text.",
  "{team} strike, {score}! He'll be celebrating for a while yet.",
  "Goal! {team} ahead at {score}. He'll want to share this, beat him to it.",
  "{flag} {team} score, {score}! He is buzzing. Drop him a message.",
  "They've done it, {team} {score}! He's thrilled. Say something kind.",
  "Goal for {team}! {score}. He's on cloud nine, good time to check in.",
  "{flag} {team} net one, {score}! He'll be celebrating. Join him.",
  "{team} score! {score}. He couldn't be happier. Text him now.",
  "Get in! {team} make it {score}. He's living for this. Reach out.",
  "{flag} Goal! {team} go {score}. He's buzzing, send him a quick line.",
  "{team} score, {score}! He'll be beaming. Perfect time to message him.",
  "They've scored! {team} {score}. He is over the moon, text him.",
  "{flag} {team} find the net, {score}! He's made up. Say well played.",
  "Goal! {team} lead {score}. He's having a moment. Good time to text.",
];

export const GOAL_CONCEDED: readonly string[] = [
  "{flag} {team} score. {score}. He won't be happy, give him a minute.",
  "Tough one, {team} make it {score}. He'll be quiet for a bit.",
  "{team} have scored, {score}. Not his moment. Maybe leave him be.",
  "{flag} {team} go {score}. He'll be frustrated, a kind word helps.",
  "They've conceded. {team} {score}. He'll need a second, be gentle.",
  "{team} score, {score}. He's gutted. Now's a good time to be soft.",
  "{flag} Goal for {team}, {score}. Not what he wanted. Go easy on him.",
  "{team} make it {score}. He'll be muttering at the telly. Let him.",
  "Ouch, {team} score. {score}. He's deflated, a little support goes far.",
  "{flag} {team} on top, {score}. He'll be tense. Maybe just check in.",
  "They've gone behind. {team} {score}. He'll need a moment, be kind.",
  "{team} score, {score}. He's not loving this. A gentle text helps.",
  "{flag} {team} ahead now, {score}. He'll be stressed, go softly.",
  "Tough watch. {team} {score}. He'll be frustrated, give him space.",
  "{team} find a goal, {score}. He's quiet. Not the teasing time.",
  "{flag} {team} score, {score}. He'll be down. A kind word means a lot.",
  "Not great, {team} go {score}. He'll be on edge. Be patient with him.",
  "{team} have scored, {score}. He'll need a minute before he talks.",
  "{flag} {team} make it {score}. He's gutted, save the jokes for later.",
  "They've conceded again, {score}. Soft and supportive wins here.",
  "{team} score, {score}. He'll be sighing at the screen. Go gentle.",
  "{flag} {team} on the board, {score}. Not his night so far, be kind.",
  "Rough one, {team} {score}. He'll be frustrated, a little warmth helps.",
  "{team} score, {score}. He's deflated. Maybe just send a heart.",
  "{flag} {team} ahead, {score}. He'll be quiet. Don't poke the bear yet.",
  "They've gone behind, {score}. He'll need a sec. Be the calm one.",
  "{team} make it {score}. He's not happy, a gentle check-in lands well.",
  "{flag} Goal {team}, {score}. He'll be tense, keep it soft for now.",
  "Tough, {team} score {score}. He'll want a minute. Give it to him.",
  "{team} on top at {score}. He's frustrated. A kind message helps.",
  "{flag} {team} score, {score}. Not his moment. Be patient and warm.",
  "They've conceded, {score}. He'll be quiet, now's a time to be soft.",
  "{team} go {score}. He's gutted. Hold the teasing, send support.",
  "{flag} {team} make it {score}. He'll be on edge. Go easy tonight.",
  "Ouch. {team} score, {score}. He'll need a beat before he chats.",
  "{team} ahead, {score}. He's deflated. A gentle word does wonders.",
  "{flag} {team} score, {score}. Tough one for him. Be the kind voice.",
  "They've gone behind, {team} {score}. He'll be frustrated. Stay soft.",
  "{team} make it {score}. Not what he hoped. Check he's okay.",
  "{flag} {team} score, {score}. He's quiet now. A little warmth helps.",
];

export const GOAL_BOTH: readonly string[] = [
  "It's {score} between {home} and {away}. Goals flying in!",
  "End to end stuff, {home} and {away} at {score}. Chaos!",
  "{score}! {home} and {away} are trading goals. What a game.",
  "Both teams scoring, {score}. {home} vs {away} is wide open.",
  "Goals galore! {home} {score} {away}. This one's a thriller.",
  "{score} and counting. {home} and {away} can't stop scoring.",
  "What a match, {home} {score} {away}. Goals at both ends.",
  "It's {score}! {home} and {away} are putting on a show.",
  "Mad game. {home} {score} {away}. Neither side wants to defend.",
  "Goals flying in, {score}. {home} and {away} are going for it.",
  "{score}! End to end between {home} and {away}. Edge of your seat.",
  "Both nets bulging, {home} {score} {away}. Proper entertainment.",
  "It's basketball out there, {score}. {home} and {away} trading blows.",
  "{home} {score} {away} and the goals keep coming. What a watch.",
  "Wild one, {score}! {home} and {away} both finding the net.",
  "Goals everywhere, {home} {score} {away}. This game has it all.",
  "{score} already! {home} and {away} are not holding back.",
  "Trading goals, {home} {score} {away}. Hope his heart can take it.",
  "It's {score}! Defences optional in {home} vs {away}.",
  "Helter skelter, {home} {score} {away}. Goals at a rate of knots.",
  "{score} and rising. {home} and {away} are putting on a clinic.",
  "Both teams at it, {score}. {home} vs {away} is pure chaos.",
  "Goal fest! {home} {score} {away}. He'll be loving this one.",
  "It's {score}! {home} and {away} keep answering each other.",
  "What a spectacle, {home} {score} {away}. Goals galore.",
  "{score}! Neither {home} nor {away} can stop scoring tonight.",
  "End to end again, {home} {score} {away}. Breathless stuff.",
  "Goals raining down, {score}. {home} and {away} both on it.",
  "It's a shootout, {home} {score} {away}. Edge of the sofa time.",
  "{score} and open as you like. {home} vs {away} is bonkers.",
  "Both finding the net, {home} {score} {away}. Some game this.",
  "Goals, goals, goals. {home} {score} {away}. He's glued to it.",
  "It's {score}! {home} and {away} have thrown the script away.",
  "Frantic stuff, {home} {score} {away}. Goals flowing both ways.",
  "{score}! Toe to toe, {home} and {away}. What a contest.",
  "Both teams firing, {home} {score} {away}. Tell him not to blink.",
  "It's wild, {score}. {home} and {away} trading punches.",
  "Goals everywhere you look, {home} {score} {away}. Brilliant.",
  "{score} and end to end. {home} vs {away} is a proper watch.",
  "Madness, {home} {score} {away}. Both nets getting plenty of action.",
];

// ============================================================
// HALF-TIME pools. {score} = follower-first. {team} = follower's team.
// ============================================================

export const HT_AHEAD: readonly string[] = [
  "Up {score} at the break. He's already insufferable. Lean in, it's adorable.",
  "{score} up at half. He's \"staying calm.\" He is absolutely not staying calm.",
  "Up {score}! One more goal and he's completely unbearable. Cherish it.",
  "Half-time, {score} up. He's got the smug face on. You know the one.",
  "Up {score} at the break. He's basically claiming he predicted this.",
  "{score} ahead at half. He's strutting around like he's playing.",
  "Up {score}! He's narrating the highlights to himself already.",
  "{score} up at the break. Peak smug. Let him have his little moment.",
  "Up {score} at half. Do not say the word \"easy.\" You'll curse it.",
  "{score} ahead at the break. Don't mention the score. He'll panic.",
  "Up {score}! He won't move from his spot. Respect the lucky cushion.",
  "Half-time, {score} up. Same seat, same mug, do not break the spell.",
  "{score} up at half. He's terrified of jinxing it. Tread carefully.",
  "Up {score} at the break. He'd rather you didn't celebrate yet. Superstitions.",
  "Up {score} at half. \"It's not over,\" he says, grinning ear to ear.",
  "{score} ahead at the break. He's playing it cool. He is not cool.",
  "Up {score}! He's pretending this is normal. It is not normal.",
  "Half-time, {score} up. Cautiously optimistic, loudly relieved.",
  "Up {score} at the break. Bank this mood, you're cashing it in at full-time.",
  "{score} up at half. Good mood loading. Save the big ask for the whistle.",
  "Up {score}! Keep this energy noted. Full-time you is going to need it.",
  "Half-time, {score} up. If it holds, tonight's ask writes itself.",
  "Up {score} at the break. He's having a great time. Drop him a line.",
  "{score} ahead at half. He's buzzing quietly. Good moment to say hi.",
  "Up {score} at the break. He's chuffed. Send him a quick something.",
  "Half-time, {score} up. He'll take that. Text him while he's happy.",
  "Up {score} at half. He's already planning the celebration. Bold.",
  "{score} up at the break. He's calling his mates to gloat. Predictable.",
  "Up {score}! He's doing the little fist pump on repeat. Cute.",
  "Half-time, {score} up. He's insufferable AND right. Worst combo.",
  "Up {score} at the break. He's acting like he's at the final already.",
  "{score} ahead at half. He's got opinions on the trophy now. Steady on.",
  "Up {score}! Don't ask how he is. He'll tell you. At length.",
  "Half-time, {score} up. He's a goal into a victory speech. It's 45 early.",
  "Up {score} at the break. He's beaming. Let him be ridiculous.",
  "{score} up at half. He's googling the knockout bracket. Optimist.",
  "Up {score}! He's so happy he might even do the washing up. Strike now.",
  "Half-time, {score} up. The smug is strong. Roll your eyes fondly.",
  "Up {score} at the break. He's pretending not to check the table. He is.",
  "{score} ahead at half. He's living his best life. Join him for a sec.",
];

export const HT_BEHIND: readonly string[] = [
  "Down {score} at half. He's already blaming the ref. Just nod along.",
  "{score} down at the break. He's gone quiet and tragic. Give it the second half.",
  "Down {score}! He's reenacting the missed chance for the third time.",
  "Half-time, {score} down. He's sighing like a Victorian widow. Bless him.",
  "{score} down at half. He's taking it personally. He always does.",
  "Down {score} at the break. He's muttering darkly at the telly. Let him.",
  "{score} down! He's declared it \"men against boys.\" It's half-time.",
  "Half-time, {score} down. He's in his feelings. Tread gently.",
  "Down {score} at half. He'd have made five changes by now. None of them legal.",
  "{score} down at the break. He's redesigning the midfield in his head. Let him cook.",
  "Down {score}! Suddenly he's the manager, and the manager is furious.",
  "Half-time, {score} down. He's got a tactical fix and a team talk ready. Nod along.",
  "{score} down at half. He's screaming at the formation. It can't hear him.",
  "Down {score} at the break. He could fix this in two subs, apparently.",
  "{score} down! He's questioning the lineup, the tactics, the ref, the grass.",
  "Half-time, {score} down. One bad pass from becoming the gaffer. Let him rant.",
  "Down {score} at half. Bad moment to ask for anything. File it for later.",
  "{score} down at the break. Park the favour. He can't take good news now.",
  "Down {score}! Not the time for the holiday chat. Noted for full-time.",
  "Half-time, {score} down. Hold your news. He's not in a yes mood.",
  "Down {score} at half. He's deflated. A kind word goes a long way.",
  "{score} down at the break. Comeback's still on. Keep him hopeful.",
  "Down {score}! Plenty of time, even if he's forgotten that. Remind him gently.",
  "Half-time, {score} down. He'll need a lift. Be the calm one.",
  "{score} down at half. He's doing the head-in-hands thing. Dramatic, him.",
  "Down {score} at the break. He's blaming everyone but the players. Classic.",
  "{score} down! He's threatening to turn it off. He won't. He never does.",
  "Half-time, {score} down. He's rehearsing his post-match misery. Save him.",
  "Down {score} at half. He's gone full pundit, full grump. Let it pass.",
  "{score} down at the break. He's annoyed at the world. Mostly the left back.",
  "Down {score}! He's convinced the ref has a grudge. He does not.",
  "Half-time, {score} down. He's sulking with style. Give him a minute.",
  "{score} down at half. He's already drafting the group-chat complaints.",
  "Down {score} at the break. He's taking deep breaths. Many of them.",
  "{score} down! He wants to \"have words\" with the manager. Good luck.",
  "Half-time, {score} down. He's lost the plot, found the snacks. Coping.",
  "Down {score} at half. He's quiet. The dangerous kind. Tread softly.",
  "{score} down at the break. He's blaming his socks now. Reaching.",
  "Down {score}! He needs a hug and a substitution. You can only offer one.",
  "Half-time, {score} down. He's grumpy but it's not over. Stay upbeat.",
];

export const HT_LEVEL: readonly string[] = [
  "Level {score} at the break. Coin-flip stuff. His mood tonight is still TBD.",
  "All square {score}. The second half decides what evening you're getting.",
  "{score} at half. Could go either way, and so could he. Brace yourself.",
  "Level {score}. 45 minutes to decide if tonight's a celebration or a sulk.",
  "{score} at the break. His whole night hinges on the next 45. No pressure.",
  "All square {score} at half. Heads he's lovely, tails he's a nightmare.",
  "Level {score}. The result decides the vibe. Stay flexible, soldier.",
  "{score} at the break. Anyone's game, anyone's mood. Pack a coping plan.",
  "Level {score} at half. Tonight's forecast: entirely score-dependent.",
  "All square {score}. Could be wine and chats, could be sulking. TBD.",
  "{score} at half. He's suddenly the manager, full of formation opinions.",
  "All square {score}. He's shouting tactics at men who cannot hear him.",
  "Level {score} at the break. He'd \"make three changes.\" He manages nothing.",
  "{score} at half. Expect a TED talk on the midfield any second now.",
  "All square {score}. He's diagrammed a better setup on the sofa. Visionary.",
  "Level {score}. He's analysing it like he's on the panel. Let him present.",
  "{score} at the break. He has notes. Many notes. For the actual coach.",
  "All square {score} at half. He's solved the game. The game disagrees.",
  "Level {score}. He's calling for a sub no one else can see the need for.",
  "{score} at half. He'd win this in five minutes. From the couch. Sure.",
  "{score} at half. He won't move from his spot. Respect the lucky cushion.",
  "Level {score}. Do not comment on the score. You'll jinx it, apparently.",
  "All square {score} at the break. Same seat, same mug, same nerves.",
  "{score} at half. He's blaming his socks. The socks are now load-bearing.",
  "Level {score}. He's convinced the lucky shirt is working. Don't argue.",
  "All square {score}. He sat down and they levelled. His fault now, obviously.",
  "{score} at the break. Don't jinx it, don't praise it, barely breathe.",
  "Level {score} at half. He hasn't moved in an hour. Ritual in progress.",
  "{score} at half. The remote stays exactly there. House rules now.",
  "All square {score}. He's doing the lucky routine. Humour the man.",
  "{score} at the break. He's \"not worried.\" He's worried. Bless him.",
  "Level {score}. He says it's fine. His knee hasn't stopped bouncing.",
  "All square {score} at half. \"Plenty of time,\" he says, gripping the remote.",
  "{score} at the break. Cool as anything, apart from the pacing.",
  "Level {score}. He's calm. The cushion he's strangling disagrees.",
  "{score} at half. \"No stress,\" he lies, checking the clock again.",
  "All square {score}. He's relaxed. In the way a coiled spring is relaxed.",
  "Level {score} at the break. He's fine. He's said it nine times. He's fine.",
  "{score} at half. Totally chilled, aside from the death grip on his phone.",
  "Level {score}. He's the picture of calm. The picture is shaking slightly.",
];

// ============================================================
// FULL-TIME pools. {score} = follower-first. {team} = follower's team.
// ============================================================

export const FT_WIN: readonly string[] = [
  "Full-time, they win {score}! He's glowing all night. Prime time for the trip chat.",
  "Win! {score}. He'd say yes to anything for the next hour. Use it wisely.",
  "They've won {score}! Game's done, he's buzzing. Slide in that favour now.",
  "Full-time win {score}! Catch him beaming, the weekend away books itself.",
  "Win, {score}! He's happy and off the telly. Now ask about those tickets.",
  "Full-time {score}! Best mood he'll be in all week. Strike now.",
  "They win {score}! Match over, mood sky high. Mention the summer plan.",
  "Win! {score}. He's floating. Perfect window for the dinner-with-mum chat.",
  "Full-time, won {score}! He'll agree to anything for an hour. Move fast.",
  "They've done it, {score}! Catch him glowing, the big ask lands easy.",
  "Win {score}! The man is putty right now. Ask for the nice thing.",
  "Full-time win {score}! Cash in the good mood while it's hot.",
  "Won {score}! He's generous in victory. Test that theory now.",
  "Full-time {score}! He's saying yes to life. And probably to you. Try it.",
  "Win! {score}. He's beaming. The holiday basically books itself right now.",
  "They win {score}! He's unbreakable right now. Sneak in the favour.",
  "Full-time, won {score}! Good mood window open. You have one hour.",
  "Win {score}! He's so pleased he forgot to be sensible. Pounce.",
  "Full-time win {score}! Now's the moment for \"so, about that thing\".",
  "Won {score}! He's high on it. Ride the wave, ask the question.",
  "Full-time, they win {score}! He'll be over the moon. Send him a heart.",
  "Win! {score} at the whistle. He's made up. Say well played.",
  "They win {score}! He'll be buzzing for ages. Drop him a quick text.",
  "Full-time win {score}! He's delighted. Tell him you watched it all.",
  "Victory, {score}! He's on cloud nine. Perfect moment to message him.",
  "Win {score}! He'll be grinning all evening. Good time to text.",
  "Full-time, won {score}! He's thrilled. Send him something nice.",
  "They've won {score}! He'll be celebrating. Drop him a line.",
  "Win! {score}. He's beaming. A quick \"get in!\" will make his night.",
  "Full-time {score}, a win! He's loving life. Say hi.",
  "Won {score}! He'll be buzzing. Tell him how good they looked.",
  "Victory {score}! He's made up. Good moment to reach out.",
  "Full-time win {score}! He's over the moon. Send a heart.",
  "They win {score}! He's thrilled to bits. Text him now.",
  "Win, {score}! He's on top of the world. Say well played.",
  "Full-time, they win {score}! He's delighted. A quick text lands well.",
  "Won {score}! He'll be glowing. Good time to check in.",
  "Win! {score}. He's buzzing. Drop him a celebratory line.",
  "Full-time win {score}! He couldn't be happier. Message him.",
  "They've done it, {score}! He's over the moon. Say something nice.",
];

export const FT_LOSS: readonly string[] = [
  "Full-time, lost {score}. Whatever you were going to ask, file it for another day.",
  "Lost {score}. Not the night for the big conversation. Bank it, be kind.",
  "Full-time {score}. Park the favour. Tonight he needs a snack and sympathy.",
  "Beaten {score}. Hold that thought till next time. Tonight's a write-off for asks.",
  "Lost {score} at full-time. Shelve the holiday chat. Wrong night entirely.",
  "Full-time, lost {score}. Save your news. He can't take good vibes right now.",
  "Beaten {score}. The ask can wait. Tonight is purely comfort duty.",
  "Lost {score}. Don't bring up the trip. Bring snacks instead.",
  "Full-time {score}. File the favour under \"another day\". Be gentle tonight.",
  "Lost {score} at the whistle. Not a yes-mood. Hold your fire.",
  "Beaten {score}. Park the big plan. Right now he needs you, not questions.",
  "Full-time, lost {score}. Whatever you wanted, ask it tomorrow. Tonight, kindness.",
  "Full-time, lost {score}. He'll need a minute on this one.",
  "Beaten {score} at the whistle. He'll be gutted, go easy on him.",
  "Full-time {score}, a defeat. He'll be quiet. Be gentle tonight.",
  "Lost {score} at full-time. He'll be down. A kind word helps.",
  "Defeat, {score}. He'll be frustrated. Maybe leave him be for a bit.",
  "Full-time and they've lost {score}. He'll need space. Be soft.",
  "Beaten {score}. He'll be deflated. Not the teasing time.",
  "Lost {score} at the whistle. He'll be sighing. Go easy on him.",
  "Full-time {score}, tough one. He'll be gutted. Send some warmth.",
  "Defeat {score}. He'll be quiet for a while. A gentle text lands well.",
  "They've lost {score}. He'll be frustrated. Be patient with him.",
  "Full-time, beaten {score}. Not his night. Just check he's okay.",
  "Lost {score}. He'll be down about it. A little support goes far.",
  "Full-time {score}, a loss. He'll need a beat. Be the kind voice.",
  "Beaten {score} at full-time. He'll be deflated. Go softly tonight.",
  "Defeat, {score}. He'll be muttering about it. Let him, then be kind.",
  "Lost {score} at the whistle. He'll be gutted. Hold the jokes.",
  "Full-time and it's a defeat, {score}. He'll be quiet. Be gentle.",
  "Beaten {score}. He'll need a minute before he talks. Give it to him.",
  "Lost {score}. Tough watch for him. A warm message helps.",
  "Full-time {score}, defeat. He'll be frustrated. Stay soft with him.",
  "They've lost {score}. He'll be down. Maybe just send a heart.",
  "Beaten {score} at full-time. Not what he wanted. Go easy.",
  "Defeat {score}. He'll be deflated. Now's a good time to be soft.",
  "Lost {score} at the whistle. He'll be gutted. Be patient tonight.",
  "Full-time, lost {score}. He'll need space. A kind word means a lot.",
  "Beaten {score}. He'll be sighing at the telly. Be gentle with him.",
  "Full-time {score}, a loss. He'll be down. Be the calm one for him.",
];

export const FT_DRAW: readonly string[] = [
  "Full-time, {score} draw. Honours even.",
  "It ends {score}. A point apiece, he'll take it or rue it.",
  "Full-time {score}, all square. A fair result, he'll say.",
  "Draw, {score} at the whistle. Even contest, even result.",
  "Full-time and it's {score}. Honours shared. He'll have thoughts.",
  "{score} draw at full-time. A point each. He'll be mulling it over.",
  "It finishes {score}. All square. He'll be philosophical about it.",
  "Full-time {score}, a draw. Nobody wins. Ask him how he feels.",
  "Drawn {score}. Even stevens at the whistle. He'll take a point.",
  "Full-time, all square {score}. Fair enough, he'll probably say.",
  "{score} at full-time, a draw. He'll have mixed feelings. Ask him.",
  "It ends level, {score}. Point shared. He'll be reflecting on it.",
  "Full-time draw, {score}. Honours even. Good time to check in.",
  "Drawn {score} at the whistle. He'll weigh it up. Ask his verdict.",
  "Full-time {score}. All square. A point gained or two dropped, ask him.",
  "It finishes {score}, a draw. He'll be chewing it over. Text him.",
  "Level at full-time, {score}. Honours shared. He'll have a view.",
  "{score} draw. Even result for an even game. He'll take it.",
  "Full-time, {score}. A point each. He'll be weighing the result.",
  "Drawn {score} at full-time. A fair shout, he'll say. Ask him.",
  "It ends {score}, all square. He'll be thoughtful about this one.",
  "Full-time draw {score}. Honours even. He'll have plenty to say.",
  "{score} at the whistle, a draw. Point apiece. Ask how he rates it.",
  "Level {score} at full-time. Shared spoils. He'll be reflecting.",
  "Full-time {score}, drawn. Nobody loses. Good moment to ask his take.",
  "It finishes all square, {score}. He'll mull it over. Drop him a line.",
  "Draw, {score}. Even game, even result. He'll take the point.",
  "Full-time, {score} draw. Honours shared. He'll have an opinion.",
  "{score} at full-time. All square. Ask if he's happy with it.",
  "Drawn {score}. A point each at the whistle. He'll weigh it up.",
  "Full-time {score}, level. A fair result, he'll agree. Text him.",
  "It ends {score}, a draw. He'll be philosophical. Ask his verdict.",
  "Level at full-time, {score}. Spoils shared. He'll have thoughts.",
  "Full-time draw, {score}. Honours even. He'll be chewing it over.",
  "{score} at the whistle, all square. A point. Ask how he feels.",
  "Drawn {score} at full-time. Even contest. He'll take the point.",
  "Full-time, {score}. A draw. Nobody wins. Good time to check in.",
  "It finishes {score}, level. He'll be reflecting. Drop him a text.",
  "Full-time {score}, all square. Honours shared. He'll have a take.",
  "Draw, {score} at the whistle. A point each. Ask him his verdict.",
];
