# Overheard content for category "culture". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "fergie-time": dict(
        overheard="Six added at the end and they score in the ninth. Fergie time, that.",
        speaker="chat",
        gist="Stoppage minutes that suit the big side",
        decoys=["The years a famous manager was in charge", "Kick-off times chosen to suit television"],
        when=["any", "after-loss", "title"],
    ),
    "the-gaffer": dict(
        overheard="New gaffer, new ideas. Give him till Christmas before you judge.",
        speaker="him",
        gist="The manager, in old workplace slang",
        decoys=["The person in charge of the floodlights", "The club captain who leads on the pitch"],
        when=["any", "new-manager", "bad-run", "after-heavy-loss"],
    ),
    "the-boss": dict(
        overheard="Listen to the interviews. Not one of them says his name, it's all the boss.",
        speaker="pundit",
        gist="The manager, the word players use on camera",
        decoys=["The club owner who pays everyone's wages", "The senior player who speaks in the dressing room"],
        when=["any", "new-manager"],
    ),
    "hard-man": dict(
        overheard="Their centre-half is a proper hard man. Tell him to stay on his feet.",
        speaker="chat",
        gist="A player feared for his fierce, physical game",
        decoys=["A player who is difficult to deal with off it", "A defender who blocks shots with his body"],
        when=["any", "derby"],
    ),
    "class-act": dict(
        overheard="Stayed out and clapped the travelling fans after that. Class act.",
        speaker="pundit",
        gist="A player admired for his manner as much as his football",
        decoys=["A player putting on a show for the cameras", "A polished touch that makes the game look easy"],
        when=["good-run", "after-win"],
    ),
    "top-top-player": dict(
        overheard="Forget the goal, look at the pass before it. Top top player.",
        speaker="pundit",
        gist="Pundit-speak for very good indeed",
        decoys=["Someone at the top of the scoring charts", "A man voted best on the pitch that day"],
        when=["good-run", "after-win", "after-big-win", "window"],
    ),
    "match-of-the-day": dict(
        overheard="Staying up for Match of the Day, or do you want the short version?",
        speaker="him",
        gist="The BBC's Saturday night highlights show",
        decoys=["The televised game picked out each Saturday", "A vote for the best player after a game"],
        when=["any", "after-win", "after-loss"],
    ),
    "pundit": dict(
        overheard="The pundits said we'd be fine. That's the worry.",
        speaker="him",
        gist="A retired player paid to give opinions on TV",
        decoys=["A journalist who writes the match report", "An expert who predicts the score beforehand"],
        when=["any", "after-loss"],
    ),
    "the-lads": dict(
        overheard="Buzzing for the lads tonight. First time they've looked like a team.",
        speaker="chat",
        gist="The team, as the players and fans call it",
        decoys=["The younger players coming through the academy", "The travelling fans who follow every game"],
        when=["any", "after-win", "good-run"],
    ),
    "bottle-it": dict(
        overheard="Eight points clear in March. I'm telling you now, we'll bottle it.",
        speaker="him",
        gist="To lose your nerve and throw away a winning position",
        decoys=["To throw a drink onto the pitch from the stand", "To waste chances in front of goal all game"],
        when=["title", "run-in", "bad-run", "after-loss"],
    ),
    "banter": dict(
        overheard="Sent him a photo of a bin with the score on it. Banter.",
        speaker="chat",
        gist="Teasing between fans, mostly friendly",
        decoys=["Chatter between the players on the pitch", "A row between fans that has gone too far"],
        when=["any", "derby", "after-win"],
    ),
    "group-chat": dict(
        overheard="The group chat's gone into meltdown. Forty messages at half-time.",
        speaker="him",
        gist="Where his mates react to every goal instantly",
        decoys=["An online forum open to all supporters", "Fans posting videos from inside the ground"],
        when=["any", "derby", "after-win", "after-loss"],
    ),
    "season-ticket": dict(
        overheard="Renewed the season ticket. Same seat I've had since I was nine.",
        speaker="him",
        gist="A pass covering every home league game",
        decoys=["A ticket sold cheaply at certain times of year", "A membership that lets you buy cup tickets early"],
        when=["any", "early-season"],
    ),
    "away-day": dict(
        overheard="Big away day Saturday. Train at seven, back God knows when.",
        speaker="chat",
        gist="A trip to watch the team at another ground",
        decoys=["A day off given to the players midweek", "A club trip abroad before the season starts"],
        when=["any", "cup", "europe"],
    ),
    "the-away-end": dict(
        overheard="You can hear the away end from up here. Three thousand of them.",
        speaker="telly",
        gist="The part of the ground given to visiting fans",
        decoys=["The end of the pitch the visitors attack", "The stand behind the goal that sings"],
        when=["any", "cup", "europe", "derby"],
    ),
    "kop": dict(
        overheard="The Kop are on their feet and they've not sat down for ten minutes.",
        speaker="telly",
        gist="Liverpool's loud home stand at Anfield",
        decoys=["The area where police stand in a stadium", "A stand named after a club's great manager"],
        when=["any"],
    ),
    "terraces": dict(
        overheard="That song came off the terraces in the seventies. It's older than he is.",
        speaker="pundit",
        gist="The old standing areas, and the fans in them",
        decoys=["The rows of houses behind an old ground", "The seats reserved for club members"],
        when=["any", "derby"],
    ),
    "chant": dict(
        overheard="There's a chant about him now. The away end did it all game.",
        speaker="him",
        gist="A song the crowd sings to a pop tune",
        decoys=["A rhythm the crowd claps without words", "The anthem played before European nights"],
        when=["any", "derby", "cup"],
    ),
    "half-and-half-scarf": dict(
        overheard="Bloke in front of us in a half-and-half scarf. Unbelievable scenes.",
        speaker="chat",
        gist="A souvenir showing both teams' colours",
        decoys=["A ticket that covers both legs of a round", "A shirt design split into two colours"],
        when=["derby", "cup"],
    ),
    "plastic-fan": dict(
        overheard="Half this lot are plastic fans. Where were they when we went down?",
        speaker="him",
        gist="Someone who only supports a club because they win",
        decoys=["Someone who turns up in a shop-bought kit", "A supporter from the artificial-pitch days"],
        when=["any", "derby", "good-run"],
    ),
    "glory-hunter": dict(
        overheard="His lad supports whoever's top of the table. Glory hunter in the making.",
        speaker="chat",
        gist="A fan who picked a club for its trophies",
        decoys=["A player chasing his own goals over the team", "Someone who collects club shirts and badges"],
        when=["any", "good-run", "title"],
    ),
    "the-boot-room": dict(
        overheard="Liverpool did it with the boot room. Nobody has that patience now.",
        speaker="pundit",
        gist="Promoting the next manager from inside the club",
        decoys=["The place at a ground where kit is stored", "A club's academy for teenage players"],
        when=["any", "new-manager"],
    ),
    "the-invincibles": dict(
        overheard="Their lot will bring up the Invincibles before the first goal.",
        speaker="chat",
        gist="A whole league season without a defeat",
        decoys=["Players who avoided injury for a whole season", "A side that won three trophies in one year"],
        when=["title", "good-run"],
    ),
    "sack-race": dict(
        overheard="He's odds-on in the sack race and we're not out of September.",
        speaker="chat",
        gist="The unofficial contest over which manager goes first",
        decoys=["A charity event before a game at the ground", "The scramble to sign players before the window shuts"],
        when=["bad-run", "new-manager", "after-heavy-loss"],
    ),
    "new-manager-bounce": dict(
        overheard="Two wins and a clean sheet. That's a new manager bounce, nothing more.",
        speaker="pundit",
        gist="The short run of good results after a change",
        decoys=["The lift in ticket sales after an appointment", "The boost a home crowd gives a struggling side"],
        when=["new-manager", "good-run"],
    ),
    "silly-season": dict(
        overheard="Paper says we're signing three strikers. Silly season, ignore it.",
        speaker="him",
        gist="Summer, when every rumour gets printed",
        decoys=["The run of games over Christmas and New Year", "A spell when results make no sense at all"],
        when=["window", "early-season"],
    ),
    "here-we-go": dict(
        overheard="Here we go. Medical booked, he's ours by Friday.",
        speaker="chat",
        gist="The reporter's signal a transfer is done",
        decoys=["The shout that goes up as a move starts", "The countdown to the window shutting"],
        when=["window"],
    ),
    "football-twitter": dict(
        overheard="Don't look at Football Twitter tonight. It'll be carnage.",
        speaker="him",
        gist="The online corner where fans argue all day",
        decoys=["A club's official account posting the news", "The reporters who break transfer stories"],
        when=["any", "window", "after-loss"],
    ),
    "fantasy-football": dict(
        overheard="I need him to score tonight for my fantasy football team. Sorry.",
        speaker="him",
        gist="A game where you pick real players for points",
        decoys=["A made-up league played on a games console", "Betting on which players will score"],
        when=["any", "early-season"],
    ),
    "we-go-again": dict(
        overheard="Rubbish today. Nothing to say. We go again Tuesday.",
        speaker="chat",
        gist="Bad result, forget it, on to the next match",
        decoys=["The match is being replayed after a draw", "Fans are heading off to another away trip"],
        when=["after-loss", "after-heavy-loss", "bad-run", "after-draw"],
    ),
    "the-lino": dict(
        overheard="Lino! Flag stayed down, how has he not seen that?",
        speaker="him",
        gist="The official watching for offside",
        decoys=["The painted markings around the pitch", "The fourth official holding up the board"],
        when=["any"],
    ),
    "wags": dict(
        overheard="Watched a documentary about the WAGs at that 2006 World Cup. Wild.",
        speaker="chat",
        gist="Tabloid slang for players' wives and girlfriends",
        decoys=["A word for the jokers in a dressing room", "The section of the stand kept for families"],
        when=["any"],
    ),
    "magic-sponge": dict(
        overheard="A wipe with the magic sponge and he's up and running again.",
        speaker="telly",
        gist="A wet flannel that fixes any knock",
        decoys=["A cloth used to dry the ball in the rain", "The stretcher carried on for a bad injury"],
        when=["any"],
    ),
    "goal-of-the-month": dict(
        overheard="Whatever else you liked, that's goal of the month for me.",
        speaker="pundit",
        gist="The best strike, picked by a viewers' vote",
        decoys=["The award for a player's form over four weeks", "A scoring target a striker is set each month"],
        when=["any", "after-win", "after-big-win"],
    ),
    "the-magic-of-the-cup": dict(
        overheard="A part-time side two goals up at a Premier League ground. The magic of the cup.",
        speaker="telly",
        gist="The idea that a small club can beat a big one",
        decoys=["A trophy handed over on the pitch at the end", "The extra money a cup run brings a club"],
        when=["cup"],
    ),
    "wembley": dict(
        overheard="Two games from Wembley. Don't say it out loud, don't jinx it.",
        speaker="him",
        gist="The national stadium in north-west London, under an arch",
        decoys=["The name fans give to the cup final itself", "The training base the national team uses"],
        when=["cup", "run-in"],
    ),
    "the-third-round": dict(
        overheard="Third round draw is Monday. Please give us someone rubbish at home.",
        speaker="him",
        gist="The FA Cup stage in January when the big clubs enter",
        decoys=["The third game of a group in a tournament", "The round of matches played on Boxing Day"],
        when=["cup"],
    ),
}
