# Overheard content for category "match_situations". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "kick-off": dict(
        overheard="Kick-off's at three. I'll be no use to anyone after that.",
        speaker="him",
        gist="The moment the match starts",
        decoy="The coin toss that starts the game",
        spare="The first shot that tests the keeper",
        when=["any"],
        moment="anytime",
        basic=True,
    ),
    "half-time": dict(
        overheard="Right, that's half-time. I'm putting the kettle on, do you want one?",
        speaker="him",
        gist="The break in the middle of the match",
        decoy="The fifteen minutes before kick-off",
        spare="A short break for drinks in hot weather",
        when=["any"],
        moment="common",
        basic=True,
    ),
    "full-time": dict(
        overheard="Full-time here. They'll take that, I'm sure.",
        speaker="telly",
        gist="The referee ends it whatever the score",
        decoy="The end of the first half, not the match",
        spare="The whistle that starts the added minutes",
        when=["any"],
        moment="common",
        basic=True,
    ),
    "nil-nil": dict(
        overheard="Nil-nil, that. He'll be in a mood all night.",
        speaker="him",
        gist="A match that ended level with nobody scoring",
        decoy="The game was abandoned, so no score counts",
        spare="A draw where both sides scored a goal each",
        when=["after-draw", "after-clean-sheet", "opp-clean-sheets", "favourites"],
        moment="rare",
    ),
    "see-the-game-out": dict(
        overheard="They just need to see the game out from here.",
        speaker="telly",
        gist="Protect a lead until the final whistle",
        decoy="Stay on the pitch without getting sent off",
        spare="Push for another goal to settle it",
        when=["after-win", "after-clean-sheet", "derby", "run-in", "underdog"],
        moment="common",
    ),
    "squeaky-bum-time": dict(
        overheard="Squeaky bum time now. Don't talk to me.",
        speaker="him",
        gist="The jitters as the clock winds down",
        decoy="The bit where players start time-wasting",
        spare="The nervous wait while a goal is checked",
        when=["run-in", "title", "relegation", "derby", "after-win"],
        moment="common",
        player=dict(
            slot='ours.forward',
            overheard="Squeaky bum time. I'd want {ours.forward} on the pitch for this, me.",
            sayIt='"Squeaky bum time. Is {ours.forward} the one you want on for this?"',
        ),
    ),
    "six-pointer": dict(
        overheard="Six-pointer on Saturday. Don't be planning anything.",
        speaker="him",
        gist="A match between two sides chasing the same place",
        decoy="A match where a win is worth six points",
        spare="A game worth double because it is a derby",
        when=["title", "relegation", "run-in", "h2h-we-win"],
        moment="rare",
    ),
    "top-four": dict(
        overheard="Top four, and he'd call the season a success.",
        speaker="pundit",
        gist="A finish high enough for Champions League",
        decoy="The sides who reach a cup semi-final",
        spare="Winning the league and lifting the trophy",
        when=["top-four", "run-in"],
        moment="anytime",
    ),
    "title-race": dict(
        overheard="This title race is doing my head in.",
        speaker="chat",
        gist="The close fight at the top of the table",
        decoy="The final few weeks of the season",
        spare="The scrap for a place in Europe",
        when=["title", "run-in"],
        moment="anytime",
    ),
    "relegation-battle": dict(
        overheard="They're properly in a relegation battle now. Grim.",
        speaker="chat",
        gist="A scrap near the bottom to avoid going down",
        decoy="A play-off to decide who goes up a division",
        spare="A run of hard games against the top clubs",
        when=["relegation", "run-in"],
        moment="anytime",
    ),
    "sitter": dict(
        overheard="He's missed a sitter there. I've seen enough.",
        speaker="him",
        gist="A chance so easy it should have been a goal",
        decoy="A shot dragged wide from a tight angle",
        spare="A shot the keeper palms away at full stretch",
        when=["any", "after-loss", "after-draw", "opp-close-range"],
        moment="common",
        player=dict(
            slot='theirs.forward',
            overheard='If {theirs.forward} gets a sitter like that, are we in trouble?',
            sayIt='"Would {theirs.forward} put a sitter like that away, do you think?"',
        ),
    ),
    "clinical-finish": dict(
        overheard="That's clinical finishing. He'll sleep well tonight.",
        speaker="pundit",
        gist="A calm, precise shot that beats the keeper",
        decoy="A goal that takes a big deflection",
        spare="A move drilled on the training ground",
        when=["after-win", "after-big-win", "good-run", "opp-close-range", "opp-good-form"],
        moment="common",
        player=dict(
            slot='theirs.forward',
            overheard="Clinical finishing, that is. That's what they pay {theirs.forward} for.",
            sayIt='"That\'s a clinical finish. Is that what {theirs.forward} is there for?"',
        ),
    ),
    "screamer": dict(
        overheard="And that is a screamer. Get the replay on.",
        speaker="telly",
        gist="A goal hit very hard from a long way out",
        decoy="A shot that flies well over the bar",
        spare="A goal that settles a nervy game late on",
        when=["any", "after-win", "after-big-win", "opp-long-range"],
        moment="rare",
    ),
    "top-bins": dict(
        overheard="TOP BINS. Oh, that's filthy, that is.",
        speaker="him",
        gist="A corner of the goal no keeper can reach",
        decoy="A shot that creeps in off the inside of the post",
        spare="A shot the keeper gets a hand to and can't stop",
        when=["any", "after-win", "after-big-win", "opp-long-range"],
        moment="rare",
    ),
    "worldie": dict(
        overheard="Worldie, that. I've watched it four times.",
        speaker="chat",
        gist="A goal of genuine world-class quality",
        decoy="A goal scored at the World Cup",
        spare="A goal that wins goal of the month",
        when=["after-win", "after-big-win", "opp-long-range"],
        moment="rare",
    ),
    "hit-the-woodwork": dict(
        overheard="That's twice they've hit the woodwork. Not their day.",
        speaker="telly",
        gist="The ball struck the post or bar and stayed out",
        decoy="The ball smashed into the boards behind the goal",
        spare="A shot that beat the keeper and went wide",
        when=["any", "after-draw", "after-loss", "opp-long-range"],
        moment="common",
    ),
    "row-z": dict(
        overheard="He's put that in Row Z. He'll not want to see that again.",
        speaker="him",
        gist="The back of the stand, where a wild shot lands",
        decoy="A shot that clears the crossbar by inches",
        spare="The seats behind the goal at either end",
        when=["any", "after-draw", "opp-long-range"],
        moment="common",
    ),
    "howler": dict(
        overheard="Absolute howler from the keeper. Have you seen it?",
        speaker="chat",
        gist="A glaring, embarrassing mistake",
        decoy="A save so good the crowd roared",
        spare="A furious shout at his own defenders",
        when=["any", "after-loss", "after-heavy-loss", "h2h-they-win"],
        moment="rare",
    ),
    "hospital-ball": dict(
        overheard="That's a hospital ball. He can't be doing that at this level.",
        speaker="pundit",
        gist="A loose pass that leaves a teammate in trouble",
        decoy="A heavy touch that gives the ball away",
        spare="A challenge bad enough to injure someone",
        when=["any", "after-loss", "after-heavy-loss", "opp-counter"],
        moment="common",
    ),
    "hoof": dict(
        overheard="Just hoof it! He's under pressure there.",
        speaker="him",
        gist="Boot the ball clear with no particular aim",
        decoy="Knock it back to the keeper to start again",
        spare="Put it out of play to stop the attack",
        when=["any", "relegation", "underdog"],
        moment="common",
        player=dict(
            slot='ours.keeper',
            overheard="Just hoof it. There's nothing on for {ours.keeper} back there anyway.",
            sayIt='"Do they just hoof it every time? Even {ours.keeper}?"',
        ),
    ),
    "dive": dict(
        overheard="He's dived, ref! Are you watching this?",
        speaker="him",
        gist="Falling over on purpose to win a foul",
        decoy="Going down hurt to waste a bit of time",
        spare="Sliding in feet first to win the ball",
        when=["any", "derby"],
        moment="common",
    ),
    "early-bath": dict(
        overheard="That's an early bath for him, then. Silly boy.",
        speaker="telly",
        gist="Sent off, heading for the showers",
        decoy="Subbed off before he gets himself booked",
        spare="Missing the next game as punishment",
        when=["any", "derby", "after-loss"],
        moment="rare",
    ),
    "handbags": dict(
        overheard="Handbags at the corner flag. The ref's got a job on.",
        speaker="chat",
        gist="A bit of pushing and shoving, nothing more",
        decoy="A proper brawl that gets two players sent off",
        spare="Players surrounding the referee in a group",
        when=["any", "derby"],
        moment="common",
    ),
    "in-the-book": dict(
        overheard="He's in the book after four minutes. Calm down, lad.",
        speaker="him",
        gist="The referee has shown him a yellow card",
        decoy="The referee has spoken to him and let him off",
        spare="He has been sent off and must leave",
        when=["any", "derby"],
        moment="common",
    ),
    "hooked": dict(
        overheard="He's getting hooked here. He knows it, too.",
        speaker="him",
        gist="Taken off for playing badly, not for a rest",
        decoy="Caught by an arm and pulled back illegally",
        spare="Swapped out to save him for the next game",
        when=["after-loss", "after-heavy-loss", "bad-run", "opp-bad-form"],
        moment="common",
    ),
    "nutmeg": dict(
        overheard="He's nutmegged him and the ground's gone up.",
        speaker="telly",
        gist="Knocking the ball through a defender's legs",
        decoy="Barging a defender off the ball and going past",
        spare="Flicking the ball over a defender's head",
        when=["any", "after-win", "after-big-win"],
        moment="common",
    ),
    "done-him": dict(
        overheard="He's done him there. Watch the replay of that.",
        speaker="chat",
        gist="Leaving a defender standing",
        decoy="Fouling an opponent on purpose",
        spare="Rounding the keeper and walking it in",
        when=["any", "after-win", "after-big-win"],
        moment="common",
    ),
    "caught-napping": dict(
        overheard="Caught napping again, that lot. Dear me.",
        speaker="pundit",
        gist="Switching off and letting an attacker get free",
        decoy="Losing a header to a much taller player",
        spare="Being caught too high up when it turns over",
        when=["any", "after-loss", "after-draw", "after-heavy-loss", "opp-counter"],
        moment="common",
    ),
    "against-the-run-of-play": dict(
        overheard="That is against the run of play, no question.",
        speaker="telly",
        gist="A goal for the side who have been worse",
        decoy="A goal that came from a counter-attack",
        spare="A goal scored in the closing minutes",
        when=["after-win", "after-loss", "after-draw", "opp-counter", "h2h-they-win"],
        moment="common",
    ),
    "smash-and-grab": dict(
        overheard="Smash and grab, that. They'll be laughing all the way home.",
        speaker="him",
        gist="A win in a match you were outplayed in",
        decoy="A tackle that takes the ball and the man",
        spare="A late equaliser to rescue a point",
        when=["after-win", "after-loss", "derby", "underdog"],
        moment="rare",
    ),
    "game-of-two-halves": dict(
        overheard="It's been a game of two halves, hasn't it?",
        speaker="pundit",
        gist="A match that turned after the break",
        decoy="A match split into two equal periods",
        spare="A match where both sides scored twice",
        when=["after-win", "after-loss", "after-draw"],
        moment="common",
    ),
    "backs-to-the-wall": dict(
        overheard="Backs to the wall for the home side, and the noise is up.",
        speaker="telly",
        gist="Soaking up heavy pressure near your own goal",
        decoy="Players lining up in a wall at a free-kick",
        spare="Playing the ball back to the keeper to waste time",
        when=["after-clean-sheet", "after-win", "europe", "derby", "underdog"],
        moment="common",
        player=dict(
            slot='ours.defender',
            overheard='Backs to the wall from here. Get {ours.defender} in the middle of it.',
            sayIt='"Backs to the wall. Is {ours.defender} the one who heads everything away?"',
        ),
    ),
    "in-the-mixer": dict(
        overheard="Get it in the mixer! Stop faffing about.",
        speaker="him",
        gist="Launching the ball into a crowded penalty area",
        decoy="Getting it wide to the winger to cross",
        spare="Booting it into the corner to run the clock",
        when=["any", "after-draw", "relegation", "opp-set-piece", "opp-close-range"],
        moment="common",
        player=dict(
            slot='theirs.defender',
            overheard='Get it in the mixer. See if {theirs.defender} fancies it.',
            sayIt='"In the mixer, that\'s the plan. Does {theirs.defender} like it in there?"',
        ),
    ),
    "route-one": dict(
        overheard="Proper route one stuff, this. Not for me.",
        speaker="pundit",
        gist="Kicking it long and chasing it, no build-up",
        decoy="Working the ball wide and crossing it",
        spare="Passing it through the middle at speed",
        when=["any", "relegation", "opp-aerial", "underdog"],
        moment="common",
    ),
    "on-the-break": dict(
        overheard="Give it away up there and anyone will hurt you on the break. Anyone.",
        speaker="him",
        gist="Attacking at speed before they can get back",
        decoy="Scoring right after the half-time interval",
        spare="Winning the ball high up the pitch",
        when=["any", "europe", "opp-counter"],
        moment="common",
        player=dict(
            slot='theirs.midfielder',
            overheard="Give it away and they're off on the break. Where does {theirs.midfielder} fit?",
            sayIt='"Are they good on the break? Is {theirs.midfielder} part of that?"',
        ),
    ),
    "dead-rubber": dict(
        overheard="Dead rubber tonight. I'll probably miss it.",
        speaker="chat",
        gist="A match with nothing riding on it any more",
        decoy="A match played with a worn-out ball",
        spare="A match replayed after a draw, later on",
        when=["run-in", "europe"],
        moment="rare",
    ),
    "giant-killing": dict(
        overheard="The ground can smell a giant-killing now.",
        speaker="telly",
        gist="A small club knocking a big one out of a cup",
        decoy="A tall side winning everything in the air",
        spare="A late winner that dumps a team out of a cup",
        when=["cup", "favourites", "underdog"],
        moment="rare",
    ),
    "hairdryer": dict(
        overheard="Hairdryer time in that dressing room, I bet.",
        speaker="chat",
        gist="A manager screaming at players up close",
        decoy="A calm team talk to settle everyone down",
        spare="A row between players in the dressing room",
        when=["bad-run", "new-manager", "after-loss", "after-heavy-loss", "opp-bad-form"],
        moment="common",
    ),
    "man-of-the-match": dict(
        overheard="They've got man of the match wrong again, you know.",
        speaker="pundit",
        gist="The player judged best on the day",
        decoy="The supporters' player of the season",
        spare="The player who speaks to the cameras after",
        when=["any", "after-win"],
        moment="common",
        player=dict(
            slot='ours.midfielder',
            overheard="{ours.midfielder} could win man of the match every week and they'd still moan.",
            sayIt='"Would you give {ours.midfielder} man of the match? Or is that just me?"',
        ),
    ),
    "top-drawer": dict(
        overheard="He's top drawer, that lad. Always has been.",
        speaker="pundit",
        gist="Excellent and of the very highest quality",
        decoy="Playing in the top division, nothing less",
        spare="A player kept back for the big games",
        when=["any", "after-win", "after-big-win"],
        moment="common",
        player=dict(
            slot='theirs.keeper',
            overheard="Is {theirs.keeper} top drawer, though? That's the question, for me.",
            sayIt='"Is {theirs.keeper} top drawer, then? You\'d know better than me."',
        ),
    ),
    "second-ball": dict(
        overheard="It's all about the second ball, this.",
        speaker="telly",
        gist="Whatever drops loose after a header",
        decoy="Crossing in again after a short corner",
        spare="The second goal that settles a match",
        when=["any", "cup", "derby", "opp-set-piece", "opp-aerial"],
        moment="common",
    ),
    "unlucky": dict(
        overheard="Unlucky! Oh, for crying out loud.",
        speaker="him",
        gist="A shout of sympathy at a player who missed",
        decoy="A groan when the keeper makes a save",
        spare="A shout at the referee for a poor call",
        when=["any", "after-loss", "after-draw", "h2h-they-win"],
        moment="common",
    ),
}
