# Overheard content for category "match_situations". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "kick-off": dict(
        overheard="Kick-off's been moved to Sunday teatime for the telly.",
        speaker="him",
        gist="The moment the match starts",
        decoys=["The first player to touch the ball", "The whistle that ends the match"],
        when=["any"],
    ),
    "half-time": dict(
        overheard="Right, that's half-time. I'm putting the kettle on, do you want one?",
        speaker="him",
        gist="The break in the middle of the match",
        decoys=["The stage where half the season has gone", "Added minutes at the end of a half"],
        when=["any"],
    ),
    "full-time": dict(
        overheard="Full-time whistle's gone. That's that, then.",
        speaker="telly",
        gist="The referee ends it, whatever the score",
        decoys=["A player signed permanently, not on loan", "The whistle at the end of the first half"],
        when=["any"],
    ),
    "nil-nil": dict(
        overheard="Nil-nil, and that's me an hour of my life down.",
        speaker="him",
        gist="Nobody scored, the match finished level",
        decoys=["The game was abandoned, so no score counts", "A draw where both sides scored"],
        when=["after-draw", "after-clean-sheet"],
    ),
    "see-the-game-out": dict(
        overheard="They just need to see the game out from here.",
        speaker="telly",
        gist="Protect a lead until the final whistle",
        decoys=["Watch the match right to the end on telly", "Push for another goal to settle it"],
        when=["after-win", "after-clean-sheet", "derby", "run-in"],
    ),
    "squeaky-bum-time": dict(
        overheard="Ten minutes left, we're 1-0 up. Squeaky bum time.",
        speaker="him",
        gist="Nervous closing stages protecting a lead",
        decoys=["The bit where players start time-wasting", "Players sitting down because they're exhausted"],
        when=["run-in", "title", "relegation", "derby", "after-win"],
    ),
    "six-pointer": dict(
        overheard="Both of us down there. This is a proper six-pointer on Saturday.",
        speaker="him",
        gist="A match between two sides chasing the same place",
        decoys=["A match where a win is worth six points", "A game decided by six goals or more"],
        when=["title", "relegation", "run-in"],
    ),
    "top-four": dict(
        overheard="Top four with six to play. That's the season now.",
        speaker="pundit",
        gist="A finish high enough for Champions League",
        decoys=["The four best players picked by the fans", "Winning the league and lifting the trophy"],
        when=["top-four", "run-in"],
    ),
    "title-race": dict(
        overheard="Nobody's running away with this title race, are they?",
        speaker="pundit",
        gist="Two or more clubs close at the top with games left",
        decoys=["A sprint between players to reach the ball", "The final few weeks of the season"],
        when=["title", "run-in"],
    ),
    "relegation-battle": dict(
        overheard="They're properly in a relegation battle now. Grim.",
        speaker="chat",
        gist="A scrap near the bottom to avoid going down",
        decoys=["A fight that breaks out between players", "A play-off to decide who goes up a division"],
        when=["relegation", "run-in"],
    ),
    "sitter": dict(
        overheard="He's missed a sitter from six yards. Unbelievable.",
        speaker="him",
        gist="A chance so easy it should have been a goal",
        decoys=["A shot dragged wide from a tight angle", "A shot the keeper palms away at full stretch"],
        when=["any", "after-loss", "after-draw"],
    ),
    "clinical-finish": dict(
        overheard="That's clinical finishing. One chance, one goal.",
        speaker="pundit",
        gist="A calm, precise shot that beats the keeper",
        decoys=["The medical team checking a player over", "A goal that takes a big deflection"],
        when=["after-win", "after-big-win", "good-run"],
    ),
    "screamer": dict(
        overheard="Thirty yards out. That is a screamer.",
        speaker="telly",
        gist="A goal hit very hard from a long way out",
        decoys=["A fan yelling abuse from the stand", "A shot that flies well over the bar"],
        when=["any", "after-win", "after-big-win"],
    ),
    "top-bins": dict(
        overheard="TOP BINS. The keeper never moved.",
        speaker="him",
        gist="The corner of the net nobody can reach",
        decoys=["The club sitting at the top of the table", "A shot that creeps in off the inside of the post"],
        when=["any", "after-win", "after-big-win"],
    ),
    "worldie": dict(
        overheard="That's a worldie. Nothing else you can call it.",
        speaker="chat",
        gist="A goal of genuine world-class quality",
        decoys=["A goal scored at the World Cup", "A goal that wins goal of the month"],
        when=["after-win", "after-big-win"],
    ),
    "hit-the-woodwork": dict(
        overheard="That's twice they've hit the woodwork. Not their day.",
        speaker="telly",
        gist="The ball struck the post or bar and stayed out",
        decoys=["The ball smashed into the boards behind the goal", "The keeper tipped it round the post"],
        when=["any", "after-draw", "after-loss"],
    ),
    "row-z": dict(
        overheard="He's put that in Row Z. My nan could have scored.",
        speaker="him",
        gist="The back of the stand, where a wild shot lands",
        decoys=["The seat number printed on his ticket", "A shot cleared off the line by a defender"],
        when=["any", "after-draw"],
    ),
    "howler": dict(
        overheard="Absolute howler from the keeper. Straight through his hands.",
        speaker="chat",
        gist="A glaring, embarrassing mistake",
        decoys=["A save so good the crowd roared", "A shot hit so hard it screamed in"],
        when=["any", "after-loss", "after-heavy-loss"],
    ),
    "hospital-ball": dict(
        overheard="That's a hospital ball. He's hung him out to dry.",
        speaker="pundit",
        gist="A loose pass that leaves a teammate in trouble",
        decoys=["A charity match played for a local hospital", "A heavy touch that gives the ball away"],
        when=["any", "after-loss", "after-heavy-loss"],
    ),
    "hoof": dict(
        overheard="Just hoof it! Anywhere but there.",
        speaker="him",
        gist="Boot the ball clear with no particular aim",
        decoys=["Stamp on an opponent's foot deliberately", "Pass it back to the keeper to settle things"],
        when=["any", "relegation"],
    ),
    "dive": dict(
        overheard="He's dived, ref! There's not a hand on him.",
        speaker="him",
        gist="Falling over on purpose to win a foul",
        decoys=["A goalkeeper throwing himself at a shot", "Going down hurt to waste a bit of time"],
        when=["any", "derby"],
    ),
    "early-bath": dict(
        overheard="Second yellow. That's an early bath for him.",
        speaker="telly",
        gist="Sent off, heading for the showers",
        decoys=["Going home before the final whistle", "Being left out of the squad altogether"],
        when=["any", "derby", "after-loss"],
    ),
    "handbags": dict(
        overheard="Bit of handbags at the corner flag there.",
        speaker="chat",
        gist="A bit of pushing and shoving, nothing more",
        decoys=["The bags the kit man carries onto the pitch", "A proper brawl that gets two players sent off"],
        when=["any", "derby"],
    ),
    "in-the-book": dict(
        overheard="He's in the book after four minutes. Silly, that.",
        speaker="him",
        gist="The referee has shown him a yellow card",
        decoys=["His name is on the team sheet for today", "He has been sent off and must leave"],
        when=["any", "derby"],
    ),
    "hooked": dict(
        overheard="He's getting hooked at half-time, watch.",
        speaker="him",
        gist="Taken off for playing badly, not for a rest",
        decoys=["Caught by an arm and pulled back illegally", "Left out of the squad before the match"],
        when=["after-loss", "after-heavy-loss", "bad-run"],
    ),
    "nutmeg": dict(
        overheard="He's nutmegged him and the whole ground's gone up.",
        speaker="telly",
        gist="Knocking the ball through a defender's legs",
        decoys=["Kicking an opponent on the ankle by accident", "A shot that squeezes under the keeper"],
        when=["any", "after-win", "after-big-win"],
    ),
    "done-him": dict(
        overheard="He's done him for pace. Not seen him since.",
        speaker="chat",
        gist="Leaving a defender standing",
        decoys=["Fouling an opponent on purpose", "Marking a player out of the game"],
        when=["any", "after-win", "after-big-win"],
    ),
    "caught-napping": dict(
        overheard="They were caught napping at the back post again.",
        speaker="pundit",
        gist="Switching off and letting an attacker get free",
        decoys=["A player having a sleep before an evening game", "Being beaten in the air by a taller player"],
        when=["any", "after-loss", "after-draw", "after-heavy-loss"],
    ),
    "against-the-run-of-play": dict(
        overheard="That's against the run of play. They've been second to everything.",
        speaker="telly",
        gist="A goal for the side who have been worse",
        decoys=["A goal scored while the clock was stopped", "A goal that came from a counter-attack"],
        when=["after-win", "after-loss", "after-draw"],
    ),
    "smash-and-grab": dict(
        overheard="Smash and grab, that. We had one shot and won.",
        speaker="him",
        gist="A win in a match you were outplayed in",
        decoys=["A tackle that takes the ball and the man", "A late equaliser to rescue a point"],
        when=["after-win", "after-loss", "derby"],
    ),
    "game-of-two-halves": dict(
        overheard="Game of two halves, this. You'd not know it was the same eleven.",
        speaker="pundit",
        gist="A match that turned after the break",
        decoys=["A match split into two equal periods", "A match where both sides scored twice"],
        when=["after-win", "after-loss", "after-draw"],
    ),
    "backs-to-the-wall": dict(
        overheard="Backs to the wall for twenty minutes here. Some defending.",
        speaker="telly",
        gist="Soaking up heavy pressure near your own goal",
        decoys=["Players lining up in a wall at a free-kick", "Playing the ball back to the keeper to waste time"],
        when=["after-clean-sheet", "after-win", "europe", "derby"],
    ),
    "in-the-mixer": dict(
        overheard="Get it in the mixer! We've nothing to lose now.",
        speaker="him",
        gist="Launching the ball into a crowded penalty area",
        decoys=["Swapping the players' positions around", "Passing it about at the back to keep it"],
        when=["any", "after-draw", "relegation"],
    ),
    "route-one": dict(
        overheard="Proper route one stuff, this. Kick it and chase it.",
        speaker="pundit",
        gist="Kicking it long and chasing it, no build-up",
        decoys=["The coach taking the shortest road to the ground", "Working the ball wide and crossing it"],
        when=["any", "relegation"],
    ),
    "on-the-break": dict(
        overheard="They'll hurt you on the break, this lot. All pace.",
        speaker="him",
        gist="Attacking fast the moment you win the ball",
        decoys=["Scoring right after the half-time interval", "Winning the ball high up the pitch"],
        when=["any", "europe"],
    ),
    "dead-rubber": dict(
        overheard="It's a dead rubber. He's resting half the side.",
        speaker="chat",
        gist="A match with nothing riding on it any more",
        decoys=["A match played with a worn-out ball", "A match replayed after a draw"],
        when=["run-in", "europe"],
    ),
    "giant-killing": dict(
        overheard="A giant-killing is on the cards here, you feel.",
        speaker="telly",
        gist="A small club knocking a big one out of a cup",
        decoys=["A very tall striker dominating the box", "A big club signing a lower-league player"],
        when=["cup"],
    ),
    "hairdryer": dict(
        overheard="One nil down and shocking. Hairdryer time in there.",
        speaker="chat",
        gist="A manager screaming at players up close",
        decoys=["A blast of hot air blowing across the pitch", "A quiet word with a player on the touchline"],
        when=["bad-run", "new-manager", "after-loss", "after-heavy-loss"],
    ),
    "man-of-the-match": dict(
        overheard="Man of the match for me, and he didn't even score.",
        speaker="pundit",
        gist="The player judged best on the day",
        decoys=["The captain who leads the side out", "The supporters' player of the season"],
        when=["any", "after-win"],
    ),
    "top-drawer": dict(
        overheard="Top drawer, that pass. Didn't even look up.",
        speaker="pundit",
        gist="Excellent, the very highest quality",
        decoys=["The top division of English football", "A pass that splits the defence open"],
        when=["any", "after-win", "after-big-win"],
    ),
    "second-ball": dict(
        overheard="They're winning every second ball. That's the game.",
        speaker="telly",
        gist="Whatever drops loose after a header",
        decoys=["A spare match ball kept by the fourth official", "The second goal that settles a match"],
        when=["any", "cup", "derby"],
    ),
    "unlucky": dict(
        overheard="Unlucky, son! That was never going in anyway.",
        speaker="him",
        gist="A shout of sympathy at a player who missed",
        decoys=["A player who keeps picking up injuries", "A groan when the keeper makes a save"],
        when=["any", "after-loss", "after-draw"],
    ),
}
