# Overheard content for category "match_situations". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "kick-off": dict(
        overheard="Kick-off's at three. I'll be no use to anyone after that.",
        speaker="him",
        gist="The moment the match starts",
        decoys=["The coin toss that decides which way to play", "The first shot that tests the keeper"],
        when=["any"],
        basic=True,
    ),
    "half-time": dict(
        overheard="Right, that's half-time. I'm putting the kettle on, do you want one?",
        speaker="him",
        gist="The break in the middle of the match",
        decoys=["The fifteen minutes before kick-off", "A short break for drinks in hot weather"],
        when=["any"],
        basic=True,
    ),
    "full-time": dict(
        overheard="Full-time here. They'll take that, I'm sure.",
        speaker="telly",
        gist="The referee ends it, whatever the score",
        decoys=["The end of the first of the two halves", "The whistle that starts the added minutes"],
        when=["any"],
        basic=True,
    ),
    "nil-nil": dict(
        overheard="Nil-nil, that. He'll be in a mood all night.",
        speaker="him",
        gist="Nobody scored, the match finished level",
        decoys=["The game was abandoned, so no score counts", "A draw where both sides scored"],
        when=["after-draw", "after-clean-sheet"],
    ),
    "see-the-game-out": dict(
        overheard="They just need to see the game out from here.",
        speaker="telly",
        gist="Protect a lead until the final whistle",
        decoys=["Stay on the pitch without getting sent off", "Push for another goal to settle it"],
        when=["after-win", "after-clean-sheet", "derby", "run-in"],
    ),
    "squeaky-bum-time": dict(
        overheard="Squeaky bum time now. Don't talk to me.",
        speaker="him",
        gist="The jitters as the clock winds down",
        decoys=["The bit where players start time-wasting", "The nervous wait while a goal is checked"],
        when=["run-in", "title", "relegation", "derby", "after-win"],
    ),
    "six-pointer": dict(
        overheard="Six-pointer on Saturday. Don't be planning anything.",
        speaker="him",
        gist="A match between two sides chasing the same place",
        decoys=["A match where a win is worth six points", "A game worth double because it is a derby"],
        when=["title", "relegation", "run-in"],
    ),
    "top-four": dict(
        overheard="Top four, and he'd call the season a success.",
        speaker="pundit",
        gist="A finish high enough for Champions League",
        decoys=["Winning the league and lifting the trophy", "The sides who reach a cup semi-final"],
        when=["top-four", "run-in"],
    ),
    "title-race": dict(
        overheard="This title race is doing my head in.",
        speaker="chat",
        gist="The close fight at the top of the table",
        decoys=["The final few weeks of the season", "The scrap for a place in Europe"],
        when=["title", "run-in"],
    ),
    "relegation-battle": dict(
        overheard="They're properly in a relegation battle now. Grim.",
        speaker="chat",
        gist="A scrap near the bottom to avoid going down",
        decoys=["A play-off to decide who goes up a division", "A run of hard games against the top clubs"],
        when=["relegation", "run-in"],
    ),
    "sitter": dict(
        overheard="He's missed a sitter there. I've seen enough.",
        speaker="him",
        gist="A chance so easy it should have been a goal",
        decoys=["A shot dragged wide from a tight angle", "A shot the keeper palms away at full stretch"],
        when=["any", "after-loss", "after-draw"],
    ),
    "clinical-finish": dict(
        overheard="That's clinical finishing. He'll sleep well tonight.",
        speaker="pundit",
        gist="A calm, precise shot that beats the keeper",
        decoys=["A goal that takes a big deflection", "A move drilled on the training ground"],
        when=["after-win", "after-big-win", "good-run"],
    ),
    "screamer": dict(
        overheard="And that is a screamer. Get the replay on.",
        speaker="telly",
        gist="A goal hit very hard from a long way out",
        decoys=["A shot that flies well over the bar", "A goal that settles a nervy game late on"],
        when=["any", "after-win", "after-big-win"],
    ),
    "top-bins": dict(
        overheard="TOP BINS. Oh, that's filthy, that is.",
        speaker="him",
        gist="A corner of the goal no keeper can reach",
        decoys=["A shot that creeps in off the inside of the post", "A shot the keeper gets a hand to and can't stop"],
        when=["any", "after-win", "after-big-win"],
    ),
    "worldie": dict(
        overheard="Worldie, that. I've watched it four times.",
        speaker="chat",
        gist="A goal of genuine world-class quality",
        decoys=["A goal scored at the World Cup", "A goal that wins goal of the month"],
        when=["after-win", "after-big-win"],
    ),
    "hit-the-woodwork": dict(
        overheard="That's twice they've hit the woodwork. Not their day.",
        speaker="telly",
        gist="The ball struck the post or bar and stayed out",
        decoys=["The ball smashed into the boards behind the goal", "A shot that beat the keeper and went wide"],
        when=["any", "after-draw", "after-loss"],
    ),
    "row-z": dict(
        overheard="He's put that in Row Z. He'll not want to see that again.",
        speaker="him",
        gist="The back of the stand, where a wild shot lands",
        decoys=["A shot that clears the crossbar by inches", "The seats behind the goal at either end"],
        when=["any", "after-draw"],
    ),
    "howler": dict(
        overheard="Absolute howler from the keeper. Have you seen it?",
        speaker="chat",
        gist="A glaring, embarrassing mistake",
        decoys=["A save so good the crowd roared", "A furious shout at his own defenders"],
        when=["any", "after-loss", "after-heavy-loss"],
    ),
    "hospital-ball": dict(
        overheard="That's a hospital ball. He can't be doing that at this level.",
        speaker="pundit",
        gist="A loose pass that leaves a teammate in trouble",
        decoys=["A heavy touch that gives the ball away", "A challenge bad enough to injure someone"],
        when=["any", "after-loss", "after-heavy-loss"],
    ),
    "hoof": dict(
        overheard="Just hoof it! He's under pressure there.",
        speaker="him",
        gist="Boot the ball clear with no particular aim",
        decoys=["Knock it back to the keeper to start again", "Put it out of play to stop the attack"],
        when=["any", "relegation"],
    ),
    "dive": dict(
        overheard="He's dived, ref! Are you watching this?",
        speaker="him",
        gist="Falling over on purpose to win a foul",
        decoys=["Going down hurt to waste a bit of time", "Sliding in feet first to win the ball"],
        when=["any", "derby"],
    ),
    "early-bath": dict(
        overheard="That's an early bath for him, then. Silly boy.",
        speaker="telly",
        gist="Sent off, heading for the showers",
        decoys=["Subbed off before he gets himself booked", "Missing the next game as punishment"],
        when=["any", "derby", "after-loss"],
    ),
    "handbags": dict(
        overheard="Handbags at the corner flag. The ref's got a job on.",
        speaker="chat",
        gist="A bit of pushing and shoving, nothing more",
        decoys=["A proper brawl that gets two players sent off", "Players surrounding the referee in a group"],
        when=["any", "derby"],
    ),
    "in-the-book": dict(
        overheard="He's in the book after four minutes. Calm down, lad.",
        speaker="him",
        gist="The referee has shown him a yellow card",
        decoys=["He has been sent off and must leave", "The referee has spoken to him and let him off"],
        when=["any", "derby"],
    ),
    "hooked": dict(
        overheard="He's getting hooked here. He knows it, too.",
        speaker="him",
        gist="Taken off for playing badly, not for a rest",
        decoys=["Caught by an arm and pulled back illegally", "Swapped out to save him for the next game"],
        when=["after-loss", "after-heavy-loss", "bad-run"],
    ),
    "nutmeg": dict(
        overheard="He's nutmegged him and the ground's gone up.",
        speaker="telly",
        gist="Knocking the ball through a defender's legs",
        decoys=["Barging a defender off the ball and going past", "Flicking the ball over a defender's head"],
        when=["any", "after-win", "after-big-win"],
    ),
    "done-him": dict(
        overheard="He's done him there. Watch the replay of that.",
        speaker="chat",
        gist="Leaving a defender standing",
        decoys=["Fouling an opponent on purpose", "Rounding the keeper and walking it in"],
        when=["any", "after-win", "after-big-win"],
    ),
    "caught-napping": dict(
        overheard="Caught napping again, that lot. Dear me.",
        speaker="pundit",
        gist="Switching off and letting an attacker get free",
        decoys=["Losing a header to a much taller player", "Being caught too high up when it turns over"],
        when=["any", "after-loss", "after-draw", "after-heavy-loss"],
    ),
    "against-the-run-of-play": dict(
        overheard="That is against the run of play, no question.",
        speaker="telly",
        gist="A goal for the side who have been worse",
        decoys=["A goal that came from a counter-attack", "A goal scored in the closing minutes"],
        when=["after-win", "after-loss", "after-draw"],
    ),
    "smash-and-grab": dict(
        overheard="Smash and grab, that. Typical of this lot.",
        speaker="him",
        gist="A win in a match you were outplayed in",
        decoys=["A tackle that takes the ball and the man", "A late equaliser to rescue a point"],
        when=["after-win", "after-loss", "derby"],
    ),
    "game-of-two-halves": dict(
        overheard="It's been a game of two halves, hasn't it?",
        speaker="pundit",
        gist="A match that turned after the break",
        decoys=["A match split into two equal periods", "A match where both sides scored twice"],
        when=["after-win", "after-loss", "after-draw"],
    ),
    "backs-to-the-wall": dict(
        overheard="Backs to the wall for the home side, and the noise is up.",
        speaker="telly",
        gist="Soaking up heavy pressure near your own goal",
        decoys=["Players lining up in a wall at a free-kick", "Playing the ball back to the keeper to waste time"],
        when=["after-clean-sheet", "after-win", "europe", "derby"],
    ),
    "in-the-mixer": dict(
        overheard="Get it in the mixer! Stop faffing about.",
        speaker="him",
        gist="Launching the ball into a crowded penalty area",
        decoys=["Getting it wide to the winger to cross", "Booting it into the corner to run the clock"],
        when=["any", "after-draw", "relegation"],
    ),
    "route-one": dict(
        overheard="Proper route one stuff, this. Not for me.",
        speaker="pundit",
        gist="Kicking it long and chasing it, no build-up",
        decoys=["Working the ball wide and crossing it", "Passing it through the middle at speed"],
        when=["any", "relegation"],
    ),
    "on-the-break": dict(
        overheard="They'll hurt you on the break, this lot. Watch.",
        speaker="him",
        gist="Attacking at speed before they can get back",
        decoys=["Scoring right after the half-time interval", "Winning the ball high up the pitch"],
        when=["any", "europe"],
    ),
    "dead-rubber": dict(
        overheard="Dead rubber tonight. I'll probably miss it.",
        speaker="chat",
        gist="A match with nothing riding on it any more",
        decoys=["A match played with a worn-out ball", "A match replayed after a draw"],
        when=["run-in", "europe"],
    ),
    "giant-killing": dict(
        overheard="The ground can smell a giant-killing now.",
        speaker="telly",
        gist="A small club knocking a big one out of a cup",
        decoys=["A tall side winning everything in the air", "A late winner that dumps a team out of a cup"],
        when=["cup"],
    ),
    "hairdryer": dict(
        overheard="Hairdryer time in that dressing room, I bet.",
        speaker="chat",
        gist="A manager screaming at players up close",
        decoys=["A calm team talk to settle everyone down", "A row between players in the dressing room"],
        when=["bad-run", "new-manager", "after-loss", "after-heavy-loss"],
    ),
    "man-of-the-match": dict(
        overheard="They've got man of the match wrong again, you know.",
        speaker="pundit",
        gist="The player judged best on the day",
        decoys=["The supporters' player of the season", "The player who speaks to the cameras after"],
        when=["any", "after-win"],
    ),
    "top-drawer": dict(
        overheard="He's top drawer, that lad. Always has been.",
        speaker="pundit",
        gist="Excellent, the very highest quality",
        decoys=["The top division of English football", "A player kept back for the big games"],
        when=["any", "after-win", "after-big-win"],
    ),
    "second-ball": dict(
        overheard="It's all about the second ball, this.",
        speaker="telly",
        gist="Whatever drops loose after a header",
        decoys=["A cross played in after a short corner", "The second goal that settles a match"],
        when=["any", "cup", "derby"],
    ),
    "unlucky": dict(
        overheard="Unlucky! Oh, for crying out loud.",
        speaker="him",
        gist="A shout of sympathy at a player who missed",
        decoys=["A groan when the keeper makes a save", "A shout at the referee for a poor call"],
        when=["any", "after-loss", "after-draw"],
    ),
}
