# Overheard content for category "rules". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "premier-league": dict(
        overheard="First Premier League game of the season on Saturday. Finally.",
        speaker="him",
        gist="England's top division, twenty clubs, August to May",
        decoys=["A knockout competition for the top clubs", "Midweek matches against clubs from Europe"],
        when=["any", "early-season"],
    ),
    "points": dict(
        overheard="didnt deserve that at all but ill take the points.",
        speaker="chat",
        gist="Three for a win, one for a draw, none for a loss",
        decoys=["Goals scored, added up over the season", "The gap in the table between two clubs"],
        when=["any", "run-in", "after-win", "after-draw"],
    ),
    "the-table": dict(
        overheard="Have a look at the table. Fourth, and a game in hand.",
        speaker="him",
        gist="Every club ranked by points, top to bottom",
        decoys=["A fixture list showing who plays who", "The list of goalscorers across the season"],
        when=["any", "run-in", "title", "top-four", "relegation"],
    ),
    "goal-difference": dict(
        overheard="Level on points, so goal difference decides it. They need three more.",
        speaker="pundit",
        gist="Goals scored minus goals let in",
        decoys=["The margin of victory in one match", "Shots on target against shots off it"],
        when=["run-in", "title", "top-four", "relegation", "after-big-win"],
    ),
    "relegation": dict(
        overheard="If we don't win tonight we're in a relegation scrap by Christmas.",
        speaker="him",
        gist="Dropping out of the division at the bottom",
        decoys=["A player pushed down to the reserves", "Finishing outside the places for Europe"],
        when=["relegation", "run-in"],
    ),
    "promotion": dict(
        overheard="mate they've done it. promotion with three games to spare.",
        speaker="chat",
        gist="Going up a division at the end of a season",
        decoys=["A player moved up into the first team", "Winning a cup and qualifying for Europe"],
        when=["early-season", "run-in"],
    ),
    "championship": dict(
        overheard="He's a Championship player at this level, I'm afraid.",
        speaker="pundit",
        gist="The division below the top one in England",
        decoys=["The trophy for winning the top division", "The group stage before a knockout round"],
        when=["early-season", "relegation"],
    ),
    "play-offs": dict(
        overheard="Third place, so it's the play-offs for them in May.",
        speaker="telly",
        gist="A mini knockout deciding who goes up",
        decoys=["Matches called off and rearranged later", "The two-legged semi-final of a cup"],
        when=["early-season", "run-in"],
    ),
    "offside": dict(
        overheard="Flag's up. He was offside by a mile, look at the replay.",
        speaker="him",
        gist="He was beyond the final defender for the pass",
        decoys=["He'd stepped off the side of the pitch", "He handled the ball before he shot"],
        when=["any"],
    ),
    "var": dict(
        overheard="VAR is checking for a possible offside. Bear with us.",
        speaker="telly",
        gist="The video referee is looking at the replay",
        decoys=["The ref is checking his watch for added time", "The goal has already been ruled out"],
        when=["any"],
    ),
    "clear-and-obvious": dict(
        overheard="Four minutes on the monitor. That is not clear and obvious.",
        speaker="pundit",
        gist="A decision so wrong nobody could argue",
        decoys=["A camera angle with a good view of it", "The referee explaining his call out loud"],
        when=["any"],
    ),
    "foul": dict(
        overheard="Foul, ref! He's kicked him halfway up the pitch.",
        speaker="him",
        gist="Going through the man instead of the ball",
        decoys=["Any tackle that wins the ball cleanly", "Arguing with the referee after a decision"],
        when=["any"],
    ),
    "handball": dict(
        overheard="handball there surely. his arm was up by his head!",
        speaker="chat",
        gist="Touching the ball with an arm on purpose",
        decoys=["The keeper picking the ball up in the box", "A throw taken with one hand only"],
        when=["any"],
    ),
    "penalty": dict(
        overheard="The referee points to the spot. It's a penalty.",
        speaker="telly",
        gist="A free shot from twelve yards, keeper alone",
        decoys=["A punishment card shown after a bad tackle", "A free kick given just outside the box"],
        when=["any"],
    ),
    "the-box": dict(
        overheard="Get it in the box! Nobody's attacking the cross.",
        speaker="him",
        gist="The rectangle in front of goal, eighteen yards deep",
        decoys=["The dugout where the manager and subs sit", "The six-yard area a keeper kicks from"],
        when=["any"],
    ),
    "free-kick": dict(
        overheard="Lovely position for a free kick, twenty-five yards out.",
        speaker="pundit",
        gist="A restart from where the offence happened",
        decoys=["A shot nobody is allowed to stand in front of", "A drop ball to restart after an injury"],
        when=["any"],
    ),
    "corner": dict(
        overheard="Corner. Get the big lads up, this is our chance.",
        speaker="him",
        gist="A kick from the flag after the defence put it out",
        decoys=["The point where two touchlines meet", "A throw-in taken from near the goal line"],
        when=["any"],
    ),
    "throw-in": dict(
        overheard="Throw-in to them, deep inside their own half.",
        speaker="telly",
        gist="Restarting play from the sideline with two hands",
        decoys=["Giving up and letting the other lot win", "A free kick taken from the sideline"],
        when=["any"],
    ),
    "yellow-card": dict(
        overheard="hes on a yellow card and he's still diving in.",
        speaker="chat",
        gist="A formal warning, two of them and you're off",
        decoys=["A note the referee writes the goals down on", "A ban from the next match, straight away"],
        when=["any"],
    ),
    "red-card": dict(
        overheard="It's a red card. He's the last man and he's hauled him down.",
        speaker="pundit",
        gist="A sending off, so they play a man short",
        decoys=["A warning before the referee books you", "A penalty given for a foul in the box"],
        when=["any", "derby"],
    ),
    "ten-men": dict(
        overheard="Ten men for half an hour and we've held on. Unbelievable.",
        speaker="him",
        gist="Playing a man short after a sending off",
        decoys=["The eleven on the pitch minus the keeper", "A defensive shape with nobody up front"],
        when=["any", "after-loss"],
    ),
    "added-time": dict(
        overheard="Six minutes of added time to be played here.",
        speaker="telly",
        gist="Extra play at the end for stoppages",
        decoys=["Time taken off the clock for a substitution", "The clock stopping whenever the ball goes out"],
        when=["any"],
    ),
    "extra-time": dict(
        overheard="Thirty more minutes. Extra time, and the legs have gone already.",
        speaker="pundit",
        gist="Half an hour more to settle a cup game",
        decoys=["A short break before penalties are taken", "The same round played again a week later"],
        when=["cup", "europe"],
    ),
    "penalty-shootout": dict(
        overheard="penalty shootout. i cant look, text me when its done.",
        speaker="chat",
        gist="A round of five spot kicks each, then sudden death",
        decoys=["A quick round of shots in the warm-up", "A free shot from twelve yards during play"],
        when=["cup", "europe"],
    ),
    "two-legs": dict(
        overheard="Remember, this is over two legs. Nothing is settled tonight.",
        speaker="telly",
        gist="One round played as two matches, home and away",
        decoys=["The two halves either side of the half-time break", "A round replayed at another ground after a draw"],
        when=["europe", "cup"],
    ),
    "aggregate": dict(
        overheard="They're two up on the night, three-two on aggregate.",
        speaker="pundit",
        gist="The two scores added together over a round",
        decoys=["A club's goals added up across a season", "The gap between goals scored and let in"],
        when=["europe", "cup"],
    ),
    "substitution": dict(
        overheard="First substitution already and it's only half an hour gone.",
        speaker="him",
        gist="Swapping a player on the pitch for one waiting",
        decoys=["Moving a player into a different position", "A change of shape with nobody coming off"],
        when=["any"],
    ),
    "the-bench": dict(
        overheard="hes on the bench again. third game running now…",
        speaker="chat",
        gist="The substitutes waiting beside the pitch",
        decoys=["The seats where the away fans sit", "The players left out of the squad entirely"],
        when=["any", "cup"],
    ),
    "starting-eleven": dict(
        overheard="Team's up. Same starting eleven as Saturday.",
        speaker="him",
        gist="The players who begin the match",
        decoys=["The order the players run out in", "The squad named for a European round"],
        when=["any", "early-season"],
    ),
    "clean-sheet": dict(
        overheard="Another clean sheet. That's four in six for the back four.",
        speaker="pundit",
        gist="Letting in no goals at all in a match",
        decoys=["A fresh set of kit for the second half", "Winning without conceding a penalty"],
        when=["after-clean-sheet", "after-win", "good-run"],
    ),
    "own-goal": dict(
        overheard="Oh, that's an own goal. Off the defender's shin and in.",
        speaker="telly",
        gist="A ball put into your own net by mistake",
        decoys=["A goal you score on your own, unassisted", "A goal the referee chalks off for a foul"],
        when=["any", "after-loss"],
    ),
    "brace": dict(
        overheard="two for him already. that's a brace by half-time.",
        speaker="chat",
        gist="Two goals by one player in a match",
        decoys=["A strapping worn on a knee or ankle", "Two players scoring in the same move"],
        when=["after-win", "after-big-win"],
    ),
    "hat-trick": dict(
        overheard="He's got his hat-trick! Match ball going home with him.",
        speaker="him",
        gist="Three goals by one player in a match",
        decoys=["Three different clubs beaten in one week", "A goal, an assist and a clean sheet in one game"],
        when=["after-win", "after-big-win"],
    ),
    "assist": dict(
        overheard="Ten goals and eight assists from midfield. Quietly brilliant.",
        speaker="pundit",
        gist="The pass that leads straight to a goal",
        decoys=["A player helping the keeper organise the wall", "The cross that wins a corner"],
        when=["any", "after-win"],
    ),
    "fixtures": dict(
        overheard="Fixtures are out. We've got them away on Boxing Day.",
        speaker="him",
        gist="The list of who plays who, and when",
        decoys=["Repairs being done to the ground in summer", "The order the clubs sit in, by points"],
        when=["any", "early-season"],
    ),
    "derby": dict(
        overheard="derby weekend. nobody book anything sunday, im no use after.",
        speaker="chat",
        gist="A match between two clubs from the same city",
        decoys=["A horse race the fixture is named after", "A repeat of a cup final from a season before"],
        when=["derby"],
    ),
    "the-cups": dict(
        overheard="We're out of both cups by January. Brilliant, that.",
        speaker="him",
        gist="The knockout competitions run beside the season",
        decoys=["The trophies on show in the club museum", "The group stage played midweek in Europe"],
        when=["cup"],
    ),
    "fa-cup": dict(
        overheard="Third round of the FA Cup, and a non-league side lead.",
        speaker="telly",
        gist="The oldest knockout competition, open to every club",
        decoys=["The competition every club in Europe can enter", "The knockout for clubs from the lower divisions"],
        when=["cup"],
    ),
    "league-cup": dict(
        overheard="It's the League Cup. He'll make eight changes and nobody minds.",
        speaker="pundit",
        gist="The smaller of the two domestic cups",
        decoys=["A trophy for the winners of the division", "The pre-season tournament played in August"],
        when=["cup"],
    ),
    "champions-league": dict(
        overheard="That anthem, those lights. Champions League football is back.",
        speaker="telly",
        gist="Europe's top club competition, midweek nights",
        decoys=["A competition for the winners of each division", "The summer tournament between national sides"],
        when=["europe", "top-four", "title"],
    ),
    "europa-league": dict(
        overheard="Thursday nights in the Europa League. Rock and roll.",
        speaker="him",
        gist="Europe's second competition, below the top one",
        decoys=["The knockout stage of Europe's top competition", "A tournament for national sides in Europe"],
        when=["europe", "top-four"],
    ),
    "conference-league": dict(
        overheard="conference league away trip in november. whos coming?",
        speaker="chat",
        gist="Europe's third competition, below the other two",
        decoys=["A meeting of clubs about the rules", "The qualifying round before a group stage"],
        when=["europe", "top-four"],
    ),
    "transfer-window": dict(
        overheard="The transfer window shuts Monday and they've signed nobody.",
        speaker="pundit",
        gist="The weeks when clubs can buy and sell players",
        decoys=["The board showing which players came off", "The fee one club pays another for a player"],
        when=["window", "early-season"],
    ),
    "deadline-day": dict(
        overheard="It's deadline day and the window shuts at eleven tonight. Stay with us.",
        speaker="telly",
        gist="The final day clubs can buy or sell players",
        decoys=["The final day to buy tickets for the season", "Cut-off for naming the squad for a cup"],
        when=["window"],
    ),
    "loan": dict(
        overheard="He's gone out on loan for the season. Needs the games.",
        speaker="him",
        gist="Borrowing a player from another club for a while",
        decoys=["Money a club borrows to build a new stand", "Signing a player and paying in instalments"],
        when=["window", "early-season"],
    ),
    "sacked": dict(
        overheard="hes getting sacked in the morning and about time too.",
        speaker="chat",
        gist="A manager losing his job over bad results",
        decoys=["A player dropped from the squad for a game", "A manager leaving for a bigger club"],
        when=["bad-run", "new-manager", "after-heavy-loss"],
    ),
}
