# Overheard content for category "rules". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "premier-league": dict(
        overheard="Premier League is back Saturday. Three months of my life, gone.",
        speaker="him",
        gist="England's top division of twenty clubs",
        decoy="Britain's top clubs, English and Scottish",
        spare="All the English divisions taken together",
        when=["any", "early-season"],
        moment="anytime",
        basic=True,
    ),
    "points": dict(
        overheard="didnt deserve that at all but ill take the points.",
        speaker="chat",
        gist="Three for a win and one for a draw",
        decoy="One for every goal, added up all season",
        spare="A tally handed out by finishing position",
        when=["any", "run-in", "after-win", "after-draw"],
        moment="common",
    ),
    "the-table": dict(
        overheard="Have a look at the table and tell me that's fair.",
        speaker="him",
        gist="Every club ordered by points won",
        decoy="Weekend fixtures listed by kick-off time",
        spare="The clubs sorted by goals scored so far",
        when=["any", "run-in", "title", "top-four", "relegation"],
        moment="anytime",
        basic=True,
    ),
    "goal-difference": dict(
        overheard="I think this one goes to goal difference. That's a worry.",
        speaker="pundit",
        gist="Goals scored minus goals let in",
        decoy="Margin of victory in a single match",
        spare="A gap in points between two clubs",
        when=["run-in", "title", "top-four", "relegation", "after-big-win"],
        moment="anytime",
    ),
    "relegation": dict(
        overheard="If we don't win tonight we're in a relegation scrap by Christmas.",
        speaker="him",
        gist="Dropping out of the division at the bottom",
        decoy="Being pushed down into the reserves",
        spare="Finishing outside the places for Europe",
        when=["relegation", "run-in"],
        moment="anytime",
        player=dict(
            slot='ours.forward',
            overheard="If it's a relegation scrap, does a lad like {ours.forward} stick around?",
            sayIt='"Would {ours.forward} still be here if it was a relegation scrap?"',
        ),
    ),
    "promotion": dict(
        overheard="mate they've done it. promotion with three games to spare.",
        speaker="chat",
        gist="Moving up into the division above",
        decoy="Moving up into the first team",
        spare="Finishing top of the division, champions",
        when=["early-season", "run-in"],
        moment="anytime",
    ),
    "championship": dict(
        overheard="He's a Championship player at this level, I'm afraid.",
        speaker="pundit",
        gist="The division below the top one in England",
        decoy="A league for clubs' reserve and youth sides",
        spare="The tier where the clubs are part-time",
        when=["early-season", "relegation"],
        moment="anytime",
    ),
    "play-offs": dict(
        overheard="Play-offs again. I can't go through that a third year running.",
        speaker="telly",
        gist="A mini knockout deciding who goes up",
        decoy="A one-off final for the title",
        spare="Extra games to decide who avoids going down",
        when=["early-season", "run-in"],
        moment="anytime",
    ),
    "offside": dict(
        overheard="That's never offside. I don't care what the replay says.",
        speaker="him",
        gist="He was beyond the final defender for the pass",
        decoy="He got in the keeper's way at the near post",
        spare="The ball had already gone out for a goal kick",
        when=["any"],
        moment="common",
    ),
    "var": dict(
        overheard="VAR has been the story of this season, for better or worse.",
        speaker="telly",
        gist="The video referee is looking at the replay",
        decoy="A panel that reviews decisions after the match",
        spare="The screen in the ground showing the decision",
        when=["any"],
        moment="common",
    ),
    "clear-and-obvious": dict(
        overheard="They keep saying clear and obvious. I've stopped believing in it.",
        speaker="pundit",
        gist="A decision so wrong nobody could argue",
        decoy="A decision the referee got right first time",
        spare="Footage good enough to see it",
        when=["any"],
        moment="rare",
    ),
    "foul": dict(
        overheard="Foul, ref! Are you watching the same game as me?",
        speaker="him",
        gist="Going through the man instead of the ball",
        decoy="Any stoppage the referee calls, right or wrong",
        spare="Arguing with the referee after a decision",
        when=["any"],
        moment="common",
    ),
    "handball": dict(
        overheard="handball there surely. how has he not given that?",
        speaker="chat",
        gist="Touching the ball with an arm on purpose",
        decoy="Grabbing an opponent's shirt to hold him back",
        spare="The keeper picking the ball up outside his box",
        when=["any"],
        moment="common",
    ),
    "penalty": dict(
        overheard="Penalty. The whole ground has gone quiet.",
        speaker="telly",
        gist="A free shot with just the keeper to beat",
        decoy="A punishment card shown after a bad tackle",
        spare="A free kick given just outside the box",
        when=["any"],
        moment="rare",
    ),
    "the-box": dict(
        overheard="Get it in the box. Stop passing it sideways.",
        speaker="him",
        gist="The big rectangle in front of each goal",
        decoy="The dugout where the manager and subs sit",
        spare="The six-yard area a keeper kicks from",
        when=["any"],
        moment="common",
        player=dict(
            slot='theirs.keeper',
            overheard='Get it in the box and make {theirs.keeper} come and claim it.',
            sayIt='"Why not just put it in the box? {theirs.keeper} has to deal with it then."',
        ),
    ),
    "free-kick": dict(
        overheard="That's a free kick, surely. He's gone through the back of him.",
        speaker="pundit",
        gist="A restart taken from where the offence happened",
        decoy="A kick awarded for a foul inside the box",
        spare="A drop ball restart after a player's hurt",
        when=["any", "opp-set-piece"],
        moment="common",
    ),
    "corner": dict(
        overheard="Corner. Get the big lads up, this is our chance.",
        speaker="him",
        gist="A kick from the flag after a defender puts it out",
        decoy="A cross from deep while the ball is live",
        spare="A free kick given wide, level with the goal",
        when=["any", "opp-set-piece"],
        moment="common",
        basic=True,
    ),
    "throw-in": dict(
        overheard="Throw-in to them, deep inside their own half.",
        speaker="telly",
        gist="Putting the ball back in from the sideline",
        decoy="Giving up and letting the other lot have it",
        spare="A free kick given out on the touchline",
        when=["any"],
        moment="common",
        basic=True,
    ),
    "yellow-card": dict(
        overheard="yellow card for that? he's barely touched him.",
        speaker="chat",
        gist="A formal warning and a step towards a ban",
        decoy="A fine the club pays, not the player",
        spare="A ban from the next match, straight away",
        when=["any"],
        moment="common",
        player=dict(
            slot='theirs.defender',
            overheard="If {theirs.defender} picks up a yellow card early, he's in bother all afternoon.",
            sayIt='"If {theirs.defender} gets a yellow card, does he have to be careful after?"',
        ),
    ),
    "red-card": dict(
        overheard="Red card. Well, that's the game gone.",
        speaker="pundit",
        gist="A player off, and nobody replaces him",
        decoy="A warning before he is sent off",
        spare="A penalty given against them for the foul",
        when=["any", "derby"],
        moment="rare",
    ),
    "ten-men": dict(
        overheard="Ten men and we're somehow level here. Unbelievable.",
        speaker="him",
        gist="A man down for the rest of the match",
        decoy="The ten outfield players, not the keeper",
        spare="A shape with nobody up front",
        when=["any", "after-loss"],
        moment="rare",
    ),
    "added-time": dict(
        overheard="Six minutes of added time. Where has he got that from?",
        speaker="telly",
        gist="Extra play at the end for stoppages",
        decoy="Time carried over from the first half",
        spare="A count of how long the ball was out of play",
        when=["any"],
        moment="common",
    ),
    "extra-time": dict(
        overheard="Extra time it is, then. Nobody wanted that.",
        speaker="pundit",
        gist="Half an hour more to settle a cup game",
        decoy="Penalties to decide who goes through",
        spare="The same round played again a week later",
        when=["cup", "europe"],
        moment="rare",
    ),
    "penalty-shootout": dict(
        overheard="penalty shootout. i cant look, text me when its done.",
        speaker="chat",
        gist="Five spot kicks each and then sudden death",
        decoy="One kick each, whoever misses is out",
        spare="A free shot from twelve yards during play",
        when=["cup", "europe"],
        moment="rare",
        player=dict(
            slot='ours.keeper',
            overheard='penalty shootout. dont tell me how it goes. not even if {ours.keeper} saves one.',
            sayIt='"A penalty shootout. Is {ours.keeper} the one who has to save them?"',
        ),
    ),
    "two-legs": dict(
        overheard="Remember, this is over two legs. Anything can happen from here.",
        speaker="telly",
        gist="One round played as two matches home and away",
        decoy="Both halves, either side of the break",
        spare="A round decided by a second match if it's level",
        when=["europe", "cup"],
        moment="rare",
    ),
    "aggregate": dict(
        overheard="The aggregate is all that matters now. Forget the performance.",
        speaker="pundit",
        gist="Both scores added together over a round",
        decoy="Every goal a club scores in a season",
        spare="The gap between goals scored and let in",
        when=["europe", "cup"],
        moment="rare",
    ),
    "substitution": dict(
        overheard="First substitution already, and it's half an hour gone.",
        speaker="him",
        gist="Swapping a player on the pitch for one waiting",
        decoy="Taking a player off with nobody coming on",
        spare="One player moving to cover another's role",
        when=["any"],
        moment="common",
    ),
    "the-bench": dict(
        overheard="hes on the bench again. third game running now…",
        speaker="chat",
        gist="The substitutes waiting beside the pitch",
        decoy="The coaching staff sat in the dugout",
        spare="The players left out of the squad entirely",
        when=["any", "cup"],
        moment="common",
        basic=True,
    ),
    "starting-eleven": dict(
        overheard="Team's up. Same starting eleven again, he's not learning.",
        speaker="him",
        gist="The players picked to begin the match",
        decoy="The order the players run out in",
        spare="The squad named for a European round",
        when=["any", "early-season"],
        moment="common",
        basic=True,
    ),
    "clean-sheet": dict(
        overheard="Another clean sheet, and we didn't half ride our luck.",
        speaker="him",
        gist="Letting in no goals at all in a match",
        decoy="Ninety minutes with no cards and no trouble",
        spare="Winning without conceding a penalty",
        when=["after-clean-sheet", "after-win", "good-run", "opp-clean-sheets"],
        moment="common",
    ),
    "own-goal": dict(
        overheard="And that's an own goal. The second of the afternoon.",
        speaker="telly",
        gist="A ball put into your own net by mistake",
        decoy="A goal you score on your own, unassisted",
        spare="A goal that came off a defender on the way in",
        when=["any", "after-loss"],
        moment="rare",
        basic=True,
    ),
    "brace": dict(
        overheard="hes got a brace already and its not even half-time.",
        speaker="chat",
        gist="Two goals by the same player in a match",
        decoy="Strapping worn on a knee or ankle",
        spare="One goal and one assist in a match",
        when=["after-win", "after-big-win"],
        moment="rare",
    ),
    "hat-trick": dict(
        overheard="That's the hat-trick, then. What a way to spend a Saturday.",
        speaker="him",
        gist="Three goals by one man in a match",
        decoy="Three wins on the bounce for a club",
        spare="Three goals for a side inside one half",
        when=["after-win", "after-big-win"],
        moment="rare",
    ),
    "assist": dict(
        overheard="Another assist for him. He's having a season.",
        speaker="pundit",
        gist="The pass that leads straight to a goal",
        decoy="The whole move that led up to the goal",
        spare="Winning the ball back to start an attack",
        when=["any", "after-win"],
        moment="common",
        player=dict(
            slot='ours.midfielder',
            overheard='Assists, assists, assists. Nobody asks what {ours.midfielder} actually does.',
            sayIt='"Does {ours.midfielder} get many assists, or is it all goals with him?"',
        ),
    ),
    "fixtures": dict(
        overheard="Fixtures are out. I've already booked three days off.",
        speaker="him",
        gist="Who plays who each week and when",
        decoy="Dates the tickets go on sale, week by week",
        spare="The TV picks for the weekend's games",
        when=["any", "early-season"],
        moment="anytime",
        basic=True,
    ),
    "derby": dict(
        overheard="derby weekend. nobody book anything sunday, im no use after.",
        speaker="chat",
        gist="A match between two clubs from the same city",
        decoy="A fixture played every year on the same day",
        spare="Any local game with a real edge to it",
        when=["derby"],
        moment="rare",
    ),
    "the-cups": dict(
        overheard="He never takes the cups seriously and it shows.",
        speaker="him",
        gist="The knockout competitions beside the league",
        decoy="The trophies handed out at the end of a season",
        spare="The two European competitions played midweek",
        when=["cup"],
        moment="anytime",
        player=dict(
            slot='ours.defender',
            overheard="He never takes the cups seriously. I'd start {ours.defender} in every one.",
            sayIt='"Do the cups actually matter? Would you even play {ours.defender} in them?"',
        ),
    ),
    "fa-cup": dict(
        overheard="FA Cup third round. This is the one he wants.",
        speaker="telly",
        gist="The oldest knockout open to every club",
        decoy="The cup for the top two divisions",
        spare="The competition every club in Europe can enter",
        when=["cup"],
        moment="rare",
    ),
    "league-cup": dict(
        overheard="It's the League Cup, and the sponsors have changed the name again.",
        speaker="pundit",
        gist="The smaller of the two domestic cups",
        decoy="A trophy for the winners of the division",
        spare="The pre-season tournament played in August",
        when=["cup"],
        moment="rare",
    ),
    "champions-league": dict(
        overheard="That anthem, those lights. Champions League football is back.",
        speaker="telly",
        gist="Europe's top club competition",
        decoy="Every division's champion in one cup",
        spare="A tournament between national sides",
        when=["europe", "top-four", "title"],
        moment="rare",
        player=dict(
            slot='theirs.forward',
            overheard='Champions League football is back, and {theirs.forward} is up front for them.',
            sayIt='"Champions League, and {theirs.forward} up front. Should I be worried?"',
        ),
    ),
    "europa-league": dict(
        overheard="Europa League on Thursday. I'll be up late again.",
        speaker="him",
        gist="Europe's second club competition",
        decoy="Knockout rounds of Europe's top cup",
        spare="A tournament for national sides in Europe",
        when=["europe", "top-four"],
        moment="rare",
    ),
    "conference-league": dict(
        overheard="conference league away trip in november. whos coming?",
        speaker="chat",
        gist="Europe's third club competition",
        decoy="Non-league clubs below the top divisions",
        spare="The qualifying round before a group stage",
        when=["europe", "top-four"],
        moment="rare",
    ),
    "transfer-window": dict(
        overheard="We're a month into the transfer window and they've signed nobody.",
        speaker="pundit",
        gist="The weeks when deals can be done",
        decoy="A club's list of targets",
        spare="The fee one club pays another for a player",
        when=["window", "early-season"],
        moment="anytime",
        player=dict(
            slot='theirs.midfielder',
            overheard="Would you take {theirs.midfielder}? That's your transfer window done.",
            sayIt='"Would we ever sign someone like {theirs.midfielder} in a transfer window?"',
        ),
    ),
    "deadline-day": dict(
        overheard="Deadline day, and we're outside the ground with nothing to tell you.",
        speaker="telly",
        gist="The final day for doing deals",
        decoy="The final day to buy season tickets",
        spare="Cut-off for naming the squad for a cup",
        when=["window"],
        moment="rare",
    ),
    "loan": dict(
        overheard="He's gone out on loan for the season. Bit of a surprise.",
        speaker="him",
        gist="Borrowing a player from another club for a while",
        decoy="Dropping down a division to get regular games",
        spare="Playing for the reserve side until he's wanted",
        when=["window", "early-season"],
        moment="anytime",
    ),
    "sacked": dict(
        overheard="hes getting sacked in the morning and about time too.",
        speaker="chat",
        gist="Losing the job when results go bad",
        decoy="Being dropped from the squad for a game",
        spare="The manager walking out for a bigger club",
        when=["bad-run", "new-manager", "after-heavy-loss", "opp-bad-form"],
        moment="anytime",
    ),
}
