# Overheard content for category "tactics". See LINGO_OVERHEARD_BRIEF.md.
# Keep ids in lingo_src.py order. Every id in the category must appear here.

OVERHEARD = {
    "formation": dict(
        overheard="They've changed the formation again. Back three now, apparently.",
        speaker="him",
        gist="The shape the ten outfield players start in",
        decoys=["The order they line up in the tunnel before kick-off", "The names read out over the tannoy before kick-off"],
        when=["any", "new-manager"],
    ),
    "back-four": dict(
        overheard="Not a lot for the back four to do there. Dealt with everything.",
        speaker="telly",
        gist="The defenders in a flat line in front of the goalkeeper",
        decoys=["The four players sitting furthest back on the bench", "The four across the middle of the pitch"],
        when=["any", "after-clean-sheet"],
    ),
    "centre-back": dict(
        overheard="We need another centre-back. He's getting done for pace every week.",
        speaker="him",
        gist="A defender in the middle who wins headers",
        decoys=["A defender posted right on the halfway line", "A midfielder who shields the defence behind him"],
        when=["any", "after-clean-sheet"],
    ),
    "full-back": dict(
        overheard="The full-backs are getting forward too much. Nobody's covering behind.",
        speaker="pundit",
        gist="A defender out wide who also joins the attack",
        decoys=["An attacker who hugs the touchline the whole game", "A defender who plays the whole ninety every week"],
        when=["any"],
    ),
    "wing-back": dict(
        overheard="He's gone wing-backs today. Three at the back, then.",
        speaker="him",
        gist="A wide defender pushed up almost as an attacker",
        decoys=["A substitute warming up on the touchline for ages", "The reserve who covers for the winger and full-back"],
        when=["any", "new-manager"],
    ),
    "holding-midfielder": dict(
        overheard="They need a proper holding midfielder. That's been the problem all season.",
        speaker="him",
        gist="The one who sits in front of the defence",
        decoys=["A player told to hold on to the ball", "The one who plays just behind the striker"],
        when=["any"],
    ),
    "box-to-box": dict(
        overheard="He covers every blade of grass, that lad. Box-to-box all day.",
        speaker="chat",
        gist="A midfielder who runs the length of the pitch",
        decoys=["A pass played from one penalty area to the other", "A player swapping sides with a mate at half-time"],
        when=["any"],
    ),
    "number-ten": dict(
        overheard="He's the number ten tonight. Floating about behind the striker.",
        speaker="telly",
        gist="The creative one just off the front man",
        decoys=["The player wearing the shirt with ten on", "The player who takes their penalties"],
        when=["any"],
    ),
    "playmaker": dict(
        overheard="Take their playmaker out of the game and there's nothing else there.",
        speaker="pundit",
        gist="The one every attack goes through",
        decoys=["The coach who writes the corner routines", "The captain who organises the defence"],
        when=["any"],
    ),
    "winger": dict(
        overheard="Their winger is destroying our right side. Someone get over there.",
        speaker="chat",
        gist="An attacker who runs at people wide",
        decoys=["A defender who covers the far side", "The forward who plays off the striker"],
        when=["any"],
    ),
    "striker": dict(
        overheard="We're crying out for a striker in this window. Crying out.",
        speaker="him",
        gist="The one up front whose job is scoring",
        decoys=["The one who takes their free kicks and corners", "A defender who goes up for corners late on"],
        when=["any", "window"],
    ),
    "target-man": dict(
        overheard="They've no target man to aim at when they go long. It just comes back.",
        speaker="pundit",
        gist="A big forward the ball gets launched at",
        decoys=["The player the crowd has turned on this season", "A defender told to follow one player about"],
        when=["any"],
    ),
    "false-nine": dict(
        overheard="There's no recognised striker. He's playing a false nine there.",
        speaker="telly",
        gist="A forward who drops deep to confuse markers",
        decoys=["A player faking an injury to waste a bit of time", "A forward told to stay high up on the shoulder"],
        when=["any"],
    ),
    "pressing": dict(
        overheard="Look at the work off the ball. They're pressing and he's not getting a second.",
        speaker="pundit",
        gist="Hounding whoever has it into a mistake",
        decoys=["Newspapers and TV crowding round the club", "Playing the ball forward at every chance"],
        when=["any", "good-run"],
    ),
    "high-press": dict(
        overheard="The high press has knackered them. They can't get out of their half.",
        speaker="him",
        gist="Winning it back right on top of their keeper",
        decoys=["Launching the ball up into the air and chasing", "Sitting deep and waiting for a chance to break"],
        when=["any", "good-run"],
    ),
    "low-block": dict(
        overheard="They've dropped into a low block now. Two banks of four.",
        speaker="telly",
        gist="Defending deep, letting the other lot have it",
        decoys=["The stand where the cheap seats are behind the goal", "A tackle that stops a shot right on the goal line"],
        when=["any", "after-clean-sheet"],
    ),
    "park-the-bus": dict(
        overheard="They've parked the bus since the goal. Ten men behind the ball.",
        speaker="pundit",
        gist="Everyone back defending, nobody trying to attack",
        decoys=["The team coach is blocking the stadium exit", "Substituting all your attackers at once"],
        when=["any", "after-draw", "after-clean-sheet"],
    ),
    "counter-attack": dict(
        overheard="They'll counter-attack us all night if we keep pushing up.",
        speaker="chat",
        gist="Breaking forward fast the second you win it",
        decoys=["Scoring straight back after going behind early", "Pushing everyone forward chasing a late goal"],
        when=["any", "europe"],
    ),
    "possession": dict(
        overheard="You can have all the possession you like. It's goals that count.",
        speaker="him",
        gist="The share of the game a side has the ball",
        decoys=["The number of times a side touches the ball", "The count of shots each side has had on target"],
        when=["any", "after-draw", "after-loss"],
    ),
    "tiki-taka": dict(
        overheard="All that tiki-taka and they haven't had a shot worth the name.",
        speaker="chat",
        gist="Endless short passes to keep hold of the ball",
        decoys=["The chant the away end sings on repeat all game", "A quick one-two played round a defender's legs"],
        when=["any", "europe"],
    ),
    "long-ball": dict(
        overheard="It's long ball after long ball. We've given up trying to play.",
        speaker="him",
        gist="Hitting it high and far instead of passing",
        decoys=["A shot struck from forty yards or further out", "The cross whipped in hard and low from the byline"],
        when=["any", "relegation"],
    ),
    "man-marking": dict(
        overheard="They've gone man-marking today. Straight out of the eighties, that.",
        speaker="telly",
        gist="Sticking to one opponent, not a zone",
        decoys=["Giving a player marks out of ten", "Standing between the ball and the goal"],
        when=["any"],
    ),
    "zonal-marking": dict(
        overheard="That's what zonal marking gets you. A free header at the far post.",
        speaker="him",
        gist="Each defender guards a patch of grass",
        decoys=["Switching off and losing concentration", "The wall lined up in front of a free kick"],
        when=["any", "after-loss"],
    ),
    "set-piece": dict(
        overheard="They're a threat from every set piece. Look at the size of them.",
        speaker="pundit",
        gist="A rehearsed routine from a dead ball",
        decoys=["The eleven a manager settles on for a game", "A goal that comes from open play instead"],
        when=["any", "derby", "cup"],
    ),
    "overlap": dict(
        overheard="He's got the overlap and he's ignored him again.",
        speaker="telly",
        gist="A defender running outside his winger",
        decoys=["Two players standing in the same spot", "A pass played inside to the middle"],
        when=["any"],
    ),
    "through-ball": dict(
        overheard="Look at the through ball. He didn't even lift his head up.",
        speaker="telly",
        gist="A pass slid between two defenders",
        decoys=["A ball nudged past a player's legs", "A cross aimed at the far post"],
        when=["any"],
    ),
    "cutback": dict(
        overheard="Another cutback. They score all their goals like that.",
        speaker="him",
        gist="A pass pulled square from the byline",
        decoys=["A player turning inside to lose a marker", "A cross floated to the far post"],
        when=["any"],
    ),
    "inverted-full-back": dict(
        overheard="Both of them are inverted full-backs now. It's a midfield three, really.",
        speaker="pundit",
        gist="A wide defender stepping into midfield",
        decoys=["A defender playing on the opposite side", "A midfielder dropping in among the defenders"],
        when=["any"],
    ),
    "half-space": dict(
        overheard="He lives in the half-space, that lad. It's a podcast word, apparently.",
        speaker="him",
        gist="The lane between the middle and the touchline",
        decoys=["The half of the pitch a side sets up to defend", "The strip of grass right in front of the goal mouth"],
        when=["any"],
    ),
    "xg": dict(
        overheard="Look at the xG. We battered them and lost. That's football.",
        speaker="chat",
        gist="A score for how good a chance was",
        decoys=["How many goals a side should score in a season", "The shots on target added up"],
        when=["any", "after-draw", "after-loss"],
    ),
    "game-management": dict(
        overheard="Two up and they've not left their own half for ten minutes. Game management.",
        speaker="him",
        gist="Slowing it down to protect a lead",
        decoys=["The people who run the club upstairs", "Changing the shape after an hour"],
        when=["after-win", "after-clean-sheet", "europe", "derby"],
    ),
    "dark-arts": dict(
        overheard="Every throw-in takes him thirty seconds. Proper dark arts, that.",
        speaker="chat",
        gist="The sneaky stuff that winds them up",
        decoys=["A match played under the floodlights", "Playing a weakened side on purpose"],
        when=["derby", "europe", "after-loss"],
    ),
    "rotation": dict(
        overheard="He's named a side I don't recognise. Rotation, he says.",
        speaker="him",
        gist="Changing several players to rest legs",
        decoys=["Players taking turns as captain through a season", "Swapping positions with someone during a match"],
        when=["cup", "europe"],
    ),
}
