import SwiftUI

struct TeamPageView: View {
    let teamId: String
    @Environment(AppState.self) var appState
    @State private var content: TeamPageContent?
    @State private var playerCards: [PlayerCard] = []
    /// Up to 4 insider items: latest of each type (stat, history, oddity,
    /// anecdote). Powers the redesigned "Things he doesn't know" section
    /// at the bottom of the team page. Empty array = section hidden.
    @State private var insiderSet: [InsiderItem] = []
    /// Pre-tournament preview content_items keyed by synthetic fixture
    /// id (`"<team_id>:<iso-date>:<opponent-slug>"`). When a row in the
    /// Calendar tab matches a key here, tapping the row navigates to
    /// that content_item's ContentDetailView. Empty for PL clubs and
    /// for any WC country that hasn't been seeded yet. See Lesson 78.
    @State private var previewByFixtureId: [String: ContentItem] = [:]
    @State private var isLoading = true
    @State private var hasError = false
    @State private var presentedPlayer: PlayerCard?
    @State private var expandedCard: TeamCardType?
    /// Which of the ones to know is on screen.
    @State private var onesIndex = 0
    /// The pink strip under the one on screen, open downwards with more on
    /// him and his own opener. Stays open as she swipes to the next.
    @State private var onesOpen = false
    @State private var squad = LiveSquadService.shared
    @State private var showLastGames = false
    /// Which table the Table tab is showing, by competition label. Nil means
    /// the club's own league, which is the default and the common case.
    @State private var standingsScope: String? = nil
    @State private var activeTab: TeamTab = .info
    @Environment(\.dynamicTypeSize) private var dynamicTypeSize
    /// Calendar-row columns. Fixed points clipped the date stack and the
    /// importance label the moment Dynamic Type went up, so both scale — and
    /// both stop growing before they would starve the club name in the middle.
    @ScaledMetric(relativeTo: .footnote) private var dateColumnScale: CGFloat = 70
    @ScaledMetric(relativeTo: .footnote) private var importanceColumnScale: CGFloat = 110
    private var dateColumnWidth: CGFloat { min(dateColumnScale, 110) }
    private var importanceColumnWidth: CGFloat { min(importanceColumnScale, 150) }

    private enum TeamCardType: String, Hashable {
        case basics, manager, onesToKnow, rivalry, form, season, comingUp
    }

    /// 3-way segmented control at the top of the team page.
    /// - `.info`: the existing scroll of cards (mood, basics, manager,
    ///   ones to know, rivalry, form, season, coming up, insider headlines).
    /// - `.calendar`: visual upcoming-fixtures list with per-game importance
    ///   ratings + one-liners (server-generated by team-page-generator).
    /// - `.table`: full standings — 20-row PL table for clubs, 4-row group
    ///   for WC countries, user's row highlighted rose.
    private enum TeamTab: String, CaseIterable, Identifiable {
        case info = "Info"
        case calendar = "Calendar"
        case table = "Table"
        var id: String { rawValue }
    }

    private var hisNameOrHis: String { appState.namePossessiveCap }

    /// Resolve the entity for this team page — could be a PL Team or a WC
    /// Country, both keyed by the teamId string. V2.0: countries live in
    /// the same `teams` table as clubs.
    private var entityDisplayName: String {
        if let team = Team(rawValue: teamId) { return team.displayName }
        if let country = Country(rawValue: teamId) { return country.displayName }
        return ""
    }

    /// Crest for the team-page header. PL clubs render their club crest;
    /// WC countries render their flag. Both come from API-Football's CDN
    /// via `TeamCrestView`, which falls back to a soft-blush shield icon
    /// if the image is still loading or the URL is unavailable. Replaces
    /// the pink-circle-with-first-letter placeholder used in V1, which
    /// rendered "S" for Sweden, "A" for Arsenal etc. — a brand-aligned
    /// placeholder that became a regression once the team data carried
    /// real crest URLs.
    @ViewBuilder
    private var entityCrest: some View {
        if let team = Team(rawValue: teamId) {
            TeamCrestView(team: team, size: 64)
        } else if let country = Country(rawValue: teamId) {
            TeamCrestView(country: country, size: 64)
        } else {
            // teamId matched neither enum (data integrity issue elsewhere).
            // TeamCrestView's url:nil initialiser yields the same shield
            // fallback it shows for any failed image load.
            TeamCrestView(url: nil, size: 64)
        }
    }

    /// Word-aware truncation; avoids mid-word cuts.
    private func truncateAtWord(_ text: String, maxChars: Int) -> String {
        if text.count <= maxChars { return text }
        let cutEnd = text.index(text.startIndex, offsetBy: maxChars)
        let head = text[..<cutEnd]
        if let lastSpace = head.lastIndex(where: { $0.isWhitespace }) {
            return String(text[..<lastSpace]) + "…"
        }
        return String(head) + "…"
    }

    /// Rivalry blurbs from team-page-generator are shaped `"<rivals> — <context>..."`.
    /// Split on the dash to surface just the rival names as a headline.
    private func rivalsHeadline(_ text: String) -> String {
        // "<Rival> — the X derby..." or "<Rival>, the X derby..." → the rival.
        let separators: [Character] = ["—", "–", ",", "."]
        if let idx = text.firstIndex(where: { separators.contains($0) }) {
            let head = text[..<idx].trimmingCharacters(in: .whitespaces)
            if !head.isEmpty && head.count <= 40 && head.split(separator: " ").count <= 4 { return head }
        }
        // "X's fiercest rivalry is with <Rival>, ..." → the rival.
        if let range = text.range(of: " with ") {
            let tail = text[range.upperBound...]
            if let end = tail.firstIndex(where: { separators.contains($0) }) {
                let name = tail[..<end].trimmingCharacters(in: .whitespaces)
                if !name.isEmpty && name.count <= 40 { return name }
            }
        }
        return "The rivalry"
    }

    var body: some View {
        ZStack {
            Color.appBackground.ignoresSafeArea()

            if let content {
                ScrollViewReader { proxy in
                    ScrollView {
                        VStack(spacing: 12) {
                            headerSection
                            tabSelector
                            tabContent(content.cards)
                        }
                        .padding(.horizontal, 16)
                        .padding(.bottom, 40)
                    }
                    #if DEBUG
                    // The screenshot harness cannot scroll, so a card below the
                    // fold is unverifiable without this. -gdTeamExpand also
                    // scrolls to the card it opens.
                    .onAppear {
                        let args = ProcessInfo.processInfo.arguments
                        var target = expandedCard
                        if let i = args.firstIndex(of: "-gdTeamScrollTo"), i + 1 < args.count,
                           let card = TeamCardType(rawValue: args[i + 1]) { target = card }
                        // `-gdTeamOnesIndex N`: the Nth of the ones to know.
                        if let i = args.firstIndex(of: "-gdTeamOnesIndex"), i + 1 < args.count,
                           let n = Int(args[i + 1]) { onesIndex = n }
                        // `-gdTeamOnesOpen`: the pink strip open.
                        if args.contains("-gdTeamOnesOpen") { onesOpen = true }
                        guard let target else { return }
                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.6) {
                            withAnimation { proxy.scrollTo(target, anchor: .top) }
                        }
                    }
                    #endif
                }
            } else if isLoading {
                teamPageLoadingView
            } else if hasError {
                teamPageErrorView
            } else {
                warmPlaceholderView
            }
        }
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(Color.appBackground, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
        .task { await loadTeamPage() }
        // His club's squad rows, for the shirt numbers. Only for the club My
        // Turn's squad pack is for: the service caches one club.
        .task(id: teamId) {
            guard let team = appState.selectedTeam, team.rawValue == teamId else { return }
            await squad.refresh(team: team, personalise: { appState.personalise($0) })
        }
        .sheet(item: $presentedPlayer) { player in
            PlayerCardModal(player: player)
        }
        #if DEBUG
        .onAppear {
            // Screenshot harness (see MainTabView): -gdTeamTab calendar|table,
            // -gdTeamExpand basics|manager|rivalry|season|comingUp.
            let args = ProcessInfo.processInfo.arguments
            if let i = args.firstIndex(of: "-gdTeamTab"), i + 1 < args.count {
                switch args[i + 1] { case "calendar": activeTab = .calendar; case "table": activeTab = .table; default: break }
            }
            // -gdStandingsScope "Europa League" selects the European table.
            if let i = args.firstIndex(of: "-gdStandingsScope"), i + 1 < args.count {
                standingsScope = args[i + 1]
            }
            if let i = args.firstIndex(of: "-gdTeamExpand"), i + 1 < args.count {
                switch args[i + 1] {
                case "basics": expandedCard = .basics
                case "manager": expandedCard = .manager
                case "rivalry": expandedCard = .rivalry
                case "season": expandedCard = .season
                case "comingUp": expandedCard = .comingUp
                default: break
                }
            }
        }
        #endif
    }

    // MARK: - Header

    private var headerSection: some View {
        VStack(spacing: 12) {
            entityCrest

            Text(entityDisplayName)
                .font(.jakarta(20, weight: .bold))
                .foregroundColor(.warmWhite)

            Text("\(hisNameOrHis) team")
                .font(.jakarta(14, weight: .regular))
                .foregroundColor(.mutedText)
        }
        .frame(maxWidth: .infinity)
        .padding(.top, 8)
        .padding(.bottom, 4)
    }

    // MARK: - Tab selector + dispatcher

    /// 3-way control: only the SELECTED tab renders as a hot-rose pill —
    /// the other two sit as bare, recessed text on the team-page
    /// background. The previous design had a soft-blush gutter + white
    /// pills for the unselected tabs; on the deep-mauve team page that
    /// read as competing chrome. Lighter visual = the page header
    /// breathes, and your eye lands on the active tab immediately.
    private var tabSelector: some View {
        HStack(spacing: 0) {
            ForEach(TeamTab.allCases) { tab in
                Button {
                    withAnimation(.spring(duration: 0.25)) {
                        activeTab = tab
                    }
                    UIImpactFeedbackGenerator(style: .light).impactOccurred()
                } label: {
                    Text(tab.rawValue)
                        .font(.jakarta(15, weight: .medium))
                        .frame(maxWidth: .infinity)
                        .frame(height: 40)
                        .background(activeTab == tab ? Color.hotRose : Color.clear)
                        .foregroundColor(activeTab == tab ? .warmWhite : .warmWhite.opacity(0.6))
                        .cornerRadius(12)
                }
            }
        }
    }

    @ViewBuilder
    private func tabContent(_ cards: TeamPageCards) -> some View {
        switch activeTab {
        case .info:     cardsSection(cards)
        case .calendar: calendarTab(cards)
        case .table:    tableTab(cards)
        }
    }

    // MARK: - Cards section

    @ViewBuilder
    private func cardsSection(_ cards: TeamPageCards) -> some View {
        // Card 1: the next game. It is the reason she opened the page, so it
        // sits above everything else; after the whistle the post-match card
        // takes the same slot until it expires.
        if showPostMatch, let postMatch = content?.cards.postMatch {
            postMatchCard(postMatch)
        } else if let fixture = cards.nextFixture {
            comingUpCard(fixture).id(TeamCardType.comingUp)
        }

        // Mood banner
        if let mood = cards.mood {
            TeamPageMoodBanner(mood: mood)
        }

        // THIS WEEK hero. Only when it is not the same fixture the Coming-up
        // card above has just described in more detail: with Coming up first on
        // the tab, the two read as the same sentence twice, which reads like a
        // bug. It still earns its place when there is no next fixture to show.
        if let thisWeek = cards.thisWeek, cards.nextFixture == nil {
            TeamPageThisWeek(card: thisWeek)
        }

        // Card 1: The basics
        if let basics = cards.basics {
            TeamPageCard(
                title: "The basics",
                primaryText: basics.nickname,
                zone2Label: "Say this:",
                talkingPoint: basics.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .basics,
                onTap: { toggleCard(.basics) },
                zone1Collapsed: {
                    // The glance line: last season's finish when we have it
                    // (the fact she is most likely to need first), otherwise
                    // the stadium, otherwise the nickname — the collapsed card
                    // always has a visible second line.
                    Text(basics.lastSeason.map { "Last season: \($0)" } ?? basics.stadium ?? basics.nickname)
                        .font(.jakarta(13, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.7))
                        .lineLimit(1)
                },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 6) {
                        infoLine(label: "Known as", value: basics.nickname)
                        if let stadium = basics.stadium {
                            infoLine(label: "Home ground", value: stadium)
                        }
                        // The three facts that place a club: how long in the
                        // top flight, last season, last league title.
                        if let since = basics.plSince {
                            infoLine(label: "Top flight", value: since)
                        }
                        if let last = basics.lastSeason {
                            infoLine(label: "Last season", value: last)
                        }
                        if let title = basics.lastTitle {
                            infoLine(label: "Last league title", value: title)
                        }
                        Text(appState.personalise(basics.funFact))
                            .font(.jakarta(13, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.7))
                            .padding(.top, 4)
                    }
                }
            )
        }

        // Card 2: The manager. Skip when the backend's "<UNKNOWN>" placeholder
        // landed in the data (team-page-generator's fallback for missing
        // API-Football coach data). Otherwise the card would render the
        // literal string to users.
        if let manager = cards.manager, manager.name != "<UNKNOWN>",
           let portrait = PlayerPortrait.asset(club: teamId, name: manager.name) {
            managerFeature(manager, portrait: portrait).id(TeamCardType.manager)
        } else if let manager = cards.manager, manager.name != "<UNKNOWN>" {
            TeamPageCard(
                title: "The manager",
                primaryText: manager.name,
                zone2Label: "Drop this:",
                talkingPoint: manager.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .manager,
                onTap: { toggleCard(.manager) },
                leadingImageURL: manager.photoURL.flatMap(URL.init),
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    Text(appState.personalise(manager.summary))
                        .font(.jakarta(14, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.9))
                        .padding(.top, 2)
                }
            )
        }

        // Card 3: Ones to know — one man at a time, big, and the next one a
        // swipe or a tap away (Anton, 2026-10-01: three in a list was too
        // small closed and too much open).
        if let onesToKnow = cards.onesToKnow, !onesToKnow.players.isEmpty {
            onesToKnowCarousel(onesToKnow).id(TeamCardType.onesToKnow)
        }

        // Card 4: The rivalry
        if let rivalry = cards.rivalry {
            TeamPageCard(
                title: "The rivalry",
                primaryText: rivalry.rival ?? rivalsHeadline(appState.personalise(rivalry.text)),
                zone2Label: "Use this:",
                talkingPoint: rivalry.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .rivalry,
                onTap: { toggleCard(.rivalry) },
                hidePrimaryWhenExpanded: true,
                leadingImageURL: rivalry.rivalCrestURL,
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 8) {
                        Text(appState.personalise(rivalry.text))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))

                        if let intensity = cards.rivalryIntensity {
                            TeamPageRivalryMeter(intensity: intensity)
                        }
                    }
                }
            )
            .id(TeamCardType.rivalry)
        }

        // Card 5: How they're doing
        if let form = cards.form {
            TeamPageCard(
                title: "How they're doing",
                primaryText: form.leaguePositionLabel,
                zone2Label: "Say this:",
                talkingPoint: form.talkingPoint.map { appState.personalise($0) },
                isExpanded: expandedCard == .form,
                onTap: { toggleCard(.form) },
                zone1Collapsed: {
                    TeamPageFormDots(recentForm: form.recentForm, isExpanded: false)
                },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 6) {
                        TeamPageFormDots(recentForm: form.recentForm, isExpanded: expandedCard == .form)

                        Text(appState.personalise(form.formSummary))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))
                    }
                }
            )
        }

        // Card 6: The season so far
        if let season = cards.season {
            TeamPageCard(
                title: "The season so far",
                primaryText: truncateAtWord(appState.personalise(season.summary), maxChars: 50),
                zone2Label: "Drop this:",
                talkingPoint: season.talkingPoint.map { appState.personalise($0) },
                isExpanded: expandedCard == .season,
                onTap: { toggleCard(.season) },
                hidePrimaryWhenExpanded: true,
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    Text(appState.personalise(season.summary))
                        .font(.jakarta(14, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.9))
                }
            )
        }

        // Card 8 (T2+ only): "Things he doesn't know" — 4 niche items
        // (latest of each type: stat / history / oddity / anecdote)
        // refreshed by the gd-insider cloud routine. Headlines only,
        // no body text — InsiderHeadlineRow keeps it compact. Gating:
        // TierGating.isAvailable(.insiderCard, tier:) returns true for
        // tier 2 and 3 — T1 users never see it. Section also hides if
        // the team has no items yet (brand-new entity the routine hasn't
        // populated, or a backfill skip).
        if TierGating.isAvailable(.insiderCard, tier: appState.selectedTier),
           !insiderSet.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Text("Things \(appState.pSubject) \(appState.usesHeVoice ? "doesn't" : "don't") know".uppercased())
                    .font(.sectionHeader)
                    .tracking(1)
                    .foregroundColor(.mutedText)
                    // Align with the row's inner padding (14pt around the
                    // rose bar + content) so the tracker label sits flush
                    // with each row's content edge.
                    .padding(.leading, 14)
                VStack(spacing: 8) {
                    ForEach(insiderSet) { item in
                        InsiderHeadlineRow(item: item)
                    }
                }
            }
            .padding(.top, 8)
        }

        // Freshness line
        if let text = cards.freshnessText {
            Text(text)
                .font(.jakarta(12, weight: .regular))
                .foregroundColor(.mutedText)
                .frame(maxWidth: .infinity)
                .padding(.top, 8)
        }
    }

    // MARK: - Coming up card

    @ViewBuilder
    private func comingUpCard(_ fixture: NextFixtureCard) -> some View {
        // The opponent's own API id when the fixture carries one, else the
        // matching Calendar row's, else a PL club resolved by name.
        let crest = fixture.opponentApiId.flatMap { URL(string: "https://media.api-sports.io/football/teams/\($0).png") }
            ?? content?.cards.upcomingFixtures?.first { String($0.date.prefix(10)) == String(fixture.date.prefix(10)) }?.opponentCrestURL
            ?? Team.allCases.first {
                $0.displayName.caseInsensitiveCompare(fixture.opponent) == .orderedSame
                    || $0.shortName.caseInsensitiveCompare(fixture.opponent) == .orderedSame
            }?.crestURL
        TeamPageCard(
            title: "Coming up",
            primaryText: "\(fixture.opponent) (\(fixture.venue.uppercased()))",
            zone2Label: comingUpLabel(for: fixture.date),
            talkingPoint: fixture.talkingPoint.map { appState.personalise($0) },
            isExpanded: expandedCard == .comingUp,
            onTap: { toggleCard(.comingUp) },
            leadingImageURL: crest,
            footerLabel: "Pre game talk ›",
            zone1Collapsed: {
                HStack(spacing: 8) {
                    Text(formattedFixtureDate(fixture.date))
                        .font(.jakarta(13, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.7))
                        .lineLimit(1)
                    // Which competition. "Hull City, home" on a League Cup
                    // night was indistinguishable from a league Saturday.
                    if let competition = fixture.competitionShort {
                        Text(competition)
                            .font(.jakarta(11, weight: .bold))
                            .foregroundColor(.warmWhite.opacity(0.85))
                            .lineLimit(1)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 3)
                            .background(Capsule().fill(Color.warmWhite.opacity(0.12)))
                    }
                    if let favorite = fixture.favorite {
                        Text(favorite.label)
                            .font(.jakarta(11, weight: .bold))
                            .foregroundColor(.hotRose)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 3)
                            .background(Capsule().fill(Color.hotRose.opacity(0.12)))
                    }
                }
            },
            zone1Expanded: {
                VStack(alignment: .leading, spacing: 8) {
                    Text(kickoffLine(fixture))
                        .font(.jakarta(13, weight: .bold))
                        .foregroundColor(.warmWhite.opacity(0.7))

                    if let favorite = fixture.favorite {
                        Text(favorite.label)
                            .font(.jakarta(11, weight: .bold))
                            .foregroundColor(.hotRose)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 3)
                            .background(Capsule().fill(Color.hotRose.opacity(0.12)))
                    }

                    // The preview is the deterministic paragraph, then
                    // optionally a blank line and one sentence of colour from
                    // the Monday routine. Older WC previews run to many
                    // paragraphs and carry the opponent detail inline, so they
                    // keep today's rule: whole text unless the opponent block
                    // below is going to say it structurally.
                    let opponent = content?.cards.onesToKnow?.opponent
                    let hasStructuredOpponent = !(opponent?.players.isEmpty ?? true)
                    let preview = fixture.preview ?? ""
                    let paragraphs = preview.components(separatedBy: "\n\n")
                    let colour = paragraphs.count == 2 ? paragraphs[1] : nil
                    let previewText = (hasStructuredOpponent || colour != nil)
                        ? (paragraphs.first ?? preview)
                        : preview
                    if !previewText.isEmpty {
                        Text(appState.personalise(previewText))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))
                    }
                    if let colour, !colour.isEmpty {
                        Text(appState.personalise(colour))
                            .font(.jakarta(13, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.6))
                    }
                    if let opponent, !opponent.players.isEmpty {
                        opponentSection(opponent)
                    }
                }
            }
        )
    }

    /// "Tue 16 Sep, 8pm · Europa League · home". The competition chip on the
    /// collapsed card already strips the sponsor parenthetical; a league game
    /// has no competition recorded, and saying "Premier League" is friendlier
    /// than leaving a gap.
    private func kickoffLine(_ fixture: NextFixtureCard) -> String {
        var parts: [String] = []
        if let date = Self.parseISO(fixture.date) {
            // "8pm" reads better than "8:00pm"; a 19:45 kickoff keeps both. On a
            // 24-hour device the same trim would make "21:00" read "21", so it
            // only applies when the clock actually printed am/pm.
            let s = Self.kickoffLineFmt.string(from: date)
            let is12Hour = s.localizedCaseInsensitiveContains(Self.kickoffLineFmt.pmSymbol)
                || s.localizedCaseInsensitiveContains(Self.kickoffLineFmt.amSymbol)
            parts.append(is12Hour ? s.replacingOccurrences(of: ":00", with: "") : s)
        }
        // A cup competition already carries its round ("League Cup, last 32");
        // a league round is "Regular Season - 4", which says nothing.
        let round = fixture.round.flatMap { $0.hasPrefix("Regular Season") ? nil : $0 }
        parts.append(fixture.competitionShort ?? round ?? "Premier League")
        parts.append(fixture.venue.lowercased())
        return parts.joined(separator: " · ")
    }

    /// Template, not a hard format: a device on a 24-hour clock shows "21:00"
    /// instead of an out-of-place "9:00pm".
    private static let kickoffLineFmt: DateFormatter = {
        let f = DateFormatter()
        f.setLocalizedDateFormatFromTemplate("EEE d MMM jm")
        f.amSymbol = "am"; f.pmSymbol = "pm"
        return f
    }()

    // MARK: - Post-match card

    @ViewBuilder
    private func postMatchCard(_ postMatch: TeamPostMatchCard) -> some View {
        let tintColor: Color? = {
            switch postMatch.state {
            case .win: return Color.hotRose.opacity(0.06)
            case .loss: return Color.red.opacity(0.04)
            case .draw: return nil
            }
        }()

        let label: String = {
            switch postMatch.state {
            case .win: return "Say this:"
            case .loss: return "Tonight:"
            case .draw: return "Ask \(appState.pObject):"
            }
        }()

        TeamPageCard(
            title: postMatch.state == .win ? "After the win" : postMatch.state == .loss ? "After the loss" : "After the draw",
            primaryText: truncateAtWord(appState.personalise(postMatch.text), maxChars: 50),
            zone2Label: label,
            talkingPoint: appState.personalise(postMatch.talkingPoint),
            isExpanded: expandedCard == .comingUp,
            onTap: { toggleCard(.comingUp) },
            tintColor: tintColor,
            hidePrimaryWhenExpanded: true,
            zone1Collapsed: { EmptyView() },
            zone1Expanded: {
                Text(appState.personalise(postMatch.text))
                    .font(.jakarta(14, weight: .regular))
                    .foregroundColor(.warmWhite.opacity(0.9))
            }
        )
    }

    // MARK: - Calendar tab

    @ViewBuilder
    private func calendarTab(_ cards: TeamPageCards) -> some View {
        // 15 rows is roughly to the end of the next block of the season; the
        // server sends no more, the cap is here so a longer list can never
        // turn the tab into an endless scroll.
        let fixtures = Array((cards.upcomingFixtures ?? []).prefix(15))
        let recent = cards.recentResults ?? []
        return VStack(spacing: Layout.cardSpacing) {
            if fixtures.isEmpty {
                emptyState(
                    icon: "calendar",
                    text: "No upcoming fixtures yet. Check back closer to kickoff."
                )
            } else {
                importanceLegend
                ForEach(fixtures) { fixture in
                    let preview = previewByFixtureId[previewKey(for: fixture)]
                    calendarRow(fixture, preview: preview)
                }
            }
            if !recent.isEmpty {
                lastGamesSection(recent)
            }
        }
    }

    /// Collapsible "last games" list (E1): recent finished fixtures with the
    /// result, marked played. Collapsed by default so it doesn't crowd the
    /// upcoming list.
    @ViewBuilder
    private func lastGamesSection(_ recent: [RecentResult]) -> some View {
        VStack(spacing: Layout.cardSpacing) {
            Button {
                withAnimation(.easeInOut(duration: 0.2)) { showLastGames.toggle() }
            } label: {
                HStack(spacing: 6) {
                    Text(showLastGames ? "Hide last games" : "Show last games")
                        .font(.sectionHeader).tracking(1)
                        .foregroundColor(.hotRose)
                    Image(systemName: showLastGames ? "chevron.up" : "chevron.down")
                        .font(.system(size: 11, weight: .bold))
                        .foregroundColor(.hotRose)
                    Spacer()
                }
            }
            .buttonStyle(.plain)

            if showLastGames {
                ForEach(recent) { lastGameRow($0) }
            }
        }
        .padding(.top, 4)
    }

    @ViewBuilder
    private func lastGameRow(_ r: RecentResult) -> some View {
        let parsed = Self.parseISO(r.date)
        HStack(alignment: .center, spacing: 14) {
            Text(r.outcome)
                .font(.feedHeadline)
                .foregroundColor(.warmWhite)
                .frame(width: 28, height: 28)
                .background(Circle().fill(resultColor(r.outcome)))
            VStack(alignment: .leading, spacing: 2) {
                Text(r.opponent)
                    .font(.feedHeadline).foregroundColor(.warmWhite)
                Text("\(parsed.map { Self.dayMonth($0) } ?? r.date) · \(r.venue.capitalized) · FT")
                    .font(.feedTimestamp).foregroundColor(.warmWhite.opacity(0.6))
            }
            Spacer(minLength: 0)
            Text("\(r.teamScore)-\(r.oppScore)")
                .font(.feedHeadline).foregroundColor(.warmWhite)
        }
        .opacity(0.85)
    }

    private func resultColor(_ outcome: String) -> Color {
        switch outcome {
        case "W": return Color.hotRose.opacity(0.7)
        case "L": return Color.red.opacity(0.45)
        default:  return Color.warmWhite.opacity(0.2)
        }
    }

    /// Renders one Calendar row. When `preview` is non-nil, the row is
    /// wrapped in a NavigationLink that opens the preview content_item's
    /// ContentDetailView. Rows without a preview render the same visual
    /// but are tap-inert (matches V1 behaviour — graceful for friendlies
    /// and post-group fixtures that aren't previewed).
    @ViewBuilder
    private func calendarRow(_ f: UpcomingFixture, preview: ContentItem?) -> some View {
        let row = calendarRowBody(f, hasPreview: preview != nil)
        if let preview {
            NavigationLink(value: ContentDetailDestination(
                contentId: preview.id,
                scrollToTalkingPoints: false,
                isEveryoneContext: false,
                preloadedItem: preview
            )) {
                row
            }
            .buttonStyle(.plain)
        } else {
            row
        }
    }

    @ViewBuilder
    private func calendarRowBody(_ f: UpcomingFixture, hasPreview: Bool) -> some View {
        Group {
            // Three columns side by side leave the club name a sliver at
            // accessibility text sizes — "Wolverhampton Wanderers" came out as
            // one letter per line. Above the accessibility threshold the row
            // stacks instead and every part gets the full width.
            if dynamicTypeSize.isAccessibilitySize {
                VStack(alignment: .leading, spacing: 10) {
                    calendarDateColumn(f)
                    calendarOpponentColumn(f)
                    calendarImportanceColumn(f, hasPreview: hasPreview)
                }
            } else {
                HStack(alignment: .top, spacing: 14) {
                    calendarDateColumn(f)
                        .frame(width: dateColumnWidth, alignment: .leading)
                    calendarOpponentColumn(f)
                        // Priority 1 so the club name gets the width it needs
                        // before the importance label does.
                        .layoutPriority(1)
                    Spacer(minLength: 0)
                    calendarImportanceColumn(f, hasPreview: hasPreview)
                        // No floor here. A 76pt minimum was tried on
                        // 2026-09-23 to stop "Champions League" breaking as
                        // "Champion s League", and it moved the break onto the
                        // club name instead — "Nottingha m Forest" at default
                        // text size on a 390pt phone, which is worse, because
                        // the club name is the thing she is reading. The
                        // column takes what is left and the label shrinks to
                        // fit it; both Texts below scale rather than split.
                        .frame(maxWidth: importanceColumnWidth, alignment: .trailing)
                }
            }
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.15), lineWidth: 1)
        )
    }

    private func calendarDateColumn(_ f: UpcomingFixture) -> some View {
        let parsed = Self.parseISO(f.date)
        return VStack(alignment: .leading, spacing: 2) {
            Text(parsed.map { Self.dayOfWeek($0) } ?? "")
                .font(.sectionHeader).tracking(1)
                .foregroundColor(.hotRose)
            Text(parsed.map { Self.dayMonth($0) } ?? f.date)
                .font(.feedHeadline).foregroundColor(.warmWhite)
                // "2 Jan 2027" shrinks rather than wrapping onto two lines.
                .lineLimit(1).minimumScaleFactor(0.7)
            // A postponed game has no kickoff to show, and a TBD one has a
            // placeholder time that would be a lie if we printed it.
            if !f.isPostponed {
                Text(f.isTimeTBC ? "Time TBC" : (parsed.map { Self.kickoffTime($0) } ?? ""))
                    .font(.feedTimestamp).foregroundColor(.warmWhite.opacity(0.6))
            }
        }
    }

    private func calendarOpponentColumn(_ f: UpcomingFixture) -> some View {
        HStack(alignment: .top, spacing: 14) {
            TeamCrestView(url: f.opponentCrestURL, size: 28)
            VStack(alignment: .leading, spacing: 2) {
                Text(f.opponent)
                    .font(.feedHeadline).foregroundColor(.warmWhite)
                    // Wrap between words, shrink before splitting one.
                    // "Nottingham" is 99.6pt and the column is narrower than
                    // that on a 390pt phone once the date and the importance
                    // label have taken theirs.
                    .minimumScaleFactor(0.8)
                    .fixedSize(horizontal: false, vertical: true)
                Text(f.venue.capitalized)
                    .font(.feedTimestamp).foregroundColor(.warmWhite.opacity(0.6))
            }
        }
    }

    /// Dots + label (+ chevron hint when the row is tappable).
    /// One line above the list saying what the dots on every row are, so the
    /// rows themselves stay uncluttered (2026-10-03: nothing said).
    private var importanceLegend: some View {
        HStack(spacing: 8) {
            HStack(spacing: 3) {
                ForEach(1...5, id: \.self) { dot in
                    Circle()
                        .fill(dot <= 3 ? Color.hotRose : Color.mutedText.opacity(0.3))
                        .frame(width: 6, height: 6)
                }
            }
            Text("How big the game is: more dots, bigger game")
                .font(.feedTimestamp)
                .foregroundColor(.warmWhite.opacity(0.6))
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 4)
        .accessibilityElement(children: .combine)
        .accessibilityLabel("The dots show how big each game is. More dots, bigger game.")
    }

    private func calendarImportanceColumn(_ f: UpcomingFixture, hasPreview: Bool) -> some View {
        VStack(alignment: .trailing, spacing: 4) {
            HStack(spacing: 3) {
                // A postponed game gets one dot: it is still on the list,
                // but it is not something to plan the evening around.
                let dots = f.isPostponed ? 1 : f.importanceDots
                ForEach(1...5, id: \.self) { dot in
                    Circle()
                        .fill(dot <= dots ? Color.hotRose : Color.mutedText.opacity(0.3))
                        .frame(width: 6, height: 6)
                }
            }
            HStack(spacing: 4) {
                Text(f.isPostponed ? "Postponed" : f.importanceLabel)
                    .font(.feedTimestamp).foregroundColor(.hotRose)
                    .lineLimit(2)
                    // Shrink before splitting a word: the label is free text
                    // from the server and the next one may be longer than
                    // anything the floor above was measured against.
                    .minimumScaleFactor(0.6)
                    .multilineTextAlignment(.trailing)
                if hasPreview {
                    Image(systemName: "chevron.right")
                        .font(.system(size: 10, weight: .semibold))
                        .foregroundColor(.hotRose.opacity(0.7))
                }
            }
        }
    }

    // Cached formatters — DateFormatter() init is expensive (locale/calendar
    // setup) and each calendar row needs all three. Allocating fresh per
    // call would be ~24 inits per render with 8 fixtures.
    private static let dayOfWeekFmt: DateFormatter = {
        let f = DateFormatter(); f.dateFormat = "EEE"; return f
    }()
    private static let dayMonthFmt: DateFormatter = {
        let f = DateFormatter(); f.dateFormat = "d MMM"; return f
    }()
    private static let kickoffTimeFmt: DateFormatter = {
        let f = DateFormatter()
        f.setLocalizedDateFormatFromTemplate("jm")
        f.amSymbol = "am"; f.pmSymbol = "pm"
        return f
    }()

    private static func dayOfWeek(_ d: Date) -> String { dayOfWeekFmt.string(from: d).uppercased() }

    /// "16 Sep", and "16 Sep 2027" once the fixture belongs to another calendar
    /// year — a January game in a list read in December otherwise looked like
    /// it was three weeks ago.
    private static func dayMonth(_ d: Date) -> String {
        let cal = Calendar.current
        let year = cal.component(.year, from: d)
        let text = dayMonthFmt.string(from: d)
        return year == cal.component(.year, from: Date()) ? text : "\(text) \(year)"
    }
    private static func kickoffTime(_ d: Date) -> String { kickoffTimeFmt.string(from: d) }

    // MARK: - Table tab

    @ViewBuilder
    private func tableTab(_ cards: TeamPageCards) -> some View {
        // Two tables when the club is in Europe: the league they live in and
        // the competition they are visiting. Before this the Table tab showed
        // only the league, so a Champions League night had a Coming-up card,
        // a calendar row and no table anywhere.
        let europe = cards.europeStandings.flatMap { $0.entries.isEmpty ? nil : $0 }
        let league = cards.standings.flatMap { $0.entries.isEmpty ? nil : $0 }

        if league != nil || europe != nil {
            VStack(alignment: .leading, spacing: 8) {
                if let europe, let league {
                    standingsSwitcher(league: league, europe: europe)
                } else if let only = league ?? europe {
                    Text(only.competitionLabel.uppercased())
                        .font(.sectionHeader).tracking(1)
                        .foregroundColor(.hotRose.opacity(0.7))
                        .padding(.leading, 14)
                    standingsTable(only.entries)
                }
            }
        } else {
            emptyState(icon: "tablecells", text: "Standings will appear when the data lands.")
        }
    }

    /// League / Europe switcher. Same visual language as the Info / Calendar /
    /// Table control above it, one level down and quieter.
    @ViewBuilder
    private func standingsSwitcher(league: StandingsCard, europe: StandingsCard) -> some View {
        // No explicit choice yet means the league table, which is what the tab
        // shows. Comparing the raw nil highlighted neither half of the switcher.
        let scope = standingsScope ?? league.competitionLabel
        HStack(spacing: 0) {
            ForEach([league, europe], id: \.competitionLabel) { card in
                let selected = scope == card.competitionLabel
                Button {
                    withAnimation(.easeInOut(duration: 0.2)) { standingsScope = card.competitionLabel }
                    UIImpactFeedbackGenerator(style: .light).impactOccurred()
                } label: {
                    Text(card.competitionLabel)
                        .font(.jakarta(13, weight: .semiBold))
                        .lineLimit(1)
                        .minimumScaleFactor(0.8)
                        .frame(maxWidth: .infinity)
                        .frame(height: 34)
                        .background(selected ? Color.hotRose : Color.clear)
                        .foregroundColor(selected ? .warmWhite : .warmWhite.opacity(0.6))
                        .cornerRadius(10)
                }
                .buttonStyle(.plain)
                .accessibilityAddTraits(selected ? .isSelected : [])
            }
        }
        .padding(.horizontal, 6)

        let shown = scope == europe.competitionLabel ? europe : league
        standingsTable(shown.entries)
    }

    @ViewBuilder
    private func standingsTable(_ entries: [StandingsEntry]) -> some View {
        // Resolve the user's row index once per render rather than calling
        // isUserTeam() inside the ForEach (which would do a string lookup
        // for every entry; for a 20-row PL table that's 20 ops per body
        // recomputation).
        let userIdx = entries.firstIndex { isUserTeam($0) }
        VStack(spacing: 0) {
            standingsHeader
            ForEach(Array(entries.enumerated()), id: \.element.id) { idx, entry in
                standingsRow(entry, isUser: idx == userIdx)
                if entry.id != entries.last?.id {
                    Divider().background(Color.warmWhite.opacity(0.08))
                }
            }
        }
        .padding(.vertical, 8)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.2), lineWidth: 1)
        )
    }

    private var standingsHeader: some View {
        HStack {
            Text("#").frame(width: 24, alignment: .leading)
            Text("TEAM").frame(maxWidth: .infinity, alignment: .leading)
            Text("P").frame(width: 28, alignment: .trailing)
            Text("GD").frame(width: 40, alignment: .trailing)
            Text("PTS").frame(width: 36, alignment: .trailing)
        }
        .font(.sectionHeader).tracking(1)
        .foregroundColor(.mutedText)
        .padding(.horizontal, 14)
        .padding(.bottom, 6)
    }

    @ViewBuilder
    private func standingsRow(_ e: StandingsEntry, isUser: Bool) -> some View {
        HStack {
            Text("\(e.rank)")
                .font(.jakarta(13, weight: .regular))
                .frame(width: 24, alignment: .leading)
            HStack(spacing: 8) {
                TeamCrestView(
                    url: e.teamIdApiFootball.flatMap { URL(string: "https://media.api-sports.io/football/teams/\($0).png") },
                    size: 20
                )
                Text(e.teamName)
                    .font(.jakarta(14, weight: isUser ? .bold : .regular))
                    .lineLimit(1)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            Text("\(e.played)").frame(width: 28, alignment: .trailing)
                .font(.jakarta(13, weight: .regular))
            Text(formatGd(e.gd)).frame(width: 40, alignment: .trailing)
                .font(.jakarta(13, weight: .regular))
            Text("\(e.points)").frame(width: 36, alignment: .trailing)
                .font(.jakarta(13, weight: isUser ? .bold : .semiBold))
        }
        .foregroundColor(.warmWhite)
        .padding(.horizontal, 14)
        .padding(.vertical, 8)
        .background(isUser ? Color.hotRose.opacity(0.12) : Color.clear)
    }

    /// User's API-Football id, used to match the standings row precisely
    /// (the previous bidirectional-contains match was wrong for cases like
    /// "Manchester United" vs "Manchester City" — both contain "Manchester").
    /// Falls back to a name-equality check if the entry has no API id.
    private var userApiFootballId: Int? {
        if let team = Team(rawValue: teamId) { return team.apiFootballId }
        if let country = Country(rawValue: teamId) { return country.apiFootballId }
        return nil
    }

    private func isUserTeam(_ e: StandingsEntry) -> Bool {
        if let mine = userApiFootballId, let theirs = e.teamIdApiFootball {
            return mine == theirs
        }
        // No id on this entry — last-ditch exact-name fallback. Avoid
        // substring matching to prevent false positives on "Manchester *".
        return e.teamName.lowercased() == entityDisplayName.lowercased()
    }

    private func formatGd(_ gd: Int) -> String {
        gd > 0 ? "+\(gd)" : "\(gd)"
    }

    @ViewBuilder
    private func emptyState(icon: String, text: String) -> some View {
        VStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 28)).foregroundColor(.hotRose.opacity(0.6))
            Text(text)
                .font(.jakarta(14, weight: .regular))
                .foregroundColor(.warmWhite.opacity(0.7))
                .multilineTextAlignment(.center)
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
    }

    // MARK: - Helpers

    private func toggleCard(_ type: TeamCardType) {
        withAnimation(.spring(duration: 0.3)) {
            expandedCard = (expandedCard == type) ? nil : type
        }
    }

    private var showPostMatch: Bool {
        guard let pm = content?.cards.postMatch,
              let expires = Self.parseISO(pm.expiresAt)
        else { return false }
        return Date() < expires
    }

    /// The routine writes ISO 8601 with or without fractional seconds. A
    /// `.withInternetDateTime`-only parser printed the raw string back at her —
    /// a calendar row reading "2026-09-20T15:00:00.000Z" where a date belongs.
    private static func parseISO(_ raw: String) -> Date? {
        isoFormatter.date(from: raw) ?? isoFractionalFormatter.date(from: raw)
    }

    private static let isoFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    private static let isoFractionalFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    private func comingUpLabel(for dateString: String) -> String {
        guard let date = Self.parseISO(dateString) else { return "Coming up:" }

        if Calendar.current.isDateInToday(date) {
            let hour = Calendar.current.component(.hour, from: date)
            return hour >= 17 ? "Tonight:" : "This afternoon:"
        }

        let daysUntil = Calendar.current.dateComponents([.day], from: Date(), to: date).day ?? 0
        if daysUntil <= 7 {
            let weekday = Calendar.current.component(.weekday, from: date)
            let isWeekend = weekday == 1 || weekday == 7 // Sun or Sat
            return isWeekend ? "This weekend:" : "This week:"
        }
        return "Coming up:"
    }

    @ViewBuilder
    private func infoLine(label: String, value: String) -> some View {
        HStack(spacing: 8) {
            Text(label)
                .font(.jakarta(12, weight: .regular))
                .foregroundColor(.warmWhite.opacity(0.5))
            Text(value)
                .font(.jakarta(14, weight: .bold))
                .foregroundColor(.warmWhite)
        }
    }

    /// The upcoming opponent's key players, rendered inside the "Coming up"
    /// card (which already names the opponent) under a bold hot-rose header.
    /// Bold names + positions + photos, with a row gap between players for
    /// breathing room. Rows are non-tappable (no dossier lookup for the away
    /// side). This is the structured counterpart to the plain-text opponent
    /// detail in next_fixture.preview.
    @ViewBuilder
    private func opponentSection(_ opp: OpponentSide) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Their ones to watch")
                .font(.jakarta(13, weight: .bold))
                .foregroundColor(.hotRose)
                .padding(.top, 6)
            ForEach(Array(opp.players.prefix(3))) { player in
                playerRow(player: player, tappable: false)
            }
        }
    }

    // MARK: - The manager and the ones to know, big

    /// The manager, already open: the black-and-white portrait large, the
    /// name, what he is like, and the line to drop. Nothing to tap — closed,
    /// the card was a name and a thumbnail (Anton, 2026-10-01).
    private func managerFeature(_ manager: ManagerCard, portrait: String) -> some View {
        VStack(spacing: 0) {
            ZStack(alignment: .bottomTrailing) {
                Color.deepMauve
                Image(portrait)
                    .resizable()
                    .scaledToFit()
                    .frame(height: 250)
                    .offset(x: 18)
                    .accessibilityHidden(true)
                VStack(alignment: .leading, spacing: 6) {
                    Text("THE MANAGER")
                        .font(.jakarta(11, weight: .semiBold)).tracking(0.5)
                        .foregroundColor(.mutedText)
                    Text(manager.name)
                        .font(.jakarta(26, weight: .bold))
                        .foregroundColor(.warmWhite)
                        .fixedSize(horizontal: false, vertical: true)
                    Spacer(minLength: 0)
                }
                .padding(16)
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
            }
            .frame(height: 250)
            .clipped()

            Text(appState.personalise(manager.summary))
                .font(.jakarta(15, weight: .regular))
                .foregroundColor(.warmWhite.opacity(0.9))
                .fixedSize(horizontal: false, vertical: true)
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.deepMauve)

            if let point = manager.talkingPoint {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Drop this:")
                        .font(.jakarta(13, weight: .bold))
                    Text(appState.personalise(point))
                        .font(.jakarta(14, weight: .mediumItalic))
                        .fixedSize(horizontal: false, vertical: true)
                }
                .foregroundColor(.warmWhite)
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.hotRose)
            }
        }
        .cornerRadius(16)
        .overlay(RoundedRectangle(cornerRadius: 16).stroke(Color.hotRose.opacity(0.5), lineWidth: 2).padding(1))
        .accessibilityElement(children: .combine)
    }

    /// One of the ones to know at a time: his picture big, his number and
    /// name under it, the one-liner, and the pink strip opening his dossier.
    /// A swipe or the arrow brings the next one.
    private func onesToKnowCarousel(_ onesToKnow: OnesToKnowCard) -> some View {
        let players = Array(onesToKnow.players.prefix(3))
        let index = min(onesIndex, players.count - 1)
        let player = players[index]
        let number = shirtNumber(player.name)
        return VStack(spacing: 0) {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    Text("ONES TO KNOW")
                        .font(.jakarta(11, weight: .semiBold)).tracking(0.5)
                        .foregroundColor(.mutedText)
                    Spacer()
                    Text("\(index + 1) of \(players.count)")
                        .font(.jakarta(12, weight: .medium))
                        .foregroundColor(.mutedText)
                }

                HStack(spacing: 8) {
                    carouselArrow("chevron.left", enabled: index > 0) { onesIndex = index - 1 }
                    portrait(player)
                        .frame(maxWidth: .infinity)
                    carouselArrow("chevron.right", enabled: index + 1 < players.count) { onesIndex = index + 1 }
                }

                VStack(alignment: .leading, spacing: 4) {
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        if let number {
                            Text("\(number)")
                                .font(.jakarta(26, weight: .extraBold))
                                .foregroundColor(.hotRose)
                        }
                        Text(player.name)
                            .font(.jakarta(22, weight: .bold))
                            .foregroundColor(.warmWhite)
                    }
                    Text(player.position.capitalized)
                        .font(.jakarta(13, weight: .medium))
                        .foregroundColor(.warmWhite.opacity(0.55))
                    if let oneLiner = player.oneLiner {
                        Text(appState.personalise(oneLiner))
                            .font(.jakarta(15, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))
                            .fixedSize(horizontal: false, vertical: true)
                            .padding(.top, 4)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .id(player.name)
                .transition(.opacity)
            }
            .padding(16)
            .background(Color.deepMauve)
            .contentShape(Rectangle())
            // Swipe left for the next one, right for the one before.
            .gesture(DragGesture(minimumDistance: 30).onEnded { drag in
                withAnimation(.easeInOut(duration: 0.2)) {
                    if drag.translation.width < -30, index + 1 < players.count { onesIndex = index + 1 }
                    if drag.translation.width > 30, index > 0 { onesIndex = index - 1 }
                }
            })

            // Opens downwards, the way every other card's pink strip does.
            // It used to put up a white sheet from nowhere (Anton,
            // 2026-10-01), and the card-wide "Your opener" read as being
            // about nobody in particular: each man has his own now, in here.
            Button {
                withAnimation(.spring(duration: 0.3)) { onesOpen.toggle() }
            } label: {
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Text("More about \(surnameShown(player.name))")
                            .font(.jakarta(14, weight: .semiBold))
                        Spacer()
                        Image(systemName: "chevron.down")
                            .font(.system(size: 13, weight: .semibold))
                            .rotationEffect(.degrees(onesOpen ? 180 : 0))
                    }
                    if onesOpen {
                        let card = dossier(for: player)
                        if !card.summary.isEmpty {
                            Text(appState.personalise(card.summary))
                                .font(.jakarta(14, weight: .regular))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        if let form = card.form, !form.isEmpty {
                            Text(appState.personalise(form))
                                .font(.jakarta(13, weight: .regular))
                                .opacity(0.85)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Your opener:")
                                .font(.jakarta(13, weight: .bold))
                            Text(appState.personalise(opener(for: player)))
                                .font(.jakarta(14, weight: .mediumItalic))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        .padding(.top, 2)
                        HStack {
                            Spacer()
                            Text("Tap to close ›")
                                .font(.jakarta(11, weight: .regular))
                                .opacity(0.7)
                            Spacer()
                        }
                    }
                }
                .foregroundColor(.warmWhite)
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.hotRose)
                .contentShape(Rectangle())
            }
            .accessibilityHint(onesOpen ? "Closes" : "Opens more about him and a line to say")
            .buttonStyle(.plain)
        }
        .cornerRadius(16)
        .overlay(RoundedRectangle(cornerRadius: 16).stroke(Color.hotRose, lineWidth: 2).padding(1))
    }

    @ViewBuilder
    private func portrait(_ player: TopPlayer) -> some View {
        if let asset = PlayerPortrait.asset(club: teamId, name: player.name) {
            Image(asset)
                .resizable()
                .scaledToFit()
                .frame(height: 280)
                .accessibilityHidden(true)
        } else {
            playerAvatar(player: player, size: 160)
                .frame(height: 200)
        }
    }

    private func carouselArrow(_ symbol: String, enabled: Bool, action: @escaping () -> Void) -> some View {
        Button {
            withAnimation(.easeInOut(duration: 0.2)) { action() }
        } label: {
            Image(systemName: symbol)
                .font(.system(size: 18, weight: .bold))
                .foregroundColor(enabled ? .hotRose : .clear)
                .frame(width: 32, height: 64)
                .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .disabled(!enabled)
        .accessibilityLabel(symbol == "chevron.right" ? "Next player" : "Previous player")
    }

    /// His shirt number off the squad table, matched on the folded surname
    /// when one man in the squad has it, under the squad pack's rule for a
    /// number the feed gives two men (`LiveSquadPack.shirtNumber`).
    private func shirtNumber(_ name: String) -> Int? {
        LiveSquadPack.shirtNumber(named: name, team: teamId, in: squad.players)
    }

    /// "Ødegaard" out of "Martin Ødegaard" or "M. Ødegaard".
    private func surnameShown(_ name: String) -> String {
        name.split(separator: " ").last.map(String.init) ?? name
    }

    /// His own line to say: the squad pack's strongest fact about him this
    /// season ("Saka has three league goals already…"), the same one the
    /// quiz teaches, or the line for his position when the facts are thin.
    private func opener(for player: TopPlayer) -> String {
        let rows = squad.players.filter { $0.team_id == nil || $0.team_id == teamId }
        let key = PlayerPortrait.surname(player.name)
        let hits = rows.filter { PlayerPortrait.surname($0.name) == key }
        let row = hits.count == 1 ? hits[0] : nil
        let team = Team(rawValue: teamId)
        if let row, let team {
            let played = content?.cards.standings?.entries
                .first { $0.teamIdApiFootball == team.apiFootballId || $0.teamName == team.displayName }?.played
            if let use = PlayerHooks.build(players: rows, club: team.shortName, played: played)[row.api_player_id]?.top?.use {
                return use
            }
        }
        let label = LiveClubPack.positionLabel(row?.position ?? player.position)
        return LiveClubPack.positionUse(label, short: surnameShown(player.name))
    }

    /// The dossier, matched on the folded surname when one card has it, and
    /// an empty stub when none does. A contains-match missed "M. Ødegaard"
    /// against "Martin Ødegaard", so Ødegaard and Saka had no "More about".
    private func dossier(for player: TopPlayer) -> PlayerCard {
        let key = PlayerPortrait.surname(player.name)
        let hits = playerCards.filter { key != nil && PlayerPortrait.surname($0.playerName) == key }
        return (hits.count == 1 ? hits.first : nil)
            ?? PlayerCard.stub(teamId: teamId, playerName: player.name, position: player.position)
    }

    private func playerRow(player: TopPlayer, tappable: Bool) -> some View {
        HStack(alignment: .top, spacing: 12) {
            playerAvatar(player: player, size: 36)
            VStack(alignment: .leading, spacing: 2) {
                HStack {
                    Text(player.name)
                        .font(.jakarta(14, weight: .bold))
                        .foregroundColor(.warmWhite)
                    Text(player.position)
                        .font(.jakarta(12, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.5))
                    Spacer()
                    if tappable {
                        Image(systemName: "chevron.right")
                            .font(.system(size: 10))
                            .foregroundColor(.warmWhite.opacity(0.5))
                    }
                }
                if let oneLiner = player.oneLiner {
                    Text(appState.personalise(oneLiner))
                        .font(.jakarta(12, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.7))
                }
            }
        }
        .padding(.vertical, 2)
    }

    /// Circular player headshot mirroring the onboarding flow's
    /// `MeetTeamView.playerAvatar`, shrunk to row-height (default 36pt).
    /// Image source is the API-Football CDN URL stored on
    /// `TopPlayer.photoURL`; falls back to hot-rose-tinted initials when
    /// the URL is missing or the AsyncImage load fails. `URLCache.shared`
    /// (configured in AppDelegate.swift) gives us a free disk cache so
    /// re-renders are instant after first view.
    @ViewBuilder
    private func playerAvatar(player: TopPlayer, size: CGFloat) -> some View {
        ZStack {
            Circle().fill(Color.hotRose.opacity(0.15))
            if let urlString = player.photoURL, let url = URL(string: urlString) {
                AsyncImage(url: url) { phase in
                    switch phase {
                    case .success(let image):
                        image.resizable().scaledToFill()
                    default:
                        playerInitials(player.name, size: size)
                    }
                }
            } else {
                playerInitials(player.name, size: size)
            }
        }
        .frame(width: size, height: size)
        .clipShape(Circle())
    }

    private func playerInitials(_ name: String, size: CGFloat) -> some View {
        let initials = name
            .split(separator: " ")
            .prefix(2)
            .compactMap { $0.first.map(String.init) }
            .joined()
            .uppercased()
        return Text(initials)
            .font(.jakarta(size * 0.4, weight: .bold))
            .foregroundColor(.hotRose)
    }

    /// "Tue 8 Sep, 8:45pm" for the collapsed Coming-up row. The weekday was
    /// spelled out until a competition chip joined it on the same line and the
    /// time started truncating; the Calendar tab abbreviates it too.
    private func formattedFixtureDate(_ isoDate: String) -> String {
        guard let date = Self.parseISO(isoDate) else { return isoDate }
        return Self.kickoffLineFmt.string(from: date)
    }

    // MARK: - Loading state

    private var teamPageLoadingView: some View {
        VStack(spacing: 12) {
            Circle()
                .fill(Color.feedDivider)
                .frame(width: 64, height: 64)
                .padding(.top, 16)

            ForEach(0..<5, id: \.self) { _ in
                RoundedRectangle(cornerRadius: 16)
                    .fill(Color.deepMauve.opacity(0.5))
                    .frame(height: 120)
                    .overlay(
                        RoundedRectangle(cornerRadius: 16)
                            .stroke(Color.hotRose.opacity(0.2), lineWidth: 2)
                            .padding(1)
                    )
            }
        }
        .padding(.horizontal, 16)
    }

    // MARK: - Error state

    private var teamPageErrorView: some View {
        VStack(spacing: 16) {
            Text("Couldn't load \(hisNameOrHis.lowercased()) team right now.")
                .font(.jakarta(15, weight: .semiBold))
                .foregroundColor(.warmWhite)
            Button {
                Task { await loadTeamPage() }
            } label: {
                Text("Try again")
                    .font(.jakarta(15, weight: .semiBold))
                    .foregroundColor(.warmWhite)
                    .padding(.horizontal, 24)
                    .padding(.vertical, 10)
                    .background(Color.hotRose)
                    .cornerRadius(Layout.buttonCornerRadius)
            }
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
        .padding(.horizontal, 16)
    }

    // MARK: - Warm placeholder

    private var warmPlaceholderView: some View {
        VStack(spacing: 16) {
            Image(systemName: "sportscourt")
                .font(.system(size: 32))
                .foregroundColor(.hotRose.opacity(0.6))
            Text("We're getting \(hisNameOrHis.lowercased()) team ready. Check back in a moment.")
                .font(.jakarta(15, weight: .medium))
                .foregroundColor(.warmWhite.opacity(0.7))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 24)
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
        .padding(.horizontal, 16)
    }

    // MARK: - Data loading with cache

    private func loadTeamPage() async {
        isLoading = true
        hasError = false

        #if DEBUG
        // Screenshot harness: render a `team_pages.content` document read from
        // a file instead of the network, so a payload the backend has not
        // started writing yet can still be reviewed on a real screen.
        // -gdTeamPageJSON /path/to/page.json
        let args = ProcessInfo.processInfo.arguments
        if let i = args.firstIndex(of: "-gdTeamPageJSON"), i + 1 < args.count,
           let data = FileManager.default.contents(atPath: args[i + 1]),
           let stub = try? JSONDecoder().decode(TeamPageContent.self, from: data) {
            content = stub
            isLoading = false
            return
        }
        #endif

        // Check cache first
        if let cached = TeamPageCache.load(teamId: teamId) {
            content = cached.content
            isLoading = false

            // Fetch player cards + insider set + previews in parallel with fresh data
            async let freshContent = fetchFromNetwork()
            async let players = fetchPlayerCards()
            async let insider = fetchInsiderSet()
            async let previews = fetchPreviewItems()

            playerCards = await players
            insiderSet = await insider
            previewByFixtureId = indexPreviews(await previews)

            if let fresh = await freshContent {
                content = fresh
                TeamPageCache.save(content: fresh, teamId: teamId)
            }
            return
        }

        // No cache — fetch from network
        do {
            let fetched = try await APIClient.shared.fetchTeamPage(teamId: teamId)
            if let fetched {
                content = fetched
                TeamPageCache.save(content: fetched, teamId: teamId)
                async let players = fetchPlayerCards()
                async let insider = fetchInsiderSet()
                async let previews = fetchPreviewItems()
                playerCards = await players
                insiderSet = await insider
                previewByFixtureId = indexPreviews(await previews)
            } else {
                #if DEBUG
                if let mock = MockData.teamPage(for: teamId) {
                    content = mock
                } else {
                    content = nil
                }
                #endif
            }
        } catch {
            #if DEBUG
            if let mock = MockData.teamPage(for: teamId) {
                content = mock
            } else {
                hasError = true
            }
            #else
            hasError = true
            #endif
        }
        isLoading = false
    }

    private func fetchFromNetwork() async -> TeamPageContent? {
        try? await APIClient.shared.fetchTeamPage(teamId: teamId)
    }

    private func fetchPlayerCards() async -> [PlayerCard] {
        (try? await APIClient.shared.fetchPlayerCards(teamId: teamId)) ?? []
    }

    /// Fetches up to 4 insider items, one of each type (stat, history,
    /// oddity, anecdote — in that order). Returns an empty array on error
    /// or when the team has no items yet — caller treats both identically
    /// (the section just hides).
    private func fetchInsiderSet() async -> [InsiderItem] {
        (try? await APIClient.shared.fetchInsiderSet(teamId: teamId)) ?? []
    }

    /// Fetches pre-tournament preview content_items for this team. Used to
    /// power the Calendar tap-to-detail navigation. Empty array on error
    /// or for teams without seeded previews (most teams pre-V1.1).
    private func fetchPreviewItems() async -> [ContentItem] {
        (try? await APIClient.shared.fetchPreviewItems(teamId: teamId)) ?? []
    }

    /// Build a `previewFixtureId → ContentItem` map for fast lookup at
    /// row-render time. Only items with non-nil `previewFixtureId` enter
    /// the map; the fetch query already filters for these, but the guard
    /// is cheap and defensive.
    private func indexPreviews(_ items: [ContentItem]) -> [String: ContentItem] {
        var out: [String: ContentItem] = [:]
        for item in items {
            if let key = item.previewFixtureId { out[key] = item }
        }
        return out
    }

    /// Compute the synthetic fixture id used to link an upcoming fixture
    /// row to its preview content_item. Format mirrors the migration 053
    /// COMMENT: `"<team_id>:<iso-date>:<opponent-slug>"`. ISO date is
    /// the date portion only (no time) so minor timestamp drift between
    /// the team_pages payload and the content_items row doesn't break
    /// the match. Opponent slug lowercases the display name and swaps
    /// spaces for underscores ("Costa Rica" → "costa_rica").
    private func previewKey(for fixture: UpcomingFixture) -> String {
        let datePart = String(fixture.date.prefix(10))
        let slug = fixture.opponent
            .lowercased()
            .replacingOccurrences(of: " ", with: "_")
        return "\(teamId):\(datePart):\(slug)"
    }
}
