import SwiftUI

struct TeamPageView: View {
    let teamId: String
    @Environment(AppState.self) var appState
    @State private var content: TeamPageContent?
    @State private var playerCards: [PlayerCard] = []
    /// Up to 4 insider items: latest of each type (stat, history, oddity,
    /// anecdote). Powers the redesigned "Things he doesn't know" section
    /// at the bottom of the team page. Empty array = section hidden.
    @State private var insiderSet: [InsiderItem] = []
    @State private var isLoading = true
    @State private var hasError = false
    @State private var presentedPlayer: PlayerCard?
    @State private var expandedCard: TeamCardType?
    @State private var activeTab: TeamTab = .info

    private enum TeamCardType: Hashable {
        case basics, manager, onesToKnow, rivalry, form, season, comingUp
    }

    /// 3-way segmented control at the top of the team page.
    /// - `.info`: the existing scroll of cards (mood, basics, manager,
    ///   ones to know, rivalry, form, season, coming up, insider headlines).
    /// - `.calendar`: visual upcoming-fixtures list with per-game importance
    ///   ratings + one-liners (server-generated by team-page-generator).
    /// - `.table`: full standings — 20-row PL table for clubs, 4-row group
    ///   for WC countries, user's row highlighted rose.
    private enum TeamTab: String, CaseIterable, Identifiable {
        case info = "Info"
        case calendar = "Calendar"
        case table = "Table"
        var id: String { rawValue }
    }

    private var hisNameOrHis: String {
        appState.hisName.isEmpty ? "His" : appState.hisName + "'s"
    }

    /// Resolve the entity for this team page — could be a PL Team or a WC
    /// Country, both keyed by the teamId string. V2.0: countries live in
    /// the same `teams` table as clubs.
    private var entityDisplayName: String {
        if let team = Team(rawValue: teamId) { return team.displayName }
        if let country = Country(rawValue: teamId) { return country.displayName }
        return ""
    }

    /// Crest for the team-page header. PL clubs render their club crest;
    /// WC countries render their flag. Both come from API-Football's CDN
    /// via `TeamCrestView`, which falls back to a soft-blush shield icon
    /// if the image is still loading or the URL is unavailable. Replaces
    /// the pink-circle-with-first-letter placeholder used in V1, which
    /// rendered "S" for Sweden, "A" for Arsenal etc. — a brand-aligned
    /// placeholder that became a regression once the team data carried
    /// real crest URLs.
    @ViewBuilder
    private var entityCrest: some View {
        if let team = Team(rawValue: teamId) {
            TeamCrestView(team: team, size: 64)
        } else if let country = Country(rawValue: teamId) {
            TeamCrestView(country: country, size: 64)
        } else {
            // teamId matched neither enum (data integrity issue elsewhere).
            // TeamCrestView's url:nil initialiser yields the same shield
            // fallback it shows for any failed image load.
            TeamCrestView(url: nil, size: 64)
        }
    }

    /// Word-aware truncation; avoids mid-word cuts.
    private func truncateAtWord(_ text: String, maxChars: Int) -> String {
        if text.count <= maxChars { return text }
        let cutEnd = text.index(text.startIndex, offsetBy: maxChars)
        let head = text[..<cutEnd]
        if let lastSpace = head.lastIndex(where: { $0.isWhitespace }) {
            return String(text[..<lastSpace]) + "…"
        }
        return String(head) + "…"
    }

    /// Rivalry blurbs from team-page-generator are shaped `"<rivals> — <context>..."`.
    /// Split on the dash to surface just the rival names as a headline.
    private func rivalsHeadline(_ text: String) -> String {
        let separators: [Character] = ["—", "–", "-"]
        if let dashIdx = text.firstIndex(where: { separators.contains($0) }) {
            let head = text[..<dashIdx].trimmingCharacters(in: .whitespaces)
            if !head.isEmpty && head.count <= 60 { return head }
        }
        return truncateAtWord(text, maxChars: 50)
    }

    var body: some View {
        ZStack {
            Color.appBackground.ignoresSafeArea()

            if let content {
                ScrollView {
                    VStack(spacing: 12) {
                        headerSection
                        tabSelector
                        tabContent(content.cards)
                    }
                    .padding(.horizontal, 16)
                    .padding(.bottom, 40)
                }
            } else if isLoading {
                teamPageLoadingView
            } else if hasError {
                teamPageErrorView
            } else {
                warmPlaceholderView
            }
        }
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(Color.appBackground, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
        .task { await loadTeamPage() }
        .sheet(item: $presentedPlayer) { player in
            PlayerCardModal(player: player)
        }
    }

    // MARK: - Header

    private var headerSection: some View {
        VStack(spacing: 12) {
            entityCrest

            Text(entityDisplayName)
                .font(.jakarta(20, weight: .bold))
                .foregroundColor(.warmWhite)

            Text("\(hisNameOrHis) team")
                .font(.jakarta(14, weight: .regular))
                .foregroundColor(.mutedText)
        }
        .frame(maxWidth: .infinity)
        .padding(.top, 8)
        .padding(.bottom, 4)
    }

    // MARK: - Tab selector + dispatcher

    /// 3-way control: only the SELECTED tab renders as a hot-rose pill —
    /// the other two sit as bare, recessed text on the team-page
    /// background. The previous design had a soft-blush gutter + white
    /// pills for the unselected tabs; on the deep-mauve team page that
    /// read as competing chrome. Lighter visual = the page header
    /// breathes, and your eye lands on the active tab immediately.
    private var tabSelector: some View {
        HStack(spacing: 0) {
            ForEach(TeamTab.allCases) { tab in
                Button {
                    withAnimation(.spring(duration: 0.25)) {
                        activeTab = tab
                    }
                    UIImpactFeedbackGenerator(style: .light).impactOccurred()
                } label: {
                    Text(tab.rawValue)
                        .font(.jakarta(15, weight: .medium))
                        .frame(maxWidth: .infinity)
                        .frame(height: 40)
                        .background(activeTab == tab ? Color.hotRose : Color.clear)
                        .foregroundColor(activeTab == tab ? .warmWhite : .warmWhite.opacity(0.6))
                        .cornerRadius(12)
                }
            }
        }
    }

    @ViewBuilder
    private func tabContent(_ cards: TeamPageCards) -> some View {
        switch activeTab {
        case .info:     cardsSection(cards)
        case .calendar: calendarTab(cards)
        case .table:    tableTab(cards)
        }
    }

    // MARK: - Cards section

    @ViewBuilder
    private func cardsSection(_ cards: TeamPageCards) -> some View {
        // Mood banner
        if let mood = cards.mood {
            TeamPageMoodBanner(mood: mood)
        }

        // THIS WEEK hero
        if let thisWeek = cards.thisWeek {
            TeamPageThisWeek(card: thisWeek)
        }

        // Card 1: The basics
        if let basics = cards.basics {
            TeamPageCard(
                title: "The basics",
                primaryText: basics.nickname,
                zone2Label: "Say this:",
                talkingPoint: basics.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .basics,
                onTap: { toggleCard(.basics) },
                zone1Collapsed: {
                    // Stadium when we have one; nickname as a backup
                    // subtitle for WC countries without a clear single
                    // home venue. Either way the collapsed card has a
                    // visible second line — empty subtitle reads as a
                    // broken state.
                    Text(basics.stadium ?? basics.nickname)
                        .font(.jakarta(13, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.7))
                        .lineLimit(1)
                },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 6) {
                        infoLine(label: "Known as", value: basics.nickname)
                        if let stadium = basics.stadium {
                            infoLine(label: "Home ground", value: stadium)
                        }
                        Text(appState.personalise(basics.funFact))
                            .font(.jakarta(13, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.7))
                            .padding(.top, 4)
                    }
                }
            )
        }

        // Card 2: The manager. Skip when the backend's "<UNKNOWN>" placeholder
        // landed in the data (team-page-generator's fallback for missing
        // API-Football coach data). Otherwise the card would render the
        // literal string to users.
        if let manager = cards.manager, manager.name != "<UNKNOWN>" {
            TeamPageCard(
                title: "The manager",
                primaryText: manager.name,
                zone2Label: "Drop this:",
                talkingPoint: manager.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .manager,
                onTap: { toggleCard(.manager) },
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    Text(appState.personalise(manager.summary))
                        .font(.jakarta(14, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.9))
                        .padding(.top, 2)
                }
            )
        }

        // Card 3: Ones to know
        if let onesToKnow = cards.onesToKnow, !onesToKnow.players.isEmpty {
            TeamPageCard(
                title: "Ones to know",
                primaryText: onesToKnow.players.prefix(3).map(\.name).joined(separator: ", "),
                zone2Label: "Your opener:",
                talkingPoint: onesToKnow.talkingPoint.map { appState.personalise($0) },
                isExpanded: expandedCard == .onesToKnow,
                onTap: { toggleCard(.onesToKnow) },
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    // Always tappable. Diacritic-folded + lowercased contains
                    // so "Odegaard" matches "Martin Ødegaard" and "Saka"
                    // matches "Bukayo Saka". Stub-with-empty-summary triggers
                    // PlayerCardModal's .empty branch when no dossier exists.
                    let foldedPlayerCards: [(card: PlayerCard, foldedName: String)] = playerCards.map {
                        ($0, $0.playerName.folding(options: [.diacriticInsensitive, .caseInsensitive], locale: .current))
                    }
                    VStack(alignment: .leading, spacing: 4) {
                        ForEach(Array(onesToKnow.players.prefix(3))) { player in
                            let onesName = player.name.folding(options: [.diacriticInsensitive, .caseInsensitive], locale: .current)
                            let matchingCard = foldedPlayerCards.first { entry in
                                entry.foldedName.contains(onesName) || onesName.contains(entry.foldedName)
                            }?.card

                            Button {
                                presentedPlayer = matchingCard ?? PlayerCard.stub(
                                    teamId: teamId,
                                    playerName: player.name,
                                    position: player.position
                                )
                            } label: {
                                playerRow(player: player, tappable: true)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }
            )
        }

        // Card 4: The rivalry
        if let rivalry = cards.rivalry {
            TeamPageCard(
                title: "The rivalry",
                primaryText: rivalsHeadline(appState.personalise(rivalry.text)),
                zone2Label: "Use this:",
                talkingPoint: rivalry.talkingPoint.map { appState.personalise($0) },
                isStatic: true,
                isExpanded: expandedCard == .rivalry,
                onTap: { toggleCard(.rivalry) },
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 8) {
                        Text(appState.personalise(rivalry.text))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))

                        if let intensity = cards.rivalryIntensity {
                            TeamPageRivalryMeter(intensity: intensity)
                        }
                    }
                }
            )
        }

        // Card 5: How they're doing
        if let form = cards.form {
            TeamPageCard(
                title: "How they're doing",
                primaryText: form.leaguePositionLabel,
                zone2Label: "Say this:",
                talkingPoint: form.talkingPoint.map { appState.personalise($0) },
                isExpanded: expandedCard == .form,
                onTap: { toggleCard(.form) },
                zone1Collapsed: {
                    TeamPageFormDots(recentForm: form.recentForm, isExpanded: false)
                },
                zone1Expanded: {
                    VStack(alignment: .leading, spacing: 6) {
                        TeamPageFormDots(recentForm: form.recentForm, isExpanded: expandedCard == .form)

                        Text(appState.personalise(form.formSummary))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))
                    }
                }
            )
        }

        // Card 6: The season so far
        if let season = cards.season {
            TeamPageCard(
                title: "The season so far",
                primaryText: truncateAtWord(appState.personalise(season.summary), maxChars: 50),
                zone2Label: "Drop this:",
                talkingPoint: season.talkingPoint.map { appState.personalise($0) },
                isExpanded: expandedCard == .season,
                onTap: { toggleCard(.season) },
                zone1Collapsed: { EmptyView() },
                zone1Expanded: {
                    Text(appState.personalise(season.summary))
                        .font(.jakarta(14, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.9))
                }
            )
        }

        // Card 7: Coming up / Post-match
        if showPostMatch, let postMatch = content?.cards.postMatch {
            postMatchCard(postMatch)
        } else if let fixture = cards.nextFixture {
            comingUpCard(fixture)
        }

        // Card 8 (T2+ only): "Things he doesn't know" — 4 niche items
        // (latest of each type: stat / history / oddity / anecdote)
        // refreshed by the gd-insider cloud routine. Headlines only,
        // no body text — InsiderHeadlineRow keeps it compact. Gating:
        // TierGating.isAvailable(.insiderCard, tier:) returns true for
        // tier 2 and 3 — T1 users never see it. Section also hides if
        // the team has no items yet (brand-new entity the routine hasn't
        // populated, or a backfill skip).
        if TierGating.isAvailable(.insiderCard, tier: appState.selectedTier),
           !insiderSet.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Text("THINGS HE DOESN'T KNOW")
                    .font(.sectionHeader)
                    .tracking(1)
                    .foregroundColor(.mutedText)
                    // Align with the row's inner padding (14pt around the
                    // rose bar + content) so the tracker label sits flush
                    // with each row's content edge.
                    .padding(.leading, 14)
                VStack(spacing: 8) {
                    ForEach(insiderSet) { item in
                        InsiderHeadlineRow(item: item)
                    }
                }
            }
            .padding(.top, 8)
        }

        // Freshness line
        if let text = cards.freshnessText {
            Text(text)
                .font(.jakarta(12, weight: .regular))
                .foregroundColor(.mutedText)
                .frame(maxWidth: .infinity)
                .padding(.top, 8)
        }
    }

    // MARK: - Coming up card

    @ViewBuilder
    private func comingUpCard(_ fixture: NextFixtureCard) -> some View {
        TeamPageCard(
            title: "Coming up",
            primaryText: "\(fixture.opponent) (\(fixture.venue.uppercased()))",
            zone2Label: comingUpLabel(for: fixture.date),
            talkingPoint: fixture.talkingPoint.map { appState.personalise($0) },
            isExpanded: expandedCard == .comingUp,
            onTap: { toggleCard(.comingUp) },
            zone1Collapsed: {
                Text(formattedFixtureDate(fixture.date))
                    .font(.jakarta(13, weight: .regular))
                    .foregroundColor(.warmWhite.opacity(0.7))
                    .lineLimit(1)
            },
            zone1Expanded: {
                VStack(alignment: .leading, spacing: 6) {
                    TeamPageCountdown(targetDate: fixture.date)

                    if !fixture.preview.isEmpty {
                        Text(appState.personalise(fixture.preview))
                            .font(.jakarta(14, weight: .regular))
                            .foregroundColor(.warmWhite.opacity(0.9))
                            .padding(.top, 2)
                    }
                }
            }
        )
    }

    // MARK: - Post-match card

    @ViewBuilder
    private func postMatchCard(_ postMatch: TeamPostMatchCard) -> some View {
        let tintColor: Color? = {
            switch postMatch.state {
            case .win: return Color.hotRose.opacity(0.06)
            case .loss: return Color.red.opacity(0.04)
            case .draw: return nil
            }
        }()

        let label: String = {
            switch postMatch.state {
            case .win: return "Say this:"
            case .loss: return "Tonight:"
            case .draw: return "Ask him:"
            }
        }()

        TeamPageCard(
            title: postMatch.state == .win ? "After the win" : postMatch.state == .loss ? "After the loss" : "After the draw",
            primaryText: truncateAtWord(appState.personalise(postMatch.text), maxChars: 50),
            zone2Label: label,
            talkingPoint: appState.personalise(postMatch.talkingPoint),
            isExpanded: expandedCard == .comingUp,
            onTap: { toggleCard(.comingUp) },
            tintColor: tintColor,
            zone1Collapsed: { EmptyView() },
            zone1Expanded: {
                Text(appState.personalise(postMatch.text))
                    .font(.jakarta(14, weight: .regular))
                    .foregroundColor(.warmWhite.opacity(0.9))
            }
        )
    }

    // MARK: - Calendar tab

    @ViewBuilder
    private func calendarTab(_ cards: TeamPageCards) -> some View {
        let fixtures = cards.upcomingFixtures ?? []
        if fixtures.isEmpty {
            emptyState(
                icon: "calendar",
                text: "No upcoming fixtures yet. Check back closer to kickoff."
            )
        } else {
            VStack(spacing: Layout.cardSpacing) {
                ForEach(fixtures) { fixture in
                    calendarRow(fixture)
                }
            }
        }
    }

    @ViewBuilder
    private func calendarRow(_ f: UpcomingFixture) -> some View {
        let parsed = Self.isoFormatter.date(from: f.date)
        HStack(alignment: .top, spacing: 14) {
            // Left: date stack
            VStack(alignment: .leading, spacing: 2) {
                Text(parsed.map { Self.dayOfWeek($0) } ?? "")
                    .font(.sectionHeader).tracking(1)
                    .foregroundColor(.hotRose)
                Text(parsed.map { Self.dayMonth($0) } ?? f.date)
                    .font(.feedHeadline).foregroundColor(.warmWhite)
                Text(parsed.map { Self.kickoffTime($0) } ?? "")
                    .font(.feedTimestamp).foregroundColor(.warmWhite.opacity(0.6))
            }
            .frame(width: 70, alignment: .leading)

            // Middle: opponent + venue
            VStack(alignment: .leading, spacing: 2) {
                Text(f.opponent)
                    .font(.feedHeadline).foregroundColor(.warmWhite)
                Text(f.venue.capitalized)
                    .font(.feedTimestamp).foregroundColor(.warmWhite.opacity(0.6))
            }
            Spacer(minLength: 0)

            // Right: dots + label
            VStack(alignment: .trailing, spacing: 4) {
                HStack(spacing: 3) {
                    ForEach(1...5, id: \.self) { dot in
                        Circle()
                            .fill(dot <= f.importanceDots ? Color.hotRose : Color.mutedText.opacity(0.3))
                            .frame(width: 6, height: 6)
                    }
                }
                Text(f.importanceLabel)
                    .font(.feedTimestamp).foregroundColor(.hotRose)
                    .lineLimit(1)
            }
            .frame(width: 100, alignment: .trailing)
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.15), lineWidth: 1)
        )
    }

    // Cached formatters — DateFormatter() init is expensive (locale/calendar
    // setup) and each calendar row needs all three. Allocating fresh per
    // call would be ~24 inits per render with 8 fixtures.
    private static let dayOfWeekFmt: DateFormatter = {
        let f = DateFormatter(); f.dateFormat = "EEE"; return f
    }()
    private static let dayMonthFmt: DateFormatter = {
        let f = DateFormatter(); f.dateFormat = "d MMM"; return f
    }()
    private static let kickoffTimeFmt: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "h:mma"
        f.amSymbol = "am"; f.pmSymbol = "pm"
        return f
    }()

    private static func dayOfWeek(_ d: Date) -> String { dayOfWeekFmt.string(from: d).uppercased() }
    private static func dayMonth(_ d: Date) -> String { dayMonthFmt.string(from: d) }
    private static func kickoffTime(_ d: Date) -> String { kickoffTimeFmt.string(from: d) }

    // MARK: - Table tab

    @ViewBuilder
    private func tableTab(_ cards: TeamPageCards) -> some View {
        if let standings = cards.standings, !standings.entries.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Text(standings.competitionLabel.uppercased())
                    .font(.sectionHeader).tracking(1)
                    .foregroundColor(.hotRose.opacity(0.7))
                    .padding(.leading, 14)
                standingsTable(standings.entries)
            }
        } else {
            emptyState(icon: "tablecells", text: "Standings will appear when the data lands.")
        }
    }

    @ViewBuilder
    private func standingsTable(_ entries: [StandingsEntry]) -> some View {
        // Resolve the user's row index once per render rather than calling
        // isUserTeam() inside the ForEach (which would do a string lookup
        // for every entry; for a 20-row PL table that's 20 ops per body
        // recomputation).
        let userIdx = entries.firstIndex { isUserTeam($0) }
        VStack(spacing: 0) {
            standingsHeader
            ForEach(Array(entries.enumerated()), id: \.element.id) { idx, entry in
                standingsRow(entry, isUser: idx == userIdx)
                if entry.id != entries.last?.id {
                    Divider().background(Color.warmWhite.opacity(0.08))
                }
            }
        }
        .padding(.vertical, 8)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.2), lineWidth: 1)
        )
    }

    private var standingsHeader: some View {
        HStack {
            Text("#").frame(width: 24, alignment: .leading)
            Text("TEAM").frame(maxWidth: .infinity, alignment: .leading)
            Text("P").frame(width: 28, alignment: .trailing)
            Text("GD").frame(width: 40, alignment: .trailing)
            Text("PTS").frame(width: 36, alignment: .trailing)
        }
        .font(.sectionHeader).tracking(1)
        .foregroundColor(.mutedText)
        .padding(.horizontal, 14)
        .padding(.bottom, 6)
    }

    @ViewBuilder
    private func standingsRow(_ e: StandingsEntry, isUser: Bool) -> some View {
        HStack {
            Text("\(e.rank)")
                .font(.jakarta(13, weight: .regular))
                .frame(width: 24, alignment: .leading)
            Text(e.teamName)
                .font(.jakarta(14, weight: isUser ? .bold : .regular))
                .frame(maxWidth: .infinity, alignment: .leading)
                .lineLimit(1)
            Text("\(e.played)").frame(width: 28, alignment: .trailing)
                .font(.jakarta(13, weight: .regular))
            Text(formatGd(e.gd)).frame(width: 40, alignment: .trailing)
                .font(.jakarta(13, weight: .regular))
            Text("\(e.points)").frame(width: 36, alignment: .trailing)
                .font(.jakarta(13, weight: isUser ? .bold : .semiBold))
        }
        .foregroundColor(.warmWhite)
        .padding(.horizontal, 14)
        .padding(.vertical, 8)
        .background(isUser ? Color.hotRose.opacity(0.12) : Color.clear)
    }

    /// User's API-Football id, used to match the standings row precisely
    /// (the previous bidirectional-contains match was wrong for cases like
    /// "Manchester United" vs "Manchester City" — both contain "Manchester").
    /// Falls back to a name-equality check if the entry has no API id.
    private var userApiFootballId: Int? {
        if let team = Team(rawValue: teamId) { return team.apiFootballId }
        if let country = Country(rawValue: teamId) { return country.apiFootballId }
        return nil
    }

    private func isUserTeam(_ e: StandingsEntry) -> Bool {
        if let mine = userApiFootballId, let theirs = e.teamIdApiFootball {
            return mine == theirs
        }
        // No id on this entry — last-ditch exact-name fallback. Avoid
        // substring matching to prevent false positives on "Manchester *".
        return e.teamName.lowercased() == entityDisplayName.lowercased()
    }

    private func formatGd(_ gd: Int) -> String {
        gd > 0 ? "+\(gd)" : "\(gd)"
    }

    @ViewBuilder
    private func emptyState(icon: String, text: String) -> some View {
        VStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 28)).foregroundColor(.hotRose.opacity(0.6))
            Text(text)
                .font(.jakarta(14, weight: .regular))
                .foregroundColor(.warmWhite.opacity(0.7))
                .multilineTextAlignment(.center)
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
    }

    // MARK: - Helpers

    private func toggleCard(_ type: TeamCardType) {
        withAnimation(.spring(duration: 0.3)) {
            expandedCard = (expandedCard == type) ? nil : type
        }
    }

    private var showPostMatch: Bool {
        guard let pm = content?.cards.postMatch,
              let expires = Self.isoFormatter.date(from: pm.expiresAt)
        else { return false }
        return Date() < expires
    }

    private static let isoFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    private func comingUpLabel(for dateString: String) -> String {
        guard let date = Self.isoFormatter.date(from: dateString) else { return "Coming up:" }

        if Calendar.current.isDateInToday(date) {
            let hour = Calendar.current.component(.hour, from: date)
            return hour >= 17 ? "Tonight:" : "This afternoon:"
        }

        let daysUntil = Calendar.current.dateComponents([.day], from: Date(), to: date).day ?? 0
        if daysUntil <= 7 {
            let weekday = Calendar.current.component(.weekday, from: date)
            let isWeekend = weekday == 1 || weekday == 7 // Sun or Sat
            return isWeekend ? "This weekend:" : "This week:"
        }
        return "Coming up:"
    }

    @ViewBuilder
    private func infoLine(label: String, value: String) -> some View {
        HStack(spacing: 8) {
            Text(label)
                .font(.jakarta(12, weight: .regular))
                .foregroundColor(.warmWhite.opacity(0.5))
            Text(value)
                .font(.jakarta(14, weight: .bold))
                .foregroundColor(.warmWhite)
        }
    }

    @ViewBuilder
    private func playerRow(player: TopPlayer, tappable: Bool) -> some View {
        HStack(alignment: .top, spacing: 12) {
            playerAvatar(player: player, size: 36)
            VStack(alignment: .leading, spacing: 2) {
                HStack {
                    Text(player.name)
                        .font(.jakarta(14, weight: .bold))
                        .foregroundColor(.warmWhite)
                    Text(player.position)
                        .font(.jakarta(12, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.5))
                    Spacer()
                    if tappable {
                        Image(systemName: "chevron.right")
                            .font(.system(size: 10))
                            .foregroundColor(.warmWhite.opacity(0.5))
                    }
                }
                if let oneLiner = player.oneLiner {
                    Text(appState.personalise(oneLiner))
                        .font(.jakarta(12, weight: .regular))
                        .foregroundColor(.warmWhite.opacity(0.7))
                }
            }
        }
        .padding(.vertical, 2)
    }

    /// Circular player headshot mirroring the onboarding flow's
    /// `MeetTeamView.playerAvatar`, shrunk to row-height (default 36pt).
    /// Image source is the API-Football CDN URL stored on
    /// `TopPlayer.photoURL`; falls back to hot-rose-tinted initials when
    /// the URL is missing or the AsyncImage load fails. `URLCache.shared`
    /// (configured in AppDelegate.swift) gives us a free disk cache so
    /// re-renders are instant after first view.
    @ViewBuilder
    private func playerAvatar(player: TopPlayer, size: CGFloat) -> some View {
        ZStack {
            Circle().fill(Color.hotRose.opacity(0.15))
            if let urlString = player.photoURL, let url = URL(string: urlString) {
                AsyncImage(url: url) { phase in
                    switch phase {
                    case .success(let image):
                        image.resizable().scaledToFill()
                    default:
                        playerInitials(player.name, size: size)
                    }
                }
            } else {
                playerInitials(player.name, size: size)
            }
        }
        .frame(width: size, height: size)
        .clipShape(Circle())
    }

    private func playerInitials(_ name: String, size: CGFloat) -> some View {
        let initials = name
            .split(separator: " ")
            .prefix(2)
            .compactMap { $0.first.map(String.init) }
            .joined()
            .uppercased()
        return Text(initials)
            .font(.jakarta(size * 0.4, weight: .bold))
            .foregroundColor(.hotRose)
    }

    private func formattedFixtureDate(_ isoDate: String) -> String {
        guard let date = Self.isoFormatter.date(from: isoDate) else { return isoDate }

        let display = DateFormatter()
        display.dateFormat = "EEEE d MMM, h:mma"
        display.amSymbol = "am"
        display.pmSymbol = "pm"
        return display.string(from: date)
    }

    // MARK: - Loading state

    private var teamPageLoadingView: some View {
        VStack(spacing: 12) {
            Circle()
                .fill(Color.feedDivider)
                .frame(width: 64, height: 64)
                .padding(.top, 16)

            ForEach(0..<5, id: \.self) { _ in
                RoundedRectangle(cornerRadius: 16)
                    .fill(Color.deepMauve.opacity(0.5))
                    .frame(height: 120)
                    .overlay(
                        RoundedRectangle(cornerRadius: 16)
                            .stroke(Color.hotRose.opacity(0.2), lineWidth: 2)
                            .padding(1)
                    )
            }
        }
        .padding(.horizontal, 16)
    }

    // MARK: - Error state

    private var teamPageErrorView: some View {
        VStack(spacing: 16) {
            Text("Couldn't load \(hisNameOrHis.lowercased()) team right now.")
                .font(.jakarta(15, weight: .semiBold))
                .foregroundColor(.warmWhite)
            Button {
                Task { await loadTeamPage() }
            } label: {
                Text("Try again")
                    .font(.jakarta(15, weight: .semiBold))
                    .foregroundColor(.warmWhite)
                    .padding(.horizontal, 24)
                    .padding(.vertical, 10)
                    .background(Color.hotRose)
                    .cornerRadius(Layout.buttonCornerRadius)
            }
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
        .padding(.horizontal, 16)
    }

    // MARK: - Warm placeholder

    private var warmPlaceholderView: some View {
        VStack(spacing: 16) {
            Image(systemName: "sportscourt")
                .font(.system(size: 32))
                .foregroundColor(.hotRose.opacity(0.6))
            Text("We're getting \(hisNameOrHis.lowercased()) team ready. Check back in a moment.")
                .font(.jakarta(15, weight: .medium))
                .foregroundColor(.warmWhite.opacity(0.7))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 24)
        }
        .padding(Layout.cardPadding)
        .frame(maxWidth: .infinity)
        .background(Color.deepMauve)
        .cornerRadius(Layout.cardCornerRadius)
        .overlay(
            RoundedRectangle(cornerRadius: Layout.cardCornerRadius)
                .stroke(Color.hotRose.opacity(0.3), lineWidth: 2)
                .padding(1)
        )
        .padding(.horizontal, 16)
    }

    // MARK: - Data loading with cache

    private func loadTeamPage() async {
        isLoading = true
        hasError = false

        // Check cache first
        if let cached = TeamPageCache.load(teamId: teamId) {
            content = cached.content
            isLoading = false

            // Fetch player cards + insider set in parallel with fresh data
            async let freshContent = fetchFromNetwork()
            async let players = fetchPlayerCards()
            async let insider = fetchInsiderSet()

            playerCards = await players
            insiderSet = await insider

            if let fresh = await freshContent {
                content = fresh
                TeamPageCache.save(content: fresh, teamId: teamId)
            }
            return
        }

        // No cache — fetch from network
        do {
            let fetched = try await APIClient.shared.fetchTeamPage(teamId: teamId)
            if let fetched {
                content = fetched
                TeamPageCache.save(content: fetched, teamId: teamId)
                async let players = fetchPlayerCards()
                async let insider = fetchInsiderSet()
                playerCards = await players
                insiderSet = await insider
            } else {
                #if DEBUG
                if let mock = MockData.teamPage(for: teamId) {
                    content = mock
                } else {
                    content = nil
                }
                #endif
            }
        } catch {
            #if DEBUG
            if let mock = MockData.teamPage(for: teamId) {
                content = mock
            } else {
                hasError = true
            }
            #else
            hasError = true
            #endif
        }
        isLoading = false
    }

    private func fetchFromNetwork() async -> TeamPageContent? {
        try? await APIClient.shared.fetchTeamPage(teamId: teamId)
    }

    private func fetchPlayerCards() async -> [PlayerCard] {
        (try? await APIClient.shared.fetchPlayerCards(teamId: teamId)) ?? []
    }

    /// Fetches up to 4 insider items, one of each type (stat, history,
    /// oddity, anecdote — in that order). Returns an empty array on error
    /// or when the team has no items yet — caller treats both identically
    /// (the section just hides).
    private func fetchInsiderSet() async -> [InsiderItem] {
        (try? await APIClient.shared.fetchInsiderSet(teamId: teamId)) ?? []
    }
}
