# His Club packs: Manchester United, Newcastle United, Nottingham Forest, Tottenham Hotspur, Sunderland.

MAN_UTD = [
    (1, "What is Manchester United's home ground called?", ["Old Trafford", "Maine Road", "The Etihad", "Anfield"], 0, "Old Trafford, since 1910. Bobby Charlton called it the Theatre of Dreams."),
    (1, "What is Manchester United's nickname?", ["The Red Devils", "The Reds", "The Busby Boys", "The Citizens"], 0, "The Red Devils, adopted in the 1960s by Matt Busby, who borrowed it from the Salford rugby team."),
    (2, "Manchester United were founded in 1878 under what name?", ["Newton Heath", "Manchester Rangers", "Salford United", "Trafford Athletic"], 0, "Newton Heath LYR, a railway workers' team. They became Manchester United in 1902 when they nearly went bust."),
    (1, "Who managed Manchester United from 1986 to 2013?", ["Sir Alex Ferguson", "Sir Matt Busby", "José Mourinho", "Ron Atkinson"], 0, "Sir Alex Ferguson. Thirteen league titles, two Champions Leagues, and a stand named after him."),
    (1, "In which year did Manchester United win the treble of league, FA Cup and Champions League?", ["1994", "1999", "2003", "2008"], 1, "1999, sealed with two goals in the last three minutes of the Champions League final in Barcelona."),
    (2, "Which two substitutes scored the late goals in the 1999 Champions League final?", ["Sheringham and Solskjær", "Cole and Yorke", "Giggs and Scholes", "Beckham and Butt"], 0, "Teddy Sheringham and Ole Gunnar Solskjær, both off the bench, against Bayern Munich. Football, bloody hell."),
    (2, "In which year did the Munich air disaster claim the lives of eight Manchester United players?", ["1948", "1958", "1968", "1978"], 1, "1958, on the way home from a European Cup game. Matt Busby survived and rebuilt the team."),
    (2, "Manchester United became the first English club to win the European Cup in which year?", ["1958", "1963", "1968", "1977"], 2, "1968, beating Benfica 4-1 at Wembley, ten years after Munich. Bobby Charlton scored twice."),
    (2, "Which group of United academy players from the early 1990s is known as the Class of '92?", ["Beckham, Scholes, Giggs and the Nevilles", "Rooney, Ronaldo and Nani", "Best, Law and Charlton", "Keane, Ince and Cantona"], 0, "David Beckham, Paul Scholes, Ryan Giggs, Nicky Butt, Gary and Phil Neville. They won the 1992 FA Youth Cup together."),
    (2, "Who is Manchester United's all-time record goalscorer?", ["Wayne Rooney", "Bobby Charlton", "Denis Law", "Cristiano Ronaldo"], 0, "Wayne Rooney, 253 goals, passing Bobby Charlton's record in 2017."),
    (1, "Who are Manchester United's fiercest rivals?", ["Liverpool", "Leeds United", "Manchester City", "Arsenal"], 0, "Liverpool. Two cities thirty miles apart that have won more than everybody else."),
    (2, "Cristiano Ronaldo first joined Manchester United in 2003 from which club?", ["Sporting Lisbon", "Benfica", "Porto", "Real Madrid"], 0, "Sporting Lisbon, aged eighteen, after tormenting United's players in a friendly. He was given the number seven shirt."),
    (2, "How many Premier League titles has Manchester United won?", ["Eleven", "Thirteen", "Fifteen", "Twenty"], 1, "Thirteen, all under Ferguson, from 1993 to 2013. Nobody else is close."),
    (3, "What was Ole Gunnar Solskjær's nickname as a player?", ["The baby-faced assassin", "The Norwegian nightmare", "Super sub", "The quiet man"], 0, "The baby-faced assassin, for the innocent looks and the ruthless finishing, often off the bench."),
    (2, "Which manager rebuilt United after the war and after Munich, and has a statue at Old Trafford?", ["Sir Matt Busby", "Sir Alex Ferguson", "Tommy Docherty", "Ron Atkinson"], 0, "Sir Matt Busby, manager from 1945 to 1969. The road outside the ground is named after him."),
    (2, "In which year did Manchester United last win the Premier League?", ["2009", "2011", "2013", "2017"], 2, "2013, Ferguson's final season. He retired as champion and the club has not won it since."),
    (2, "What is the name of the stand behind the goal where Manchester United's loudest fans sit?", ["The Stretford End", "The Kop", "The Holte End", "The Shed"], 0, "The Stretford End, at the west end of Old Trafford."),
    (2, "Which American family bought Manchester United in 2005?", ["The Glazers", "The Krafts", "The Kroenkes", "The Henrys"], 0, "The Glazer family, who own the Tampa Bay Buccaneers. Fans have protested against them ever since."),
    (3, "Which British billionaire bought a stake in United in 2024 and took over the football side?", ["Sir Jim Ratcliffe", "Sir Richard Branson", "Mike Ashley", "Sir Philip Green"], 0, "Sir Jim Ratcliffe of INEOS, a boyhood United fan from Failsworth."),
    (2, "Manchester United won the 2024 FA Cup by beating which club?", ["Manchester City", "Liverpool", "Chelsea", "Coventry City"], 0, "Manchester City, 2-1 at Wembley, denying City a second double in a row. Erik ten Hag was still sacked months later."),
]

NEWCASTLE = [
    (1, "What is Newcastle United's home ground called?", ["St James' Park", "Roker Park", "Stadium of Light", "Gallowgate Park"], 0, "St James' Park, right in the middle of the city, since 1892."),
    (1, "What colours are Newcastle's home shirts?", ["Black and white stripes", "Red and white stripes", "All black", "Blue and white"], 0, "Black and white stripes, hence the Magpies. Since 1894."),
    (1, "What is Newcastle United's nickname?", ["The Magpies", "The Geordies", "The Mackems", "The Blaydon Racers"], 0, "The Magpies, for the stripes. The fans are the Toon Army."),
    (2, "Who are Newcastle's fiercest rivals?", ["Sunderland", "Middlesbrough", "Leeds United", "Carlisle"], 0, "Sunderland, in the Tyne-Wear derby. Twelve miles apart and very little love."),
    (2, "Who is Newcastle United's all-time record goalscorer?", ["Alan Shearer", "Jackie Milburn", "Malcolm Macdonald", "Les Ferdinand"], 0, "Alan Shearer, 206 goals, a Geordie who turned down Manchester United to come home. He has a statue outside the ground."),
    (3, "Newcastle paid a world-record fee for Alan Shearer in 1996. How much?", ["£8 million", "£15 million", "£22 million", "£30 million"], 1, "£15 million, from Blackburn Rovers. The most anyone had ever paid for a footballer."),
    (2, "Where did Kevin Keegan's Entertainers finish in 1996 after leading the league by twelve points?", ["First", "Second", "Third", "Fourth"], 1, "Second, behind Manchester United. Newcastle fans still talk about it, usually not happily."),
    (2, "In which year was Newcastle United bought by a Saudi-led consortium?", ["2017", "2019", "2021", "2023"], 2, "2021, ending Mike Ashley's fourteen years as owner. Fans celebrated outside the ground in Saudi dress."),
    (3, "Before 2025, in which year had Newcastle last won a domestic trophy?", ["1927", "1955", "1969", "1976"], 1, "1955, the FA Cup, their third in five years. Seventy years without one followed."),
    (2, "Newcastle won the League Cup in 2025 by beating which club?", ["Liverpool", "Arsenal", "Manchester City", "Chelsea"], 0, "Liverpool, 2-1 at Wembley. Dan Burn, a Geordie, scored the first. Grown men wept."),
    (2, "In which year did Newcastle last win the league title?", ["1905", "1927", "1955", "1996"], 1, "1927, their fourth. They have had four seconds since, and no firsts."),
    (3, "What is the name of the stand at the south end of St James' Park, where the loudest fans gather?", ["The Gallowgate End", "The Leazes End", "The Milburn Stand", "The Toon End"], 0, "The Gallowgate End, named after the road to the old town gallows."),
    (2, "Which manager, later knighted, managed Newcastle from 1999 to 2004 and was a Geordie himself?", ["Sir Bobby Robson", "Sir Alf Ramsey", "Kevin Keegan", "Sir Bobby Charlton"], 0, "Sir Bobby Robson, who took them to the Champions League in his late sixties. His statue stands outside the ground."),
    (2, "Which manager took Newcastle back into the Champions League in 2023?", ["Eddie Howe", "Rafael Benítez", "Steve Bruce", "Alan Pardew"], 0, "Eddie Howe, appointed in 2021 with the club in the relegation zone. Fourth place eighteen months later."),
    (3, "Kevin Keegan's 1996 TV rant, 'I would love it if we beat them', was aimed at which manager?", ["Alex Ferguson", "Arsène Wenger", "Kenny Dalglish", "George Graham"], 0, "Alex Ferguson, who had suggested other teams tried harder against United. Newcastle lost the title anyway."),
    (3, "Which retail billionaire owned Newcastle from 2007 to 2021?", ["Mike Ashley", "Philip Green", "Jim Ratcliffe", "Peter Jones"], 0, "Mike Ashley of Sports Direct. He renamed the stadium after his shop for a while. It did not go down well."),
    (3, "Newcastle United were formed in 1892 by the merger of which two clubs?", ["Newcastle East End and West End", "Newcastle Rangers and Tyne", "Gateshead and Byker", "Jesmond and Heaton"], 0, "Newcastle East End and Newcastle West End. East End moved into West End's ground, St James' Park."),
    (1, "Newcastle sits on which river?", ["The Tyne", "The Wear", "The Tees", "The Humber"], 0, "The Tyne. Hence the Tyne-Wear derby with Sunderland, which sits on the Wear."),
    (3, "Which European trophy did Newcastle win in 1969?", ["The Fairs Cup", "The Cup Winners' Cup", "The European Cup", "The UEFA Cup"], 0, "The Inter-Cities Fairs Cup, the forerunner of the UEFA Cup, beating Újpest of Hungary in the final."),
    (2, "Alexander Isak joined Newcastle in 2022 from which club?", ["Real Sociedad", "Borussia Dortmund", "AIK", "Willem II"], 0, "Real Sociedad, for a club-record fee at the time. Sweden's most expensive footballer."),
]

NOTTM_FOREST = [
    (1, "What is Nottingham Forest's home ground called?", ["The City Ground", "Meadow Lane", "Pride Park", "Trent Bridge"], 0, "The City Ground, on the south bank of the River Trent. Notts County's ground is 300 yards away across the river."),
    (1, "What colour are Nottingham Forest's home shirts?", ["Red", "Green", "Black and white", "Yellow"], 0, "Red, known as Garibaldi red after the Italian revolutionary. Forest chose it in 1865."),
    (2, "How many times have Nottingham Forest won the European Cup?", ["Once", "Twice", "Three times", "Never"], 1, "Twice, in 1979 and 1980, back to back, having only been promoted in 1977. Nobody has matched that."),
    (1, "Which manager led Nottingham Forest to their European Cups?", ["Brian Clough", "Bill Shankly", "Bob Paisley", "Don Revie"], 0, "Brian Clough, the most quotable manager in English football. There is a statue of him in the city centre."),
    (2, "Between which years did Brian Clough manage Nottingham Forest?", ["1965-1978", "1975-1993", "1980-1995", "1970-1985"], 1, "1975 to 1993, eighteen years. He retired after relegation in his final season."),
    (3, "Who did Forest beat in the 1979 European Cup final?", ["Malmö", "Hamburg", "Real Madrid", "Ajax"], 0, "Malmö of Sweden, 1-0 in Munich. Trevor Francis scored with a header."),
    (3, "Trevor Francis, the 1979 European Cup final scorer, was the first British player to cost how much?", ["£500,000", "£1 million", "£2 million", "£5 million"], 1, "One million pounds, from Birmingham City. Clough claimed the fee was £999,999 so it would not go to his head."),
    (3, "Who did Forest beat in the 1980 European Cup final?", ["Hamburg", "Malmö", "Bayern Munich", "Liverpool"], 0, "Hamburg, 1-0 in Madrid, with Kevin Keegan in the German side. John Robertson scored."),
    (2, "Who are Nottingham Forest's fiercest rivals?", ["Derby County", "Leicester City", "Notts County", "Sheffield United"], 0, "Derby County, fifteen miles away. Clough managed both, which only made it worse."),
    (2, "When Forest returned to the Premier League in 2022, how many years had they been away?", ["13", "18", "23", "28"], 2, "Twenty-three years, since relegation in 1999. They had spent three of them in the third tier."),
    (2, "Which Welsh manager took Nottingham Forest back to the Premier League in 2022?", ["Steve Cooper", "Chris Coleman", "Ryan Giggs", "Rob Page"], 0, "Steve Cooper, who took over with the club bottom of the Championship and won the play-off final at Wembley."),
    (2, "In which year was Nottingham Forest founded, making them one of the world's oldest clubs?", ["1857", "1865", "1878", "1892"], 1, "1865, by a group of shinty players. Only a handful of clubs anywhere are older."),
    (2, "In which year did Nottingham Forest win the league title?", ["1959", "1978", "1980", "1990"], 1, "1978, the season after promotion, and a year before the first European Cup. Their only title."),
    (3, "Which Forest goalkeeper of the European Cup years became England's most-capped player?", ["Peter Shilton", "Ray Clemence", "Gordon Banks", "David Seaman"], 0, "Peter Shilton, 125 England caps. He played until he was 47."),
    (2, "Which England defender, nicknamed Psycho, captained Forest for over a decade?", ["Stuart Pearce", "Des Walker", "Steve Chettle", "Viv Anderson"], 0, "Stuart Pearce, a former electrician who kept his trade in the programme in case anyone needed a job doing."),
    (3, "Which Greek shipping magnate has owned Nottingham Forest since 2017?", ["Evangelos Marinakis", "Aristotle Onassis", "Dimitris Melissanidis", "Ivan Savvidis"], 0, "Evangelos Marinakis, who also owns Olympiacos in Greece."),
    (3, "What is Nottingham Forest's mascot called?", ["Sherwood the Bear", "Robin", "Forest Fred", "Trenty"], 0, "Sherwood the Bear. Robin Hood's forest, a bear. It is not explained further."),
    (3, "What is the name of the stand behind the goal at the City Ground where the home fans gather?", ["The Trent End", "The Bridgford End", "The Brian Clough Stand", "The Main Stand"], 0, "The Trent End, backing onto the river. Clough said the fans there were the twelfth man."),
    (3, "The trophy contested between Forest and Derby County is named after whom?", ["Brian Clough", "Peter Taylor", "Roy McFarland", "Robin Hood"], 0, "Brian Clough, who won the league with both clubs. The Brian Clough Trophy was first played for in 2007."),
    (1, "Nottingham Forest are from which county?", ["Nottinghamshire", "Derbyshire", "Leicestershire", "Lincolnshire"], 0, "Nottinghamshire, in the East Midlands."),
]

SPURS = [
    (1, "What is Tottenham Hotspur's home ground called?", ["Tottenham Hotspur Stadium", "White Hart Lane", "Wembley", "The Lane"], 0, "The Tottenham Hotspur Stadium, opened in 2019 on the site of the old White Hart Lane."),
    (2, "What was the name of Spurs' old ground, demolished in 2017?", ["White Hart Lane", "Highbury", "Plough Lane", "The Boleyn Ground"], 0, "White Hart Lane, their home from 1899. The new stadium was built around and over it."),
    (1, "What colours are Spurs' home kit?", ["White shirts and navy shorts", "Navy shirts and white shorts", "All white", "Red and white"], 0, "White shirts, navy shorts. The Lilywhites."),
    (1, "Who are Tottenham's fiercest rivals?", ["Arsenal", "Chelsea", "West Ham", "Watford"], 0, "Arsenal, since Arsenal moved to north London in 1913, uninvited, four miles from White Hart Lane."),
    (2, "Spurs won the Europa League in 2025 by beating which club in the final?", ["Manchester United", "Athletic Bilbao", "Bodø/Glimt", "Lazio"], 0, "Manchester United, 1-0 in Bilbao. Their first trophy in seventeen years, and a Champions League place."),
    (2, "Which Australian manager led Spurs to the 2025 Europa League?", ["Ange Postecoglou", "Harry Kewell", "Graham Arnold", "Tony Popovic"], 0, "Ange Postecoglou, who had said he always wins something in his second season. He was sacked sixteen days later."),
    (2, "Before 2025, in which year had Spurs last won a trophy?", ["1999", "2008", "2011", "2019"], 1, "2008, the League Cup, beating Chelsea 2-1 at Wembley. Seventeen years of jokes followed."),
    (2, "Who is Tottenham's all-time record goalscorer?", ["Harry Kane", "Jimmy Greaves", "Bobby Smith", "Gareth Bale"], 0, "Harry Kane, 280 goals, passing Jimmy Greaves in 2023."),
    (2, "Harry Kane left Spurs in 2023 to join which club?", ["Bayern Munich", "Manchester City", "Real Madrid", "Manchester United"], 0, "Bayern Munich, for around £100 million, still without a trophy. He won the Bundesliga with them in 2025."),
    (3, "Which manager led Spurs to the league and cup double in 1961, the first of the twentieth century?", ["Bill Nicholson", "Keith Burkinshaw", "Terry Venables", "Arthur Rowe"], 0, "Bill Nicholson, Spurs' greatest manager. The road outside the stadium is named after him."),
    (3, "Spurs became the first British club to win a European trophy in 1963. Which?", ["The Cup Winners' Cup", "The European Cup", "The Fairs Cup", "The Super Cup"], 0, "The Cup Winners' Cup, beating Atlético Madrid 5-1 in Rotterdam. Jimmy Greaves scored twice."),
    (2, "Whose club goalscoring record did Harry Kane break in 2023?", ["Jimmy Greaves", "Gary Lineker", "Teddy Sheringham", "Martin Chivers"], 0, "Jimmy Greaves, whose 266 goals had stood since 1970."),
    (2, "Gareth Bale left Spurs in 2013 for a then world-record fee to join which club?", ["Real Madrid", "Barcelona", "Manchester United", "Bayern Munich"], 0, "Real Madrid, for about £85 million. He won five Champions Leagues there."),
    (2, "Spurs reached the Champions League final in 2019 and lost to which club?", ["Liverpool", "Manchester City", "Ajax", "Barcelona"], 0, "Liverpool, 2-0 in Madrid, after a semi-final comeback against Ajax that nobody who saw it has forgotten."),
    (2, "Which Argentine managed Spurs from 2014 to 2019 and took them to that Champions League final?", ["Mauricio Pochettino", "Diego Simeone", "Marcelo Bielsa", "Mauricio Pellegrino"], 0, "Mauricio Pochettino, adored by the fans, sacked five months after the final."),
    (1, "The cockerel on the Spurs badge stands on what?", ["A football", "A crown", "A shield", "A cannon"], 0, "A football. There has been a cockerel on the badge since 1909, with spurs on its legs."),
    (3, "What is Tottenham Hotspur's Latin motto, and what does it mean?", ["Audere est Facere — To dare is to do", "Nil Satis Nisi Optimum — Only the best", "Superbia in Proelio — Pride in battle", "Arte et Labore — By skill and hard work"], 0, "Audere est Facere, to dare is to do. The others belong to Everton, Manchester City and Blackburn."),
    (2, "Tottenham Hotspur are named after which historical figure?", ["Harry Hotspur", "Henry Tottenham", "Lord Hotspur of Tottenham", "Sir Harry Spurs"], 0, "Harry Hotspur, a medieval knight whose family owned land in the area. He is a character in Shakespeare's Henry IV."),
    (1, "Spurs are from which part of London?", ["North", "East", "South", "West"], 0, "North London, in Tottenham, a few miles up the road from Arsenal."),
    (2, "Besides football, which American sport is played every year at the Tottenham Hotspur Stadium?", ["NFL American football", "Baseball", "Basketball", "Ice hockey"], 0, "The NFL. The stadium has a second pitch underneath the grass one, and the grass slides away for the games."),
]

SUNDERLAND = [
    (1, "What is Sunderland's home ground called?", ["Stadium of Light", "Roker Park", "St James' Park", "Wearside Park"], 0, "The Stadium of Light, since 1997. Benfica's ground in Lisbon has the same name."),
    (1, "What is Sunderland's nickname?", ["The Black Cats", "The Mackems", "The Rokerites", "The Wearsiders"], 0, "The Black Cats, chosen by fans in a vote in 2000. A black cat was the club's lucky mascot at a 1937 cup final."),
    (1, "What colours are Sunderland's home shirts?", ["Red and white stripes", "Black and white stripes", "All red", "Blue and white"], 0, "Red and white stripes, with black shorts."),
    (2, "Who are Sunderland's fiercest rivals?", ["Newcastle United", "Middlesbrough", "Hartlepool", "Leeds United"], 0, "Newcastle United. The Tyne-Wear derby: two rivers, twelve miles, and total mutual dislike."),
    (2, "What was Sunderland's home ground before 1997?", ["Roker Park", "Ayresome Park", "Boothferry Park", "Newcastle Road"], 0, "Roker Park, their home from 1898. The Roker Roar was one of football's famous noises."),
    (2, "In which year was Sunderland founded?", ["1879", "1889", "1899", "1909"], 0, "1879, by a schoolteacher, as Sunderland and District Teachers' AFC. The teachers part was dropped within a year."),
    (3, "How many league titles have Sunderland won?", ["Two", "Four", "Six", "Eight"], 2, "Six, the last in 1936. Only a few clubs have more, and most of them are the ones you would expect."),
    (2, "Sunderland, then in the second division, won the 1973 FA Cup by beating which club?", ["Leeds United", "Arsenal", "Liverpool", "Manchester United"], 0, "Leeds United, the best team in the country, 1-0 at Wembley. One of the great cup shocks."),
    (3, "Who scored the winning goal in the 1973 FA Cup final?", ["Ian Porterfield", "Bobby Kerr", "Dennis Tueart", "Billy Hughes"], 0, "Ian Porterfield, in the first half. Goalkeeper Jim Montgomery then made a double save people still talk about."),
    (3, "Which Sunderland manager ran across Wembley in a raincoat and trilby to hug his goalkeeper in 1973?", ["Bob Stokoe", "Alan Brown", "Brian Clough", "Lawrie McMenemy"], 0, "Bob Stokoe. There is a statue of the run outside the Stadium of Light."),
    (2, "Sunderland dropped to League One in 2018. In which year did they return to the Championship?", ["2019", "2020", "2021", "2022"], 3, "2022, after four seasons in the third tier, via the play-off final against Wycombe."),
    (2, "What was the name of the Netflix documentary series about Sunderland's decline?", ["Sunderland 'Til I Die", "Haway the Lads", "The Black Cats", "Wearside Blues"], 0, "Sunderland 'Til I Die, three series of things going wrong, watched all over the world. Fans did not enjoy the fame."),
    (2, "Sunderland were promoted to the Premier League in 2025 by beating which club in the play-off final?", ["Sheffield United", "Bristol City", "Coventry City", "Leeds United"], 0, "Sheffield United, 2-1 at Wembley, with a winner in the 95th minute from Tom Watson."),
    (2, "Which French manager led Sunderland to promotion in 2025?", ["Régis Le Bris", "Patrick Vieira", "Michael Beale", "Tony Mowbray"], 0, "Régis Le Bris, in his first season, aged 49, and barely known in England when he arrived."),
    (3, "Which former Sunderland striker, from Ireland, later became the club's chairman?", ["Niall Quinn", "Kevin Phillips", "Roy Keane", "Don Goodman"], 0, "Niall Quinn, who led the Irish takeover in 2006 and then hired Roy Keane as manager."),
    (3, "Which Sunderland striker won the European Golden Shoe in 2000 with 30 Premier League goals?", ["Kevin Phillips", "Niall Quinn", "Darren Bent", "Jermain Defoe"], 0, "Kevin Phillips, the only Englishman ever to win it. He had been playing non-league football six years earlier."),
    (1, "Sunderland sits on which river?", ["The Wear", "The Tyne", "The Tees", "The Humber"], 0, "The Wear. The Stadium of Light sits on its north bank."),
    (3, "What are Sunderland's two black cat mascots called?", ["Samson and Delilah", "Tom and Jerry", "Roker and Wear", "Salt and Pepper"], 0, "Samson and Delilah. Samson has been at the club since 2000."),
    (2, "Which England goalkeeper came through Sunderland's academy before joining Everton in 2017?", ["Jordan Pickford", "Nick Pope", "Aaron Ramsdale", "Dean Henderson"], 0, "Jordan Pickford, born in Washington, Tyne and Wear. Sunderland got £25 million for him."),
    (3, "The Stadium of Light was built on the site of what?", ["A coal mine", "A shipyard", "A brewery", "A racecourse"], 0, "Monkwearmouth Colliery, one of the last pits in the area. The name honours miners' lamps; a Davy lamp stands outside."),
]

PACKS = [
    ("club-man-utd", "Manchester United", MAN_UTD),
    ("club-newcastle", "Newcastle United", NEWCASTLE),
    ("club-nottm-forest", "Nottingham Forest", NOTTM_FOREST),
    ("club-spurs", "Tottenham Hotspur", SPURS),
    ("club-sunderland", "Sunderland", SUNDERLAND),
]
