# His Club packs: Manchester United, Newcastle United, Nottingham Forest, Tottenham Hotspur, Sunderland. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)

MAN_UTD = [
    (1, "What is Manchester United's home ground called?", ["Old Trafford", "Maine Road", "Anfield"], 0,
     "Old Trafford, since 1910. Bobby Charlton called it the Theatre of Dreams and the name stuck. It holds around 74,000.",
     "The Theatre of Dreams is a phrase he uses. Knowing who coined it is the extra step.",
     "say", "\"Theatre of Dreams. That was Bobby Charlton's line.\""),
    (1, "What is Manchester United's nickname?", ["The Red Devils", "The Red Lions", "The Citizens"], 0,
     "The Red Devils, borrowed in the 1960s from Salford's rugby league team, who were called les Diables Rouges on a tour of France. It sounded fiercer than the old nickname.",
     "The devil came from rugby. Even United fans often don't know.",
     "impress", "\"The Red Devils name was nicked from a Salford rugby team. The club thought it sounded scarier.\""),
    (2, "Manchester United were founded in 1878 under what name?", ["Newton Heath", "Salford United", "Trafford Athletic"], 0,
     "Newton Heath LYR, a railway workers' team in green and gold. They nearly went bust in 1902 and were rescued by a brewer, who renamed them Manchester United.",
     "A railway team saved by a brewer: the origin story is better than the badge suggests.",
     "impress", "\"United started as a railway workers' team called Newton Heath. Played in green and gold.\""),
    (2, "What was Sir Alex Ferguson's famous treatment for a player who had let him down?", ["The hairdryer", "The cold shoulder", "The naughty step"], 0,
     "The hairdryer: Ferguson, United manager from 1986 to 2013, inches from a player's face, shouting hard enough to blow his hair back. It turns up in every autobiography.",
     "'The hairdryer' is a phrase he'll use about any furious manager. Now you know whose it was.",
     "say", "\"He'd have got the hairdryer for that.\" (After any howler.)"),
    (1, "In which year did Manchester United win the treble of league, FA Cup and Champions League?", ["1994", "1999", "2008"], 1,
     "1999, sealed with two goals in the final three minutes of the Champions League final against Bayern Munich in Barcelona. The first English club to do the treble.",
     "'99 is the year United fans return to. It is the peak of everything.",
     "ask", "Ask him: \"Where were you for the final three minutes of the 1999 final?\""),
    (2, "Which two subs scored United's stoppage-time goals against Bayern in the treble-winning final?", ["Sheringham and Solskjær", "Cole and Yorke", "Giggs and Scholes"], 0,
     "Teddy Sheringham and Ole Gunnar Solskjær, both off the bench, in the 91st and 93rd minutes. Ferguson said afterwards: 'Football, bloody hell.'",
     "'Football, bloody hell' is a quote he will know. This is where it comes from.",
     "impress", "\"Two subs scored in stoppage time to win the treble. 'Football, bloody hell,' Ferguson said.\""),
    (2, 'In which year did the Munich air disaster claim the lives of eight Manchester United players?', ['1949', '1958', '1966'], 1,
     '1958, flying home from a European Cup game, when the plane crashed on take-off in snow. The manager survived and rebuilt. A clock at the ground carries the date.',
     'Munich is sacred to United. Knowing it, quietly, matters more than any trophy fact.',
     'say', '"There\'s a clock on the corner of the ground with the date of the Munich crash on it. 1958."'),
    (2, "Manchester United became the first English club to win the European Cup in which year?", ["1963", "1968", "1977"], 1,
     "1968, beating Benfica 4-1 at Wembley after extra time. Bobby Charlton, who had survived the Munich crash, scored twice.",
     "A European Cup won with a crash survivor scoring is the story that makes grown men cry.",
     "impress", "\"They won the European Cup in 1968, and a survivor of the Munich crash scored twice in the final.\""),
    (2, "Which group of United academy players from the early 1990s is known as the Class of '92?", ["Beckham, Scholes, Giggs and the Nevilles", "Rooney, Ronaldo and Nani", "Bruce, Keane, Ince, Cantona and Hughes"], 0,
     "Beckham, Scholes, Giggs, Butt and the Neville brothers, who won the 1992 FA Youth Cup together and then the treble. A pundit said you win nothing with kids.",
     "'You'll win nothing with kids' is the quote he will produce. Now you know the punchline.",
     "say", "\"'You'll win nothing with kids.' Alan Hansen said that about the Class of '92. Then they won everything.\""),
    (2, "Which striker passed Bobby Charlton's United goals tally in 2017?", ["Wayne Rooney", "Ruud van Nistelrooy", "Cristiano Ronaldo"], 0,
     "Wayne Rooney, who passed Charlton's 249 in January 2017 and finished on 253. He had arrived from Everton as an eighteen-year-old in 2004.",
     "Rooney overtaking Charlton is the modern-versus-legend debate in one fact.",
     "ask", "Ask him: \"Rooney or Charlton, who was the better United player?\""),
    (2, "What is a Manchester United v Liverpool match called?", ["The North West derby", "The Manchester derby", "The Merseyside derby"], 0,
     "The North West derby, between two cities thirty miles apart that by 2025 had twenty league titles each. City is the local derby; Liverpool is the grudge.",
     "United fans rank their hatreds. Liverpool comes first, and it is not close.",
     "say", "\"City's the neighbours. Liverpool's the enemy. Different things.\""),
    (2, "Cristiano Ronaldo first joined Manchester United in 2003 from which club?", ["Sporting Lisbon", "Benfica", "Vitória Guimarães"], 0,
     "Sporting Lisbon, aged eighteen, after tormenting United's defenders in a friendly. The players asked Ferguson to sign him on the plane home. He got the number seven.",
     "Ronaldo's arrival is a story United fans tell like a legend. It also explains the number seven.",
     "impress", "\"United's players asked Ferguson to sign Ronaldo on the flight home after he ran rings round them in a friendly.\""),
    (2, 'By 2013, how many Premier League titles had Manchester United won?', ['Eleven', 'Thirteen', 'Fifteen'], 1,
     'Thirteen, all under Ferguson, between 1993 and 2013. That made twenty league titles in all, counting the ones before the Premier League began.',
     'Thirteen and twenty are the two numbers he will quote. Know which is which.',
     'say', '"Thirteen Premier Leagues, all under Ferguson. Twenty titles in all by the time he left."'),
    (3, "What was Ole Gunnar Solskjær's nickname as a player?", ["The baby-faced assassin", "The Norwegian nightmare", "The Oslo Rocket"], 0,
     "The baby-faced assassin: innocent looks, ruthless finishing, often off the bench. He once scored four in twelve minutes as a sub. Later, less happily, the manager.",
     "A sub who comes on and scores late gets compared to him. The nickname is the older fans' shorthand.",
     "say", "\"He's a Solskjær. Comes off the bench and scores.\" (About any good substitute.)"),
    (2, "Which manager rebuilt United after the war and after Munich, and has a statue outside the ground?", ["Sir Matt Busby", "Sir Alex Ferguson", "Tommy Docherty"], 0,
     "Sir Matt Busby, manager 1945 to 1969: built the Busby Babes, lost them at Munich, built again and won the European Cup. The road outside is Sir Matt Busby Way.",
     "Busby is the father of the club. Ferguson is the son. Both have statues.",
     "say", "\"Busby built the club twice. Before Munich and after it.\""),
    (2, "Which Scot left Everton in 2013 to become Manchester United manager?", ["David Moyes", "Kenny Dalglish", "Alex McLeish"], 0,
     "David Moyes, hand-picked by the man he replaced and sacked before his first season was out. The years after were a long argument about whose fault it was.",
     "The post-Ferguson years are the sore subject. Knowing where they start helps you tread carefully.",
     "ask", "Ask him: \"Did Moyes ever get a fair chance at United?\""),
    (2, "What is the name of the stand at United's ground where the loudest fans gather?", ["The Stretford End", "The Kop", "The Holte End"], 0,
     "The Stretford End, at the west end of the ground, named after the district behind it. Where the songs start.",
     "Stands with names are stands with reputations. This is United's.",
     "say", "\"The Stretford End. That's where the noise comes from.\""),
    (2, "Which American family bought Manchester United in 2005?", ["The Glazers", "The Kroenkes", "The Henrys"], 0,
     "The Glazer family, owners of an American football team, who bought the club with borrowed money and loaded the debt onto it. Fans were marching against them in 2025.",
     "Ask any United fan about the Glazers and stand back. It is the one thing they all agree on.",
     "ask", "Ask him: \"Are the Glazers as bad as everyone says, or is that just an excuse?\""),
    (3, "Which British billionaire bought a stake in United in 2024 and took over the football side?", ["Sir Jim Ratcliffe", "Sir Richard Branson", "Sir Philip Green"], 0,
     "Sir Jim Ratcliffe of the chemicals firm INEOS, a boyhood United fan. In 2024-25 he cut costs, staff and the free staff lunches, and the team finished 15th.",
     "Ratcliffe is the 2024 chapter in the who's-to-blame saga. Fans have strong views.",
     "ask", "Ask him: \"Has Ratcliffe made anything better, honestly?\""),
    (2, "Manchester United won the 2024 FA Cup by beating which club?", ["Manchester City", "Liverpool", "Newcastle United"], 0,
     "Manchester City, 2-1 at Wembley, as heavy underdogs, denying City a second double in a row. The manager was sacked months later anyway.",
     "Beating City in a final is the happiest recent United memory. Bring it up on a bad day.",
     "say", "\"They beat City in the 2024 cup final and sacked the manager anyway. Classic United.\""),
]

NEWCASTLE = [
    (1, "What is Newcastle United's home ground called?", ["St James' Park", "Stadium of Light", "Ewood Park"], 0,
     "St James' Park, right in the middle of the city since 1892. You can see the stands from the shopping streets.",
     "A stadium in the city centre is part of why Newcastle feels like a football city.",
     "say", "\"St James' is right in the middle of town. Walk from the shops to the match.\""),
    (1, "What colours are Newcastle's home shirts?", ["Black and white stripes", "Red and white stripes", "Blue and white"], 0,
     "Black and white stripes since 1894, worn with black shorts. Spot the stripes in a crowd and you have found the Newcastle end.",
     "Two striped teams in the North East. Getting the colours right is the minimum.",
     "say", "\"Black and white stripes. You can spot a Newcastle fan from a mile off.\""),
    (1, "What is Newcastle United's nickname?", ["The Magpies", "The Canaries", "The Mackems"], 0,
     "The Magpies, for the stripes. The fans are the Toon Army; Toon is how Geordies say town.",
     "'The Toon' is how he refers to Newcastle. It means town in the local accent.",
     "say", "\"Howay the Toon. It just means 'come on Newcastle'.\""),
    (2, "Who are Newcastle's fiercest rivals?", ["Sunderland", "Middlesbrough", "Leeds United"], 0,
     "Sunderland, twelve miles down the road, in the Tyne-Wear derby. Two rivers, two cities, over a century of not getting on. Newcastle fans call Sunderland fans Mackems.",
     "The North East derby is as fierce as any in England. Know the names both sides use.",
     "say", "\"Tyne-Wear derby. Geordies against Mackems. Properly nasty.\""),
    (2, "Which Newcastle striker passed Jackie Milburn's club goals tally in 2006?", ["Alan Shearer", "Andy Cole", "Les Ferdinand"], 0,
     "Alan Shearer, who finished on 206, a Geordie who turned down Manchester United in 1996 to come home. His statue stands outside the ground, arm raised in celebration.",
     "Shearer is Newcastle. If you know one player, know him.",
     "say", "\"Shearer turned down United to come home. That's why they worship him.\""),
    (3, "In 1996 Newcastle paid Blackburn a world-record fee for a Geordie striker. How much?", ["£8 million", "£15 million", "£22 million"], 1,
     "£15 million, a world record at the time, for a local boy coming home. Fifteen thousand fans turned up just to watch him hold up a shirt.",
     "A world record for a local boy coming home is a story the whole city shares.",
     "impress", "\"Newcastle paid fifteen million for a local lad in 1996, a world record. Fifteen thousand came to watch him hold up a shirt.\""),
    (2, "Where did Kevin Keegan's Entertainers finish in 1996 after leading the league by twelve points?", ["First", "Second", "Third"], 1,
     "Second, behind Manchester United, having been twelve points clear in January. The best-loved team to win nothing, and fans have not fully recovered.",
     "'The Entertainers' is the phrase for that team. The collapse is the club's great what-if.",
     "ask", "Ask him: \"Do Newcastle fans forgive Keegan for 1996, or do they love him anyway?\""),
    (2, "In which year was Newcastle United bought by a Saudi-led consortium?", ["2017", "2019", "2021"], 2,
     "2021, ending fourteen unloved years under the previous owner. Fans celebrated outside the ground, some in Saudi dress, which caused a row of its own.",
     "The takeover is the dividing line in modern Newcastle. Before and after.",
     "ask", "Ask him: \"Do you feel OK about where the money comes from, or do you not think about it?\""),
    (3, "Newcastle's 2025 League Cup ended a wait for a major domestic trophy that began in which year?", ['1955', '1969', '1976'], 0,
     "1955, the FA Cup, their third in five years. Then seventy years without a major domestic trophy, which became the club's identity.",
     'Seventy years without a trophy is the number that explains the tears in 2025.',
     'impress', '"Seventy years between major domestic trophies. 1955 to 2025. That\'s why grown men cried at Wembley."'),
    (2, "Newcastle won the League Cup in 2025 by beating which club?", ["Liverpool", "Arsenal", "Manchester City"], 0,
     "Liverpool, 2-1 at Wembley. Dan Burn, a six-foot-seven Geordie who had grown up a fan, scored the first goal. The city did not sleep.",
     "The 2025 cup is the day every Newcastle fan will tell you about. Ask about it.",
     "ask", "Ask him: \"Where were you when Newcastle won the cup? Did you cry? Be honest.\""),
    (2, "In which year did Newcastle win the fourth of their league titles?", ["1936", "1927", "1948"], 1,
     "1927. Four titles, all before the Second World War, and none in the ninety-nine years to 2026.",
     "The fourth title being before the war explains the yearning.",
     "say", "\"Four titles, and the fourth was 1927. Nearly a hundred years ago.\""),
    (3, "What is the name of the stand at the south end of Newcastle's ground where the loudest fans gather?", ["The Gallowgate End", "The Leazes End", "The Milburn Stand"], 0,
     "The Gallowgate End, named after the road that led to the old town gallows. Where the songs start.",
     "A stand named after a road to the gallows is a fact with atmosphere.",
     "impress", "\"The Gallowgate End is named after the road to the old gallows. Cheerful.\""),
    (2, "Which manager, later knighted, managed Newcastle from 1999 to 2004, his boyhood club?", ["Sir Bobby Robson", "Sir Alf Ramsey", "Sir Bobby Charlton"], 0,
     "Sir Bobby Robson, born in County Durham, who took Newcastle into the Champions League in his late sixties. Sacked at 71, adored forever. His statue is outside the ground.",
     "Robson is the grandfather figure of the club. Speaking of him warmly is always right.",
     "say", "\"Bobby Robson got them into the Champions League at nearly seventy. And they sacked him.\""),
    (2, "Which manager took Newcastle back into the Champions League in 2023?", ["Eddie Howe", "Rafael Benítez", "Alan Pardew"], 0,
     "Eddie Howe, appointed with the club in the relegation zone. Fourth place eighteen months later, and the 2025 League Cup after that.",
     "Howe is the man who turned the money into football. Fans said his name with relief.",
     "say", "\"Howe took them from the relegation zone to the Champions League in eighteen months.\""),
    (3, "Kevin Keegan's 1996 TV rant, 'I would love it if we beat them', was aimed at which manager?", ["Alex Ferguson", "Arsène Wenger", "Kenny Dalglish"], 0,
     "Alex Ferguson, who had suggested teams tried harder against United than Newcastle. Keegan, in headphones, lost it live on television. Newcastle lost the title anyway.",
     "'I would love it' is one of football's best-known clips. Know the story behind it.",
     "impress", "\"'I would love it if we beat them. Love it.' Keegan, 1996, live on Sky, in headphones. They didn't.\""),
    (3, "Which retail billionaire owned Newcastle for the fourteen years before the Saudi takeover?", ["Mike Ashley", "Philip Green", "Jim Ratcliffe"], 0,
     "Mike Ashley of Sports Direct, who renamed the stadium after his shop, sold the best players and was protested against for fourteen years.",
     "The Ashley years are the misery the takeover ended. He is the villain of every fan's story.",
     "ask", "Ask him: \"How bad were the Ashley years, honestly?\""),
    (3, "Newcastle United were formed in 1892 by the merger of which two clubs?", ["Newcastle East End and West End", "Newcastle Rangers and Tyne", "Jesmond and Heaton"], 0,
     "Newcastle East End and Newcastle West End. East End moved into West End's ground in 1892, and the merged club took a new name.",
     "Two clubs became one on the same pitch they play on today. Neat.",
     "impress", "\"Newcastle are two clubs merged, East End and West End. Same ground since 1892.\""),
    (2, "Which old Geordie folk song do Newcastle fans sing at home games?", ["Blaydon Races", "Delilah", "Keep Right On"], 0,
     "Blaydon Races, a music-hall song from 1862 about a rowdy trip to the races just outside the city. Its chorus rolls round the ground on big days.",
     "It's the song he'll sing without thinking. Knowing the name is a start.",
     "ask", "Ask him: \"Can you sing me the Blaydon Races? Just the chorus.\""),
    (3, "Which European trophy did Newcastle win in 1969?", ["The Fairs Cup", "The European Cup", "The UEFA Cup"], 0,
     "The Inter-Cities Fairs Cup, forerunner of the UEFA Cup, beating Újpest of Hungary over two legs. The club's first European trophy.",
     "A European trophy few people remember is the perfect impress fact.",
     "impress", "\"Newcastle won a European trophy in 1969. The Fairs Cup. Nobody outside Newcastle remembers.\""),
    (2, "Alexander Isak joined Newcastle in 2022 from which club?", ["Real Sociedad", "Borussia Dortmund", "Willem II"], 0,
     "Real Sociedad, for around £60 million, a club record at the time. The Swede's goals took them into Europe, then he left for Liverpool in 2025 after a bitter stand-off.",
     "Isak's 2025 exit is a sore subject. Approach with care.",
     "ask", "Ask him: \"Isak to Liverpool. Betrayal, or just business?\""),
]

NOTTM_FOREST = [
    (1, "What is Nottingham Forest's home ground called?", ["City Ground", "Meadow Lane", "Pride Park"], 0,
     "The City Ground, on the riverbank since 1898. Notts County's ground is about 300 yards away on the other side of the water, which visitors refuse to believe.",
     "Two grounds you can see from each other is a fact people refuse to believe.",
     "impress", "\"Forest and Notts County's grounds are three hundred yards apart. Either side of the river.\""),
    (1, "What colour are Nottingham Forest's home shirts?", ["Red", "Green", "Yellow"], 0,
     "Red, known as Garibaldi red after the Italian revolutionary whose followers wore it. The founders picked it, and Forest later gave a set of shirts to the new Arsenal.",
     "Arsenal wear red because Forest sent them shirts. A genuinely good fact.",
     "impress", "\"Arsenal play in red because Forest gave them their first kit in 1886.\""),
    (3, "Brian Clough's Forest once went how many league games in a row without losing?", ["22", "32", "42"], 2,
     "Forty-two, a whole season's worth, before Liverpool ended the run. Arsenal's Invincibles passed it in 2004, on their way to 49.",
     "Arsenal fans think the unbeaten run is their story. Forest had the one they had to beat.",
     "impress", "\"Forest went forty-two league games unbeaten under Clough. Arsenal didn't pass it until 2004.\""),
    (2, "What was Brian Clough's nickname?", ["Old Big 'Ead", "The Special One", "The Professor"], 0,
     "Old Big 'Ead, a name he wore happily: 'I wouldn't say I was the best manager in the business, but I was in the top one.' His statue is in the city centre.",
     "Clough quotes are a genre. Knowing the man behind them is the point.",
     "ask", "Ask him: \"What's your favourite Clough quote?\" He has one."),
    (2, "Between which years did Brian Clough manage Nottingham Forest?", ["1975-1993", "1980-1995", "1970-1985"], 0,
     "1975 to 1993, eighteen years. He took them from the second division to European champions in four seasons, and retired after relegation in his final year.",
     "The Clough years are the club's whole identity. Dates help you place the stories.",
     "say", "\"Clough was there eighteen years. Second division to European champions in four.\""),
    (3, "Who did Forest beat in the 1979 European Cup final?", ["Malmö", "Bayern Munich", "Ajax"], 0,
     "Malmö of Sweden, 1-0 in Munich, with a diving header from Trevor Francis in his first European game for Forest. He had not been eligible in the earlier rounds.",
     "A winner on his European debut is the tidy detail.",
     "impress", "\"Trevor Francis scored the winner in the 1979 final. It was his first European game for Forest.\""),
    (3, "Trevor Francis, the 1979 European Cup final scorer, was the first British player to cost how much?", ["£1 million", "£2 million", "£5 million"], 0,
     "One million pounds, from Birmingham City in 1979. Clough claimed the fee was £999,999 so it would not go to the player's head, then made him make the tea.",
     "Clough making a million-pound signing make tea is the Clough story to tell.",
     "impress", "\"Clough paid a million for Trevor Francis, then made him make the tea for the other players.\""),
    (3, "Who did Forest beat in the 1980 European Cup final?", ["Hamburg", "Real Madrid", "Liverpool"], 0,
     "Hamburg, 1-0 in Madrid, with Kevin Keegan in the German side. John Robertson, a chain-smoking Scottish winger, scored the goal.",
     "Two finals, two 1-0 wins. Forest fans know both scorers by heart.",
     "say", "\"John Robertson scored in 1980. Clough called him the Picasso of our game.\""),
    (2, "Who are Nottingham Forest's fiercest rivals?", ["Derby County", "Leicester City", "Notts County"], 0,
     "Derby County, fifteen miles away. Clough managed both clubs and won the league with both, which made the rivalry worse. Their matches are for the Brian Clough Trophy.",
     "A rivalry where both sides claim the same hero is unusual. This is it.",
     "impress", "\"Forest and Derby both claim Clough. He won the league with both. They play for a trophy named after him.\""),
    (2, "When Forest returned to the Premier League in 2022, how many years had they been away?", ["13", "18", "23"], 2,
     "Twenty-three years, since relegation in 1999, including three seasons in the third tier. Fans of a European champion, watching League One.",
     "Twenty-three years away is the context for how emotional the return was.",
     "ask", "Ask him: \"Twenty-three years out of the Premier League. Did you keep going through the third division?\""),
    (2, "Which Welsh manager took Nottingham Forest back to the Premier League in 2022?", ["Steve Cooper", "Chris Coleman", "Ryan Giggs"], 0,
     "Steve Cooper, who took over with Forest bottom of the Championship in September and won the play-off final at Wembley in May. Fans put his face on flags.",
     "Bottom in September to promoted in May is the turnaround fans measure others against.",
     "impress", "\"Cooper took Forest from bottom of the Championship to promoted in one season.\""),
    (2, "In which year was Nottingham Forest founded?", ["1857", "1865", "1878"], 1,
     "1865, by a group of shinty players, at a meeting in a pub. Among the oldest clubs in the world, and the first to use shin pads.",
     "Forest invented shin pads. A fact that works on anyone who has ever played.",
     "impress", "\"Forest invented shin pads. 1874. A player cut down his cricket pads.\""),
    (2, 'In which year were Nottingham Forest crowned league champions?', ['1978', '1980', '1990'], 0,
     '1978, the season after promotion, and a year before the first European Cup. A newly promoted side winning the league stunned everyone.',
     'Winning the league the year after promotion is the beginning of the Forest legend.',
     'say', '"They won the league the season after coming up. Then two European Cups. In three years."'),
    (3, "Which Forest goalkeeper of the European Cup years went on to 125 England caps?", ["Peter Shilton", "Ray Clemence", "David Seaman"], 0,
     "Peter Shilton, 125 caps, a figure no outfield player had reached by 2024. He played professionally until he was 47.",
     "The keeper who played until 47 is a fact for anyone who feels old.",
     "impress", "\"Forest's keeper Peter Shilton played until he was 47. Forty-seven.\""),
    (2, "Which England left-back, nicknamed Psycho, spent twelve years at Forest?", ["Stuart Pearce", "Des Walker", "Viv Anderson"], 0,
     "Stuart Pearce, a former electrician who kept advertising his trade in the match programme in case anyone needed a job doing. Famous for his 1996 penalty roar for England.",
     "Pearce is the hard man fans of every club respect. The electrician detail seals it.",
     "impress", "\"Pearce kept advertising as an electrician in the programme while captaining Forest and England.\""),
    (3, "Which Greek shipping magnate bought Nottingham Forest in 2017?", ["Evangelos Marinakis", "Aristotle Onassis", "Dimitris Melissanidis"], 0,
     "Evangelos Marinakis, who had bought Olympiacos in Greece in 2010. Generous with money, short on patience: in 2025 he confronted his own manager on the pitch after a game.",
     "Owners are a topic at every club now. Forest's is one of the more colourful.",
     "ask", "Ask him: \"Is Marinakis good for Forest, or one bad month from chaos?\""),
    (3, "What is Nottingham Forest's mascot called?", ["Sherwood the Bear", "Robin the Redbreast", "Forest Fred"], 0,
     "Sherwood the Bear. Robin Hood's forest, a bear. The logic is not explained further.",
     "Mascot names are the safest small talk in football.",
     "say", "\"Sherwood the Bear. There are no bears in Sherwood Forest, but fine.\""),
    (3, "What is the name of the stand behind the goal at Forest's ground where the home fans gather?", ["The Trent End", "The Sherwood End", "The Main Stand"], 0,
     "The Trent End, backing onto the river. Clough called the fans there the twelfth man.",
     "Stands with names are stands with reputations. The Trent End is Forest's.",
     "say", "\"The Trent End. Right on the river.\""),
    (3, "Who was Brian Clough's assistant manager for Forest's European Cup wins?", ["Peter Taylor", "Don Revie", "Ron Atkinson"], 0,
     "Peter Taylor, Clough's partner at club after club: Taylor judged the players, Clough did the talking. 'I'm the shop window, he's the goods in the back,' Clough said.",
     "Clough without Taylor is half the story. Older fans will tell you so.",
     "impress", "\"Clough said he was the shop window and Peter Taylor was the goods in the back.\""),
    (2, "Which pop song did Forest fans turn into their slow, arms-up anthem?", ["Mull of Kintyre", "Delilah", "You'll Never Walk Alone"], 0,
     "Mull of Kintyre, the Wings hit of 1977, rewritten by fans about following Forest round the grounds of England. Sung slowly, which surprises visitors.",
     "When the whole ground sways and sings a Wings song, now you know why.",
     "ask", "Ask him: \"Why do Forest fans sing a Paul McCartney song about Scotland?\""),
]

SPURS = [
    (2, "In which year did Spurs open their new stadium?", ["2018", "2019", "2021"], 1,
     "2019, months later than planned, after nearly two seasons playing at Wembley. It came with a cheese room and its own brewery.",
     "The new stadium is the club's proudest possession. Praise it and he glows.",
     "say", "\"The new stadium's ridiculous. There's a cheese room. And a brewery.\""),
    (2, "What was the name of Spurs' old ground, demolished in 2017?", ["White Hart Lane", "Highbury", "Plough Lane"], 0,
     "White Hart Lane, their home from 1899. The new stadium went up on the same site, so the club barely moved an inch.",
     "White Hart Lane is the name in every old story he tells.",
     "say", "\"White Hart Lane. The new ground's built right where it stood.\""),
    (1, "What colours are Spurs' home kit?", ["White shirts and navy shorts", "Navy shirts and white shorts", "Red and white"], 0,
     "White shirts, navy shorts. The Lilywhites, an old nickname nobody under sixty uses.",
     "Kit recognition is how you follow a match without commentary.",
     "say", "\"White shirts, navy shorts. Spurs.\""),
    (1, "Who are Tottenham's fiercest rivals?", ["Arsenal", "Chelsea", "West Ham"], 0,
     "Arsenal, since 1913, when Arsenal moved across London to settle four miles from Spurs, uninvited. Spurs fans resent that, and the 1919 vote that lifted Arsenal over them.",
     "The Arsenal grievance has two parts, and the 1919 one is the bit few people know.",
     "impress", "\"Spurs hate Arsenal partly for moving in next door in 1913 and partly for a dodgy vote in 1919 that put Arsenal up instead of them.\""),
    (2, "Spurs won the Europa League in 2025 by beating which club in the final?", ["Manchester United", "Athletic Bilbao", "Bodø/Glimt"], 0,
     "Manchester United, 1-0 in Bilbao, in a season where Spurs finished 17th in the league. A trophy at last, and a Champions League place with it.",
     "The 2025 trophy ended years of jokes. He will want to relive it.",
     "ask", "Ask him: \"Bilbao 2025. Where were you when the whistle went?\""),
    (2, "Which Australian manager led Spurs to the 2025 Europa League?", ["Ange Postecoglou", "Harry Kewell", "Graham Arnold"], 0,
     "Ange Postecoglou, who had said 'I always win something in my second season' and was mocked for it until he did. He was sacked sixteen days after the final.",
     "Winning a trophy and being sacked a fortnight later is peak Spurs. He will have a view.",
     "ask", "Ask him: \"Sacking Ange two weeks after he won you a trophy. Right call or madness?\""),
    (2, "Spurs' 2025 Europa League ended a wait for a trophy that began in which year?", ["2008", "2011", "2019"], 0,
     "2008, the League Cup, beating Chelsea 2-1 at Wembley. Seventeen years of jokes followed, including a whole genre about Spurs bottling things.",
     "'Spursy' became an adjective in those years. Knowing why is knowing the club's self-image.",
     "say", "\"Seventeen years without a trophy. 'Spursy' became an actual word.\""),
    (2, "Which Tottenham midfielder's tears at the 1990 World Cup made him a national hero?", ["Paul Gascoigne", "Chris Waddle", "Glenn Hoddle"], 0,
     "Paul Gascoigne, Gazza, booked in the semi-final against West Germany, which meant he would miss the final. He cried on the pitch and the country fell for him.",
     "Gazza's tears are the moment English football became loveable again. He'll know the clip.",
     "ask", "Ask him: \"Are you old enough to remember Gazza crying in 1990?\""),
    (2, "Harry Kane left Spurs in 2023 to join which club?", ["Bayern Munich", "Manchester City", "Real Madrid"], 0,
     "Bayern Munich, for around £100 million, chasing a trophy. Bayern then failed to win the league for the first time in eleven years. He got his medal in 2025.",
     "The Kane trophy curse was a running joke across football for two years.",
     "say", "\"Kane went to Bayern for a trophy and they immediately stopped winning. Then he finally got one.\""),
    (3, "Which manager led Spurs to the league and cup double in 1961?", ["Bill Nicholson", "Terry Venables", "Arthur Rowe"], 0,
     "Bill Nicholson, the manager older Spurs fans revere above all, whose team won the first double of the twentieth century. The road outside the stadium is named after him.",
     "The 1961 double is the club's high point. Older fans measure everything against it.",
     "say", "\"1961 double. Bill Nicholson. The road outside the ground is named after him.\""),
    (3, "In 1963 Spurs became the first British club to win a European trophy. Which?", ["The Cup Winners' Cup", "The European Cup", "The Fairs Cup"], 0,
     "The Cup Winners' Cup, beating Atlético Madrid 5-1 in Rotterdam, with two goals from the winger Terry Dyson. A British first.",
     "Being first in Europe is a fact Spurs fans hold onto when the trophy count is mentioned.",
     "impress", "\"Spurs were the first British club to win in Europe. 1963, beat Atlético 5-1.\""),
    (2, "Whose club goalscoring mark did Harry Kane pass in 2023?", ["Jimmy Greaves", "Gary Lineker", "Teddy Sheringham"], 0,
     "Jimmy Greaves, whose 266 goals had stood since 1970. Greaves was the great goalscorer of his era, and later a much-loved TV presenter.",
     "Greaves is the name older fans use to explain what a striker should be.",
     "say", "\"Greaves scored 266 for Spurs and was on telly for years after. Kane finally passed him.\""),
    (2, "Gareth Bale left Spurs in 2013 for a world-record fee to join which club?", ["Real Madrid", "Barcelona", "Bayern Munich"], 0,
     "Real Madrid, for about £85 million. He won five Champions Leagues there, scored in two finals, and came back to Spurs on loan for a farewell.",
     "Bale is the Spurs player who went and won everything elsewhere. It stings and it doesn't.",
     "ask", "Ask him: \"Bale winning five Champions Leagues at Madrid. Proud or gutted?\""),
    (2, "Spurs reached the Champions League final in 2019 and lost to which club?", ["Liverpool", "Ajax", "Barcelona"], 0,
     "Liverpool, 2-0 in Madrid, after a penalty in the second minute. The semi-final comeback against Ajax, three second-half goals away from home, was the night fans remember.",
     "The Ajax semi is the greatest Spurs night of the century. The final is the footnote.",
     "ask", "Ask him: \"The Ajax semi-final. Lucas Moura's third goal. Where were you?\""),
    (2, "Which Argentine managed Spurs from 2014 to 2019 and took them to that Champions League final?", ["Mauricio Pochettino", "Marcelo Bielsa", "Mauricio Pellegrino"], 0,
     "Mauricio Pochettino, adored by the fans, who built the best Spurs team in decades on a small budget and was sacked five months after the final.",
     "Pochettino is the manager Spurs fans pine for. Say his name and watch.",
     "say", "\"Poch. Best they've had in my lifetime, he'll say. Then they sacked him.\""),
    (1, "The cockerel on the Spurs badge stands on what?", ["A football", "A crown", "A shield"], 0,
     "A football. The cockerel has been on the badge since 1909 and wears spurs on its legs, which is the pun: Hotspur, spurs.",
     "He has looked at that badge a thousand times and may not have noticed the spurs.",
     "ask", "Ask him: \"Did you know the cockerel on the badge is wearing spurs? That's the joke.\""),
    (3, "What is Tottenham Hotspur's Latin motto?", ["Audere est Facere", "Superbia in Proelio", "Arte et Labore"], 0,
     "Audere est Facere: to dare is to do. It is on the badge and, after the 2025 final, on a lot of tattoos.",
     "'To dare is to do' is the phrase Spurs fans quote in hope and in irony.",
     "say", "\"To dare is to do. That's the motto. They dared a lot and did very little for years.\""),
    (2, "Tottenham Hotspur are named after which historical figure?", ["Harry Hotspur", "Henry Tottenham", "Sir Harry Spurs"], 0,
     "Harry Hotspur, a medieval knight whose family owned land in the area, and a character in Shakespeare's Henry IV. Schoolboys chose the name in 1882.",
     "A club named after a Shakespeare character is a good fact for a non-football crowd too.",
     "impress", "\"Spurs are named after a Shakespeare character. Harry Hotspur, from Henry IV.\""),
    (1, "Spurs are from which part of London?", ["North", "South", "West"], 0,
     "North London, on Tottenham High Road in the borough of Haringey, a few miles north of the centre.",
     "'North London' comes up in every Spurs argument. It is their whole turf.",
     "say", "\"Spurs are north London. Say south and watch his face.\""),
    (2, "Spurs' stadium has a second, artificial pitch under the grass. Which league is it for?", ['NFL', 'MLB', 'NBA'], 0,
     'The NFL, which has staged regular-season games there since 2019. The grass pitch slides out in three sections to uncover theirs.',
     "The sliding pitch is the fact that impresses people who don't care about football at all.",
     'impress', '"The Spurs pitch slides out in three pieces so the NFL can play on the one underneath."'),
]

SUNDERLAND = [
    (1, "What is Sunderland's home ground called?", ["Stadium of Light", "St James' Park", "Riverside Stadium"], 0,
     "The Stadium of Light, since 1997, built on the site of a coal mine. The name honours the miners' lamps, and a Davy lamp stands outside.",
     "The coal mine is the story. Benfica's stadium has the same name, which confuses people.",
     "impress", "\"It's built on an old pit. The Stadium of Light is for the miners' lamps.\""),
    (1, "What is Sunderland's nickname?", ["The Black Cats", "The Magpies", "The Mariners"], 0,
     "The Black Cats, chosen by fans in a vote in 2000. A black cat was the lucky mascot at the 1937 cup final. Rival fans call them Mackems, and not kindly.",
     "Two names: the one they chose and the one their rivals use.",
     "say", "\"Black Cats officially. Mackems if you're from up the road and being rude.\""),
    (1, "What colours are Sunderland's home shirts?", ["Red and white stripes", "Black and white stripes", "Blue and white"], 0,
     "Red and white stripes with black shorts. They started out in blue and switched to red and white in the 1880s.",
     "In the North East, stripe colour is identity.",
     "say", "\"Red and white stripes. Get the colour wrong up there at your peril.\""),
    (2, "Who are Sunderland's fiercest rivals?", ["Newcastle United", "Middlesbrough", "Leeds United"], 0,
     "Newcastle United, twelve miles north. Two cities, over a century of total mutual dislike. Newcastle fans are Geordies; Sunderland fans are Mackems.",
     "The derby is the fixture that decides his year. Know the date.",
     "ask", "Ask him: \"When's the derby? Are we hiding the sharp objects?\""),
    (2, "Where did Sunderland play from 1898 until 1997?", ["Roker Park", "Ayresome Park", "Burnden Park"], 0,
     "Roker Park, famous for the Roker Roar, a noise visiting teams dreaded. Fans kept the phrase for the club's atmosphere after the move.",
     "'The Roker Roar' is a phrase he may use. It survived the ground.",
     "say", "\"The Roker Roar. The old ground's gone but they kept the name for the noise.\""),
    (2, "In which year was Sunderland founded?", ["1879", "1889", "1899"], 0,
     "1879, by a schoolteacher, as Sunderland and District Teachers' Association Football Club. The teachers part went within a year.",
     "A club founded by teachers is a gentle origin story for a fierce fanbase.",
     "impress", "\"Sunderland were founded by schoolteachers. It was a teachers' association club for a year.\""),
    (3, 'How many league titles did Sunderland win between 1892 and 1936?', ['Two', 'Four', 'Six'], 2,
     'Six, the first in 1892 and the sixth in 1936. In the 1890s they were called the Team of All Talents, the best side in England.',
     'Six titles puts Sunderland among the big historic clubs, which surprises people who only know recent years.',
     'impress', '"Six league titles by 1936. More than Chelsea had until 2017. All before the war, mind."'),
    (2, "Sunderland, then in the second division, won the 1973 FA Cup by beating which club?", ["Leeds United", "Liverpool", "Manchester United"], 0,
     "Leeds United, the best team in England at the time, 1-0 at Wembley. One of the great cup shocks, and the club's defining moment.",
     "1973 is the story every Sunderland fan's parents told them. It is the founding myth.",
     "ask", "Ask him: \"Was anyone in your family at Wembley in 1973?\""),
    (3, "Which Sunderland goalkeeper made the famous double save in the 1973 FA Cup final?", ["Jim Montgomery", "Gordon Banks", "Pat Jennings"], 0,
     "Jim Montgomery, a Sunderland lad who played over 600 games for the club. A header, then a point-blank shot, both kept out in the second half to protect a 1-0 lead.",
     "The Montgomery save is the moment fans replay in their heads. Name it and he'll finish the story.",
     "say", "\"The Montgomery double save. 1973. He'll tell you it's the best there's been.\""),
    (3, "Which Sunderland manager ran across Wembley in a raincoat and trilby to hug his goalkeeper in 1973?", ["Bob Stokoe", "Alan Brown", "Brian Clough"], 0,
     "Bob Stokoe. The run is a statue outside the ground, arms out, hat on. Fans meet there before games.",
     "The statue is a landmark. Knowing what it shows makes you part of the story.",
     "impress", "\"The statue outside the ground is the manager running to hug his keeper after the 1973 final. Raincoat and all.\""),
    (2, "Sunderland dropped to League One in 2018. In which year did they return to the Championship?", ["2020", "2021", "2022"], 2,
     "2022, after four seasons in the third tier, via the play-off final against Wycombe. Two of those seasons produced a Netflix series.",
     "The League One years are the trauma. Knowing how long they lasted shows you understand.",
     "ask", "Ask him: \"Four years in League One. Did you keep your season ticket?\""),
    (2, "What was the name of the Netflix documentary series about Sunderland's decline?", ["Sunderland 'Til I Die", "Haway the Lads", "Red and White Til The End"], 0,
     "Sunderland 'Til I Die, three series of things going wrong, watched all over the world. Fans did not enjoy being famous for misery.",
     "It is the one Sunderland reference non-fans know. Use it carefully.",
     "ask", "Ask him: \"Did you watch the Netflix series, or was it too painful?\""),
    (2, "Sunderland were promoted to the Premier League in 2025 by beating which club in the play-off final?", ["Sheffield United", "Bristol City", "Coventry City"], 0,
     "Sheffield United, 2-1 at Wembley, with a winner in the 95th minute from Tom Watson, a teenager who had already agreed to join Brighton.",
     "A 95th-minute winner from a kid on his way out is the kind of ending fans cannot believe happened to them.",
     "impress", "\"Sunderland went up with a 95th-minute winner from a teenager who'd already signed for Brighton.\""),
    (2, "Which French manager led Sunderland to promotion in 2025?", ["Régis Le Bris", "Patrick Vieira", "Tony Mowbray"], 0,
     "Régis Le Bris, in his first season, barely known in England when he arrived. Quiet, and the fans took to him from the start.",
     "Le Bris is the name on the promotion. Fans took to him fast.",
     "say", "\"Le Bris. Nobody had heard of him. Took them up in his first season.\""),
    (3, "Which former Sunderland striker, from Ireland, later became the club's chairman?", ["Niall Quinn", "Kevin Phillips", "Roy Keane"], 0,
     "Niall Quinn, who led an Irish takeover in 2006 and hired Roy Keane as manager. He also gave his testimonial money to charity and once paid for stranded fans' taxis home.",
     "The player who paid for fans' taxis is why Quinn is loved in Sunderland.",
     "impress", "\"Niall Quinn once paid for taxis for a hundred stranded Sunderland fans. Then became chairman.\""),
    (3, "Which Sunderland striker won the European Golden Shoe in 2000 with 30 Premier League goals?", ["Kevin Phillips", "Niall Quinn", "Jermain Defoe"], 0,
     "Kevin Phillips, the first Englishman to win Europe's top-scorer award. He had been playing non-league football six years earlier.",
     "An Englishman winning the Golden Shoe is rare. Sunderland fans know who it was.",
     "impress", "\"Kevin Phillips out-scored everyone in Europe in 2000. From non-league to Golden Shoe in six years.\""),
    (1, 'Which Elvis song do Sunderland fans sing before kick-off at home?', ['Suspicious Minds', "Can't Help Falling in Love", 'Love Me Tender'], 1,
     "Can't Help Falling in Love, which fans call Wise Men Say. It took hold in the Roker Park days and the whole ground sings it before kick-off.",
     "If he starts singing 'wise men say' at a match, it isn't a wedding.",
     'ask', 'Ask him: "Why do Sunderland fans sing an Elvis love song before kick-off?"'),
    (3, "What are Sunderland's two black cat mascots called?", ['Samson and Delilah', 'Roker and Wear', 'Salt and Pepper'], 0,
     'Samson and Delilah, a pair of black cats named after the Old Testament couple. Samson came first, and Delilah was brought in as his partner.',
     'Biblical mascots are a fact that raises a smile in a quiet moment.',
     'say', '"Samson and Delilah. The mascots. Very Old Testament."'),
    (2, "Which England goalkeeper came through Sunderland's academy before joining Everton in 2017?", ['Jordan Pickford', 'Aaron Ramsdale', 'Dean Henderson'], 0,
     'Jordan Pickford, born in Washington, near Sunderland. Sunderland got £25 million for him, a world record for a British goalkeeper at the time.',
     "Pickford's a Sunderland lad. Handy to know whenever England are on.",
     'say', '"Pickford\'s a Sunderland boy. Came through their academy."'),
    (2, "Which England midfielder and Liverpool captain also came through Sunderland's academy?", ["Jordan Henderson", "Steven Gerrard", "James Milner"], 0,
     "Jordan Henderson, born in Sunderland, who left for Liverpool in 2011 and lifted the Champions League and the league as captain.",
     "A Liverpool captain who grew up a Sunderland boy is a point of local pride.",
     "impress", "\"Jordan Henderson came through Sunderland's academy before he captained Liverpool.\""),
]

PACKS = [
    ("club-man-utd", "Manchester United", MAN_UTD),
    ("club-newcastle", "Newcastle United", NEWCASTLE),
    ("club-nottm-forest", "Nottingham Forest", NOTTM_FOREST),
    ("club-spurs", "Tottenham Hotspur", SPURS),
    ("club-sunderland", "Sunderland", SUNDERLAND),
]
