# His Club packs: Chelsea, Coventry City, Crystal Palace, Everton, Fulham. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)

CHELSEA = [
    (1, "What is Chelsea's home ground called?", ["Stamford Bridge", "Craven Cottage", "Loftus Road"], 0,
     "Stamford Bridge. The ground opened in 1877 for athletics, and the football club came decades later, set up to fill it.",
     "A club invented to fill an empty stadium is the best Chelsea fact there is.",
     "impress", "\"Stamford Bridge existed before Chelsea did. They started the club to fill it.\""),
    (1, "In which year was Chelsea founded?", ["1899", "1905", "1919"], 1,
     "1905, in the Rising Sun pub opposite the ground, later renamed the Butcher's Hook. You can drink where the club was born.",
     "A club founded in a pub you can visit is a date-night fact.",
     "say", "\"Chelsea were founded in that pub opposite the ground. We should go for a drink there.\""),
    (1, "What colour are Chelsea's home shirts?", ["Royal blue", "Sky blue", "White"], 0,
     "Royal blue, since around 1912. They began in a paler Eton blue, and until 1952 the team were nicknamed the Pensioners, after the old soldiers nearby.",
     "Knowing the team were once the Pensioners is the extra he won't expect.",
     "impress", "\"Chelsea were nicknamed the Pensioners until the fifties. After the old soldiers down the road.\""),
    (2, "Which Russian billionaire owned Chelsea from 2003 to 2022?", ["Roman Abramovich", "Alisher Usmanov", "Dmitry Rybolovlev"], 0,
     "Roman Abramovich, whose money turned a good club into a trophy machine: nineteen major trophies in nineteen years, and a lot of sacked managers. Forced to sell in 2022.",
     "Every Chelsea conversation splits into before and after Abramovich.",
     "ask", "Ask him: \"Would Chelsea have won anything without Abramovich's money?\""),
    (2, "In which year did Chelsea first win the Champions League?", ["2008", "2012", "2021"], 1,
     "2012, in Munich, on penalties against Bayern in Bayern's own stadium, after a late equaliser. They had lost the 2008 final on penalties to United.",
     "Munich 2012 is the night Chelsea fans of a certain age will talk about for the rest of their lives.",
     "ask", "Ask him: \"Munich 2012. Where were you for the penalties?\""),
    (2, "Who did Chelsea beat in the 2021 Champions League final?", ["Manchester City", "Real Madrid", "Bayern Munich"], 0,
     "Manchester City, 1-0 in Porto, with a goal from Kai Havertz, under a manager who had been appointed that January.",
     "An all-English final is a thing fans compare notes on. Chelsea won this one.",
     "say", "\"Chelsea beat City in the 2021 final. Havertz, one-nil.\""),
    (2, "In 2013, who overtook Bobby Tambling as Chelsea's top goalscorer?", ["Didier Drogba", "Frank Lampard", "Jimmy Greaves"], 1,
     "Frank Lampard, a midfielder, who finished on 211 goals before leaving in 2014. Strikers would take that number. He later managed the club, less successfully.",
     "A midfielder out-scoring the strikers is the Chelsea fact he will confirm proudly.",
     "impress", "\"Lampard was a midfielder and scored 211 for Chelsea. Strikers would take that.\""),
    (2, "Which manager won Chelsea back-to-back league titles in 2005 and 2006?", ["Carlo Ancelotti", "José Mourinho", "Claudio Ranieri"], 1,
     "José Mourinho, who arrived from Porto calling himself the Special One. First spell 2004 to 2007, second 2013 to 2015, another title in 2015.",
     "Mourinho is the manager Chelsea fans love and everyone else loves to hate. Know the name, know the era.",
     "ask", "Ask him: \"Was Mourinho's first Chelsea team the best they've ever had?\""),
    (3, "In which year did Chelsea win their first league title?", ["1955", "1970", "2005"], 0,
     "1955, then a fifty-year wait for the second in 2005. Older fans lived through the whole gap.",
     "Fifty years between titles explains why the older fans are a bit giddy.",
     "impress", "\"Chelsea won the league in 1955 and then not again until 2005. Fifty years.\""),
    (2, "Which centre-back captained Chelsea for over a decade and was called Captain, Leader, Legend?", ["John Terry", "Marcel Desailly", "Gary Cahill"], 0,
     "John Terry, captain from 2004 to 2017, five league titles. The banner reads Captain, Leader, Legend. He also once wore a full kit to lift a trophy he hadn't played in.",
     "Terry divides opinion outside Chelsea and unites it inside. Both sides are worth hearing.",
     "ask", "Ask him: \"Terry: greatest Chelsea captain or a bit much?\""),
    (2, "Which Ivorian striker scored in four FA Cup finals for Chelsea?", ["Didier Drogba", "Salomon Kalou", "Nicolas Anelka"], 0,
     "Didier Drogba, who scored in final after final for Chelsea, a Champions League final among them. The definition of a big-game player.",
     "'Big-game player' is a phrase he uses. Drogba is the picture in his head.",
     "say", "\"He's a bit of a Drogba, saves it for the big games.\""),
    (3, "Which end of Chelsea's ground became home to the singing fans in the sixties?", ['The Shed End', 'The Stretford End', 'The Holte End'], 0,
     'The Shed End. The old covered terrace was where the singing started in the sixties, and the name survived the rebuild in the 1990s.',
     "Stands with names are stands with reputations. The Shed is Chelsea's.",
     'say', '"The Shed End. That\'s where the singing comes from."'),
    (2, "Which Italian manager won the league and cup double with Chelsea in 2010, scoring 103 league goals?", ["Carlo Ancelotti", "Roberto Di Matteo", "Gianluca Vialli"], 0,
     "Carlo Ancelotti, the calm one with the eyebrow. 103 goals was a Premier League season record at the time. Sacked the following year, in a corridor.",
     "Chelsea sacking title-winning managers is a running joke. Ancelotti is exhibit A.",
     "impress", "\"Ancelotti won the double and got sacked a year later. In a corridor.\""),
    (3, "Antonio Conte's title-winning Chelsea side of 2017 was famous for switching to which formation?", ["3-4-3", "4-4-2", "5-3-2"], 0,
     "3-4-3, after a bad start. Three centre-backs, wing-backs flying forward. They won thirteen league games in a row and half the league copied it.",
     "If he says 'back three', this is where the modern fashion for it came from.",
     "impress", "\"Conte's 3-4-3 in 2017 started the whole back-three fashion. Everyone copied it.\""),
    (3, "Which manager led Chelsea Women to seven league titles before leaving in 2024?", ["Emma Hayes", "Sarina Wiegman", "Casey Stoney"], 0,
     "Emma Hayes, twelve years at the club, then off to coach the United States women's team, who won Olympic gold within months.",
     "Chelsea Women dominated for a decade. Knowing the manager's name is knowing the story.",
     "say", "\"Emma Hayes built Chelsea Women. Seven titles, then straight to Olympic gold with the USA.\""),
    (1, "What is Chelsea's nickname?", ["The Blues", "The Royals", "The Lions"], 0,
     "The Blues. The lion on the badge comes from the coat of arms of Earl Cadogan, the local landowner who was club president.",
     "Nickname and badge in one answer.",
     "say", "\"Come on you Blues.\" (The Chelsea version. Everton say the same, awkwardly.)"),
    (3, 'Which Chelsea goalkeeper played on for years in a protective headguard after fracturing his skull?', ['Petr Čech', 'Thibaut Courtois', 'Carlo Cudicini'], 0,
     'Petr Čech, injured in 2006, who kept playing for a decade in it. In the Munich final he saved a penalty in extra time and another in the shootout.',
     'The keeper in the helmet is a visual he will remember instantly.',
     'say', '"Čech, the one with the headguard. Saved penalty after penalty in that Munich final."'),
    (2, "Which club's ground sits about two miles from Chelsea's?", ["Fulham", "Brentford", "Watford"], 0,
     "Fulham, a short trip along the river. Chelsea's own ground is actually in the borough of Fulham, which Fulham fans enjoy pointing out.",
     "West London derbies are gentle affairs, which he will deny.",
     "say", "\"The ground's technically in Fulham, not Chelsea. Don't tell him I said that.\""),
    (3, "Which Italian became Chelsea's player-manager in 1998?", ["Gianluca Vialli", "Gianfranco Zola", "Roberto Di Matteo"], 0,
     "Gianluca Vialli, who took over from Ruud Gullit and won two trophies within months while playing too. Chelsea of the late nineties were full of Italians.",
     "The Italian era, before the money, is what older fans mean when they say Chelsea were fun.",
     "ask", "Ask him: \"Were the Zola and Vialli years the fun Chelsea, before the money?\""),
    (2, "Eden Hazard left Chelsea in 2019 to join which club?", ["Real Madrid", "Barcelona", "Juventus"], 0,
     "Real Madrid, after seven seasons and two league titles. He scored twice in his final Chelsea game, the Europa League final, then barely played in Spain.",
     "Hazard is the player Chelsea fans of the 2010s adored above all. His decline in Madrid is a sad coda.",
     "ask", "Ask him: \"Was Hazard the best player you've watched at Chelsea?\""),
]

COVENTRY = [
    (1, "What is Coventry City's nickname?", ['The Robins', 'The Sky Blues', 'The Blues'], 1,
     'The Sky Blues, a name the club took on in the early sixties, replacing the old one, the Bantams, along with new shirts and a song to match.',
     'Nickname, kit and song all trace to one man in the sixties. Handy.',
     'say', '"Sky Blues. The kit, the nickname and the song all arrived together in the sixties."'),
    (2, 'In which year did Coventry City win the FA Cup?', ['1972', '1987', '1993'], 1,
     "1987, won 3-2 after extra time at Wembley. The club's first major trophy, and by 2026 they had not won another. The city celebrated for a week.",
     "1987 is the year every Coventry fan's story comes back to.",
     'ask', 'Ask him: "Was anyone in your family at Wembley in 1987?"'),
    (2, "Who did Coventry beat in their FA Cup final win?", ["Tottenham Hotspur", "Nottingham Forest", "Liverpool"], 0,
     "Tottenham, who had won every FA Cup final they had reached until that day. The winner was a Spurs own goal off Gary Mabbutt's knee in extra time.",
     "The own goal off a knee is the detail fans savour. A Coventry fanzine was named after the knee.",
     "impress", "\"Coventry won the cup with an own goal off a Spurs player's knee. There was a fanzine named after the knee.\""),
    (2, "What colour was Coventry's famous away kit of 1978?", ["Chocolate brown", "Bright tangerine", "Lime green"], 0,
     "Chocolate brown, worn away from home from 1978. It turns up on every bad-kit list going, and fans love it anyway.",
     "The brown kit is a cult object. Retro-shirt fans know it on sight.",
     "ask", "Ask him: \"Would you actually wear the brown Coventry away kit?\""),
    (2, "Coventry City were founded in 1883 under what name?", ["Singers FC", "Rootes Athletic", "Godiva United"], 0,
     "Singers FC, the works team of a bicycle factory. Coventry made bikes, then cars; the club followed the city.",
     "A club that began as a bicycle works team says everything about the city.",
     "impress", "\"Coventry started as a bicycle factory's works team. Singers FC.\""),
    (3, "Which manager and TV presenter changed Coventry's kit to sky blue and wrote the fans' song?", ["Jimmy Hill", "John Sillett", "Bobby Gould"], 0,
     "Jimmy Hill, later the presenter of Match of the Day for decades, with the famous chin. He took Coventry from the third tier to the first in the 1960s.",
     "The man off the telly who built the club. Two facts for one.",
     "ask", "Ask him: \"Did you know Jimmy Hill off Match of the Day basically invented modern Coventry?\""),
    (2, "What was Coventry's home ground from 1899 to 2005?", ["Highfield Road", "Butts Park", "Coundon Road"], 0,
     "Highfield Road, close to the city centre, for 106 years. It is housing now.",
     "Old grounds are where fans keep their childhood. Naming this one earns a story.",
     "ask", "Ask him: \"Did you ever go to Highfield Road?\""),
    (3, "In 1981 Highfield Road became the first English ground to be what?", ["All-seater", "Floodlit", "Artificial turf"], 0,
     "All-seater, at the chairman's insistence. The fans hated sitting down and the terraces came back within a few years.",
     "Being first at something everyone now does, and having it rejected, is a great trivia shape.",
     "impress", "\"Coventry were the first all-seater ground in England, in 1981. Fans hated it so much they put terraces back.\""),
    (2, 'When Coventry went down in 2001, how many consecutive seasons had they spent in the top flight?', ['24', '34', '44'], 1,
     'Thirty-four seasons, from 1967 to 2001, escaping relegation on the final day more than once. Just Arsenal, Everton and Liverpool had a longer unbroken run at the time.',
     "Thirty-four years of survival is the club's proudest habit, and then the fall.",
     'impress', '"Coventry spent thirty-four years in the top flight and kept surviving on the final day. Then they went down and kept going."'),
    (2, "Coventry's stadium opened in 2005 under which sponsor's name?", ["Ricoh", "Jaguar", "Peugeot"], 0,
     "Ricoh, the Japanese office-equipment firm. It became the Coventry Building Society Arena in 2021. The club has twice been locked out of it in rent disputes.",
     "A club locked out of its own stadium twice is a story people struggle to believe.",
     "say", "\"They've been locked out of their own stadium twice. Rent rows.\""),
    (3, "In 2013-14 Coventry played home games in which town because of a rent dispute?", ["Northampton", "Leicester", "Birmingham"], 0,
     "Northampton, 35 miles away. Fans boycotted, crowds fell to two thousand, and people protested outside the empty stadium back home.",
     "The exile years are the wound. Knowing about them is knowing what the club survived.",
     "ask", "Ask him: \"Did you boycott the Northampton games or go anyway?\""),
    (3, "From 2019 to 2021 Coventry shared a ground with which club?", ["Birmingham City", "Aston Villa", "Leicester City"], 0,
     "Birmingham City, at St Andrew's, twenty miles away. They won promotion to the Championship while homeless, and many fans could not get there.",
     "Promotion while exiled is the kind of achievement only the fans who lived it can weigh.",
     "impress", "\"Coventry won promotion while playing home games at Birmingham. Fans couldn't even get in.\""),
    (2, "Which manager took Coventry from League Two to a Championship play-off final?", ["Mark Robins", "Tony Mowbray", "Russell Slade"], 0,
     "Mark Robins, back for a second spell from 2017 to 2024. Two promotions, one of them won in exile, and a Wembley final.",
     "Robins is the name every Coventry fan says with gratitude.",
     "say", "\"Mark Robins took them from the fourth tier to a play-off final. Some of it without a home ground.\""),
    (3, "Coventry lost the 2023 Championship play-off final on penalties to which club?", ["Luton Town", "Sunderland", "Middlesbrough"], 0,
     "Luton Town, after a 1-1 draw at Wembley and a shootout that went to sudden death. One penalty from the Premier League.",
     "The near miss makes the eventual promotion sweeter. He will want to tell you both halves.",
     "ask", "Ask him: \"Was the Luton final the worst day you've had as a fan?\""),
    (2, "In which year were Coventry promoted back to the Premier League as Championship champions?", ["2024", "2025", "2026"], 2,
     "2026, with 95 points, their first top-flight season since 2001. Twenty-five years, a spell in the fourth tier and two exiles in between.",
     "This is the freshest joy in the fanbase. Ask about it and make his day.",
     "ask", "Ask him: \"Where were you when they went up as champions?\""),
    (1, "Coventry is in which region of England?", ["The North East", "The West Midlands", "The South West"], 1,
     "The West Midlands, twenty miles from Birmingham. A car-making city with a cathedral rebuilt after the war.",
     "Map first, football second.",
     "say", "\"Coventry, West Midlands. Twenty minutes from Birmingham.\""),
    (2, "What is Coventry's derby with Leicester City called?", ["The M69 derby", "The M6 derby", "The A45 derby"], 0,
     "The M69 derby, after the motorway linking the two cities, about 25 miles apart. Aston Villa and Birmingham are the other Midlands grudges.",
     "Rivalries named after roads are a very English thing. Knowing this one shows you've done your homework.",
     "ask", "Ask him: \"The M69 derby. Is Leicester the one that really matters, or Villa?\""),
    (3, "Which striker shared the Premier League Golden Boot in 1998 with eighteen goals for Coventry?", ["Dion Dublin", "Robbie Keane", "Peter Ndlovu"], 0,
     "Dion Dublin, level with Michael Owen and Chris Sutton. He later became a TV presenter and invented a percussion instrument called the Dube.",
     "A Golden Boot winner who invented a drum is the fact that wins the table.",
     "impress", "\"Dion Dublin won the Golden Boot at Coventry and then invented a drum. Called the Dube.\""),
    (3, "Which former England midfielder took over as Coventry manager in November 2024?", ["Frank Lampard", "Steven Gerrard", "Scott Parker"], 0,
     "Frank Lampard, whose managing career had stalled at Chelsea and Everton. Coventry were two points above the relegation zone when he arrived.",
     "Lampard at Coventry is a redemption story fans of every club followed.",
     "ask", "Ask him: \"Did Coventry finally prove Lampard can manage?\""),
    (3, "The Sky Blue Song is sung to the tune of what?", ["Eton Boating Song", "Rule Britannia", "Land of Hope and Glory"], 0,
     "The Eton Boating Song, a rowing song from the posh school. The club's manager co-wrote the football words in 1962 and fans have sung it ever since.",
     "Working-class fans singing an Eton rowing song is a lovely contradiction to have in your pocket.",
     "impress", "\"The Coventry song is the Eton Boating Song with new words, from 1962.\""),
]

CRYSTAL_PALACE = [
    (1, "What is Crystal Palace's home ground called?", ["Selhurst Park", "The Valley", "The Den"], 0,
     "Selhurst Park, home since 1924. Old, cramped and loud, with one end full of drums and flags.",
     "Selhurst's atmosphere is the thing rival fans concede. Mention it and he lights up.",
     "say", "\"Selhurst on a night game. Best atmosphere in London, they say.\""),
    (1, "What is Crystal Palace's nickname?", ["The Eagles", "The Seagulls", "The Hawks"], 0,
     "The Eagles, since 1973. Before that they were the Glaziers, after the glass palace the club is named for.",
     "Two nicknames, one club. The old one explains the name.",
     "say", "\"They were the Glaziers before the Eagles. Because of the glass palace.\""),
    (2, "Who are Crystal Palace's arch-rivals?", ["Brentford", "Brighton", "Wimbledon"], 1,
     "Brighton, forty miles down the M23. It began with two managers feuding in the 1970s and the fans took it on. Nobody outside quite understands it.",
     "The rivalry that makes no geographical sense is the one worth knowing about.",
     "ask", "Ask him: \"Why Brighton? They're forty miles away.\""),
    (1, "What colours are Palace's home shirts?", ["Red and blue stripes", "Claret and blue", "Yellow and green"], 0,
     "Red and blue vertical stripes, copied from Barcelona in the 1970s by a manager who admired them.",
     "Barcelona's colours in south London is a fact that surprises people.",
     "impress", "\"Palace's stripes are copied from Barcelona. A manager just liked them in the seventies.\""),
    (2, 'In which year was the professional Crystal Palace club formed?', ['1885', '1905', '1920'], 1,
     '1905, by the company that owned the Crystal Palace. In 2022 the club put 1861 on its badge, after an amateur side of that name, which historians dispute.',
     'The club is named after a building, and the building came first.',
     'say', '"Palace were formed in 1905, but the club counts from 1861. Ask a historian and it gets heated."'),
    (2, 'Which final did the Crystal Palace grounds host every year from 1895 to 1914?', ['The League Cup final', 'The European Cup final', 'The FA Cup final'], 2,
     'The FA Cup final, with some crowds topping 100,000. The glass palace burned down in 1936, but the club kept the name and the building is drawn on the badge.',
     'A club named after a building that no longer exists is a story people enjoy.',
     'impress', '"The FA Cup final used to be played at the Crystal Palace. That\'s where the club came from."'),
    (2, "Which former England manager, a Palace fan as a boy, took charge of the club in 2017?", ["Roy Hodgson", "Glenn Hoddle", "Steve McClaren"], 0,
     "Roy Hodgson, who grew up in Croydon and watched Palace from the terraces. He kept them up four years running and came back for a second spell at 75.",
     "A boyhood fan managing the club at 70 is a warm story fans love telling.",
     "ask", "Ask him: \"Hodgson managing his boyhood club in his seventies, was that lovely or a bit much?\""),
    (2, "Palace lost FA Cup finals in 1990 and 2016 to the same club. Which?", ["Manchester United", "Liverpool", "Tottenham Hotspur"], 0,
     "Manchester United both times: after a replay in 1990, in extra time in 2016. Palace led in both.",
     "Two finals lost to the same club in the same way is the kind of pain that bonds fans.",
     "say", "\"United beat them in two cup finals, 1990 and 2016. Palace led in both.\""),
    (2, 'Palace won the 2025 FA Cup, then UEFA moved them out of the Europa League. Why?', ['Shared ownership with Lyon', 'Unpaid debts to other clubs', 'Crowd trouble at Selhurst'], 0,
     "A co-owner also held a stake in Lyon, who had qualified too, and UEFA's rules bar clubs with shared owners. Palace went down to the Conference League.",
     'Winning your first trophy and then being demoted in Europe over ownership is the sore point.',
     'ask', 'Ask him: "Was the UEFA ownership ruling as unfair as Palace fans say?"'),
    (3, "Who scored the winning goal in the 2025 FA Cup final?", ["Eberechi Eze", "Ismaïla Sarr", "Adam Wharton"], 0,
     "Eberechi Eze, a local boy, in the first half. Goalkeeper Dean Henderson then saved a penalty and should probably have been sent off earlier.",
     "The scorer of the first trophy-winning goal is a name fans will hold onto for life.",
     "say", "\"Eze scored the goal that won Palace their first trophy. Local lad too.\""),
    (3, "Wilfried Zaha, who played over 450 games for Palace, left in 2023 for which club?", ["Galatasaray", "Marseille", "Fenerbahçe"], 0,
     "Galatasaray in Turkey, after two spells and a decade as the club's talisman. An unhappy year at Manchester United sits in between.",
     "Zaha is the modern Palace hero. If he mentions one player from the 2010s, it is him.",
     "ask", "Ask him: \"Was Zaha the best player Palace have ever had?\""),
    (3, "Which striker scored twice off the bench in the 1990 FA Cup final for Palace?", ["Ian Wright", "Mark Bright", "John Salako"], 0,
     "Ian Wright, playing on a leg broken weeks earlier. The final was drawn 3-3 and Palace lost the replay. Wright later became an Arsenal legend and a TV presenter.",
     "Ian Wright off the telly was a Palace hero first. That surprises people.",
     "impress", "\"Ian Wright started at Palace. Scored twice in a cup final on a half-healed broken leg.\""),
    (3, "What was the name of the real eagle that flew around Selhurst Park before matches?", ["Kayla", "Percy", "Storm"], 0,
     "Kayla, an American bald eagle, who did a lap of the ground before kick-off from 2010 until she died in 2020.",
     "A live eagle at a football match is the fact nobody believes until you show them.",
     "impress", "\"Palace had an actual eagle flying round the pitch before games. Called Kayla.\""),
    (1, "Crystal Palace are from which part of London?", ["East", "South", "West"], 1,
     "South London, around Croydon and Selhurst. The other big south London clubs, Millwall and Charlton, are rivals too.",
     "London's football map is confusing. South is Palace territory.",
     "say", "\"Palace are south London. Croydon, basically.\""),
    (3, "Who scored the extra-time winner in Palace's 4-3 FA Cup semi-final against Liverpool in 1990?", ["Alan Pardew", "Mark Bright", "Geoff Thomas"], 0,
     "Alan Pardew, a midfielder who later came back to manage the club and took them to the 2016 final. Liverpool had beaten Palace 9-0 earlier that season.",
     "Beating Liverpool 4-3 months after losing 9-0 to them is a story fans tell in full.",
     "ask", "Ask him: \"Do Palace fans bring up the 4-3 against Liverpool in 1990?\""),
    (3, "Which former Arsenal captain managed Palace from 2021 to 2023?", ["Patrick Vieira", "Thierry Henry", "Cesc Fàbregas"], 0,
     "Patrick Vieira, who made Palace young and stylish for a season, then got sacked after twelve games without a win.",
     "Vieira's Palace was briefly the neutral's favourite. The ending was less romantic.",
     "say", "\"Vieira made Palace watchable for a year. Then twelve games without a win.\""),
    (3, "The fan group behind the drums and flags at Selhurst Park is called what?", ["The Holmesdale Fanatics", "The Eagles Ultras", "The Selhurst Boys"], 0,
     "The Holmesdale Fanatics, named after the stand they fill. They organise the displays, the drums and the songs, European-style.",
     "If he mentions 'the Fanatics', this is who he means.",
     "say", "\"That's the Holmesdale Fanatics with the drums. They run the atmosphere.\""),
    (3, "Palace won promotion to the Premier League in 2004 by beating which club in the play-off final?", ["West Ham", "Sunderland", "Ipswich"], 0,
     "West Ham, 1-0 in Cardiff, with a goal from Neil Shipperley. Palace had been near the bottom of the division at Christmas.",
     "Bottom at Christmas to promoted in May: the comeback fans measure others against.",
     "impress", "\"Palace were nearly bottom of the second tier at Christmas 2003 and went up that May.\""),
    (2, 'Which Austrian manager won the FA Cup with Palace in 2025?', ['Oliver Glasner', 'Ralph Hasenhüttl', 'Adi Hütter'], 0,
     'Oliver Glasner, who had already won the Europa League with Eintracht Frankfurt. He took Palace to their first trophy in his first full season.',
     'Glasner is the name on the first trophy. He will always be a Palace legend for it.',
     'say', '"Glasner won them the cup in 2025. Their first major trophy."'),
    (2, "Palace beat which club in the 2025 FA Cup final?", ["Manchester City", "Manchester United", "Aston Villa"], 0,
     "Manchester City, 1-0, at Wembley. City had won the cup two years earlier and were favourites by a distance.",
     "Beating City in a final is the giant-killing every small club dreams of. Palace did it.",
     "say", "\"They beat City in the final. Actual Man City, one-nil.\""),
]

EVERTON = [
    (1, "Which ground was Everton's home from 1892 to 2025?", ['Goodison Park', 'Prenton Park', 'Deepdale'], 0,
     'Goodison Park, one of the first purpose-built football grounds in England. Everton left it in 2025 after 133 years.',
     'Leaving Goodison was emotional for every Everton fan. Knowing it shows you understand.',
     'ask', 'Ask him: "Did you go to Goodison before they left? What was it like?"'),
    (1, "What is Everton's nickname?", ["The Toffees", "The Tigers", "The Scousers"], 0,
     "The Toffees, after the toffee shops by the club's early grounds. The Toffee Lady, in old-fashioned dress, throws sweets into the crowd before home games.",
     "The Toffee Lady is the detail that makes rival fans smile too.",
     "impress", "\"The Toffee Lady throws sweets into the crowd before games. That's why they're the Toffees.\""),
    (1, "Who are Everton's rivals in the Merseyside derby?", ['Liverpool', 'Tranmere Rovers', 'Manchester United'], 0,
     "Liverpool, whose ground sat across Stanley Park from Everton's old one. The friendly derby, as families are split, though it's famous for red cards.",
     'A friendly derby famous for red cards is the contradiction worth quoting.',
     'impress', '"They call it the friendly derby, and it\'s famous for red cards."'),
    (2, "In which year was Everton founded?", ["1878", "1888", "1892"], 0,
     "1878, as St Domingo's, a church team. They renamed themselves Everton a year later and were founder members of the Football League in 1888.",
     "Everton were there at the start of league football. Fans are proud of the age.",
     "say", "\"Everton go back to 1878. Founder members of the league.\""),
    (1, "What colour are Everton's home shirts?", ["Royal blue", "White", "Sky blue"], 0,
     "Royal blue, since 1901. Before that they tried black with a red sash, and were nicknamed the Black Watch.",
     "Blue in Liverpool means Everton. Red means the other lot.",
     "say", "\"Blue half of Liverpool. Everton.\""),
    (2, "Which centre-forward scored 383 goals for Everton between the wars?", ["Dixie Dean", "Graeme Sharp", "Romelu Lukaku"], 0,
     "Dixie Dean, famous for his heading, in the 1920s and 30s. A statue of him went up outside the old ground in 2001. He died there, watching a derby, in 1980.",
     "Dixie Dean is the name older Evertonians say like a saint's.",
     "say", "\"Dixie Dean died at the ground, watching a derby. That's devotion.\""),
    (3, "In 1927-28 Everton's centre-forward scored how many league goals?", ['50', '60', '70'], 1,
     'Sixty, in 39 games. He got the sixtieth, a header, in the final match of the season, against Arsenal.',
     'Sixty in a season is a number that ends arguments about modern strikers.',
     'impress', '"Sixty league goals in one season, 1928. Imagine a striker doing that now."'),
    (2, "In which year did Everton win the league title, the ninth in the club's history?", ["1970", "1985", "1987"], 2,
     "1987, two years after the eighth. By 2025, four clubs had won more league titles than Everton's nine.",
     "Nine titles is the number that makes Everton a big club, whatever recent years suggest.",
     "say", "\"Nine league titles. People forget how big Everton were.\""),
    (2, 'Who managed Everton through their 1980s glory years?', ['Howard Kendall', 'Harry Catterick', 'Colin Harvey'], 0,
     'Howard Kendall: two league titles, an FA Cup and a European trophy in the mid-eighties. Then the European ban after Heysel stopped the team going any further.',
     'The mid-eighties team is the one older fans mean when they say Everton were the best in England.',
     'ask', 'Ask him: "How good would Kendall\'s Everton have been without the European ban?"'),
    (2, "Which European trophy did Everton win in 1985?", ["The Cup Winners' Cup", "The European Cup", "The UEFA Cup"], 0,
     "The Cup Winners' Cup, beating Rapid Vienna 3-1 in Rotterdam. Weeks later English clubs were banned from Europe for five years.",
     "Everton's European trophy came just before the door shut. It shapes how fans see what might have been.",
     "impress", "\"Everton won in Europe in 1985 and then English clubs got banned for five years. Terrible timing.\""),
    (2, "In which year did Everton win the FA Cup, the club's fifth?", ["1984", "1995", "2009"], 1,
     "1995, beating Manchester United 1-0 at Wembley with a Paul Rideout header. No major trophy followed in the thirty years to 2025.",
     "The trophy drought is the sore point. Handle with care and sympathy.",
     "say", "\"The 1995 cup, and then a very long wait. Not that anyone's counting.\""),
    (2, "Which 16-year-old's first Everton goal, in 2002, ended Arsenal's thirty-game unbeaten run?", ["Wayne Rooney", "Ross Barkley", "Jack Rodwell"], 0,
     "Wayne Rooney, five days before his seventeenth birthday. He left for Manchester United two years later, which Evertonians did not enjoy.",
     "Rooney is Everton's best-known product and its sorest departure.",
     "ask", "Ask him: \"Do Everton fans forgive Rooney for leaving, or not?\""),
    (2, "Which Scottish manager called Everton 'the People's Club' on his first day in 2002?", ["David Moyes", "Walter Smith", "Alex Ferguson"], 0,
     "David Moyes, who made Everton hard to beat for eleven years before leaving for Manchester United in 2013.",
     "'The People's Club' is a phrase Evertonians adopted. Use it and he'll know you did your homework.",
     "say", "\"The People's Club. Moyes said it on his first day in 2002.\""),
    (3, "By 2025, how many times had Everton been relegated from the top flight?", ["Twice", "Four times", "Six times"], 0,
     "Twice, in 1930 and 1951, and they came back up each time. By 2025 they had spent over 120 seasons in the top flight.",
     "It is the stat Everton fans reach for when the club is struggling.",
     "impress", "\"By 2025 Everton had been relegated twice in their whole history. Twice.\""),
    (2, "The tower on Everton's badge was built as what?", ["An old village jail", "A Mersey lighthouse", "A medieval church tower"], 0,
     "A village lock-up, Prince Rupert's Tower, built in 1787 to hold drunks overnight. It stands in the Everton district and has been on the badge since 1938.",
     "A jail for drunks on the badge is the fact that gets a laugh at any table.",
     "impress", "\"The tower on the Everton badge is an old lock-up for drunks. True story.\""),
    (2, "Everton's new stadium, opened in 2025, is built where?", ["Bramley-Moore Dock", "Stanley Park", "Kirkby"], 0,
     "Bramley-Moore Dock, on the Mersey waterfront north of the city centre. A filled-in dock, with the river behind one stand.",
     "The new ground is the big Everton topic of the decade. Knowing where it is shows you've kept up.",
     "ask", "Ask him: \"Have you been to the new ground yet? Is it as good as they say?\""),
    (3, "Which ground was Everton's home from 1884 to 1892?", ["Anfield", "Stanley Park", "Priory Road"], 0,
     "Anfield. Everton walked out over rent, and the landlord started a new club to play there: Liverpool. Earlier homes were Stanley Park and Priory Road.",
     "Liverpool only exist because Everton fell out with a landlord. Evertonians love this.",
     "impress", "\"Everton were at Anfield first. They left over rent and the landlord started Liverpool.\""),
    (2, "Tim Cahill, who punched the corner flag when he scored, came from which country?", ["Australia", "New Zealand", "Ireland"], 0,
     "Australia. Fifty-six Premier League goals for Everton, a lot of them headers, each celebrated by boxing the corner flag.",
     "The corner-flag celebration is a visual he can picture instantly.",
     "say", "\"Cahill. The one who used to box the corner flag.\""),
    (3, "In which position did Everton finish in 2005, earning a Champions League qualifying place?", ["Second", "Third", "Fourth"], 2,
     "Fourth, above Liverpool, who then went and won the Champions League that very season. Everton lost their qualifier and went out. Evertonians do not enjoy this story.",
     "The 2005 story is the purest example of Everton luck. Tell it gently.",
     "say", "\"Everton finished above Liverpool in 2005 and Liverpool won the Champions League anyway. Typical.\""),
    (3, "At Everton's old ground, which end did the home side like to attack in the second half?", ["The Gwladys Street", "The Park End", "The Bullens Road Stand"], 0,
     "The Gwladys Street End, where the home fans stood. Kicking towards it late on meant the noise could push the team on.",
     "Stands with names carry memories. This one is now history.",
     "ask", "Ask him: \"Did you ever stand in the Gwladys Street? What was it like at the end?\""),
]

FULHAM = [
    (1, "What is Fulham's home ground called?", ["Craven Cottage", "Stamford Bridge", "Loftus Road"], 0,
     "Craven Cottage, on the bank of the Thames, with a real cottage in one corner where the players' families sit.",
     "The prettiest ground in London, and the cottage is real. Easy win.",
     "say", "\"Craven Cottage. There's an actual cottage in the corner. Families sit on the balcony.\""),
    (1, "What is Fulham's nickname?", ["The Cottagers", "The Robins", "The Hatters"], 0,
     "The Cottagers, from the ground's name. Also, more plainly, the Whites.",
     "Nickname and ground are the same story here.",
     "say", "\"The Cottagers. It really is just because of the ground.\""),
    (2, "In which year was Fulham founded?", ["1879", "1889", "1899"], 0,
     "1879, as a church Sunday school team, which makes Fulham older than Spurs (1882), Arsenal (1886) and Chelsea (1905).",
     "Being older than the London giants is something Fulham fans enjoy quietly.",
     "impress", "\"Fulham are older than Arsenal, Spurs and Chelsea. 1879.\""),
    (1, "What colours are Fulham's home kit?", ["White shirts and black shorts", "White shirts and blue shorts", "Black shirts and white shorts"], 0,
     "White shirts, black shorts. Plain and old-fashioned, like the ground.",
     "Kit recognition, the everyday skill.",
     "say", "\"White with black shorts. That's Fulham, not Spurs.\""),
    (2, "Which Egyptian businessman owned Fulham from 1997 to 2013?", ["Mohamed Al-Fayed", "Naguib Sawiris", "Mohamed Mansour"], 0,
     "Mohamed Al-Fayed, who also owned Harrods. He took Fulham from the third tier to the Premier League and a European final.",
     "The Harrods owner is the Fulham fact everyone half-remembers.",
     "ask", "Ask him: \"Was Fulham under Al-Fayed as mad as it sounds?\""),
    (3, "A statue of which pop star stood outside Fulham's ground from 2011 to 2013?", ['Michael Jackson', 'George Michael', 'Robbie Williams'], 0,
     'Michael Jackson, a friend of the owner who had watched one match there. Fans were baffled; the next owner removed it and it spent five years in a football museum.',
     'It is one of the strangest things ever to happen at a football ground. Enjoy it.',
     'impress', '"Fulham had a Michael Jackson statue outside the ground for two years. He\'d been to one game."'),
    (2, "In which year did Fulham reach the Europa League final?", ["2010", "2014", "2018"], 0,
     "2010, losing 2-1 to Atlético Madrid in Hamburg in extra time. On the way they beat Juventus from 4-1 down on aggregate. A tiny club's greatest run.",
     "The 2010 run is the story Fulham fans tell above all others.",
     "ask", "Ask him: \"The 2010 Europa League run. Where were you for the Juventus game?\""),
    (2, "Who managed Fulham to their Europa League final?", ["Roy Hodgson", "Martin Jol", "Mark Hughes"], 0,
     "Roy Hodgson, calm and clever, who was named manager of the year for it and then took the Liverpool job, which went badly.",
     "Hodgson at Fulham is the high point of a long career. Fans remember him fondly.",
     "say", "\"Hodgson got Fulham to a European final. Then Liverpool happened.\""),
    (2, "Which American businessman bought Fulham in 2013?", ["Shahid Khan", "Stan Kroenke", "John Henry"], 0,
     "Shahid Khan, who had bought the NFL's Jacksonville Jaguars the year before and has a famous moustache.",
     "The moustache and the NFL team: two facts he will confirm.",
     "say", "\"Khan bought Fulham in 2013. The American with the moustache and the NFL team.\""),
    (2, "Fans walking to Fulham's ground from the Tube usually go through which park?", ["Bishop's Park", "Battersea Park", "Holland Park"], 0,
     "Bishop's Park, the riverside park beside the ground. Home and away fans stroll through it together from Putney Bridge station.",
     "A ground reached through a park by the river is a day out. Suggest it.",
     "say", "\"We could walk through Bishop's Park and along the river before the game.\""),
    (3, "Fulham won the second tier as champions in 2001 under which French manager?", ["Jean Tigana", "Arsène Wenger", "Claude Puel"], 0,
     "Jean Tigana, with 101 points, playing passing football. It took Fulham back to the top flight for the first time since 1968.",
     "Tigana's team was the start of modern Fulham. The older fans light up at his name.",
     "ask", "Ask him: \"Was Tigana's Fulham the best team the club's had?\""),
    (2, "Which Portuguese manager won the Championship with Fulham in 2022?", ["Marco Silva", "José Mourinho", "André Villas-Boas"], 0,
     "Marco Silva, with 90 points and a striker scoring goals for fun. Fulham had bounced between divisions for years; Silva made them stay.",
     "Silva ended the yo-yo years. That is why fans speak well of him.",
     "say", "\"Silva stopped them yo-yoing. They stayed up comfortably after that.\""),
    (2, "Who are Fulham's main London rivals?", ["Chelsea", "Arsenal", "West Ham"], 0,
     "Chelsea, under two miles away. Chelsea's ground is actually in Fulham, which Fulham fans mention. Brentford and QPR are the other local grudges.",
     "West London's rivalries are gentle by the standards of the game, and he will insist otherwise.",
     "say", "\"Stamford Bridge is in Fulham, you know. Don't tell a Chelsea fan.\""),
    (3, "Which Fulham legend became the first footballer paid £100 a week, in 1961?", ["Johnny Haynes", "George Cohen", "Bobby Robson"], 0,
     "Johnny Haynes, an England captain who played 658 games for Fulham from 1952 to 1970. A stand is named after him and his statue is outside.",
     "The first hundred-pound-a-week footballer is a fact that reaches beyond football.",
     "impress", "\"The first footballer to earn a hundred pounds a week played for Fulham. Johnny Haynes, 1961.\""),
    (3, "Which American's chipped goal finished Fulham's comeback against Juventus in the Europa League?", ["Clint Dempsey", "Brian McBride", "Eddie Johnson"], 0,
     "Clint Dempsey, with a chipped finish to complete a comeback from 4-1 down on aggregate. Fulham's greatest night by common agreement.",
     "The Dempsey chip is the goal Fulham fans replay in their heads.",
     "say", "\"Dempsey's chip against Juventus. That's the one they all talk about.\""),
    (2, "Fulham first played at their riverside ground in which decade?", ["The 1890s", "The 1920s", "The 1950s"], 0,
     "The 1890s. Fulham moved in in 1896, when the site was overgrown. Apart from two seasons sharing QPR's ground in the 2000s, it has been home since.",
     "A ground used since Victorian times is a big part of why fans love it.",
     "ask", "Ask him: \"Didn't Fulham have to play at QPR for a couple of years?\""),
    (3, "Fulham's rebuilt Riverside Stand, opened in 2024, was designed to include what unusual feature?", ["A rooftop swimming pool", "A cinema", "A four-lane bowling alley"], 0,
     "A rooftop swimming pool, alongside restaurants and a members' club, at prices that made ordinary fans wince.",
     "A pool at a football ground is a fact that stops a table.",
     "impress", "\"Fulham's new stand has a rooftop pool. At a football stadium.\""),
    (2, "Which Fulham striker scored 43 goals in the 2021-22 Championship season?", ["Aleksandar Mitrović", "Brian McBride", "Rodrigo Muniz"], 0,
     "Aleksandar Mitrović, a Serbian striker who scored like a machine in the second tier and celebrated every one like a final. He left for Saudi Arabia in 2023.",
     "Mitrović is the modern Fulham hero. His 43 is a number fans quote.",
     "say", "\"Mitrović got 43 in one Championship season. Forty-three.\""),
    (1, "Fulham are from which part of London?", ["South-west", "North", "South-east"], 0,
     "South-west London, in the borough of Hammersmith and Fulham, on a bend of the Thames.",
     "Placing the club on the map is the basic courtesy.",
     "say", "\"South-west London, by the river. Nice part of town.\""),
    (2, "What is Fulham's mascot called?", ["Billy the Badger", "Freddie the Fox", "Terry the Thames Otter"], 0,
     "Billy the Badger, who was once ordered off the pitch by a referee for breakdancing in the corner during a match.",
     "A mascot sent off for breakdancing is the ideal dull-match anecdote.",
     "impress", "\"Fulham's mascot got sent off once. For breakdancing during the game.\""),
]

PACKS = [
    ("club-chelsea", "Chelsea", CHELSEA),
    ("club-coventry", "Coventry City", COVENTRY),
    ("club-crystal-palace", "Crystal Palace", CRYSTAL_PALACE),
    ("club-everton", "Everton", EVERTON),
    ("club-fulham", "Fulham", FULHAM),
]
