# His Club packs: Hull City, Ipswich Town, Leeds United, Liverpool, Manchester City.

HULL = [
    (1, "What is Hull City's nickname?", ["The Tigers", "The Lions", "The Codheads", "The Humbers"], 0, "The Tigers, for the amber and black stripes."),
    (1, "What is Hull City's home ground called?", ["MKM Stadium", "Boothferry Park", "Craven Park", "Anlaby Road"], 0, "The MKM Stadium, since 2002. It opened as the KC Stadium."),
    (1, "What colours are Hull's home shirts?", ["Amber and black", "Red and white", "Blue and white", "Green and gold"], 0, "Amber and black stripes, like a tiger."),
    (2, "In which year was Hull City founded?", ["1888", "1904", "1919", "1946"], 1, "1904. Rugby league was the game in Hull, and the football club took decades to catch on."),
    (2, "In which year did Hull City first reach the top flight of English football?", ["1966", "1985", "2008", "2016"], 2, "2008, via the play-off final. They had never been in the top division in 104 years."),
    (3, "Who scored the winning goal in the 2008 play-off final for Hull?", ["Dean Windass", "Nick Barmby", "Fraizer Campbell", "Ian Ashbee"], 0, "Dean Windass, a 39-year-old born in Hull, with a volley from the edge of the box. He cried on the pitch."),
    (2, "Which manager took Hull into the Premier League in 2008?", ["Phil Brown", "Steve Bruce", "Peter Taylor", "Nigel Pearson"], 0, "Phil Brown, remembered for his tan, his headset and one very public team talk."),
    (3, "Phil Brown gave a half-time team talk on the pitch in front of the fans at which ground in 2008?", ["Manchester City", "Old Trafford", "Anfield", "Stamford Bridge"], 0, "Manchester City, on Boxing Day, losing 4-0 at the break. It ended 5-1. He later said he regretted it."),
    (2, "Hull reached the FA Cup final in 2014 and lost to which club?", ["Arsenal", "Chelsea", "Manchester City", "Liverpool"], 0, "Arsenal, 3-2 after extra time. Hull had led 2-0 inside eight minutes."),
    (2, "Who managed Hull in the 2014 FA Cup final?", ["Steve Bruce", "Phil Brown", "Marco Silva", "Nigel Adkins"], 0, "Steve Bruce. Hull got into Europe for the first time as a result, since Arsenal were already in the Champions League."),
    (3, "In 2013 Hull's owners tried to rename the club what, and were refused by the FA?", ["Hull Tigers", "Hull City Tigers FC", "Humberside Tigers", "Tigers United"], 0, "Hull Tigers. The Allam family argued City was common. The fans and the FA disagreed."),
    (2, "What was Hull's home ground before 2002?", ["Boothferry Park", "The Boulevard", "Craven Park", "Anlaby Road"], 0, "Boothferry Park, which had its own railway station and a supermarket built into one stand."),
    (1, "Hull is in which historic county?", ["Yorkshire", "Lincolnshire", "Lancashire", "Durham"], 0, "Yorkshire, the East Riding. Hull's full name is Kingston upon Hull."),
    (2, "Which club do Hull fans regard as their main rivals?", ["Leeds United", "Grimsby Town", "Sheffield United", "Middlesbrough"], 0, "Leeds United, across Yorkshire. Grimsby and the Sheffield clubs are the older grudges."),
    (3, "Which Portuguese manager led Hull in the Premier League in 2016-17 and later managed Fulham?", ["Marco Silva", "Nuno Espírito Santo", "Paulo Fonseca", "Carlos Carvalhal"], 0, "Marco Silva. Hull were relegated, but his reputation survived and Watford and Everton came calling."),
    (3, "After relegation from the Premier League in 2017, Hull dropped to League One in which year?", ["2018", "2019", "2020", "2021"], 2, "2020, finishing bottom of the Championship during the pandemic season."),
    (3, "Hull won League One in which year?", ["2019", "2021", "2022", "2023"], 1, "2021, at the first attempt, bouncing straight back to the Championship."),
    (3, "Which Turkish television personality bought Hull City in 2022?", ["Acun Ilıcalı", "Ali Koç", "Fatih Terim", "Cem Yılmaz"], 0, "Acun Ilıcalı, who presents Turkey's version of Survivor. He promised the Premier League."),
    (2, "Hull sits on which river?", ["The Humber", "The Tyne", "The Ouse", "The Trent"], 0, "The Humber, at the point where the River Hull meets it. Hence the name."),
    (2, "What is Hull City's mascot called?", ["Roary the Tiger", "Tigger", "Humber", "Stripes"], 0, "Roary the Tiger. Not to be confused with the Grimsby one."),
]

IPSWICH = [
    (1, "What is Ipswich Town's home ground called?", ["Portman Road", "Carrow Road", "Layer Road", "Roots Hall"], 0, "Portman Road, since 1884. The club has never played anywhere else."),
    (1, "What is Ipswich Town's nickname?", ["The Tractor Boys", "The Canaries", "The Blues", "The Farmers"], 0, "The Tractor Boys, which started as a jibe from rival fans about Suffolk farming and got adopted. Also just the Blues."),
    (2, "Who are Ipswich Town's fiercest rivals?", ["Norwich City", "Colchester United", "Southend", "Cambridge United"], 0, "Norwich City. The East Anglian derby, also known as the Old Farm derby, is the biggest game of either club's year."),
    (2, "In which year was Ipswich Town founded?", ["1878", "1888", "1898", "1908"], 0, "1878, though they stayed amateur until 1936 and only joined the Football League in 1938."),
    (2, "In which year did Ipswich win the league title?", ["1952", "1962", "1972", "1982"], 1, "1962, in their very first season in the top division. Nobody has done that since."),
    (2, "Who managed Ipswich to the 1962 title and went on to win the World Cup with England?", ["Alf Ramsey", "Bobby Robson", "Don Revie", "Walter Winterbottom"], 0, "Alf Ramsey. He left for England in 1963 and won the World Cup three years later."),
    (2, "In which year did Ipswich win the FA Cup?", ["1968", "1978", "1988", "2000"], 1, "1978, beating Arsenal 1-0 at Wembley. Their only FA Cup."),
    (2, "Which European trophy did Ipswich win in 1981?", ["The UEFA Cup", "The Cup Winners' Cup", "The European Cup", "The Super Cup"], 0, "The UEFA Cup, over two legs against AZ Alkmaar. Bobby Robson's finest hour at the club."),
    (2, "Which manager, later England manager, has a statue outside Portman Road?", ["Bobby Robson", "Alf Ramsey", "George Burley", "Joe Royle"], 0, "Bobby Robson, Ipswich manager from 1969 to 1982. Alf Ramsey has one too, on the other corner."),
    (2, "Which Northern Irish manager took Ipswich from League One to the Premier League in 2023 and 2024?", ["Kieran McKenna", "Michael O'Neill", "Brendan Rodgers", "Martin O'Neill"], 0, "Kieran McKenna, back-to-back promotions. Ipswich had been out of the top flight for 22 years."),
    (3, "Who did Ipswich beat in the 1981 UEFA Cup final?", ["AZ Alkmaar", "Feyenoord", "Real Madrid", "Cologne"], 0, "AZ Alkmaar of the Netherlands, 5-4 on aggregate. John Wark scored 14 goals in Europe that season."),
    (1, "What colours are Ipswich Town's home shirts?", ["Blue and white", "Yellow and green", "Red and white", "Claret and blue"], 0, "Blue shirts with white sleeves, white shorts."),
    (3, "Who scored the only goal of the 1978 FA Cup final for Ipswich?", ["Roger Osborne", "Paul Mariner", "Kevin Beattie", "Mick Mills"], 0, "Roger Osborne, who was so overcome he had to be substituted straight afterwards."),
    (1, "Ipswich is in which county?", ["Suffolk", "Norfolk", "Essex", "Cambridgeshire"], 0, "Suffolk, on the east coast. Norwich, in Norfolk, is forty miles north."),
    (2, "What animal is on the Ipswich Town badge?", ["A horse", "A canary", "A lion", "A tractor"], 0, "A Suffolk Punch horse, the county's heavy farm breed, standing over a football."),
    (3, "Ipswich were founder members of the Premier League in which season?", ["1992-93", "1994-95", "1996-97", "2000-01"], 0, "1992-93, having won the second tier the previous year. They were relegated in 1995."),
    (3, "In which position did Ipswich finish in 2001, their best Premier League season, under George Burley?", ["Third", "Fifth", "Seventh", "Ninth"], 1, "Fifth, in their first season back up, and into the UEFA Cup. Burley was manager of the year."),
    (3, "What tongue-in-cheek name is the Ipswich v Norwich derby sometimes given?", ["The Old Farm derby", "The Turnip derby", "The Broads derby", "The A140 derby"], 0, "The Old Farm derby, a joke on Glasgow's Old Firm. The A140 is the road between the two."),
    (2, "In which year were Ipswich relegated after just one season back in the Premier League?", ["2023", "2024", "2025", "2026"], 2, "2025, alongside Leicester and Southampton — all three promoted clubs went straight back down."),
    (3, "Who is Ipswich Town's all-time record goalscorer?", ["Ray Crawford", "Paul Mariner", "Ted Phillips", "Marcus Stewart"], 0, "Ray Crawford, 227 goals, most of them in the Ramsey years. He was the first Ipswich player capped by England."),
]

LEEDS = [
    (1, "What is Leeds United's home ground called?", ["Elland Road", "Headingley", "Roundhay Park", "Thorp Arch"], 0, "Elland Road, since the club was formed in 1919."),
    (1, "What colour do Leeds United play in?", ["All white", "Yellow and blue", "Blue and white", "White and green"], 0, "All white, since the 1960s. It was borrowed from Real Madrid."),
    (2, "In which year was Leeds United founded?", ["1904", "1919", "1925", "1946"], 1, "1919, after the previous club, Leeds City, was thrown out of the league for illegal payments."),
    (2, "Which manager built the great Leeds team of the 1960s and 70s?", ["Don Revie", "Brian Clough", "Howard Wilkinson", "Jimmy Armfield"], 0, "Don Revie, manager from 1961 to 1974. Two league titles, and a reputation for being hard to beat and hard to like."),
    (2, "In which year did Leeds last win the league title?", ["1974", "1985", "1992", "2001"], 2, "1992, the final season before the Premier League began. Leeds have not finished above United since."),
    (2, "Who managed Leeds to the 1992 title, the last English manager to win the top flight?", ["Howard Wilkinson", "Don Revie", "David O'Leary", "George Graham"], 0, "Howard Wilkinson, known as Sergeant Wilko. No English manager has won it since."),
    (2, "In which year did Leeds reach the semi-finals of the Champions League?", ["1975", "1992", "2001", "2010"], 2, "2001, losing to Valencia. They had beaten Deportivo and drawn with Barcelona along the way."),
    (3, "By which year had Leeds fallen to League One, the third tier, after their financial collapse?", ["2004", "2007", "2010", "2012"], 1, "2007, three years after leaving the Premier League. They had gambled on Champions League money that stopped."),
    (2, "Which Argentine manager took Leeds back to the Premier League in 2020?", ["Marcelo Bielsa", "Mauricio Pochettino", "Diego Simeone", "Jorge Sampaoli"], 0, "Marcelo Bielsa, who sat on a bucket, ran the players into the ground, and was adored for it."),
    (2, "Who are Leeds United's fiercest rivals?", ["Manchester United", "Sheffield United", "Bradford City", "Huddersfield Town"], 0, "Manchester United, in the Roses rivalry: Yorkshire against Lancashire, going back centuries."),
    (3, "Which Leeds captain of the Revie era has a statue outside Elland Road?", ["Billy Bremner", "Jack Charlton", "Norman Hunter", "Johnny Giles"], 0, "Billy Bremner, the fiery Scottish midfielder. Small, red-haired and afraid of nobody."),
    (2, "What is Leeds United's nickname?", ["The Whites", "The Lions", "The Yorkshire Terriers", "The Loiners"], 0, "The Whites, for the kit. They were also called the Peacocks, after a pub near the ground."),
    (2, "Why do Leeds play in all white?", ["Don Revie copied Real Madrid", "It was cheaper to wash", "A sponsor demanded it", "To match the Yorkshire rose"], 0, "Don Revie changed the kit in 1961 to copy Real Madrid, the best team in Europe, hoping some of it would rub off."),
    (3, "Leeds lost the 1975 European Cup final to which club?", ["Bayern Munich", "Ajax", "Juventus", "Benfica"], 0, "Bayern Munich, 2-0 in Paris, after two Leeds goals were disallowed. Fans rioted and Leeds were banned from Europe."),
    (3, "Leeds returned to the Premier League in 2025 as Championship champions with how many points?", ["90", "95", "100", "106"], 2, "One hundred, level with Burnley, on the last day. Both clubs went up."),
    (2, "What is the name of the Leeds United club song?", ["Marching On Together", "Glory Glory Leeds", "Yorkshire Forever", "White Rose Rising"], 0, "Marching On Together, released as a single in 1972 for the FA Cup final. Sung at every game since."),
    (3, "Leeds won the FA Cup in 1972 by beating which club?", ["Arsenal", "Chelsea", "Liverpool", "Sunderland"], 0, "Arsenal, 1-0 at Wembley, with an Allan Clarke header. Still their only FA Cup."),
    (1, "Leeds is in which county?", ["Yorkshire", "Lancashire", "Derbyshire", "Nottinghamshire"], 0, "West Yorkshire. The white rose on the badge is the county's symbol."),
    (3, "Which player did Leeds sell to Manchester United in 1992, a deal they came to regret?", ["Eric Cantona", "Gary McAllister", "Lee Chapman", "David Batty"], 0, "Eric Cantona, for about £1.2 million. He won four titles in five years at Old Trafford."),
    (2, "Which German manager led Leeds to promotion in 2025?", ["Daniel Farke", "Jesse Marsch", "Thomas Tuchel", "Ralf Rangnick"], 0, "Daniel Farke, who had already taken Norwich up twice. He knows the Championship."),
]

LIVERPOOL = [
    (1, "What is Liverpool's home ground called?", ["Anfield", "Goodison Park", "Stanley Park", "The Kop"], 0, "Anfield, since 1892. It had been Everton's ground before a rent row."),
    (1, "Which song do Liverpool fans sing before every home match?", ["You'll Never Walk Alone", "Blue Moon", "Marching On Together", "Glory Glory"], 0, "You'll Never Walk Alone, from the musical Carousel, adopted after Gerry and the Pacemakers had a hit with it in 1963."),
    (2, "Liverpool's league title in 2025 was the club's how-manyth?", ["Eighteenth", "Nineteenth", "Twentieth", "Twenty-first"], 2, "Twentieth, drawing level with Manchester United's record."),
    (2, "How many times have Liverpool won the European Cup or Champions League?", ["Three", "Four", "Five", "Six"], 3, "Six: 1977, 1978, 1981, 1984, 2005 and 2019. More than any other English club."),
    (1, "Liverpool came back from 3-0 down to win the 2005 Champions League final against which club?", ["AC Milan", "Juventus", "Barcelona", "Real Madrid"], 0, "AC Milan, in Istanbul. Three goals in six minutes, then penalties. The miracle of Istanbul."),
    (1, "Which German managed Liverpool from 2015 to 2024?", ["Jürgen Klopp", "Thomas Tuchel", "Ralf Rangnick", "Julian Nagelsmann"], 0, "Jürgen Klopp, hugs and heavy metal football. A Champions League and Liverpool's first title in thirty years."),
    (2, "In which year did Liverpool end their thirty-year wait for a league title?", ["2014", "2019", "2020", "2022"], 2, "2020, during the pandemic, with seven games to spare. Fans celebrated outside an empty Anfield."),
    (3, "Who is Liverpool's all-time record goalscorer?", ["Ian Rush", "Roger Hunt", "Mohamed Salah", "Steven Gerrard"], 0, "Ian Rush, 346 goals across two spells in the 1980s and 90s."),
    (1, "Which two clubs are Liverpool's main rivals?", ["Everton and Manchester United", "Everton and Leeds", "Manchester City and Chelsea", "Arsenal and Spurs"], 0, "Everton in the Merseyside derby, and Manchester United in the biggest rivalry in English football."),
    (3, "The Kop, Anfield's famous stand, is named after what?", ["A hill in the Boer War", "A Liverpool docker", "A shipyard", "A Norwegian word for stand"], 0, "Spion Kop, a hill in South Africa where many Liverpool soldiers died in 1900. The steep terrace reminded people of it."),
    (2, "Which Scot managed Liverpool from 1959 to 1974 and has a statue outside Anfield?", ["Bill Shankly", "Bob Paisley", "Kenny Dalglish", "Matt Busby"], 0, "Bill Shankly, who took them up from the second division and built the modern club. The gates are named after him."),
    (3, "Which Liverpool manager won three European Cups between 1977 and 1981?", ["Bob Paisley", "Bill Shankly", "Joe Fagan", "Kenny Dalglish"], 0, "Bob Paisley, Shankly's quiet assistant, who turned out to be even more successful."),
    (3, "Steven Gerrard's long-range equaliser in the 2006 FA Cup final came against which club?", ["West Ham", "Chelsea", "Arsenal", "Cardiff"], 0, "West Ham, in the last minute, from 35 yards. Liverpool won on penalties. People call it the Gerrard final."),
    (2, "Mohamed Salah joined Liverpool in 2017 from which club?", ["Roma", "Chelsea", "Fiorentina", "Basel"], 0, "Roma, for about £37 million. He scored 44 goals in his first season."),
    (3, "Virgil van Dijk joined Liverpool in 2018 from which club, for a record fee for a defender?", ["Southampton", "Celtic", "Ajax", "Tottenham"], 0, "Southampton, for £75 million. Liverpool reached two Champions League finals in his first two seasons."),
    (2, "Who succeeded Jürgen Klopp as Liverpool manager in 2024 and won the title in his first season?", ["Arne Slot", "Xabi Alonso", "Roberto De Zerbi", "Ruben Amorim"], 0, "Arne Slot, from Feyenoord. Calm where Klopp was loud, and champion within a year."),
    (2, "Who did Liverpool beat in the 2019 Champions League final?", ["Tottenham Hotspur", "Manchester City", "Barcelona", "Real Madrid"], 0, "Tottenham, 2-0 in Madrid. Salah scored a penalty in the second minute."),
    (3, "In the 2019 comeback against Barcelona, who took the quick corner for the winning goal?", ["Trent Alexander-Arnold", "Andy Robertson", "Xherdan Shaqiri", "James Milner"], 0, "Trent Alexander-Arnold, while Barcelona's defenders were not looking. Divock Origi scored. Corner taken quickly."),
    (1, "What bird is on the Liverpool badge?", ["The liver bird", "An eagle", "A magpie", "A cockerel"], 0, "The liver bird, the city's symbol, a cormorant with a sprig of seaweed in its beak."),
    (3, "Kenny Dalglish joined Liverpool in 1977 from which club?", ["Celtic", "Rangers", "Aberdeen", "Hibernian"], 0, "Celtic, for £440,000, to replace Kevin Keegan. He became the club's greatest player and then its manager."),
]

MAN_CITY = [
    (1, "What is Manchester City's home ground called?", ["Etihad Stadium", "Maine Road", "Old Trafford", "The City of Manchester Arena"], 0, "The Etihad Stadium, built for the 2002 Commonwealth Games. Officially the City of Manchester Stadium."),
    (2, "Where did Manchester City play before moving to the Etihad in 2003?", ["Maine Road", "Hyde Road", "Old Trafford", "Belle Vue"], 0, "Maine Road, in Moss Side, from 1923. Once the biggest club ground in England."),
    (1, "What colour are Manchester City's home shirts?", ["Sky blue", "Red", "Navy blue", "White"], 0, "Sky blue, since the 1890s. City fans sing Blue Moon."),
    (1, "Which Spanish manager took charge of Manchester City in 2016?", ["Pep Guardiola", "Manuel Pellegrini", "Roberto Mancini", "Mikel Arteta"], 0, "Pep Guardiola, who had won everything at Barcelona and Bayern first. Six league titles in his first eight seasons."),
    (2, "In which year was Manchester City bought by Abu Dhabi's Sheikh Mansour?", ["2003", "2008", "2012", "2016"], 1, "2008, on the last day of the transfer window. Robinho arrived the same day and the modern City began."),
    (2, "In which year did Manchester City win their first Premier League title?", ["2010", "2012", "2014", "2018"], 1, "2012, with Agüero's goal in the last seconds of the last game, against QPR, to beat United on goal difference."),
    (2, "In which year did Manchester City win the treble of league, FA Cup and Champions League?", ["2019", "2021", "2023", "2024"], 2, "2023, only the second English club to do it after Manchester United in 1999."),
    (2, "Who did Manchester City beat in the 2023 Champions League final?", ["Inter Milan", "Real Madrid", "Bayern Munich", "Chelsea"], 0, "Inter Milan, 1-0 in Istanbul. Rodri scored the goal."),
    (2, "How many goals did Erling Haaland score in the 2022-23 Premier League, a record for one season?", ["30", "34", "36", "40"], 2, "Thirty-six, in his first season in England, beating a record that had stood since 1994."),
    (2, "Manchester City became the first club to win how many consecutive English titles in 2024?", ["Three", "Four", "Five", "Six"], 1, "Four in a row, from 2021 to 2024. Nobody had done more than three."),
    (1, "Who are Manchester City's rivals in the Manchester derby?", ["Manchester United", "Liverpool", "Bolton", "Stockport"], 0, "Manchester United. City spent decades as the noisy neighbours; the noise is louder now."),
    (3, "In the 1999 play-off final against Gillingham, who scored City's 95th-minute equaliser?", ["Paul Dickov", "Shaun Goater", "Kevin Horlock", "Nicky Weaver"], 0, "Paul Dickov, at Wembley, to force extra time and penalties. City were in the third tier at the time."),
    (3, "In which year did Manchester City win the European Cup Winners' Cup?", ["1956", "1970", "1976", "1999"], 1, "1970, beating Górnik Zabrze in Vienna. Their only European trophy before 2023."),
    (3, "The Colin Bell Stand at the Etihad is named after a 1960s and 70s midfielder nicknamed what?", ["Nijinsky", "The King", "Bell Boy", "The Engine"], 0, "Nijinsky, after the racehorse, because he could run all day."),
    (3, "Which Spanish playmaker, nicknamed El Mago, has a statue outside the Etihad?", ["David Silva", "Sergio Agüero", "Vincent Kompany", "Rodri"], 0, "David Silva, the magician. Ten seasons, four titles, and a statue next to Agüero's and Kompany's."),
    (2, "In which year did Manchester City beat Manchester United 6-1 at Old Trafford?", ["2008", "2011", "2014", "2019"], 1, "2011, on the way to their first title. Balotelli scored and revealed a shirt saying 'Why always me?'"),
    (2, "What is Manchester City's nickname?", ["The Citizens", "The Blues Brothers", "The Sky Devils", "The Mancs"], 0, "The Citizens, or the Sky Blues. Fans just say City."),
    (2, "The Etihad Stadium is on which side of Manchester?", ["East", "West", "North", "South"], 0, "East Manchester, in a once-industrial area rebuilt around the stadium and the club's training campus."),
    (3, "Which Chilean manager won the Premier League with Manchester City in 2014?", ["Manuel Pellegrini", "Roberto Mancini", "Mark Hughes", "Sven-Göran Eriksson"], 0, "Manuel Pellegrini, the first manager from outside Europe to win the Premier League."),
    (3, "In which year did Manchester City win their first league title?", ["1904", "1937", "1968", "2012"], 1, "1937, and they went down the very next season while scoring more goals than anyone. Typical City, fans said for decades."),
]

PACKS = [
    ("club-hull", "Hull City", HULL),
    ("club-ipswich", "Ipswich Town", IPSWICH),
    ("club-leeds", "Leeds United", LEEDS),
    ("club-liverpool", "Liverpool", LIVERPOOL),
    ("club-man-city", "Manchester City", MAN_CITY),
]
