# His Club packs: Arsenal, Aston Villa, Bournemouth, Brentford, Brighton. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)
# Finished, dated history only. No superlatives tied to now. Every question carries its use.

ARSENAL = [
    (1, "In which year was Arsenal founded?", ["1878", "1886", "1892", "1905"], 1,
     "1886, by workers at the Royal Arsenal munitions factory in Woolwich, south-east London. That is where the cannon on the badge and the Gunners nickname come from.",
     "The badge, the nickname and the origin are one story. Knowing it makes the whole club make sense.",
     "impress", "\"Arsenal started as a works team at a weapons factory. Hence the cannon.\""),
    (2, "In which part of London did Arsenal begin life?", ["Islington", "Woolwich", "Camden", "Hackney"], 1,
     "Woolwich, south of the river. In 1913 they moved north to Highbury, a few miles from Tottenham, uninvited. Spurs fans consider it the original sin of the derby.",
     "This is the root of the Arsenal–Spurs hatred, and plenty of fans only half know it.",
     "ask", "Ask him: \"Do you know why Spurs actually hate Arsenal? It's about a house move.\""),
    (1, "Where did Arsenal play before the Emirates Stadium?", ["White Hart Lane", "Highbury", "Wembley", "The Den"], 1,
     "Highbury, from 1913 to 2006, with its art deco stands. The old ground is flats now, and the pitch is the residents' garden.",
     "Older Arsenal fans say Highbury with feeling. The flats detail is the bit they enjoy.",
     "say", "\"Highbury's flats now, isn't it? The pitch is the garden.\""),
    (1, "What is Arsenal's nickname?", ["The Gunners", "The Hammers", "The Blues", "The Irons"], 0,
     "The Gunners, for the armaments works. The fans call themselves Gooners.",
     "Gooner is the word he uses for himself. Gunners is the word for the team. Mixing them up is noticed.",
     "say", "\"Come on you Gunners.\" (The chant. Sung before every match.)"),
    (1, "What colour are Arsenal's home shirts?", ["All red", "Red with white sleeves", "Red and white stripes", "White with red sleeves"], 1,
     "Red body and white sleeves, since 1933. Before that, plain dark red. The change was Herbert Chapman's, the manager who made Arsenal a big club in the 1930s.",
     "The white sleeves are the club's signature. Knowing they were a manager's idea is a good extra.",
     "impress", "\"The white sleeves were a manager's idea in 1933. Before that they were plain red.\""),
    (3, "Which manager gave Arsenal the white sleeves and got the local Tube station renamed after the club?", ["Herbert Chapman", "Tom Whittaker", "George Allison", "Bertie Mee"], 0,
     "Herbert Chapman, manager 1925 to 1934: two titles, an FA Cup, and ideas like floodlights and numbered shirts. In 1932 he got Gillespie Road station renamed Arsenal.",
     "He is why there is a statue of a man in a suit outside the Emirates, and why the Tube stop says Arsenal.",
     "ask", "Ask him: \"Do you know why the Tube station is called Arsenal? A manager talked them into it.\""),
    (2, "In which season did Arsenal go the whole league campaign without losing?", ["1997-98", "2001-02", "2003-04", "2007-08"], 2,
     "2003-04: 38 games, 26 wins, 12 draws, no defeats. The team is called the Invincibles, and no English club has matched it since.",
     "He will bring it up unprompted. Now you can bring it up first.",
     "say", "\"The Invincibles season. Thirty-eight games without losing.\""),
    (2, "Who managed the Invincibles?", ["George Graham", "Arsène Wenger", "Herbert Chapman", "Bertie Mee"], 1,
     "Arsène Wenger, in charge 1996 to 2018, the longest-serving manager in the club's history. He changed English football's diet and training. Fans sing his name to this day.",
     "Wenger divides Arsenal fans: genius, or stayed too long. It is a conversation he has had many times.",
     "ask", "Ask him: \"Was Wenger a genius, or did he stay about five years too long?\""),
    (2, "Who captained the Invincibles?", ["Tony Adams", "Patrick Vieira", "Thierry Henry", "Sol Campbell"], 1,
     "Patrick Vieira, the tall French midfielder who ran the team. He later became a manager himself.",
     "Vieira is who he means by a proper midfielder. Every Arsenal midfielder since gets compared to him.",
     "say", "\"They've not had a midfielder like Vieira since.\" (Any time the midfield looks soft.)"),
    (2, "Who is Arsenal's top scorer in the club's history?", ["Ian Wright", "Thierry Henry", "Dennis Bergkamp", "Cliff Bastin"], 1,
     "Thierry Henry, 228 goals across two spells, 1999 to 2007 and a short return in 2012. His statue outside the Emirates shows him sliding on his knees.",
     "Henry is the club's modern hero. If you know one Arsenal player, know him.",
     "ask", "Ask him: \"Did you ever see Henry play live?\" If yes, sit back for ten minutes."),
    (2, "How many league titles had Arsenal won by the end of the 2025-26 season?", ["Ten", "Twelve", "Fourteen", "Sixteen"], 2,
     "Fourteen, the 2025-26 title being the fourteenth. Thirteen of them came before 2004; then a long wait.",
     "The number he will quote against Liverpool and United fans. Have it ready.",
     "say", "\"Fourteen titles. They finally added one after twenty-two years.\""),
    (2, "How many times had Arsenal won the FA Cup by 2020?", ["Eight", "Eleven", "Fourteen", "Seventeen"], 2,
     "Fourteen, the 2020 win over Chelsea being the fourteenth. No club had won it more often at that point.",
     "The FA Cup is Arsenal's speciality. It is the trophy fans of other clubs mock them for loving.",
     "say", "\"Arsenal and the FA Cup. Fourteen of them by 2020.\""),
    (1, "Who are Arsenal's biggest rivals?", ["Chelsea", "Tottenham Hotspur", "Manchester United", "West Ham"], 1,
     "Tottenham, four miles up the road. The North London derby; two a season, and they decide his mood for a fortnight each.",
     "Knowing the rival is the minimum. Knowing derby week is coming is the bonus.",
     "ask", "Ask him: \"When's the derby? Do I need to clear the diary?\""),
    (2, "In which year did Arsenal move to the Emirates Stadium?", ["2002", "2004", "2006", "2008"], 2,
     "2006. The stadium cost so much that the club went nine years without a trophy while paying for it. Fans called it the banter era.",
     "The trophy drought explains a decade of jokes at Arsenal's expense. He remembers every one.",
     "ask", "Ask him: \"Was the Emirates worth nine years without a trophy?\""),
    (2, "Which final did Arsenal reach in Paris in 2006, losing 2-1 to Barcelona?", ["The FA Cup final", "The Champions League final", "The UEFA Cup final", "The League Cup final"], 1,
     "The Champions League final. Their goalkeeper was sent off after eighteen minutes, they led anyway, and lost to two late goals. Arsenal fans have not forgiven the referee.",
     "European finals are rare for Arsenal, so each one is a story he can tell in detail.",
     "ask", "Ask him: \"Paris 2006. Was Lehmann's red card the end of it, or would they have lost anyway?\""),
    (2, "Tony Adams captained Arsenal to league titles in how many different decades?", ["One", "Two", "Three", "Four"], 2,
     "Three: 1989 and 1991, 1998, and 2002. A centre-back who played for Arsenal for his entire career and has a statue outside the ground.",
     "Mr Arsenal, fans call him. Three decades as captain is the fact to have.",
     "impress", "\"Adams captained them to titles in three different decades. Nobody else in England has done that.\""),
    (2, "Who managed Arsenal to the league titles of 1989 and 1991?", ["Terry Neill", "George Graham", "Don Howe", "Bruce Rioch"], 1,
     "George Graham, an ex-Arsenal player whose teams defended first and won 1-0 a lot. Rivals sang 'boring, boring Arsenal'; Arsenal fans answered 'one-nil to the Arsenal'.",
     "'Boring Arsenal' was the taunt for a decade, and the club's identity before Wenger arrived.",
     "impress", "\"'One-nil to the Arsenal' was a real chant. They won a lot of games that way under Graham.\""),
    (1, "What is the name of Arsenal's dinosaur mascot?", ["Gunnersaurus", "Rex the Gunner", "Arsenalodon", "Highbury Harry"], 0,
     "Gunnersaurus Rex, designed by a young fan in 1993. The club made him redundant in 2020 to save money and reinstated him after an outcry led by a player.",
     "The mascot being sacked and un-sacked is a story that gets a laugh every time.",
     "say", "\"They sacked Gunnersaurus in 2020 and had to bring him back. Fans revolted.\""),
    (3, "Which Arsenal striker with a statue outside the Emirates played in the Invincibles team?", ["Dennis Bergkamp", "Thierry Henry", "Ian Wright", "David Seaman"], 1,
     "Thierry Henry. Bergkamp has a statue too, but he retired in 2006. Henry scored 30 league goals in the unbeaten season.",
     "Two statues, one question he will enjoy: which of them was better.",
     "ask", "Ask him: \"Henry or Bergkamp?\" Then just listen."),
    (2, "In which season did Arsenal win the league title for the first time in twenty-two years?", ["2022-23", "2023-24", "2024-25", "2025-26"], 3,
     "2025-26, with 85 points, after finishing second three years in a row. The previous title was the Invincibles' in 2003-04.",
     "It is the freshest happy memory he has. Asking about it is a gift.",
     "ask", "Ask him: \"Where were you when they finally won it?\""),
]

ASTON_VILLA = [
    (1, "What is Aston Villa's home ground called?", ["Villa Park", "St Andrew's", "The Hawthorns", "Molineux"], 0,
     "Villa Park, since 1897, in the Aston area of Birmingham. The stand behind one goal, the Holte End, is one of the biggest single stands in England.",
     "'The Holte End' is a phrase he will use. Now you know it is a stand, not a person.",
     "say", "\"The Holte End's loud today.\""),
    (1, "What colours do Aston Villa play in?", ["Red and white", "Claret and blue", "Blue and white", "Green and black"], 1,
     "Claret and blue. Villa had it first; West Ham and Burnley copied it. A common quiz argument.",
     "Three clubs share the colours and Villa fans want credit for being first.",
     "ask", "Ask him: \"Who had claret and blue first, Villa or West Ham?\" He will say Villa, and he is right."),
    (2, "In which year was Aston Villa founded?", ["1866", "1874", "1888", "1901"], 1,
     "1874, by members of a chapel cricket team looking for something to do in winter. One of England's oldest clubs.",
     "Villa fans feel the club's history is undervalued. Knowing its age is a way in.",
     "say", "\"Villa are one of the oldest clubs in the country. 1874.\""),
    (2, "Aston Villa were founder members of which competition in 1888?", ["The FA Cup", "The Football League", "The Premier League", "The European Cup"], 1,
     "The Football League, the first league anywhere in the world. A Villa director, William McGregor, wrote the letter that proposed it.",
     "The league itself was a Villa man's idea. That is a genuinely impressive fact.",
     "impress", "\"A Villa director invented the Football League. Literally wrote the letter proposing it.\""),
    (2, "In which year did Aston Villa win the European Cup?", ["1977", "1982", "1994", "1999"], 1,
     "1982, beating Bayern Munich 1-0 in Rotterdam. The European Cup is what the Champions League used to be called.",
     "People forget Villa are European champions. Villa fans do not, and love being reminded.",
     "impress", "\"Villa are European champions. 1982, beat Bayern. People always forget.\""),
    (3, "Who scored the winning goal in the 1982 European Cup final?", ["Gary Shaw", "Peter Withe", "Tony Morley", "Dennis Mortimer"], 1,
     "Peter Withe, off his shin, from a Tony Morley cross. The word 'Withe' is painted on the goalpost at Villa Park at the exact spot the ball went in.",
     "The goalpost detail is the kind of thing only proper fans know.",
     "impress", "\"The scorer's name is painted on the goalpost at Villa Park where the ball went in.\""),
    (2, "How many English league titles has Aston Villa won?", ["Three", "Five", "Seven", "Nine"], 2,
     "Seven, six of them before 1911 and the seventh in 1981. For a spell around 1900 they were the biggest club in England.",
     "It is the number that explains why Villa fans think of themselves as a big club.",
     "say", "\"Seven league titles. They were the Manchester United of the 1890s.\""),
    (2, "Who managed Aston Villa to the league title in 1981?", ["Ron Saunders", "Graham Taylor", "Ron Atkinson", "Brian Little"], 0,
     "Ron Saunders, a strict manager who used just fourteen players all season. He quit months before the European Cup win, so his assistant lifted it.",
     "Fourteen players for a whole season is a fact that stops modern fans in their tracks.",
     "impress", "\"They won the 1981 title using fourteen players. Fourteen, all season.\""),
    (2, "Who are Aston Villa's city rivals?", ["Wolves", "Birmingham City", "West Brom", "Coventry"], 1,
     "Birmingham City. The Second City derby, played only when the two are in the same division. To Villa fans, 'the Blues' means Birmingham, not Chelsea.",
     "If he says 'the Blues' with contempt, this is who he means.",
     "say", "\"Second City derby. Villa fans think they're the bigger club, and they usually are.\""),
    (1, "What is Aston Villa's nickname?", ["The Villans", "The Lions", "The Clarets", "The Brummies"], 0,
     "The Villans, spelt with an a. Rival fans prefer the other spelling.",
     "Spelling it right in a text is a small win.",
     "say", "\"Come on you Villans.\" (With an a. He will notice.)"),
    (2, "Which animal is on the Aston Villa badge?", ["A lion", "An eagle", "A bull", "A stag"], 0,
     "A lion, taken from the Scottish royal standard because an early chairman was Scottish. The motto underneath is Prepared.",
     "Badge stories are the easiest way to show you looked properly.",
     "impress", "\"The lion on the badge is Scottish. An early chairman brought it with him.\""),
    (2, "Jack Grealish left Aston Villa in 2021 to join which club?", ["Manchester United", "Manchester City", "Chelsea", "Liverpool"], 1,
     "Manchester City, for £100 million, a British record at the time. He was Villa's captain and a local boy, which made it hurt.",
     "The local hero who left for money is a Villa sore point and a good conversation.",
     "ask", "Ask him: \"Do Villa fans forgive Grealish, or is he a traitor for life?\""),
    (2, "After relegation in 2016, in which year did Villa return to the Premier League?", ["2017", "2018", "2019", "2020"], 2,
     "2019, beating Derby in the play-off final at Wembley. Three seasons in the Championship for a club that considers itself a giant.",
     "The Championship years are the low point he measures everything against.",
     "ask", "Ask him: \"How bad were the Championship years? Did you keep going?\""),
    (2, "Which Villa goalkeeper won the World Cup with Argentina in 2022?", ["Emiliano Martínez", "Brad Friedel", "Mark Bosnich", "Tom Heaton"], 0,
     "Emiliano Martínez, who also won the award for best goalkeeper at the tournament and celebrated it in a way that upset a lot of people.",
     "A World Cup winner between the posts is a bragging right few clubs have.",
     "say", "\"Villa's keeper won the World Cup. Not many clubs can say that.\""),
    (2, "In which competition did Aston Villa play in 2024-25 for the first time in over forty years?", ["The Europa League", "The Champions League", "The FA Cup", "The Conference League"], 1,
     "The Champions League, after finishing fourth in 2024 under Unai Emery. Their previous appearance in Europe's top competition was 1982-83, defending their European Cup.",
     "Villa in the Champions League was the feel-good story of 2024. He will remember the anthem at Villa Park.",
     "ask", "Ask him: \"What was it like hearing the Champions League anthem at Villa Park again?\""),
    (3, "Which striker left Villa for Manchester United in 1998 and won the treble the next year?", ["Dwight Yorke", "Stan Collymore", "Savo Milošević", "Julian Joachim"], 0,
     "Dwight Yorke, from Trinidad and Tobago, always smiling. Villa fans watched him win everything the season after he left.",
     "Selling your best player and watching him win the treble is a specific kind of pain. It explains a lot.",
     "say", "\"Villa sold Yorke and he won the treble the next year. Typical.\""),
    (3, "Villa beat Manchester United in the 1994 League Cup final under which manager?", ["Brian Little", "Ron Atkinson", "John Gregory", "Graham Taylor"], 1,
     "Ron Atkinson, who had managed United himself. The win stopped United doing a domestic treble that year, which Villa fans enjoy more than the cup.",
     "Stopping a rival's treble is worth more than a trophy to some fans. This is the example.",
     "impress", "\"Villa stopped United's treble in 1994. Fans bring it up to this day.\""),
    (1, "Aston Villa are from which city?", ["Liverpool", "Birmingham", "Manchester", "Leeds"], 1,
     "Birmingham. Aston is a district north of the city centre; the ground is next to the motorway.",
     "England's second city has two clubs and Villa fans are clear about which is the big one.",
     "say", "\"Villa's the big club in Birmingham. Ask a Blues fan and duck.\""),
    (2, "The Holte End is a famous stand at which ground?", ["Villa Park", "Anfield", "Goodison Park", "Old Trafford"], 0,
     "Villa Park. It holds around 13,000 and is where the noise comes from. Named after a local landowner's hall.",
     "A stand with a name is a stand with a reputation. This one has both.",
     "say", "\"The Holte End. Thirteen thousand people behind one goal.\""),
    (2, "Which Spanish manager took Villa from the relegation zone in 2022 to the Champions League by 2024?", ["Unai Emery", "Rafael Benítez", "Mikel Arteta", "Pep Guardiola"], 0,
     "Unai Emery, who had won the Europa League four times elsewhere. Villa were 17th when he arrived and fourth eighteen months later.",
     "The Emery turnaround is why Villa fans have been so cheerful lately.",
     "say", "\"Emery took them from the relegation zone to the Champions League in eighteen months.\""),
]

BOURNEMOUTH = [
    (1, "What is Bournemouth's home ground called?", ["Vitality Stadium", "St Mary's", "Fratton Park", "The Valley"], 0,
     "The Vitality Stadium, also known by its old name, Dean Court. It holds about 11,000, the smallest ground in Premier League history.",
     "The tiny ground is the first thing anyone mentions about Bournemouth. Get there first.",
     "say", "\"Eleven thousand. You could fit their whole crowd in a corner of Old Trafford.\""),
    (1, "What is Bournemouth's nickname?", ["The Cherries", "The Saints", "The Pilgrims", "The Seasiders"], 0,
     "The Cherries, for the cherry-red shirts and the cherry orchards that used to stand near the ground.",
     "Nicknames turn up in every commentary. This one has a pleasant story.",
     "say", "\"The Cherries. There were orchards by the old ground.\""),
    (1, "What colours are Bournemouth's home shirts?", ["Red and black stripes", "Red and white stripes", "All red", "Blue and white"], 0,
     "Red and black stripes, copied from AC Milan in the early 1970s because the manager admired them.",
     "A small English club in Milan's colours is a neat fact for a match on telly.",
     "impress", "\"Bournemouth's stripes are copied from AC Milan. A manager just liked the look.\""),
    (2, "In which year did Bournemouth first reach the Premier League?", ["2010", "2013", "2015", "2018"], 2,
     "2015, for the first time in 116 years of existence. Seven years earlier they had nearly gone out of business.",
     "The rise is the whole Bournemouth story. Everything else is footnotes.",
     "say", "\"First time in the top flight in 2015, after 116 years. Mad.\""),
    (2, "Which manager took Bournemouth from the fourth tier to the Premier League?", ["Eddie Howe", "Harry Redknapp", "Scott Parker", "Sean Dyche"], 0,
     "Eddie Howe, a former Bournemouth defender who became manager at 31. Two spells, three promotions, then Newcastle.",
     "Howe is the name Bournemouth fans say with love, and Newcastle fans now say too.",
     "ask", "Ask him: \"Is Eddie Howe the best thing that ever happened to Bournemouth?\""),
    (3, "In which year did Bournemouth go into administration and nearly cease to exist?", ["1997", "2008", "2012", "2016"], 1,
     "2008. They started the next season on minus 17 points as a punishment and stayed up anyway. Seven years later they were in the Premier League.",
     "From nearly dead to the Premier League in seven years. It is the fact that explains the club.",
     "impress", "\"Bournemouth started 2008-09 on minus seventeen points and were in the Premier League seven years later.\""),
    (2, "Bournemouth is in which English county?", ["Hampshire", "Dorset", "Devon", "Sussex"], 1,
     "Dorset, on the south coast: beaches, pine trees, retirees, and one small football ground.",
     "Placing a club on the map is the basic courtesy of a conversation.",
     "say", "\"Bournemouth, down in Dorset. Best beaches of any away day.\""),
    (2, "How many seasons did Bournemouth's first Premier League spell last?", ["Two", "Three", "Five", "Seven"], 2,
     "Five, from 2015 to 2020, when they were relegated on the final day. Two seasons later they were back.",
     "Yo-yo clubs are a type. Knowing the pattern lets you predict the conversation.",
     "ask", "Ask him: \"Are they a proper Premier League club now, or a yo-yo club at heart?\""),
    (2, "After relegation in 2020, in which year did Bournemouth return to the Premier League?", ["2021", "2022", "2023", "2024"], 1,
     "2022, finishing second in the Championship under Scott Parker, who was sacked four games into the new season.",
     "Sacking the manager who got you promoted is a football classic. This is a clean example.",
     "impress", "\"They sacked the manager who got them promoted after four games. Four.\""),
    (1, "Bournemouth is on which coast of England?", ["The east coast", "The south coast", "The north-west coast", "The north-east coast"], 1,
     "The south coast, between Southampton and Poole. A seaside town before it was a football town.",
     "Geography first. The rest follows.",
     "say", "\"South coast club. Southampton are the neighbours they don't like.\""),
    (2, "What does Bournemouth's badge show?", ["A cherry tree", "A footballer heading a ball", "A pier", "A seagull"], 1,
     "A player heading the ball, in profile, on the red and black stripes. It was drawn in the 1970s and has barely changed.",
     "Badge spotting is a low-stakes way to show attention.",
     "say", "\"Their badge is a bloke heading a ball. Nice and literal.\""),
    (2, "Who are Bournemouth's south-coast rivals?", ["Portsmouth", "Southampton", "Brighton", "Plymouth"], 1,
     "Southampton, thirty miles east. Historically the bigger club by far, which Bournemouth fans enjoy pointing out has changed.",
     "Rivalries are where fans get funny. This one has a recent role reversal.",
     "ask", "Ask him: \"Are Bournemouth bigger than Southampton now? Be honest.\""),
    (3, "Which striker left Bournemouth for Newcastle in 2020?", ["Callum Wilson", "Joshua King", "Dominic Solanke", "Josh King"], 0,
     "Callum Wilson, their top scorer in the Premier League years, sold after relegation. He kept scoring at Newcastle.",
     "Losing your striker after relegation is the price of going down. Wilson is the example.",
     "say", "\"They had to sell Wilson when they went down. That's what relegation costs.\""),
    (3, "Andoni Iraola, appointed Bournemouth manager in 2023, comes from which country?", ["Portugal", "Spain", "Italy", "Argentina"], 1,
     "Spain, from the Basque Country. He had made Rayo Vallecano in Madrid play thrilling football on no money, and did the same at Bournemouth.",
     "Iraola made Bournemouth a team neutral fans watched on purpose. That is rare for a small club.",
     "ask", "Ask him: \"Did Iraola's Bournemouth actually play the best football in the league for a while?\""),
    (2, "After leaving Bournemouth in 2020, which club did Eddie Howe go on to manage?", ["Newcastle United", "Everton", "Crystal Palace", "Celtic"], 0,
     "Newcastle, from 2021. He took them into the Champions League and won their first domestic trophy in seventy years, the 2025 League Cup.",
     "Bournemouth's manager becoming a Newcastle hero is a shared story between two sets of fans.",
     "say", "\"Howe won Newcastle a trophy after seventy years. Bournemouth fans were chuffed for him.\""),
    (3, "What does AFC stand for in AFC Bournemouth?", ["Association Football Club", "Athletic Football Club", "Amateur Football Club", "Allied Football Club"], 1,
     "Athletic Football Club. The letters were moved to the front in 1971 so the club would appear at the top of alphabetical lists.",
     "The alphabetical trick is a perfect pub fact: small, true and slightly ridiculous.",
     "impress", "\"They put AFC at the front so they'd be first in alphabetical lists. That's the whole reason.\""),
    (3, "What was Bournemouth called before 1971?", ["Bournemouth Rovers", "Bournemouth & Boscombe Athletic", "Boscombe Wanderers", "Bournemouth Town"], 1,
     "Bournemouth & Boscombe Athletic. Boscombe is the suburb where the ground is; locals call the ground Dean Court to this day.",
     "Old names come up on old shirts and old photos. He may not know this one himself.",
     "ask", "Ask him: \"Did you know they used to be Bournemouth and Boscombe Athletic?\""),
    (3, "In which division were Bournemouth playing in 2009, six years before reaching the Premier League?", ["The Championship", "League One", "League Two", "The National League"], 2,
     "League Two, the fourth tier, and fighting relegation from it. Six years later they were playing Manchester United.",
     "Fourth tier to top tier in six years is the fastest climb in modern English football.",
     "impress", "\"Fourth division in 2009, Premier League in 2015. Six years.\""),
    (2, "Bournemouth's first ever Premier League season, 2015-16, ended in which position?", ["Ninth", "Twelfth", "Sixteenth", "Nineteenth"], 2,
     "Sixteenth, comfortably safe. Everyone had tipped them to go straight back down. Eddie Howe's team played passing football and stayed up.",
     "Staying up in year one is the achievement small clubs are judged on. Bournemouth passed.",
     "say", "\"Everyone said they'd go straight back down in 2016. Finished sixteenth, easy.\""),
    (2, "Where does the name Dean Court, Bournemouth's ground, come from?", ["A local landowner", "A former player", "A church", "A racecourse"], 0,
     "The Cooper-Dean family, local landowners who gave the club the land in 1910. The stadium sponsor changes; the fans' name for the place does not.",
     "Fans use the old name, sponsors use the new one. Knowing both is knowing the club.",
     "say", "\"Dean Court, or the Vitality if you're the sponsor. Fans say Dean Court.\""),
]

BRENTFORD = [
    (1, "What is Brentford's nickname?", ["The Bees", "The Hornets", "The Wasps", "The Bugs"], 0,
     "The Bees. The badge is a bee, the fans chant 'buzz' at throw-ins, and the mascot is called Buzz Bee.",
     "It is the friendliest nickname in the league and it comes with a chant.",
     "say", "\"The Bees. Listen, the fans buzz at throw-ins.\""),
    (1, "What is Brentford's home ground called?", ["Griffin Park", "Gtech Community Stadium", "Loftus Road", "Craven Cottage"], 1,
     "The Gtech Community Stadium, by Kew Bridge, since 2020. Squeezed between railway lines on the Thames.",
     "New grounds lose the old names slowly. He may say Griffin Park by habit.",
     "say", "\"They're at the Gtech now. Right by Kew Bridge.\""),
    (2, "What was the name of Brentford's old ground, famous for having a pub on every corner?", ["Griffin Park", "The Den", "Plough Lane", "Boleyn Ground"], 0,
     "Griffin Park, home from 1904 to 2020. Four corners, four pubs. Away fans planned their day around it.",
     "The four pubs are the fact every fan knows and loves. It works every time.",
     "impress", "\"Griffin Park had a pub on all four corners. Best away day in the country.\""),
    (2, "In which year were Brentford promoted to the Premier League?", ["2019", "2020", "2021", "2022"], 2,
     "2021, beating Swansea 2-0 in the play-off final at Wembley, after losing the final the year before.",
     "Losing a play-off final then winning the next one is a story with a happy ending. He will tell it if asked.",
     "ask", "Ask him: \"Were you at Wembley in 2021? After losing the year before?\""),
    (1, "What colours are Brentford's home shirts?", ["Red and white stripes", "Blue and white stripes", "All red", "Yellow and black"], 0,
     "Red and white stripes with black shorts. Easy to confuse with Sunderland on a small screen.",
     "Kit recognition is how you follow a match without the commentary.",
     "say", "\"Red and white stripes, black shorts. That's Brentford, not Sunderland.\""),
    (2, "Which Danish manager took Brentford into the Premier League and kept them there?", ["Thomas Frank", "Kasper Hjulmand", "Michael Laudrup", "Ståle Solbakken"], 0,
     "Thomas Frank, in charge from 2018 to 2025, seven years, then off to Tottenham. Calm, funny, and adored in west London.",
     "Frank was the model of a small-club manager. His move to Spurs is a talking point in itself.",
     "ask", "Ask him: \"Was Thomas Frank right to leave for Spurs?\""),
    (3, "Brentford's owner made his fortune in what?", ["Sports betting", "Property", "Oil", "Television"], 0,
     "Sports betting. Matthew Benham, a lifelong fan, built a gambling company on statistics and ran the club the same way. He also owns Midtjylland in Denmark.",
     "The maths club is Brentford's identity. Knowing why is knowing them.",
     "impress", "\"Brentford's owner is a professional gambler. The whole club runs on his statistics.\""),
    (1, "Brentford is in which part of London?", ["North", "East", "West", "South"], 2,
     "West London, near Kew Gardens, wedged between Fulham and QPR. A small corner of a big city.",
     "London has a dozen clubs. Placing them is the first skill.",
     "say", "\"West London. Fulham and QPR are the neighbours.\""),
    (3, "When Brentford went up in 2021, how many years had passed since their previous top-flight season?", ["24 years", "44 years", "74 years", "94 years"], 2,
     "Seventy-four years. Their previous top-flight season was 1946-47, just after the war.",
     "Seventy-four years of waiting puts every other club's complaints in perspective.",
     "impress", "\"Brentford waited seventy-four years to get back to the top flight. Since 1947.\""),
    (3, "Ivan Toney left Brentford in 2024 to play in which country?", ["Italy", "Saudi Arabia", "Spain", "Turkey"], 1,
     "Saudi Arabia, joining Al-Ahli for around £40 million. He had been their top scorer for four seasons and served a betting ban in 2023.",
     "Players leaving for Saudi money is a live debate. Toney is a name he will bring up.",
     "ask", "Ask him: \"Can you blame Toney for taking the Saudi money?\""),
    (1, "Who are Brentford's nearest rivals?", ["Fulham and QPR", "Chelsea and Arsenal", "Watford and Luton", "Crystal Palace and Millwall"], 0,
     "Fulham and Queens Park Rangers, a couple of miles away in west London. Low-key as derbies go, and he wants them won all the same.",
     "Small derbies matter as much to the fans in them as the big ones do.",
     "say", "\"West London derby. Nobody else cares, everyone in Brentford does.\""),
    (2, "What is on the Brentford badge?", ["A bee", "A griffin", "A bridge", "A crown"], 0,
     "A bee, in a red and white roundel. The griffin from the old ground's name appears on older badges.",
     "One badge, one insect. Simple to remember, and the buzz chant follows from it.",
     "say", "\"Bee on the badge, buzz from the crowd. Consistent, at least.\""),
    (3, "In 2016 Brentford closed their youth academy and replaced it with what?", ["A B team", "A partnership with Chelsea", "A women's team", "Nothing"], 0,
     "A B team, for players released by bigger clubs aged 17 to 20. Cheaper than an academy, and several of them made the first team.",
     "Brentford doing things differently is their whole appeal to football hipsters.",
     "impress", "\"Brentford shut their academy and signed rejects from other clubs instead. It worked.\""),
    (3, "Brentford's first ever Premier League match in 2021 was a 2-0 home win over which club?", ["Arsenal", "Chelsea", "Liverpool", "Spurs"], 0,
     "Arsenal, on the opening Friday night of the season, live on television. A perfect way to arrive.",
     "First-night wins get retold forever. This one was against a giant.",
     "say", "\"Their first ever Premier League game was beating Arsenal. Friday night, on telly.\""),
    (2, "Christian Eriksen joined Brentford in 2022 after collapsing on the pitch at which tournament?", ["Euro 2020", "The 2018 World Cup", "The 2022 World Cup", "Euro 2016"], 0,
     "Euro 2020, played in 2021, where his heart stopped during a Denmark match. Fitted with a defibrillator, he returned to football at Brentford six months later.",
     "Eriksen's comeback is one of the truly moving football stories of the decade, and Brentford made it possible.",
     "say", "\"Eriksen came back from a cardiac arrest at Brentford. The whole league was cheering him.\""),
    (3, "Brentford's stadium sits next to which London landmark?", ["Kew Bridge", "Tower Bridge", "Hammersmith Bridge", "Battersea Power Station"], 0,
     "Kew Bridge, over the Thames, a walk from the botanical gardens. The stadium is wedged between two railway lines.",
     "Knowing where the ground is turns a fixture into a day out.",
     "say", "\"It's right by Kew Gardens. Football and a walk round the gardens.\""),
    (1, "At which stadium did Brentford win the 2021 play-off final?", ["Wembley", "Old Trafford", "Cardiff", "Villa Park"], 0,
     "Wembley, in front of a crowd limited by the pandemic. Their first promotion to the top flight in the club's history under that name.",
     "Play-off finals are the happiest and saddest day in a fan's year. This one was the happy kind.",
     "ask", "Ask him: \"What was Wembley like with only ten thousand in?\""),
    (2, "In which year was Brentford founded?", ["1875", "1889", "1901", "1920"], 1,
     "1889, by members of a rowing club looking for a winter sport. They voted between football and rugby, and football won by a few votes.",
     "A club that nearly became a rugby team is a fact worth having.",
     "impress", "\"Brentford voted on whether to play football or rugby in 1889. Football won narrowly.\""),
    (3, "Thomas Frank left Brentford in 2025 to manage which club?", ["Tottenham Hotspur", "Chelsea", "Manchester United", "Denmark"], 0,
     "Tottenham. In the same summer Brentford lost their manager, their captain and their top scorer, and were expected to collapse.",
     "The summer of 2025 is the moment Brentford fans feared the project was over.",
     "ask", "Ask him: \"Did you think Brentford were finished when Frank, the captain and the striker all left?\""),
    (2, "Brentford's mascot is called what?", ["Buzz Bee", "Billy Bee", "Bertie", "Sting"], 0,
     "Buzz Bee. Not a complicated club when it comes to naming things.",
     "Mascots are small talk gold when the match is dull.",
     "say", "\"Buzz Bee. They didn't overthink that one.\""),
]

BRIGHTON = [
    (1, "What is Brighton's nickname?", ["The Seagulls", "The Pelicans", "The Albions", "The Shrimpers"], 0,
     "The Seagulls. It started in the 1970s as a chant to answer Crystal Palace fans singing 'Eagles', and became the official nickname.",
     "A nickname invented to annoy a rival is the best kind. And it explains the Palace thing.",
     "impress", "\"Brighton only became the Seagulls to wind up Palace fans. Seagulls versus Eagles.\""),
    (1, "What is Brighton's home ground commonly called?", ["The Amex", "The Goldstone", "Withdean", "The Dell"], 0,
     "The Amex, after the sponsor, at Falmer on the edge of the South Downs. Officially the American Express Stadium.",
     "\"At the Amex\" is how every Brighton home game is described.",
     "say", "\"They're at the Amex. Lovely ground, middle of nowhere.\""),
    (2, "Who are Brighton's fiercest rivals?", ["Southampton", "Crystal Palace", "Portsmouth", "Bournemouth"], 1,
     "Crystal Palace, forty miles away in south London. The M23 derby, named after the motorway between them. Nobody outside the two clubs quite gets it.",
     "It is the rivalry that makes no geographical sense, so knowing about it marks you as informed.",
     "ask", "Ask him: \"Why do Brighton and Palace hate each other? They're forty miles apart.\""),
    (2, "In which year were Brighton promoted to the Premier League for the first time?", ["2015", "2017", "2019", "2021"], 1,
     "2017, after thirty-four years out of the top flight, under Chris Hughton. Twenty years earlier they had nearly dropped out of the league altogether.",
     "The 2017 promotion is the moment the modern club began. He will have a memory of it.",
     "ask", "Ask him: \"Where were you when they went up in 2017?\""),
    (1, "What colours are Brighton's home shirts?", ["Blue and white stripes", "Red and white stripes", "All blue", "Green and white"], 0,
     "Blue and white stripes, with white shorts. Easy to spot, easy to confuse with Sheffield Wednesday.",
     "Kit recognition is the fastest way to follow a match.",
     "say", "\"Blue and white stripes. That's Brighton.\""),
    (3, "Brighton's owner, Tony Bloom, made his money how?", ["Professional gambling", "Property", "Software", "Shipping"], 0,
     "Professional gambling and a betting-data company. A lifelong fan known at the poker table as the Lizard, he uses his data to find players nobody else has spotted.",
     "Brighton's whole business model — buy cheap, sell for a fortune — comes from this one man.",
     "impress", "\"Brighton's owner is a poker player. His data company finds the players before anyone else.\""),
    (2, "Which Italian manager took Brighton into European football for the first time?", ["Roberto De Zerbi", "Roberto Mancini", "Carlo Ancelotti", "Maurizio Sarri"], 0,
     "Roberto De Zerbi, who took them to sixth in 2023 and the Europa League, playing football neutral fans tuned in for.",
     "De Zerbi's Brighton is the team neutral fans fell for. He is now at Spurs, so the name lives on.",
     "ask", "Ask him: \"Was De Zerbi's Brighton the best football you've seen from a small club?\""),
    (3, "Which ground did Brighton lose in 1997, leaving them homeless for two years?", ["The Goldstone Ground", "Withdean Stadium", "The Dell", "Priestfield"], 0,
     "The Goldstone Ground, sold by the owners to developers. Brighton played home games seventy miles away in Gillingham for two seasons while fans fought to save the club.",
     "The Goldstone is the trauma every Brighton fan over forty carries. Knowing it shows respect.",
     "ask", "Ask him: \"Did you go through the Goldstone years? Playing home games in Gillingham?\""),
    (3, "Brighton reached the FA Cup final in 1983 and lost the replay to which club?", ["Manchester United", "Liverpool", "Everton", "Arsenal"], 0,
     "Manchester United, 4-0 in a replay after a 2-2 draw. Gordon Smith could have won the first game late on. 'And Smith must score,' said the commentator. He didn't.",
     "'And Smith must score' is a Brighton fanzine title and a phrase fans use for any big miss.",
     "impress", "\"'And Smith must score' comes from Brighton's 1983 cup final. He didn't. There's a fanzine named after it.\""),
    (2, "Graham Potter left Brighton in 2022 to manage which club?", ["Chelsea", "Arsenal", "Manchester United", "England"], 0,
     "Chelsea, who paid Brighton over £20 million for him. He was sacked within seven months, and Brighton got better without him.",
     "Managers leaving for big clubs and flopping is a genre. This is the textbook case.",
     "say", "\"Chelsea paid twenty million for Potter and sacked him in seven months. Brighton just carried on.\""),
    (3, "Brighton sold Moisés Caicedo to Chelsea in 2023 for roughly how much?", ["£45 million", "£75 million", "£115 million", "£150 million"], 2,
     "About £115 million, a British record at the time, for a player they had bought for around £4 million from Ecuador two years earlier.",
     "Buy for four, sell for a hundred and fifteen. That is the Brighton model in one transfer.",
     "impress", "\"Brighton bought Caicedo for four million and sold him for a hundred and fifteen. In two years.\""),
    (1, "Brighton is in which county?", ["Kent", "Sussex", "Hampshire", "Surrey"], 1,
     "Sussex, on the south coast, an hour from London. The ground is on the edge of the South Downs, next to a university.",
     "The seaside city with a football club: useful context for the away-day chat.",
     "say", "\"Brighton. Sussex, seaside, students and a football club on the Downs.\""),
    (2, "Which Brighton midfielder moved to Liverpool in 2023, months after winning the World Cup?", ["Alexis Mac Allister", "Moisés Caicedo", "Marc Cucurella", "Yves Bissouma"], 0,
     "Alexis Mac Allister, a World Cup winner with Argentina in December 2022 while a Brighton player. Sold to Liverpool for about £35 million.",
     "A World Cup winner in a Brighton shirt is a fact that surprises people.",
     "impress", "\"Brighton had a World Cup winner in their team. Mac Allister, before Liverpool bought him.\""),
    (2, "In which competition did Brighton play their first European campaign, in 2023-24?", ["The Champions League", "The Europa League", "The Conference League", "The Intertoto Cup"], 1,
     "The Europa League. They beat Ajax and Marseille and went out to Roma in the round of sixteen. A club that had been homeless twenty-five years earlier.",
     "From Gillingham to Amsterdam in one lifetime is the arc Brighton fans live for.",
     "say", "\"Brighton beat Ajax in Europe. Twenty-five years after nearly going out of business.\""),
    (3, "Where did Brighton play their home games between 1999 and 2011?", ["Withdean Stadium", "The Goldstone Ground", "Gillingham", "Brighton Racecourse"], 0,
     "Withdean, a converted athletics track with temporary stands and a running track between the fans and the pitch. Fans called it the Theatre of Trees.",
     "Twelve years on an athletics track then European nights. The contrast is the story.",
     "impress", "\"They played on an athletics track for twelve years. Fans called it the Theatre of Trees.\""),
    (2, "The Brighton v Crystal Palace rivalry takes its name from what?", ["A motorway", "A railway line", "A river", "A shared manager"], 0,
     "The M23 motorway between the two. The actual origin was a feud between two managers in the 1970s, Alan Mullery and Terry Venables, that the fans adopted and kept.",
     "A derby caused by two managers falling out is a better story than geography.",
     "impress", "\"The Brighton–Palace thing started because the two managers hated each other in the seventies.\""),
    (2, "In which year was Brighton & Hove Albion founded?", ["1889", "1901", "1912", "1925"], 1,
     "1901, replacing a club called Brighton United that had gone bust. Albion is an old poetic name for Britain.",
     "The 'Albion' in the name puzzles people. Now you can explain it.",
     "say", "\"Albion just means Britain. It's the old poetic name.\""),
    (2, "What is Brighton's mascot called?", ["Gully", "Sammy the Seagull", "Albie", "Skipper"], 0,
     "Gully, a seagull, with a companion called Gully's Girl. Named after the bird, obviously.",
     "Mascot names are a safe question when the match is dull.",
     "say", "\"Gully. And there's a Gully's Girl.\""),
    (2, "In which year did Brighton's Amex Stadium open?", ["2007", "2009", "2011", "2013"], 2,
     "2011, after a fourteen-year fight for planning permission that went to a public inquiry twice. The first league game there was a 2-1 win over Doncaster.",
     "Fourteen years to build a ground. Fans remember every planning meeting.",
     "ask", "Ask him: \"Fourteen years to get the Amex built. Did you ever think it wouldn't happen?\""),
    (2, "Which Brighton manager left in 2024 and was later appointed at Tottenham?", ["Roberto De Zerbi", "Graham Potter", "Chris Hughton", "Fabian Hürzeler"], 0,
     "Roberto De Zerbi, who went to Marseille first. His replacement at Brighton, Fabian Hürzeler, was 31, the youngest manager in Premier League history at the time.",
     "Brighton appointing a 31-year-old is the kind of bold move that makes fans of other clubs jealous.",
     "impress", "\"Brighton hired a 31-year-old manager. Younger than some of the players.\""),
]

PACKS = [
    ("club-arsenal", "Arsenal", ARSENAL),
    ("club-aston-villa", "Aston Villa", ASTON_VILLA),
    ("club-bournemouth", "AFC Bournemouth", BOURNEMOUTH),
    ("club-brentford", "Brentford", BRENTFORD),
    ("club-brighton", "Brighton & Hove Albion", BRIGHTON),
]
