# His Club packs: Hull City, Ipswich Town, Leeds United, Liverpool, Manchester City. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)

HULL = [
    (1, "What is Hull City's nickname?", ["The Tigers", "The Lions", "The Codheads", "The Humbers"], 0,
     "The Tigers, for the amber and black stripes. The mascot is Roary.",
     "Kit and nickname in one. And the stripes make them easy to spot.",
     "say", "\"The Tigers. Amber and black, you can't miss them.\""),
    (1, "What is Hull City's home ground called?", ["MKM Stadium", "Boothferry Park", "Craven Park", "Anlaby Road"], 0,
     "The MKM Stadium, since 2002, shared with the rugby league club Hull FC. It opened as the KC Stadium; sponsors change, the building doesn't.",
     "Ground names change with sponsors. Knowing that stops you sounding out of date either way.",
     "say", "\"The MKM. Used to be the KC. Same place.\""),
    (1, "What colours are Hull's home shirts?", ["Amber and black", "Red and white", "Blue and white", "Green and gold"], 0,
     "Amber and black stripes, like a tiger, since the club's earliest days.",
     "Kit recognition on a small screen is the skill that lets you follow along.",
     "say", "\"Amber and black. That's Hull.\""),
    (2, "In which year was Hull City founded?", ["1888", "1904", "1919", "1946"], 1,
     "1904. Hull was a rugby league city and the football club took decades to catch on. It took them 104 years to reach the top division.",
     "A football club in a rugby town explains a lot about Hull's history.",
     "impress", "\"Hull's a rugby city. The football club took a hundred and four years to reach the top flight.\""),
    (2, "In which year did Hull City first reach the top flight of English football?", ["1966", "1985", "2008", "2016"], 2,
     "2008, via the play-off final, for the first time in the club's 104-year history. A 39-year-old local striker scored the winner.",
     "2008 is Hull's year zero. Every fan over thirty has a story about it.",
     "ask", "Ask him: \"Where were you for the 2008 play-off final?\""),
    (3, "Who scored the winning goal in Hull's 2008 play-off final?", ["Dean Windass", "Nick Barmby", "Fraizer Campbell", "Ian Ashbee"], 0,
     "Dean Windass, a 39-year-old born in Hull who had been released by the club as a teenager, with a volley from the edge of the box. He wept on the pitch.",
     "A local boy, 39, released as a kid, scoring the goal that took his hometown up. The perfect football story.",
     "impress", "\"The winner in 2008 was scored by a 39-year-old from Hull who the club had released as a teenager.\""),
    (2, "Which manager took Hull into the Premier League in 2008?", ["Phil Brown", "Steve Bruce", "Peter Taylor", "Nigel Pearson"], 0,
     "Phil Brown, remembered for his suntan, his headset and one very public team talk. He sang to the fans on the pitch when they stayed up.",
     "Brown is a character. Fans of other clubs mock him; Hull fans mostly love him.",
     "say", "\"Phil Brown. The one with the tan and the headset.\""),
    (3, "Phil Brown gave a half-time team talk on the pitch, in front of the fans, at which ground in 2008?", ["Manchester City", "Old Trafford", "Anfield", "Stamford Bridge"], 0,
     "Manchester City's, on Boxing Day, 4-0 down at the break. He sat the players on the grass and lectured them. It finished 5-1. He later admitted it was a mistake.",
     "The on-pitch team talk is one of the strangest sights in Premier League history. Worth knowing the details.",
     "impress", "\"Phil Brown once did the half-time team talk on the pitch, in front of the fans. Sat them all down. They lost 5-1.\""),
    (2, "Hull reached the FA Cup final in 2014 and lost to which club?", ["Arsenal", "Chelsea", "Manchester City", "Liverpool"], 0,
     "Arsenal, 3-2 after extra time, and Hull had led 2-0 inside eight minutes. Their one major final.",
     "Two-nil up in a cup final and losing is the kind of pain fans carry for life.",
     "ask", "Ask him: \"2014, two-nil up at Wembley after eight minutes. Do you ever think about it?\""),
    (2, "Who managed Hull in the 2014 FA Cup final?", ["Steve Bruce", "Phil Brown", "Marco Silva", "Nigel Adkins"], 0,
     "Steve Bruce, the former Manchester United captain. Because Arsenal were already in the Champions League, losing the final put Hull into Europe for the first time.",
     "Losing a final and qualifying for Europe anyway is a quirk fans enjoy explaining.",
     "impress", "\"Hull got into Europe by losing a cup final. Arsenal were already qualified.\""),
    (3, "In 2013 Hull's owners tried to rename the club what, and were refused by the FA?", ["Hull Tigers", "Hull City Tigers FC", "Humberside Tigers", "Tigers United"], 0,
     "Hull Tigers. The Allam family argued 'City' was common; fans marched, the FA said no, and the family sulked for years.",
     "Fans fighting their own owners over the club's name is a story every supporter understands.",
     "ask", "Ask him: \"Were you part of the protests when they tried to rename the club Hull Tigers?\""),
    (2, "What was Hull's home ground before 2002?", ["Boothferry Park", "The Boulevard", "Craven Park", "Anlaby Road"], 0,
     "Boothferry Park, from 1946, which had its own railway station and, by the end, a supermarket built into one stand.",
     "A ground with a supermarket in it is a fact people remember.",
     "impress", "\"Hull's old ground had a supermarket built into one of the stands. Boothferry Park.\""),
    (1, "Hull is in which historic county?", ["Yorkshire", "Lincolnshire", "Lancashire", "Durham"], 0,
     "Yorkshire, the East Riding. The city's full name is Kingston upon Hull, and it sits where the River Hull meets the Humber.",
     "Yorkshire loyalty runs deep. Getting the county right matters.",
     "say", "\"Hull's Yorkshire. East Riding, on the Humber.\""),
    (2, "Which club do Hull fans regard as their main rivals?", ["Leeds United", "Grimsby Town", "Sheffield United", "Middlesbrough"], 0,
     "Leeds United, the big Yorkshire club across the county. Grimsby, over the Humber, is the older, smaller grudge.",
     "Rivalries tell you who he shouts at. Leeds is the answer here.",
     "say", "\"Hull and Leeds. Yorkshire's a big county with a lot of grudges.\""),
    (3, "Which Portuguese manager led Hull in the Premier League in 2016-17?", ["Marco Silva", "Nuno Espírito Santo", "Paulo Fonseca", "Carlos Carvalhal"], 0,
     "Marco Silva, in his first English job. Hull went down anyway, but his reputation survived and he went on to manage Watford, Everton and Fulham.",
     "Silva is a name he will know from bigger clubs. Hull is where England first saw him.",
     "say", "\"Marco Silva started in England at Hull. Didn't keep them up, but everyone noticed him.\""),
    (3, "After relegation from the Premier League in 2017, Hull dropped to League One in which year?", ["2018", "2019", "2020", "2021"], 2,
     "2020, finishing bottom of the Championship in the pandemic season. Two relegations in three years.",
     "The fall to the third tier is the low point fans measure the current club against.",
     "ask", "Ask him: \"How bad was the League One year? Did you keep going?\""),
    (3, "Hull won League One in which year?", ["2019", "2021", "2022", "2023"], 1,
     "2021, at the first attempt, bouncing straight back up to the Championship as champions.",
     "Bouncing straight back is the happy half of the story. Fans like being reminded.",
     "say", "\"Straight back up as champions in 2021. Didn't hang about.\""),
    (3, "Which Turkish television personality bought Hull City in 2022?", ["Acun Ilıcalı", "Ali Koç", "Fatih Terim", "Cem Yılmaz"], 0,
     "Acun Ilıcalı, who presents Turkey's version of Survivor and owns a TV network. He promised the Premier League and, four years later, delivered it.",
     "A Turkish TV star owning a Yorkshire club is a fact that stops a conversation.",
     "impress", "\"Hull's owner presents Survivor in Turkey. He's basically Turkish Ant and Dec.\""),
    (2, "In which year did Hull return to the Premier League for the first time since 2017?", ["2024", "2025", "2026", "2027"], 2,
     "2026, through the play-offs after finishing sixth in the Championship. Nine years away, including one in the third tier.",
     "The 2026 promotion is the freshest joy. Ask about it.",
     "ask", "Ask him: \"Where were you when they went up through the play-offs this time?\""),
    (2, "What is Hull City's mascot called?", ["Roary the Tiger", "Tigger", "Humber", "Stripes"], 0,
     "Roary the Tiger. Not to be confused with a rugby league mascot of the same name across the city.",
     "Mascots are safe ground when the match goes quiet.",
     "say", "\"Roary. There's a rugby Roary too, apparently.\""),
]

IPSWICH = [
    (1, "What is Ipswich Town's home ground called?", ["Portman Road", "Carrow Road", "Layer Road", "Roots Hall"], 0,
     "Portman Road, since 1884, the club's home for its whole existence. Two England managers have statues outside it.",
     "A ground with two England managers' statues tells you Ipswich matter more than their size suggests.",
     "impress", "\"Two England managers have statues outside Portman Road. Ramsey and Robson.\""),
    (1, "What is Ipswich Town's nickname?", ["The Tractor Boys", "The Canaries", "The Blues", "The Farmers"], 0,
     "The Tractor Boys. Rival fans meant it as a jibe about Suffolk farming; Ipswich fans adopted it and put it on scarves. Also just the Blues.",
     "The best nicknames began as insults. This is the textbook example.",
     "say", "\"Tractor Boys started as an insult. Ipswich just took it and ran.\""),
    (2, "Who are Ipswich Town's fiercest rivals?", ["Norwich City", "Colchester United", "Southend", "Cambridge United"], 0,
     "Norwich City, forty miles north. The East Anglian derby, which fans jokingly call the Old Farm derby after Glasgow's Old Firm.",
     "The Old Farm pun is worth knowing on its own.",
     "say", "\"The Old Farm derby. Ipswich and Norwich. It's a farming joke on the Old Firm.\""),
    (2, "In which year was Ipswich Town founded?", ["1878", "1888", "1898", "1908"], 0,
     "1878, though they stayed amateur until 1936 and joined the Football League only in 1938. Late starters who then won the league within 24 years.",
     "From amateur club to champions in a generation is a remarkable arc.",
     "impress", "\"Ipswich were amateurs until 1936 and champions of England by 1962.\""),
    (2, "In which year did Ipswich win the league title?", ["1952", "1962", "1972", "1982"], 1,
     "1962, in their very first season in the top division. Nobody has done that since.",
     "Winning the league in your first top-flight season is a fact rival fans struggle to top.",
     "impress", "\"Ipswich won the title in their first ever season in the top division. 1962.\""),
    (2, "Who managed Ipswich to the 1962 title and then won the World Cup with England?", ["Alf Ramsey", "Bobby Robson", "Don Revie", "Walter Winterbottom"], 0,
     "Alf Ramsey, who left for England in 1963 and won the World Cup three years later. His statue stands outside Portman Road.",
     "England's one World Cup-winning manager came from Ipswich. That is a national-level fact.",
     "impress", "\"The manager who won England the World Cup came straight from Ipswich.\""),
    (2, "In which year did Ipswich win the FA Cup?", ["1968", "1978", "1988", "2000"], 1,
     "1978, beating Arsenal 1-0 at Wembley. Roger Osborne scored and was so overcome he had to be substituted straight afterwards.",
     "A goalscorer subbed off for fainting with emotion is a story worth the telling.",
     "impress", "\"The guy who scored Ipswich's cup final winner had to come off straight after. Overcome.\""),
    (2, "Which European trophy did Ipswich win in 1981?", ["The UEFA Cup", "The Cup Winners' Cup", "The European Cup", "The Super Cup"], 0,
     "The UEFA Cup, over two legs against AZ Alkmaar of the Netherlands, 5-4 on aggregate. Bobby Robson's team, playing lovely football.",
     "A Suffolk club winning a European trophy is the kind of thing that sounds made up.",
     "impress", "\"Ipswich won a European trophy in 1981. A Suffolk town of a hundred thousand people.\""),
    (2, "Which manager, later England manager, has a statue outside Portman Road?", ["Bobby Robson", "Alf Ramsey", "George Burley", "Joe Royle"], 0,
     "Bobby Robson, manager 1969 to 1982, then England, Barcelona and Newcastle. Alf Ramsey has one too, on the other corner.",
     "Robson is one of English football's best-loved figures. Knowing where he started is a kindness.",
     "say", "\"Bobby Robson learned his trade at Ipswich. Thirteen years before England.\""),
    (2, "Which Northern Irish manager took Ipswich from League One to the Premier League in 2023 and 2024?", ["Kieran McKenna", "Michael O'Neill", "Brendan Rodgers", "Martin O'Neill"], 0,
     "Kieran McKenna, back-to-back promotions in his first two full seasons, after 22 years out of the top flight. Big clubs came calling and he stayed.",
     "Two promotions in a row is rare. McKenna is the name Ipswich fans thank for it.",
     "say", "\"McKenna took them from the third tier to the Premier League in two seasons.\""),
    (3, "Who did Ipswich beat in the 1981 UEFA Cup final?", ["AZ Alkmaar", "Feyenoord", "Real Madrid", "Cologne"], 0,
     "AZ Alkmaar, 3-0 at home and 2-4 away. John Wark, a midfielder, scored 14 goals in the competition that season.",
     "The Alkmaar detail separates fans who know from fans who think they know.",
     "impress", "\"They beat AZ Alkmaar in the 1981 final. Their midfielder scored fourteen European goals that year.\""),
    (1, "What colours are Ipswich Town's home shirts?", ["Blue and white", "Yellow and green", "Red and white", "Claret and blue"], 0,
     "Blue shirts with white sleeves and white shorts. Norwich are yellow and green, which makes the derby easy to follow.",
     "Kit colours are the first thing you need on match day.",
     "say", "\"Blue and white is Ipswich. Yellow and green is Norwich. Two different worlds.\""),
    (3, "Who scored the winning goal of the 1978 FA Cup final for Ipswich?", ["Roger Osborne", "Paul Mariner", "Kevin Beattie", "Mick Mills"], 0,
     "Roger Osborne, a local lad, in the 77th minute. He collapsed with emotion and exhaustion and was substituted a minute later.",
     "Cup final goalscorers become immortal at small clubs. Osborne is Ipswich's.",
     "say", "\"Roger Osborne. Scored the cup final winner and had to be taken off in tears.\""),
    (1, "Ipswich is in which county?", ["Suffolk", "Norfolk", "Essex", "Cambridgeshire"], 0,
     "Suffolk, on the east coast. Norwich, in Norfolk, is forty miles north and the source of all the trouble.",
     "Suffolk versus Norfolk is the whole East Anglian rivalry in two words.",
     "say", "\"Suffolk. Norwich are Norfolk. That's the whole derby.\""),
    (2, "What animal is on the Ipswich Town badge?", ["A horse", "A canary", "A lion", "A tractor"], 0,
     "A Suffolk Punch, the county's heavy farm horse, standing over a football. Norwich have a canary; Ipswich chose a horse.",
     "Badge stories are a low-cost way to show attention.",
     "say", "\"It's a Suffolk Punch on the badge. A farm horse. They lean into it.\""),
    (3, "Ipswich were founder members of the Premier League in which season?", ["1992-93", "1994-95", "1996-97", "2000-01"], 0,
     "1992-93, having won the second tier the previous year. They were relegated in 1995 after a 9-0 defeat at Manchester United.",
     "Being there at the start of the Premier League is a small badge of honour.",
     "impress", "\"Ipswich were in the very first Premier League season. Then lost 9-0 at Old Trafford and went down.\""),
    (3, "In which position did Ipswich finish in 2001, their best Premier League season?", ["Third", "Fifth", "Seventh", "Ninth"], 1,
     "Fifth, in their first season back up, under George Burley, and into the UEFA Cup. Burley was voted manager of the year.",
     "Fifth in the Premier League is the high-water mark fans mention when hopes are up.",
     "say", "\"They finished fifth in 2001. Above Chelsea. Different times.\""),
    (3, "What tongue-in-cheek name is given to the Ipswich v Norwich derby?", ["The Old Farm derby", "The Turnip derby", "The Broads derby", "The A140 derby"], 0,
     "The Old Farm derby, a joke on Glasgow's Old Firm. The A140 is the road between the two towns, and also gets a mention.",
     "A pun both sets of fans use is rare. This is one.",
     "say", "\"Old Farm derby. Even the fans call it that.\""),
    (2, "In which year were Ipswich relegated after a single season back in the Premier League?", ["2023", "2024", "2025", "2026"], 2,
     "2025, alongside Leicester and Southampton: all three promoted clubs went straight back down. Ipswich then bounced back again the following year.",
     "The yo-yo is the story of the club's mid-2020s. He will have views on which was worse.",
     "ask", "Ask him: \"Was going down in 2025 worse because of how good 2024 had felt?\""),
    (2, "In which year did Ipswich return to the Premier League after their 2025 relegation?", ["2025", "2026", "2027", "2028"], 1,
     "2026, as Championship runners-up with 84 points. One season down, straight back up.",
     "The bounce back is the fresh good news. Lead with it.",
     "say", "\"Down in 2025, back in 2026. They didn't hang about.\""),
]

LEEDS = [
    (1, "What is Leeds United's home ground called?", ["Elland Road", "Headingley", "Roundhay Park", "Thorp Arch"], 0,
     "Elland Road, since 1919, famous for being loud and hostile to visitors. Leeds fans consider that a compliment.",
     "'Elland Road under the lights' is a phrase he will say with feeling.",
     "say", "\"Elland Road on a night game. Properly hostile.\""),
    (1, "What colour do Leeds United play in?", ["All white", "Yellow and blue", "Blue and white", "White and green"], 0,
     "All white, since 1961, when manager Don Revie copied Real Madrid's kit hoping some of the glamour would rub off. It did.",
     "The all-white kit has a reason, and the reason is a great manager's ambition.",
     "impress", "\"Leeds play in white because Revie copied Real Madrid in 1961. It worked.\""),
    (2, "In which year was Leeds United founded?", ["1904", "1919", "1925", "1946"], 1,
     "1919, after the previous club, Leeds City, was expelled from the league for illegal payments to players. A fresh start with a new name.",
     "A club born from a scandal is a good origin story.",
     "impress", "\"Leeds United only exist because the old club got kicked out of the league for paying players illegally.\""),
    (2, "Which manager built the great Leeds team of the 1960s and 70s?", ["Don Revie", "Brian Clough", "Howard Wilkinson", "Jimmy Armfield"], 0,
     "Don Revie, manager 1961 to 1974: two league titles, an FA Cup and a reputation for being brilliant, ruthless and hard to like. Left to manage England.",
     "Revie is the founding father of modern Leeds. His statue stands outside the ground.",
     "ask", "Ask him: \"Was Revie's Leeds dirty, or just better than everyone and hated for it?\""),
    (2, "In which year did Leeds win the league title, the third in the club's history?", ["1974", "1985", "1992", "2001"], 2,
     "1992, the final season before the Premier League began. Three titles in total: 1969, 1974 and 1992.",
     "Leeds fans point out they were champions the year before the Premier League began. A favourite line.",
     "say", "\"Leeds were the champions the year before the Premier League started. They like reminding people.\""),
    (2, "Who managed Leeds to the 1992 title?", ["Howard Wilkinson", "Don Revie", "David O'Leary", "George Graham"], 0,
     "Howard Wilkinson, known as Sergeant Wilko. No English manager has won the top division since.",
     "No English manager has won the league since. It comes up whenever an English manager gets a big job.",
     "impress", "\"No English manager has won the league since Howard Wilkinson at Leeds in 1992.\""),
    (2, "In which year did Leeds reach the semi-finals of the Champions League?", ["1975", "1992", "2001", "2010"], 2,
     "2001, losing to Valencia, with a young team that had beaten Deportivo and drawn with Barcelona. Then the money ran out.",
     "The 2001 run is the peak before the fall. Fans tell both halves together.",
     "ask", "Ask him: \"Do you remember the 2001 Champions League team? Before it all went wrong?\""),
    (3, "By which year had Leeds fallen to League One, the third tier, after their financial collapse?", ["2004", "2007", "2010", "2012"], 1,
     "2007, three years after leaving the Premier League. They had spent money they expected from the Champions League and it stopped coming. The phrase is 'doing a Leeds'.",
     "'Doing a Leeds' is a warning used about every over-spending club. He will know the phrase.",
     "impress", "\"'Doing a Leeds' means spending money you haven't got. They went from a Champions League semi to the third tier in six years.\""),
    (2, "Which Argentine manager took Leeds back to the Premier League in 2020?", ["Marcelo Bielsa", "Mauricio Pochettino", "Diego Simeone", "Jorge Sampaoli"], 0,
     "Marcelo Bielsa, who sat on a blue bucket, ran the players into the ground and was adored. He ended sixteen years out of the top flight.",
     "Bielsa is a cult figure across football. Leeds fans think he is theirs.",
     "ask", "Ask him: \"Bielsa: greatest thing that ever happened to Leeds, or did he burn them out?\""),
    (2, "Who are Leeds United's fiercest rivals?", ["Manchester United", "Sheffield United", "Bradford City", "Huddersfield Town"], 0,
     "Manchester United, in the Roses rivalry: Yorkshire's white rose against Lancashire's red, from a war five hundred years before football.",
     "A derby with a medieval origin is the one to know.",
     "impress", "\"Leeds and Man United is the Roses rivalry. It goes back to an actual war in the 1400s.\""),
    (3, "Which Leeds captain of the Revie era has a statue outside Elland Road?", ["Billy Bremner", "Jack Charlton", "Norman Hunter", "Johnny Giles"], 0,
     "Billy Bremner, the small, red-haired Scottish midfielder who was afraid of nobody. Captain of the 1969 and 1974 title teams.",
     "The statue is the meeting point outside the ground. Knowing who it is helps.",
     "say", "\"That's Billy Bremner. Revie's captain. Tiny and terrifying.\""),
    (2, "What is Leeds United's nickname?", ["The Whites", "The Lions", "The Yorkshire Terriers", "The Loiners"], 0,
     "The Whites, for the kit. Older fans also say the Peacocks, after a pub that stood near the ground.",
     "Two nicknames, one obvious and one obscure. The obscure one impresses.",
     "impress", "\"They used to be the Peacocks, after a pub by the ground. Nobody says it now.\""),
    (2, "Why do Leeds play in all white?", ["Revie copied Real Madrid", "It was cheaper to wash", "A sponsor demanded it", "To match the Yorkshire rose"], 0,
     "Don Revie changed the kit in 1961 to copy Real Madrid, the best team in Europe, hoping his players would carry themselves like champions.",
     "The kit as a psychological trick is a great story about ambition.",
     "say", "\"Revie put them in white to make them feel like Real Madrid. And then they won the league.\""),
    (3, "Leeds lost the 1975 European Cup final to which club?", ["Bayern Munich", "Ajax", "Juventus", "Benfica"], 0,
     "Bayern Munich, 2-0 in Paris, after two Leeds goals were disallowed. Fans rioted and the club was banned from Europe. The referee's name is a swear word in Leeds.",
     "The 1975 final is the great Leeds grievance. Knowing it earns you a long, passionate story.",
     "ask", "Ask him: \"Paris 1975. Were Leeds robbed, honestly?\""),
    (3, "Leeds returned to the Premier League in 2025 as Championship champions with how many points?", ["90", "95", "100", "106"], 2,
     "One hundred, level with Burnley, decided on the final day. Both went up, and Leeds took the title on goal difference.",
     "A hundred points is a number he will quote. Have it ready.",
     "say", "\"A hundred points and it came down to goal difference on the final day.\""),
    (2, "What is the name of the Leeds United club song?", ["Marching On Together", "Glory Glory Leeds", "Yorkshire Forever", "White Rose Rising"], 0,
     "Marching On Together, released as a single for the 1972 FA Cup final and sung at every game since. The words are on the wall outside the ground.",
     "He knows every word. You can know the title.",
     "say", "\"Marching On Together. That's the one they all sing.\""),
    (3, "Leeds won the FA Cup in 1972 by beating which club?", ["Arsenal", "Chelsea", "Liverpool", "Sunderland"], 0,
     "Arsenal, 1-0 at Wembley, with an Allan Clarke diving header. Their one FA Cup.",
     "One FA Cup in a century is a stat that surprises people about a club this big.",
     "impress", "\"Leeds have won the FA Cup once. 1972. For a club that size.\""),
    (1, "Leeds is in which county?", ["Yorkshire", "Lancashire", "Derbyshire", "Nottinghamshire"], 0,
     "West Yorkshire. The white rose on the badge is the county's symbol, and the rivalry with Manchester is Yorkshire against Lancashire.",
     "Yorkshire is not a county to Yorkshire people; it is a nationality. Get it right.",
     "say", "\"Yorkshire. Don't say 'up north' to a Leeds fan, say Yorkshire.\""),
    (3, "Which player did Leeds sell to Manchester United in 1992, a deal they came to regret?", ["Eric Cantona", "Gary McAllister", "Lee Chapman", "David Batty"], 0,
     "Eric Cantona, for about £1.2 million, months after helping Leeds win the title. He won four titles in five years at Old Trafford.",
     "Selling Cantona to your rival is the transfer Leeds fans wince at.",
     "impress", "\"Leeds sold Cantona to Man United for about a million. Then he won four titles for them.\""),
    (2, "Which German manager led Leeds to promotion in 2025?", ["Daniel Farke", "Jesse Marsch", "Thomas Tuchel", "Ralf Rangnick"], 0,
     "Daniel Farke, who had already taken Norwich up twice. He knows the Championship better than anyone in the game.",
     "Farke is the name on the 2025 promotion. Fans will judge him on what came next.",
     "ask", "Ask him: \"Is Farke a Premier League manager, or just very good at the Championship?\""),
]

LIVERPOOL = [
    (1, "What is Liverpool's home ground called?", ["Anfield", "Goodison Park", "Stanley Park", "The Kop"], 0,
     "Anfield, since 1892. It was Everton's ground first, until a rent row saw Everton leave and the landlord start a new club to play there.",
     "Liverpool exist because of a landlord dispute. Evertonians love telling this; get in first.",
     "impress", "\"Liverpool were founded because Everton fell out with their landlord over rent at Anfield.\""),
    (1, "Which song do Liverpool fans sing before every home match?", ["You'll Never Walk Alone", "Blue Moon", "Marching On Together", "Glory Glory"], 0,
     "You'll Never Walk Alone, a show tune from the musical Carousel, adopted in 1963 after a Liverpool band had a hit with it. The words are on the gates at Anfield.",
     "The best-known football song in the world, and it started as a Broadway ballad.",
     "impress", "\"You'll Never Walk Alone is from a musical. Carousel, 1945. They took it from a pop cover.\""),
    (2, "Liverpool's league title in 2025 was the club's how-manyth?", ["Eighteenth", "Nineteenth", "Twentieth", "Twenty-first"], 2,
     "Twentieth, drawing level with Manchester United. The nineteenth had come in 2020, after a thirty-year wait.",
     "Twenty versus United's twenty is the count he keeps. Know the number.",
     "say", "\"Twenty titles. Level with United. That's the argument at every family dinner.\""),
    (2, "How many times had Liverpool won the European Cup or Champions League by 2025?", ["Three", "Four", "Five", "Six"], 3,
     "Six: 1977, 1978, 1981, 1984, 2005 and 2019. No other English club has as many, which Liverpool fans mention regularly.",
     "Six European Cups is the number that ends arguments with United fans.",
     "say", "\"Six European Cups. Number six is on the shirt collar, you know.\""),
    (1, "Liverpool came back from 3-0 down to win the 2005 Champions League final against which club?", ["AC Milan", "Juventus", "Barcelona", "Real Madrid"], 0,
     "AC Milan, in Istanbul: 3-0 down at half-time, 3-3 after six minutes of the second half, won on penalties. The miracle of Istanbul.",
     "Istanbul is the greatest comeback in a European final. Every Liverpool fan can tell you where they were.",
     "ask", "Ask him: \"Istanbul 2005. Where were you at half-time?\""),
    (1, "Which German managed Liverpool from 2015 to 2024?", ["Jürgen Klopp", "Thomas Tuchel", "Ralf Rangnick", "Julian Nagelsmann"], 0,
     "Jürgen Klopp: hugs, heavy-metal football, a Champions League and the first league title in thirty years. He left as the best-loved manager since Shankly.",
     "Klopp is the manager she has probably heard of even without football. He is the reference point.",
     "say", "\"Klopp. Nine years, everyone loved him, then he just left on his own terms.\""),
    (2, "In which year did Liverpool end their thirty-year wait for a league title?", ["2014", "2019", "2020", "2022"], 2,
     "2020, during the pandemic, with seven games to spare and an empty Anfield. Fans celebrated outside the ground anyway.",
     "Thirty years of waiting then no crowd to celebrate is the bittersweet note in the story.",
     "ask", "Ask him: \"Winning it in lockdown with no fans in. Did it feel real?\""),
    (3, "Who is Liverpool's top scorer in the club's history?", ["Ian Rush", "Roger Hunt", "Mohamed Salah", "Steven Gerrard"], 0,
     "Ian Rush, 346 goals across two spells in the 1980s and 90s, a Welsh striker with a moustache and a knack for scoring against Everton.",
     "Rush is the name older fans reach for. Salah is the one chasing him.",
     "impress", "\"Ian Rush, 346 goals. Salah's been chasing that for years.\""),
    (1, "Which two clubs are Liverpool's main rivals?", ["Everton and Manchester United", "Everton and Leeds", "Manchester City and Chelsea", "Arsenal and Spurs"], 0,
     "Everton, across the park, in the Merseyside derby; and Manchester United, thirty miles away, in the biggest rivalry in English football.",
     "Two rivals, two different kinds of hate. Knowing which is which matters.",
     "say", "\"Everton's the local one. United's the real one.\""),
    (3, "The Kop, Anfield's famous stand, is named after what?", ["A hill in the Boer War", "A Liverpool docker", "A shipyard", "A Norwegian word for stand"], 0,
     "Spion Kop, a hill in South Africa where many soldiers from Liverpool died in a battle in 1900. The steep terrace reminded people of it.",
     "The name has a war behind it. That is worth knowing before you shout it.",
     "impress", "\"The Kop's named after a hill in the Boer War where Liverpool soldiers died.\""),
    (2, "Which Scot managed Liverpool from 1959 to 1974 and has a statue outside Anfield?", ["Bill Shankly", "Bob Paisley", "Kenny Dalglish", "Matt Busby"], 0,
     "Bill Shankly, who took them up from the second division and built the modern club. The gates at Anfield are named after him, and half of football's best quotes are his.",
     "Shankly quotes get used at every Liverpool occasion. Know the man behind them.",
     "say", "\"Shankly said football's more important than life and death. He was joking. Mostly.\""),
    (3, "Which Liverpool manager won three European Cups between 1977 and 1981?", ["Bob Paisley", "Bill Shankly", "Joe Fagan", "Kenny Dalglish"], 0,
     "Bob Paisley, Shankly's quiet assistant, who turned out to be even more successful: six league titles and three European Cups in nine years.",
     "The quiet man who out-won the legend is a lovely twist to know.",
     "impress", "\"Paisley won more than Shankly. Three European Cups. Nobody talks about him because he didn't do quotes.\""),
    (3, "Steven Gerrard's long-range equaliser in the 2006 FA Cup final came against which club?", ["West Ham", "Chelsea", "Arsenal", "Cardiff"], 0,
     "West Ham, in the final minute, from 35 yards, with cramp. Liverpool won on penalties. People call it the Gerrard final.",
     "A final named after one player tells you what he meant to them.",
     "say", "\"The Gerrard final. Thirty-five yards, last minute, cramp in both legs.\""),
    (2, "Mohamed Salah joined Liverpool in 2017 from which club?", ["Roma", "Chelsea", "Fiorentina", "Basel"], 0,
     "Roma, for about £37 million, after Chelsea had given up on him. He scored 44 goals in his first season.",
     "Chelsea letting Salah go is the transfer regret rivals enjoy raising.",
     "ask", "Ask him: \"Is Salah the best signing Liverpool have ever made?\""),
    (3, "Virgil van Dijk joined Liverpool in 2018 from which club?", ["Southampton", "Celtic", "Ajax", "Tottenham"], 0,
     "Southampton, for £75 million, a world record for a defender at the time. Liverpool reached the next two Champions League finals with him.",
     "Van Dijk changed Liverpool overnight. The fee looked mad and then looked cheap.",
     "say", "\"Seventy-five million for a defender looked mad. Then they won everything.\""),
    (2, "Who succeeded Jürgen Klopp as Liverpool manager in 2024 and won the title in his first season?", ["Arne Slot", "Xabi Alonso", "Roberto De Zerbi", "Ruben Amorim"], 0,
     "Arne Slot, from Feyenoord. Calm where Klopp was loud, and champion within a year.",
     "Following a legend and winning the league immediately is rare. Slot did it.",
     "ask", "Ask him: \"Did Slot win that title, or was it Klopp's team?\""),
    (2, "Who did Liverpool beat in the 2019 Champions League final?", ["Tottenham Hotspur", "Manchester City", "Barcelona", "Real Madrid"], 0,
     "Tottenham, 2-0 in Madrid, with a penalty in the second minute. Their sixth European Cup, a year after losing the final to Real Madrid.",
     "An all-English final is the kind of night that gets relived. He will remember the penalty.",
     "say", "\"Madrid 2019. Penalty in the second minute and that was that.\""),
    (3, "In the 2019 comeback against Barcelona, who took the quick corner for the winning goal?", ["Trent Alexander-Arnold", "Andy Robertson", "Xherdan Shaqiri", "James Milner"], 0,
     "Trent Alexander-Arnold, a local lad, while Barcelona's defenders were not looking. Divock Origi tapped it in to complete a 4-0 win from 3-0 down.",
     "'Corner taken quickly' is a phrase Liverpool fans say as a catchphrase. This is why.",
     "impress", "\"'Corner taken quickly, Origi.' That's the commentary from the Barcelona game. Fans quote it.\""),
    (1, "What bird is on the Liverpool badge?", ["The liver bird", "An eagle", "A magpie", "A cockerel"], 0,
     "The liver bird, the city's symbol, a cormorant with a sprig of seaweed in its beak. It is on the town hall and the Liver Building too.",
     "Reading the badge is knowing the city.",
     "say", "\"That's the liver bird. It's all over the city, not just the club.\""),
    (3, "Kenny Dalglish joined Liverpool in 1977 from which club?", ["Celtic", "Rangers", "Aberdeen", "Hibernian"], 0,
     "Celtic, for £440,000, to replace Kevin Keegan. He became the club's greatest player, then its manager, and won the league in both roles.",
     "King Kenny is the name older fans say with reverence. He has a stand named after him.",
     "say", "\"King Kenny. Player, manager, won the league as both. There's a stand named after him.\""),
]

MAN_CITY = [
    (1, "What is Manchester City's home ground called?", ["Etihad Stadium", "Maine Road", "Old Trafford", "The City of Manchester Arena"], 0,
     "The Etihad Stadium, built for the 2002 Commonwealth Games and converted for football. Officially the City of Manchester Stadium.",
     "An athletics stadium turned football ground is a good bit of context.",
     "say", "\"The Etihad was built for the Commonwealth Games. City moved in after.\""),
    (2, "Where did Manchester City play before moving to the Etihad in 2003?", ["Maine Road", "Hyde Road", "Old Trafford", "Belle Vue"], 0,
     "Maine Road, in Moss Side, from 1923 to 2003. Once the biggest club ground in England, with the biggest crowd ever for a league match, 84,000, in 1934.",
     "Older City fans get misty about Maine Road. It is where the club's soul lived before the money.",
     "ask", "Ask him: \"Did you ever go to Maine Road? Everyone says it was a different club then.\""),
    (1, "What colour are Manchester City's home shirts?", ["Sky blue", "Red", "Navy blue", "White"], 0,
     "Sky blue, since the 1890s. The fans' song is Blue Moon, sung slowly and sadly, which suited the club for much of its history.",
     "Blue Moon before every game is one of football's odder rituals. Knowing why it is sad helps.",
     "say", "\"Blue Moon. They sing it slow, from when City were rubbish. It stuck.\""),
    (1, "Which Spanish manager took charge of Manchester City in 2016?", ["Pep Guardiola", "Manuel Pellegrini", "Roberto Mancini", "Mikel Arteta"], 0,
     "Pep Guardiola, who had won everything at Barcelona and Bayern. Six league titles in his first eight seasons at City and a treble in 2023.",
     "Guardiola is the manager every other manager is compared to. His City years are the benchmark.",
     "ask", "Ask him: \"Is Guardiola the best manager there's ever been, or did the money do it?\""),
    (2, "In which year was Manchester City bought by Abu Dhabi's Sheikh Mansour?", ["2003", "2008", "2012", "2016"], 1,
     "2008, on the final day of the transfer window. They signed Robinho the same afternoon and the modern City began.",
     "Everything about City splits into before and after 2008.",
     "say", "\"2008. Before that they were a joke club. After that, well.\""),
    (2, "In which year did Manchester City win their first Premier League title?", ["2010", "2012", "2014", "2018"], 1,
     "2012, with Agüero's goal in the final seconds of the final game against QPR, to beat United on goal difference. Their first title since 1968.",
     "The Agüero moment is the one every football fan remembers, City or not.",
     "say", "\"Agüerooo. Last kick of the season. Even neutrals remember where they were.\""),
    (2, "In which year did Manchester City win the treble of league, FA Cup and Champions League?", ["2019", "2021", "2023", "2024"], 2,
     "2023, only the second English club to do it after Manchester United in 1999. The Champions League final was won 1-0 against Inter.",
     "The treble is the peak of the Guardiola era. City fans will point to it forever.",
     "say", "\"2023 treble. Only United had done it before, which City enjoyed.\""),
    (2, "Who did Manchester City beat in the 2023 Champions League final?", ["Inter Milan", "Real Madrid", "Bayern Munich", "Chelsea"], 0,
     "Inter Milan, 1-0 in Istanbul, with a goal from Rodri. Their first European Cup, after years of trying.",
     "The first European Cup is the trophy City fans waited longest for.",
     "say", "\"Rodri scored the goal in Istanbul. First European Cup, finally.\""),
    (2, "How many goals did Erling Haaland score in the 2022-23 Premier League season?", ["30", "34", "36", "40"], 2,
     "Thirty-six, in his first season in England, beating a mark that had stood since 1994. Also 52 in all competitions.",
     "Thirty-six is the number he will quote when defending Haaland in any argument.",
     "say", "\"Thirty-six league goals in his first season. In England. At 22.\""),
    (2, "In 2024 City became the first English club to win how many consecutive league titles?", ["Three", "Four", "Five", "Six"], 1,
     "Four in a row, 2021 to 2024. Nobody had done more than three before.",
     "Four in a row is the argument for City being the best team England has produced.",
     "impress", "\"Four titles in a row. Nobody had ever done that in England.\""),
    (1, "Who are Manchester City's rivals in the Manchester derby?", ["Manchester United", "Liverpool", "Bolton", "Stockport"], 0,
     "Manchester United, who called City the noisy neighbours when the money arrived. The derby decides who owns the city that week.",
     "Local pride is on the line in the derby, and City fans have enjoyed the recent decade.",
     "say", "\"The noisy neighbours. Ferguson's line. Aged badly for him.\""),
    (3, "In the 1999 play-off final against Gillingham, who scored City's 95th-minute equaliser?", ["Paul Dickov", "Shaun Goater", "Kevin Horlock", "Nicky Weaver"], 0,
     "Paul Dickov, at Wembley, with City 2-0 down and in the third tier. They won on penalties. Fans call it the biggest goal in the club's history.",
     "City in the third division in 1999 is the fact that makes the modern club astonishing.",
     "impress", "\"City were in the third division in 1999. Twenty-five years later they won the treble.\""),
    (3, "In which year did Manchester City win the European Cup Winners' Cup?", ["1956", "1970", "1976", "1999"], 1,
     "1970, beating Górnik Zabrze of Poland in Vienna. Their one European trophy until 2023.",
     "City fans of a certain age had one European trophy to cling to for fifty years. This is it.",
     "impress", "\"City won a European trophy in 1970 and then nothing in Europe until 2023.\""),
    (3, "The Colin Bell Stand at the Etihad is named after a 1960s midfielder nicknamed what?", ["Nijinsky", "The King", "Bell Boy", "The Engine"], 0,
     "Nijinsky, after a famous racehorse, because he could run all day. A stand is named after him, the sign of a true club great.",
     "A footballer nicknamed after a horse is a fact worth having on hand.",
     "impress", "\"Colin Bell was nicknamed after a racehorse. Nijinsky. Because he ran all day.\""),
    (3, "Which Spanish playmaker, nicknamed El Mago, has a statue outside the Etihad?", ["David Silva", "Sergio Agüero", "Vincent Kompany", "Rodri"], 0,
     "David Silva, the magician, ten seasons and four titles, with a statue alongside Agüero's and Kompany's. Small, left-footed, impossible to tackle.",
     "Three statues outside the ground; knowing all three names is the full set.",
     "say", "\"Silva, Agüero, Kompany. The three statues. That's the team that started it.\""),
    (2, "In which year did Manchester City beat Manchester United 6-1 at Old Trafford?", ["2008", "2011", "2014", "2019"], 1,
     "2011, on the way to their first title. Balotelli scored and lifted his shirt to reveal the words 'Why always me?'",
     "6-1 at Old Trafford is the scoreline City fans bring to every derby argument.",
     "say", "\"Six-one at Old Trafford. 'Why always me?' That whole day was ridiculous.\""),
    (2, "What is Manchester City's nickname?", ["The Citizens", "The Blues Brothers", "The Sky Devils", "The Mancs"], 0,
     "The Citizens, or the Sky Blues. Fans just say City. Cityzens, with a z, is what the club calls its members.",
     "Nicknames are how fans refer to their own. Get this one right and he notices.",
     "say", "\"City. Nobody actually says the Citizens.\""),
    (2, "The Etihad Stadium is on which side of Manchester?", ["East", "West", "North", "South"], 0,
     "East Manchester, in a once-industrial area rebuilt around the stadium, the training campus and, more recently, an arena.",
     "Knowing where the ground is turns a match into a day out.",
     "say", "\"It's in east Manchester. They've basically rebuilt the whole area around it.\""),
    (3, "Which Chilean manager won the Premier League with Manchester City in 2014?", ["Manuel Pellegrini", "Roberto Mancini", "Mark Hughes", "Sven-Göran Eriksson"], 0,
     "Manuel Pellegrini, the first manager from outside Europe to win the Premier League. Quiet, polite, and replaced by Guardiola two years later.",
     "The manager between Mancini and Guardiola is the one everyone forgets. Remembering him is the trick.",
     "impress", "\"Pellegrini won City a title in 2014 and nobody ever mentions him. First non-European to win it.\""),
    (3, "In which year did Manchester City win their first league title?", ["1904", "1937", "1968", "2012"], 1,
     "1937. They were relegated the very next season while scoring more goals than anyone in the division. 'Typical City', fans said for decades.",
     "'Typical City' is what older fans say about any self-inflicted disaster. This is where it comes from.",
     "impress", "\"City won the league in 1937 and got relegated the next year. That's where 'typical City' comes from.\""),
]

PACKS = [
    ("club-hull", "Hull City", HULL),
    ("club-ipswich", "Ipswich Town", IPSWICH),
    ("club-leeds", "Leeds United", LEEDS),
    ("club-liverpool", "Liverpool", LIVERPOOL),
    ("club-man-city", "Manchester City", MAN_CITY),
]
