# His Club packs: Chelsea, Coventry City, Crystal Palace, Everton, Fulham.

CHELSEA = [
    (1, "What is Chelsea's home ground called?", ["Stamford Bridge", "Craven Cottage", "Loftus Road", "The Bridge Arena"], 0, "Stamford Bridge, in Fulham. The ground existed before the club, which was founded to fill it."),
    (1, "In which year was Chelsea founded?", ["1886", "1899", "1905", "1919"], 2, "1905, in a pub called the Rising Sun opposite the ground. It is now called the Butcher's Hook."),
    (1, "What colour are Chelsea's home shirts?", ["Royal blue", "Sky blue", "Red", "White"], 0, "Royal blue, since the early 1960s. Before that a lighter Eton blue."),
    (2, "Which Russian billionaire owned Chelsea from 2003 to 2022?", ["Roman Abramovich", "Alisher Usmanov", "Dmitry Rybolovlev", "Mikhail Prokhorov"], 0, "Roman Abramovich. Nineteen trophies in nineteen years, and a lot of sacked managers."),
    (2, "In which year did Chelsea first win the Champions League?", ["2008", "2012", "2016", "2021"], 1, "2012, in Munich, on penalties against Bayern in their own stadium."),
    (2, "Who did Chelsea beat in the 2021 Champions League final?", ["Manchester City", "Real Madrid", "Bayern Munich", "Paris Saint-Germain"], 0, "Manchester City, 1-0 in Porto. Kai Havertz scored the goal."),
    (2, "Who is Chelsea's all-time record goalscorer?", ["Didier Drogba", "Frank Lampard", "Jimmy Greaves", "Bobby Tambling"], 1, "Frank Lampard, 211 goals. He was a midfielder, which makes it more remarkable."),
    (2, "Which manager won Chelsea back-to-back league titles in 2005 and 2006?", ["Carlo Ancelotti", "José Mourinho", "Claudio Ranieri", "Antonio Conte"], 1, "José Mourinho, the self-styled Special One, in his first spell. He came back in 2013 and won another."),
    (3, "In which year did Chelsea win their first league title?", ["1905", "1955", "1970", "2005"], 1, "1955, exactly fifty years before the second one. Chelsea fans waited a long time."),
    (2, "Which centre-back captained Chelsea for over a decade and was known as Captain, Leader, Legend?", ["John Terry", "Frank Lampard", "Marcel Desailly", "Gary Cahill"], 0, "John Terry, from 2004 to 2017. Five league titles as captain."),
    (2, "Which Ivorian striker scored in four FA Cup finals for Chelsea?", ["Didier Drogba", "Salomon Kalou", "Nicolas Anelka", "Demba Ba"], 0, "Didier Drogba, who scored in every final he played in for Chelsea. A man for the big day."),
    (3, "The Shed End is a stand at which ground?", ["Stamford Bridge", "Craven Cottage", "Upton Park", "The Den"], 0, "Stamford Bridge. The old terrace behind the south goal, where the loudest fans stood."),
    (2, "Which Italian manager led Chelsea to the league and cup double in 2010, scoring 103 league goals?", ["Carlo Ancelotti", "Antonio Conte", "Roberto Di Matteo", "Gianluca Vialli"], 0, "Carlo Ancelotti. The 103 goals were a Premier League record at the time."),
    (3, "Antonio Conte's 2017 title-winning Chelsea side was famous for switching to which formation?", ["3-4-3", "4-4-2", "4-2-3-1", "5-3-2"], 0, "3-4-3, after a bad start. They won thirteen league games in a row once he changed it."),
    (3, "Which manager led Chelsea Women to a run of Women's Super League titles before leaving in 2024?", ["Emma Hayes", "Sarina Wiegman", "Casey Stoney", "Hope Powell"], 0, "Emma Hayes, seven league titles in twelve years, then off to coach the United States."),
    (1, "What is Chelsea's nickname?", ["The Blues", "The Pensioners", "The Lions", "The Bridgers"], 0, "The Blues. They were the Pensioners until the 1950s, after the Chelsea war veterans who lived nearby."),
    (3, "Which Chelsea goalkeeper saved a penalty in the shootout of the 2012 Champions League final?", ["Petr Čech", "Thibaut Courtois", "Carlo Cudicini", "Ross Turnbull"], 0, "Petr Čech, wearing his famous protective headguard. He also saved one in extra time."),
    (2, "Who are Chelsea's closest neighbours in West London?", ["Fulham", "Brentford", "QPR", "Watford"], 0, "Fulham. Craven Cottage is under two miles away along the river."),
    (3, "Which Italian became Chelsea's player-manager in 1998?", ["Gianluca Vialli", "Gianfranco Zola", "Roberto Di Matteo", "Ruud Gullit"], 0, "Gianluca Vialli, taking over from Ruud Gullit. He won the League Cup and the Cup Winners' Cup in his first months."),
    (2, "Eden Hazard left Chelsea in 2019 to join which club?", ["Real Madrid", "Barcelona", "Paris Saint-Germain", "Juventus"], 0, "Real Madrid, after seven seasons. He scored twice in his last game, the Europa League final."),
]

COVENTRY = [
    (1, "What is Coventry City's nickname?", ["The Sky Blues", "The Blues", "The Wasps", "The Bantams"], 0, "The Sky Blues, for the shirts. The fans have sung the Sky Blue Song since the 1960s."),
    (2, "In which year did Coventry City win the FA Cup?", ["1972", "1987", "1993", "2001"], 1, "1987, the club's only major trophy. The city partied for a week."),
    (2, "Who did Coventry beat in the 1987 FA Cup final?", ["Arsenal", "Tottenham Hotspur", "Everton", "Liverpool"], 1, "Tottenham, 3-2 after extra time. Spurs had never lost an FA Cup final before."),
    (1, "What colour are Coventry's home shirts?", ["Sky blue", "Royal blue", "Claret", "Green"], 0, "Sky blue, since 1962. Before that they had played in almost every colour going."),
    (2, "Coventry City were founded in 1883 under what name?", ["Singers FC", "Coventry Rovers", "Rootes Athletic", "Godiva United"], 0, "Singers FC, the works team of a bicycle factory. They became Coventry City in 1898."),
    (3, "Which manager introduced the sky blue kit and wrote the Sky Blue Song in the 1960s?", ["Jimmy Hill", "Noel Cantwell", "John Sillett", "Bobby Gould"], 0, "Jimmy Hill, later the presenter of Match of the Day. He took them from the third tier to the first."),
    (2, "What was Coventry's home ground from 1899 to 2005?", ["Highfield Road", "The Ricoh Arena", "Butts Park", "Coundon Road"], 0, "Highfield Road, close to the city centre. It is housing now."),
    (3, "Highfield Road became the first ground in England to be what, in 1981?", ["All-seater", "Floodlit", "Covered on all sides", "Artificial turf"], 0, "All-seater. Fans hated it and the terraces came back within a few years."),
    (2, "When Coventry went down in 2001, how many seasons in a row had they spent in the top flight?", ["14", "24", "34", "44"], 2, "34, since 1967. Only a handful of clubs had a longer unbroken run at the time."),
    (2, "What is the current name of the stadium Coventry moved into in 2005?", ["CBS Arena", "Ricoh Arena", "Highfield Road", "Sky Blue Park"], 0, "The CBS Arena, after a sponsor. It opened as the Ricoh Arena."),
    (3, "In 2013-14 Coventry played their home games in which town because of a rent dispute?", ["Northampton", "Leicester", "Birmingham", "Walsall"], 0, "Northampton, 35 miles away. Attendances collapsed and fans protested outside the empty Ricoh."),
    (3, "From 2019 to 2021 Coventry shared a ground with which club?", ["Birmingham City", "Aston Villa", "Leicester City", "Wolves"], 0, "Birmingham City, at St Andrew's. They won promotion to the Championship while playing there."),
    (2, "Which manager took Coventry from League Two to a Championship play-off final?", ["Mark Robins", "Tony Mowbray", "Steven Pressley", "Russell Slade"], 0, "Mark Robins, in charge from 2017 to 2024. He had scored for the club as a player."),
    (3, "Coventry lost the 2023 Championship play-off final on penalties to which club?", ["Luton Town", "Sunderland", "Middlesbrough", "Millwall"], 0, "Luton Town, after a 1-1 draw at Wembley. Luton went up to the Premier League instead."),
    (3, "Coventry's winning goal in the 1987 FA Cup final was an own goal by which Spurs player?", ["Gary Mabbutt", "Chris Waddle", "Glenn Hoddle", "Richard Gough"], 0, "Gary Mabbutt, whose knee deflected a cross into his own net in extra time. A Coventry fanzine was named after the knee."),
    (1, "Coventry is in which region of England?", ["The North East", "The West Midlands", "East Anglia", "The South West"], 1, "The West Midlands, about twenty miles from Birmingham."),
    (2, "Which club is Coventry's main Midlands rival?", ["Birmingham City", "Nottingham Forest", "Derby County", "Stoke City"], 0, "Birmingham City, with Leicester and Aston Villa not far behind in the dislike rankings."),
    (3, "Which striker shared the Premier League Golden Boot in 1998 with 18 goals for Coventry?", ["Dion Dublin", "Darren Huckerby", "Robbie Keane", "Peter Ndlovu"], 0, "Dion Dublin, level with Michael Owen and Chris Sutton. He later became a TV presenter."),
    (3, "Which former England midfielder was appointed Coventry manager in November 2024?", ["Frank Lampard", "Steven Gerrard", "Wayne Rooney", "Scott Parker"], 0, "Frank Lampard, his first job since a difficult spell back at Chelsea."),
    (3, "The Sky Blue Song is sung to the tune of what?", ["The Eton Boating Song", "Jerusalem", "Rule Britannia", "Land of Hope and Glory"], 0, "The Eton Boating Song. Jimmy Hill wrote the words with the club secretary in 1962."),
    (2, "In which division were Coventry playing in 2017-18, the season before their climb began?", ["The Championship", "League One", "League Two", "The National League"], 2, "League Two, the fourth tier, the lowest the club had ever been. They won the play-offs that May."),
]

CRYSTAL_PALACE = [
    (1, "What is Crystal Palace's home ground called?", ["Selhurst Park", "The Valley", "The Den", "Plough Lane"], 0, "Selhurst Park, in south London, since 1924."),
    (1, "What is Crystal Palace's nickname?", ["The Eagles", "The Glaziers", "The Palace Boys", "The Hawks"], 0, "The Eagles, since 1973. Before that they were the Glaziers, after the glass palace."),
    (2, "Who are Crystal Palace's fiercest rivals?", ["Millwall", "Brighton & Hove Albion", "Charlton", "Wimbledon"], 1, "Brighton, forty miles down the M23. Nobody outside the two clubs quite understands it."),
    (1, "What colours are Palace's home shirts?", ["Red and blue stripes", "Claret and blue", "White", "Yellow and green"], 0, "Red and blue vertical stripes, modelled on Barcelona in the 1970s."),
    (2, "In which year was Crystal Palace founded?", ["1861", "1885", "1905", "1920"], 2, "1905, by workers at the Crystal Palace exhibition building. They played in the grounds at first."),
    (2, "Which former England manager took charge of Palace in 2017, the club he supported as a boy?", ["Roy Hodgson", "Sam Allardyce", "Alan Pardew", "Steve McClaren"], 0, "Roy Hodgson, who grew up in Croydon and watched Palace from the terraces."),
    (2, "Palace lost FA Cup finals in 1990 and 2016 to the same club. Which?", ["Manchester United", "Liverpool", "Arsenal", "Chelsea"], 0, "Manchester United both times, the first after a replay and the second in extra time."),
    (2, "Crystal Palace won their first major trophy in 2025. Which one?", ["The FA Cup", "The League Cup", "The Premier League", "The Europa League"], 0, "The FA Cup, beating Manchester City 1-0 at Wembley. 120 years without a trophy, then that."),
    (3, "Who scored the winning goal in the 2025 FA Cup final?", ["Eberechi Eze", "Jean-Philippe Mateta", "Ismaïla Sarr", "Adam Wharton"], 0, "Eberechi Eze, in the first half. Palace's goalkeeper Dean Henderson then saved a penalty."),
    (3, "Wilfried Zaha, Palace's most-capped Premier League player, left in 2023 for which club?", ["Galatasaray", "Arsenal", "Marseille", "Fenerbahçe"], 0, "Galatasaray in Turkey, after two spells and over 450 games for Palace."),
    (3, "Which striker scored twice off the bench in the 1990 FA Cup final for Palace?", ["Ian Wright", "Mark Bright", "Andy Gray", "John Salako"], 0, "Ian Wright, playing with a broken leg that had only just healed. United won the replay."),
    (2, "What is Crystal Palace named after?", ["A glass exhibition building", "A royal residence", "A pub", "A jeweller"], 0, "The Crystal Palace, the huge glass hall from the Great Exhibition of 1851. It burned down in 1936."),
    (3, "What is the name of the real eagle that flew around Selhurst Park before matches?", ["Kayla", "Eddie", "Percy", "Storm"], 0, "Kayla, an American bald eagle, from 2010 until her retirement. Fans miss her."),
    (1, "Crystal Palace are from which part of London?", ["North", "East", "South", "West"], 2, "South London, around Croydon and Selhurst."),
    (3, "In 1989 Palace lost 9-0 to which club, the Premier League era's precursor to their worst defeat?", ["Liverpool", "Arsenal", "Everton", "Nottingham Forest"], 0, "Liverpool, at Anfield. Palace got revenge months later, beating them 4-3 in the FA Cup semi-final."),
    (3, "Who scored the extra-time winner in Palace's 4-3 FA Cup semi-final win over Liverpool in 1990?", ["Alan Pardew", "Ian Wright", "Mark Bright", "Geoff Thomas"], 0, "Alan Pardew, who later came back to manage the club and took them to the 2016 final."),
    (3, "Which former Arsenal captain managed Palace from 2021 to 2023?", ["Patrick Vieira", "Thierry Henry", "Tony Adams", "Cesc Fàbregas"], 0, "Patrick Vieira. He was sacked after a run of twelve games without a win."),
    (3, "The fan group behind the drums and flags at Selhurst Park is called what?", ["The Holmesdale Fanatics", "The Eagles Ultras", "The Selhurst Boys", "The Glaziers"], 0, "The Holmesdale Fanatics, named after the stand they fill. The best atmosphere in London, by some accounts."),
    (3, "Palace won promotion to the Premier League in 2004 by beating which club in the play-off final?", ["West Ham", "Sunderland", "Ipswich", "Wigan"], 0, "West Ham, 1-0 in Cardiff. Neil Shipperley scored the goal."),
    (2, "Which Austrian manager won the FA Cup with Palace in 2025?", ["Oliver Glasner", "Ralph Hasenhüttl", "Ralf Rangnick", "Adi Hütter"], 0, "Oliver Glasner, who had already won the Europa League with Eintracht Frankfurt."),
]

EVERTON = [
    (1, "Which ground was Everton's home from 1892 to 2025?", ["Goodison Park", "Anfield", "Stanley Park", "Bramley-Moore Dock"], 0, "Goodison Park, the first purpose-built football stadium in England. They moved to the docks in 2025."),
    (1, "What is Everton's nickname?", ["The Toffees", "The Blues", "The Reds", "The Scousers"], 0, "The Toffees, after a sweet shop near the ground. A Toffee Lady still throws sweets before games."),
    (1, "Who are Everton's rivals in the Merseyside derby?", ["Liverpool", "Tranmere Rovers", "Manchester United", "Wigan"], 0, "Liverpool. The friendly derby, they say, though it has had more red cards than any other fixture."),
    (2, "In which year was Everton founded?", ["1878", "1888", "1892", "1902"], 0, "1878, as St Domingo's, a church team. They changed the name a year later."),
    (1, "What colour are Everton's home shirts?", ["Royal blue", "Red", "White", "Sky blue"], 0, "Royal blue, since 1901. Before that they tried black with a red sash."),
    (2, "Who is Everton's all-time record goalscorer?", ["Dixie Dean", "Graeme Sharp", "Romelu Lukaku", "Bob Latchford"], 0, "Dixie Dean, 383 goals in the 1920s and 30s. There is a statue of him outside Goodison."),
    (3, "How many league goals did Dixie Dean score in the 1927-28 season, still a record?", ["40", "50", "60", "70"], 2, "Sixty, in 39 games. He got the last three in the final match to break the record."),
    (2, "In which year did Everton last win the league?", ["1970", "1985", "1987", "1995"], 2, "1987, under Howard Kendall. They also won it in 1985."),
    (2, "Who managed Everton through their 1980s glory years?", ["Howard Kendall", "Harry Catterick", "Joe Royle", "Colin Harvey"], 0, "Howard Kendall, two league titles, an FA Cup and a European trophy in three seasons."),
    (2, "Which European trophy did Everton win in 1985?", ["The Cup Winners' Cup", "The European Cup", "The UEFA Cup", "The Super Cup"], 0, "The Cup Winners' Cup, beating Rapid Vienna 3-1 in Rotterdam. Then English clubs were banned from Europe."),
    (2, "In which year did Everton win their last major trophy, the FA Cup?", ["1984", "1995", "2004", "2009"], 1, "1995, beating Manchester United 1-0 at Wembley. Paul Rideout scored."),
    (2, "Wayne Rooney made his first-team debut for which club?", ["Everton", "Manchester United", "Liverpool", "Derby"], 0, "Everton, aged sixteen. His first goal, against Arsenal, ended a 30-game unbeaten run."),
    (2, "Which Scottish manager had two spells at Everton, from 2002 to 2013 and again from 2025?", ["David Moyes", "Walter Smith", "Alex Ferguson", "Gordon Strachan"], 0, "David Moyes. He called Everton the People's Club on his first day and it stuck."),
    (3, "Which club has spent more seasons in England's top division than any other?", ["Everton", "Arsenal", "Liverpool", "Manchester United"], 0, "Everton, relegated only twice in their history, most recently in 1951."),
    (2, "Where does the nickname the Toffees come from?", ["A sweet shop", "The colour of the shirts", "A factory", "A brewery"], 0, "Mother Noblett's toffee shop near the ground, which sold Everton Mints to fans."),
    (2, "Everton's new stadium, opened in 2025, is built where?", ["Bramley-Moore Dock", "Stanley Park", "Kirkby", "Aintree"], 0, "Bramley-Moore Dock, on the Mersey waterfront north of the city centre."),
    (3, "Where did Everton play before moving to Goodison Park in 1892?", ["Anfield", "Stanley Park", "Priory Road", "Walton Breck"], 0, "Anfield. A row over rent saw Everton leave, and the landlord started a new club there: Liverpool."),
    (2, "Tim Cahill, famous for punching the corner flag when he scored, is from which country?", ["Australia", "New Zealand", "Ireland", "South Africa"], 0, "Australia. He scored 56 Everton goals and boxed a lot of corner flags."),
    (3, "In which position did Everton finish in 2005, earning a Champions League qualifying place?", ["Second", "Third", "Fourth", "Sixth"], 2, "Fourth, above Liverpool, who then won the Champions League that same season. Everton fans do not enjoy that detail."),
    (3, "The Gwladys Street End was the home fans' stand at which ground?", ["Goodison Park", "Anfield", "Villa Park", "Elland Road"], 0, "Goodison Park. The team always tried to attack towards it in the second half."),
]

FULHAM = [
    (1, "What is Fulham's home ground called?", ["Craven Cottage", "Stamford Bridge", "Loftus Road", "Griffin Park"], 0, "Craven Cottage, on the bank of the Thames. There really is a cottage in one corner."),
    (1, "What is Fulham's nickname?", ["The Cottagers", "The Whites", "The Lilywhites", "The Riversiders"], 0, "The Cottagers, after the cottage in the corner of the ground."),
    (2, "In which year was Fulham founded?", ["1879", "1889", "1899", "1905"], 0, "1879, as a church team. They are London's oldest professional club."),
    (1, "What colours are Fulham's home kit?", ["White shirts and black shorts", "Red and white", "Blue and white", "All white"], 0, "White shirts, black shorts. Simple and old-fashioned, like the ground."),
    (2, "Which Egyptian businessman owned Fulham from 1997 to 2013?", ["Mohamed Al-Fayed", "Roman Abramovich", "Naguib Sawiris", "Mohamed Mansour"], 0, "Mohamed Al-Fayed, who also owned Harrods. He took them from the third tier to the Premier League."),
    (3, "A statue of which pop star stood outside Craven Cottage from 2011 to 2014?", ["Michael Jackson", "George Michael", "Elton John", "Robbie Williams"], 0, "Michael Jackson, a friend of Al-Fayed who had watched one game there. Fans were baffled; the next owner removed it."),
    (2, "In which year did Fulham reach the Europa League final?", ["2006", "2010", "2014", "2018"], 1, "2010, losing 2-1 to Atlético Madrid in Hamburg after extra time. A remarkable run for a small club."),
    (2, "Who managed Fulham to the 2010 Europa League final?", ["Roy Hodgson", "Martin Jol", "Mark Hughes", "Chris Coleman"], 0, "Roy Hodgson, who was named manager of the year and then took the Liverpool job."),
    (2, "Which American businessman bought Fulham in 2013?", ["Shahid Khan", "Stan Kroenke", "John Henry", "Todd Boehly"], 0, "Shahid Khan, who also owns the Jacksonville Jaguars NFL team."),
    (1, "Craven Cottage sits beside which river?", ["The Thames", "The Lea", "The Wandle", "The Brent"], 0, "The Thames. Fans can watch the rowers go past before the game."),
    (3, "Fulham won promotion as champions of the second tier in 2001 under which French manager?", ["Jean Tigana", "Gérard Houllier", "Arsène Wenger", "Claude Puel"], 0, "Jean Tigana, with 101 points. It was Fulham's first time in the top flight since 1968."),
    (2, "Which Portuguese manager won the Championship with Fulham in 2022?", ["Marco Silva", "Nuno Espírito Santo", "José Mourinho", "André Villas-Boas"], 0, "Marco Silva, with Mitrović scoring goals for fun. Fulham finally stopped bouncing between divisions."),
    (2, "Who are Fulham's main London rivals?", ["Chelsea", "Arsenal", "Tottenham", "West Ham"], 0, "Chelsea, less than two miles away. Brentford and QPR are the other local grudges."),
    (3, "Johnny Haynes, the first footballer to be paid £100 a week, spent his whole career at which club?", ["Fulham", "Chelsea", "Arsenal", "Brentford"], 0, "Fulham, 1952 to 1970. A stand at Craven Cottage is named after him and he has a statue outside."),
    (3, "Which American scored the goal that knocked Juventus out of the 2010 Europa League for Fulham?", ["Clint Dempsey", "Brian McBride", "Carlos Bocanegra", "Eddie Johnson"], 0, "Clint Dempsey, a chipped finish to complete a comeback from 4-1 down on aggregate. Fulham's greatest night."),
    (1, "What stands in the corner of Fulham's ground?", ["A cottage", "A chapel", "A lighthouse", "A pub"], 0, "A cottage, built in 1905 as a pavilion. The players' families watch from its balcony."),
    (3, "Fulham's Riverside Stand rebuild, finished in 2024, includes what unusual feature?", ["A rooftop swimming pool", "A cinema", "A bowling alley", "A helipad"], 0, "A rooftop swimming pool, among other luxuries. Not every stand has one."),
    (2, "Which Fulham striker scored 43 goals in the 2021-22 Championship, a record for the division?", ["Aleksandar Mitrović", "Louis Saha", "Brian McBride", "Rodrigo Muniz"], 0, "Aleksandar Mitrović. He broke the record with games to spare and celebrated like every one was a final."),
    (1, "Fulham are from which part of London?", ["South-west", "North", "East", "South-east"], 0, "South-west London, in the borough of Hammersmith and Fulham."),
    (2, "What is Fulham's mascot called?", ["Billy the Badger", "Freddie the Fox", "Cottage Cat", "Terry the Thames Otter"], 0, "Billy the Badger, who was once sent off by a referee for breakdancing in the corner."),
]

PACKS = [
    ("club-chelsea", "Chelsea", CHELSEA),
    ("club-coventry", "Coventry City", COVENTRY),
    ("club-crystal-palace", "Crystal Palace", CRYSTAL_PALACE),
    ("club-everton", "Everton", EVERTON),
    ("club-fulham", "Fulham", FULHAM),
]
