# His Club packs: Arsenal, Aston Villa, Bournemouth, Brentford, Brighton.
# (difficulty, question, options, answer_index, explanation). Finished history only.

ARSENAL = [
    (1, "In which year was Arsenal founded?", ["1878", "1886", "1892", "1905"], 1, "1886, by workers at the Royal Arsenal munitions factory in Woolwich. Hence the cannon."),
    (1, "Where did Arsenal play before the Emirates Stadium?", ["White Hart Lane", "Highbury", "Wembley", "The Den"], 1, "Highbury, from 1913 to 2006. The old stands are flats now, with the pitch as a garden."),
    (1, "What is Arsenal's nickname?", ["The Gunners", "The Hammers", "The Blues", "The Irons"], 0, "The Gunners, for the armaments works. The fans are Gooners."),
    (2, "In which season did Arsenal go the whole league campaign unbeaten?", ["1997-98", "2001-02", "2003-04", "2007-08"], 2, "2003-04: 26 wins, 12 draws, no defeats. The team is known as the Invincibles."),
    (2, "Who managed the Invincibles?", ["George Graham", "Arsène Wenger", "Herbert Chapman", "Bertie Mee"], 1, "Arsène Wenger, in charge from 1996 to 2018. The longest-serving manager in the club's history."),
    (2, "In which part of London did Arsenal begin life?", ["Islington", "Woolwich", "Camden", "Hackney"], 1, "Woolwich, in south-east London. They moved north to Highbury in 1913, which Spurs have never forgiven."),
    (2, "Who is Arsenal's all-time record goalscorer?", ["Ian Wright", "Thierry Henry", "Dennis Bergkamp", "Cliff Bastin"], 1, "Thierry Henry, 228 goals across two spells. He has a statue outside the ground."),
    (1, "What colour are Arsenal's home shirts?", ["All red", "Red with white sleeves", "Red and white stripes", "White with red sleeves"], 1, "Red body, white sleeves, since 1933. Herbert Chapman's idea."),
    (2, "Which club has won the FA Cup more times than any other?", ["Manchester United", "Arsenal", "Liverpool", "Chelsea"], 1, "Arsenal, fourteen times, the last of them in 2020."),
    (2, "Who managed Arsenal to league titles in 1989 and 1991?", ["Terry Neill", "George Graham", "Don Howe", "Bruce Rioch"], 1, "George Graham, a former Arsenal player. Famous for a mean defence: 'one-nil to the Arsenal'."),
    (3, "Who scored the last-minute goal at Anfield that won Arsenal the 1989 title?", ["Alan Smith", "Michael Thomas", "Paul Merson", "David Rocastle"], 1, "Michael Thomas, in the final minute of the final game. Arsenal needed to win by two and did."),
    (2, "Who captained the Invincibles?", ["Tony Adams", "Patrick Vieira", "Thierry Henry", "Sol Campbell"], 1, "Patrick Vieira, the French midfielder who later became a manager."),
    (2, "Which goalkeeper played for Arsenal for most of the 1990s?", ["David Seaman", "Jens Lehmann", "Bob Wilson", "Pat Jennings"], 0, "David Seaman, ponytail and all. England's keeper for over a decade."),
    (1, "Who are Arsenal's biggest rivals?", ["Chelsea", "Tottenham Hotspur", "Manchester United", "West Ham"], 1, "Tottenham. The North London derby. Not a friendly fixture."),
    (2, "In which year did Arsenal move to the Emirates Stadium?", ["2002", "2004", "2006", "2008"], 2, "2006. The move was expensive, and the club went nine years without a trophy afterwards."),
    (3, "Which 1930s manager, who brought in the white sleeves, has a statue outside the Emirates?", ["Herbert Chapman", "Tom Whittaker", "George Allison", "Bertie Mee"], 0, "Herbert Chapman. He also got the local Tube station renamed Arsenal — the only one named after a club."),
    (2, "Tony Adams captained Arsenal to league titles in how many different decades?", ["One", "Two", "Three", "Four"], 2, "Three: 1989 and 1991, 1998, and 2002. Nobody else in England has done that."),
    (2, "In which year did Arsenal reach their only Champions League final?", ["1999", "2004", "2006", "2011"], 2, "2006, in Paris. They lost 2-1 to Barcelona after playing most of the game with ten men."),
    (1, "What is the name of Arsenal's dinosaur mascot?", ["Gunnersaurus", "Rex the Gunner", "Arsenalodon", "Highbury Harry"], 0, "Gunnersaurus Rex, since 1993. Briefly made redundant in 2020, then reinstated after an outcry."),
    (3, "Dennis Bergkamp's famous turn-and-finish goal in 2002 was against which club?", ["Newcastle", "Leicester", "Spurs", "Leeds"], 0, "Newcastle, at St James' Park. He flicked it one side of the defender and ran round the other."),
]

ASTON_VILLA = [
    (1, "What is Aston Villa's home ground called?", ["Villa Park", "St Andrew's", "The Hawthorns", "Molineux"], 0, "Villa Park, since 1897. The famous stand behind the goal is the Holte End."),
    (1, "What colours do Aston Villa play in?", ["Red and white", "Claret and blue", "Blue and white", "Green and black"], 1, "Claret and blue. West Ham and Burnley borrowed the combination from Villa."),
    (2, "In which year was Aston Villa founded?", ["1866", "1874", "1888", "1901"], 1, "1874, by members of a Wesleyan chapel cricket team who wanted something to do in winter."),
    (2, "In which year did Aston Villa win the European Cup?", ["1977", "1982", "1994", "1999"], 1, "1982, beating Bayern Munich 1-0 in Rotterdam. Only a handful of English clubs have won it."),
    (3, "Who scored the winning goal in the 1982 European Cup final?", ["Gary Shaw", "Peter Withe", "Tony Morley", "Dennis Mortimer"], 1, "Peter Withe, off his shin, from a Tony Morley cross. 'Withe' is painted on the goalpost at Villa Park."),
    (2, "Who are Aston Villa's city rivals?", ["Wolves", "Birmingham City", "West Brom", "Coventry"], 1, "Birmingham City. The Second City derby, whenever both are in the same division."),
    (2, "Aston Villa were founder members of which competition in 1888?", ["The FA Cup", "The Football League", "The Premier League", "The European Cup"], 1, "The Football League, the world's first. A Villa director, William McGregor, came up with the idea."),
    (2, "How many English league titles has Aston Villa won?", ["Three", "Five", "Seven", "Nine"], 2, "Seven, the last in 1981. Only a few clubs have more."),
    (2, "Who managed Aston Villa to the league title in 1981?", ["Ron Saunders", "Graham Taylor", "Ron Atkinson", "Brian Little"], 0, "Ron Saunders, who used just fourteen players all season. He left months before the European Cup win."),
    (3, "Which academy midfielder captained Villa before leaving in 2009 for Manchester City?", ["Gareth Barry", "Lee Hendrie", "Gabriel Agbonlahor", "James Milner"], 0, "Gareth Barry, who went on to make more Premier League appearances than anyone."),
    (2, "Jack Grealish left Aston Villa in 2021 to join which club?", ["Manchester United", "Manchester City", "Chelsea", "Liverpool"], 1, "Manchester City, for a British record £100 million. He had been Villa captain."),
    (2, "After relegation in 2016, in which year did Villa return to the Premier League?", ["2017", "2018", "2019", "2020"], 2, "2019, beating Derby in the play-off final at Wembley."),
    (1, "What is Aston Villa's nickname?", ["The Villans", "The Lions", "The Clarets", "The Brummies"], 0, "The Villans. Spelt with an a. Rival fans prefer the other spelling."),
    (3, "Which striker left Villa for Manchester United in 1998 and won the treble the next year?", ["Dwight Yorke", "Stan Collymore", "Savo Milošević", "Julian Joachim"], 0, "Dwight Yorke, from Trinidad and Tobago. Villa fans were not pleased."),
    (2, "Which Villa goalkeeper won the World Cup with Argentina in 2022?", ["Emiliano Martínez", "Brad Friedel", "Mark Bosnich", "Tom Heaton"], 0, "Emiliano Martínez, who also won the Golden Glove at the tournament."),
    (2, "The Holte End is a famous stand at which ground?", ["Villa Park", "Anfield", "Goodison Park", "Old Trafford"], 0, "Villa Park. One of the biggest single stands in England."),
    (3, "Who was Villa's manager for the 1982 European Cup final, having taken over mid-season?", ["Tony Barton", "Ron Saunders", "Graham Turner", "Billy McNeill"], 0, "Tony Barton, promoted from assistant when Saunders quit in February. He won the biggest prize three months later."),
    (3, "Villa beat Manchester United in the 1994 League Cup final under which manager?", ["Brian Little", "Ron Atkinson", "John Gregory", "Graham Taylor"], 1, "Ron Atkinson, who had managed United himself. It stopped United winning a domestic treble."),
    (1, "Aston Villa are from which city?", ["Liverpool", "Birmingham", "Manchester", "Leeds"], 1, "Birmingham. Aston is a district of the city, north of the centre."),
    (2, "Which animal is on the Aston Villa badge?", ["A lion", "An eagle", "A bull", "A stag"], 0, "A lion, taken from the Scottish royal standard. An early chairman was Scottish."),
]

BOURNEMOUTH = [
    (1, "What is Bournemouth's home ground called?", ["Vitality Stadium", "St Mary's", "Fratton Park", "The Valley"], 0, "The Vitality Stadium, also known by its old name, Dean Court."),
    (1, "What is Bournemouth's nickname?", ["The Cherries", "The Saints", "The Pilgrims", "The Seasiders"], 0, "The Cherries. Cherry-red shirts, and cherry orchards near the original ground."),
    (2, "In which year did Bournemouth first reach the Premier League?", ["2010", "2013", "2015", "2018"], 2, "2015, for the first time in the club's history."),
    (2, "Which manager took Bournemouth from League Two to the Premier League?", ["Eddie Howe", "Harry Redknapp", "Scott Parker", "Sean Dyche"], 0, "Eddie Howe, a former Bournemouth defender. Two spells, three promotions."),
    (1, "What colours are Bournemouth's home shirts?", ["Red and black stripes", "Red and white stripes", "All red", "Blue and white"], 0, "Red and black stripes, modelled on AC Milan's kit in the early 1970s."),
    (2, "Bournemouth is in which English county?", ["Hampshire", "Dorset", "Devon", "Sussex"], 1, "Dorset, on the south coast. Beaches, pines, and a very small football ground."),
    (3, "In which year did Bournemouth go into administration and nearly go out of business?", ["1997", "2008", "2012", "2016"], 1, "2008. They started the next season on minus 17 points and stayed up. Seven years later they were in the Premier League."),
    (2, "How many seasons did Bournemouth's first Premier League spell last?", ["Two", "Three", "Five", "Seven"], 2, "Five, from 2015 to 2020, when they were relegated on the final day."),
    (2, "After relegation in 2020, in which year did Bournemouth return to the Premier League?", ["2021", "2022", "2023", "2024"], 1, "2022, finishing second in the Championship."),
    (1, "Bournemouth is on which coast of England?", ["The east coast", "The south coast", "The north-west coast", "The north-east coast"], 1, "The south coast, between Southampton and Poole."),
    (3, "Which manager led Bournemouth back to the Premier League in 2022?", ["Eddie Howe", "Jason Tindall", "Scott Parker", "Gary O'Neil"], 2, "Scott Parker, the former England midfielder. He was sacked four games into the following season."),
    (2, "What does Bournemouth's badge show?", ["A cherry tree", "A footballer heading a ball", "A pier", "A seagull"], 1, "A player heading the ball, in profile, on red and black stripes."),
    (2, "Who are Bournemouth's south-coast rivals?", ["Portsmouth", "Southampton", "Brighton", "Plymouth"], 1, "Southampton, thirty miles up the road. The bigger club historically, which Bournemouth enjoy pointing out has changed."),
    (2, "Roughly how many people does Bournemouth's ground hold?", ["About 11,000", "About 20,000", "About 30,000", "About 40,000"], 0, "About 11,000. The smallest ground in Premier League history."),
    (3, "Bournemouth striker Callum Wilson left in 2020 to join which club?", ["Newcastle United", "Everton", "Aston Villa", "West Ham"], 0, "Newcastle, where he kept scoring. He had been Bournemouth's top scorer in the top flight."),
    (3, "Andoni Iraola, appointed Bournemouth manager in 2023, is from which country?", ["Portugal", "Spain", "Italy", "Argentina"], 1, "Spain, from the Basque Country. He had managed Rayo Vallecano in Madrid."),
    (2, "After leaving Bournemouth in 2020, Eddie Howe went on to manage which club?", ["Newcastle United", "Everton", "Crystal Palace", "Celtic"], 0, "Newcastle, from 2021, taking them into the Champions League."),
    (3, "What does AFC stand for in AFC Bournemouth?", ["Association Football Club", "Athletic Football Club", "Amateur Football Club", "Allied Football Club"], 1, "Athletic Football Club. The club put the letters first in 1971 so it would appear at the top of alphabetical lists."),
    (3, "What was Bournemouth called before 1971?", ["Bournemouth Rovers", "Bournemouth & Boscombe Athletic", "Boscombe Wanderers", "Bournemouth Town"], 1, "Bournemouth & Boscombe Athletic. Boscombe is the suburb where the ground is."),
    (3, "In which division did Bournemouth play in 2009, six years before reaching the Premier League?", ["The Championship", "League One", "League Two", "The National League"], 2, "League Two, the fourth tier, and fighting relegation from it. One of the fastest rises in English football."),
]

BRENTFORD = [
    (1, "What is Brentford's nickname?", ["The Bees", "The Hornets", "The Wasps", "The Bugs"], 0, "The Bees. The badge is a bee and the fans chant 'buzz'."),
    (1, "What is Brentford's home ground called?", ["Griffin Park", "Gtech Community Stadium", "Loftus Road", "Craven Cottage"], 1, "The Gtech Community Stadium, by Kew Bridge, since 2020."),
    (2, "What was the name of Brentford's old ground, famous for a pub on every corner?", ["Griffin Park", "The Den", "Plough Lane", "Boleyn Ground"], 0, "Griffin Park, their home from 1904 to 2020. Four pubs, one on each corner."),
    (2, "In which year were Brentford promoted to the Premier League?", ["2019", "2020", "2021", "2022"], 2, "2021, beating Swansea 2-0 in the play-off final at Wembley."),
    (1, "What colours are Brentford's home shirts?", ["Red and white stripes", "Blue and white stripes", "All red", "Yellow and black"], 0, "Red and white stripes, with black shorts."),
    (2, "Which Danish manager took Brentford into the Premier League?", ["Thomas Frank", "Kasper Hjulmand", "Michael Laudrup", "Ståle Solbakken"], 0, "Thomas Frank, in charge from 2018. He stayed seven years."),
    (3, "Brentford's owner, known for using statistics and betting models, is who?", ["Matthew Benham", "Tony Bloom", "Daniel Levy", "Mike Ashley"], 0, "Matthew Benham, a lifelong fan who made his money in sports betting. He owns Danish club Midtjylland too."),
    (1, "Brentford is in which part of London?", ["North", "East", "West", "South"], 2, "West London, near Kew Gardens, sandwiched between Fulham and QPR."),
    (3, "When Brentford were promoted in 2021, how long had it been since they were last in the top flight?", ["24 years", "44 years", "74 years", "94 years"], 2, "74 years. Their previous top-flight season was 1946-47."),
    (3, "Ivan Toney left Brentford in 2024 to play in which country?", ["Italy", "Saudi Arabia", "Spain", "Turkey"], 1, "Saudi Arabia, joining Al-Ahli. He had been Brentford's top scorer for four seasons."),
    (1, "Who are Brentford's nearest rivals?", ["Fulham and QPR", "Chelsea and Arsenal", "Watford and Luton", "Crystal Palace and Millwall"], 0, "Fulham and Queens Park Rangers, both a few miles away in west London."),
    (2, "What is on the Brentford badge?", ["A bee", "A griffin", "A bridge", "A crown"], 0, "A bee, in a red and white circle."),
    (3, "In 2016 Brentford closed their youth academy and replaced it with what?", ["A B team", "A partnership with Chelsea", "A women's team", "Nothing"], 0, "A B team for players released elsewhere aged 17 to 20. Several went on to the first team."),
    (3, "Brentford's first ever Premier League match in 2021 was a 2-0 home win over which club?", ["Arsenal", "Chelsea", "Liverpool", "Spurs"], 0, "Arsenal, on the opening Friday night of the season. A fine way to arrive."),
    (2, "What is Brentford's mascot called?", ["Buzz Bee", "Billy Bee", "Bertie", "Sting"], 0, "Buzz Bee. Not a complicated one."),
    (2, "Christian Eriksen joined Brentford in 2022 after a cardiac arrest at which tournament?", ["Euro 2020", "The 2018 World Cup", "The 2022 World Cup", "Euro 2016"], 0, "Euro 2020, played in 2021, when he collapsed on the pitch for Denmark. He was fitted with a defibrillator."),
    (3, "Brentford's stadium sits beside which London landmark?", ["Kew Bridge", "Tower Bridge", "Hammersmith Bridge", "Battersea Power Station"], 0, "Kew Bridge, over the Thames. The stadium is squeezed between railway lines."),
    (1, "At which stadium did Brentford win the 2021 play-off final?", ["Wembley", "Old Trafford", "Cardiff", "Villa Park"], 0, "Wembley, in front of a limited crowd during the pandemic."),
    (2, "In which year was Brentford founded?", ["1875", "1889", "1901", "1920"], 1, "1889, by members of a rowing club looking for a winter sport. They chose football over rugby by a vote."),
    (3, "Thomas Frank left Brentford in 2025 to manage which club?", ["Tottenham Hotspur", "Chelsea", "Manchester United", "Denmark"], 0, "Tottenham. Brentford lost their manager, captain and top scorer in the same summer."),
]

BRIGHTON = [
    (1, "What is Brighton's nickname?", ["The Seagulls", "The Pelicans", "The Albions", "The Shrimpers"], 0, "The Seagulls. It began as a chant to answer Crystal Palace fans singing 'Eagles'."),
    (1, "What is Brighton's home ground commonly called?", ["The Amex", "The Goldstone", "Withdean", "The Dell"], 0, "The Amex, at Falmer, after the sponsor. Officially the American Express Stadium."),
    (2, "Who are Brighton's fiercest rivals?", ["Southampton", "Crystal Palace", "Portsmouth", "Bournemouth"], 1, "Crystal Palace, forty miles away. The M23 derby, and it is genuinely heated."),
    (2, "In which year were Brighton promoted to the Premier League for the first time?", ["2015", "2017", "2019", "2021"], 1, "2017, after 34 years out of the top flight."),
    (2, "Which manager took Brighton into the Premier League?", ["Chris Hughton", "Gus Poyet", "Graham Potter", "Roberto De Zerbi"], 0, "Chris Hughton, who kept them up for two seasons before being sacked."),
    (1, "What colours are Brighton's home shirts?", ["Blue and white stripes", "Red and white stripes", "All blue", "Green and white"], 0, "Blue and white stripes."),
    (3, "Brighton's owner, a professional gambler and lifelong fan, is who?", ["Tony Bloom", "Matthew Benham", "Dick Knight", "Paul Barber"], 0, "Tony Bloom, known as the Lizard at the poker table. His data company finds Brighton's bargains."),
    (2, "Which Italian manager took Brighton into Europe for the first time?", ["Roberto De Zerbi", "Roberto Mancini", "Carlo Ancelotti", "Maurizio Sarri"], 0, "Roberto De Zerbi, who took them to sixth in 2023 and the Europa League."),
    (3, "Which ground did Brighton lose in 1997, leaving them homeless for two years?", ["The Goldstone Ground", "Withdean Stadium", "The Dell", "Priestfield"], 0, "The Goldstone Ground, sold by the owners. They played home games in Gillingham for two seasons."),
    (3, "Brighton reached the FA Cup final in 1983 and lost the replay to which club?", ["Manchester United", "Liverpool", "Everton", "Arsenal"], 0, "Manchester United, 4-0 in the replay after a 2-2 draw. 'And Smith must score' is still quoted."),
    (2, "Graham Potter left Brighton in 2022 to manage which club?", ["Chelsea", "Arsenal", "Manchester United", "England"], 0, "Chelsea. It did not go well, and he was sacked within seven months."),
    (3, "Brighton sold Moisés Caicedo to Chelsea in 2023 for roughly how much?", ["£45 million", "£75 million", "£115 million", "£150 million"], 2, "About £115 million, a British record at the time. Brighton had paid Independiente del Valle around £4 million."),
    (1, "Brighton is in which county?", ["Kent", "Sussex", "Hampshire", "Surrey"], 1, "Sussex, on the south coast. The ground is on the edge of the South Downs."),
    (2, "Which Brighton midfielder moved to Liverpool in 2023, shortly after winning the World Cup?", ["Alexis Mac Allister", "Moisés Caicedo", "Marc Cucurella", "Yves Bissouma"], 0, "Alexis Mac Allister, a World Cup winner with Argentina in December 2022."),
    (2, "In which competition did Brighton play their first ever European campaign in 2023-24?", ["The Champions League", "The Europa League", "The Conference League", "The Intertoto Cup"], 1, "The Europa League. They reached the last 16, beating Ajax and Marseille along the way."),
    (3, "Where did Brighton play their home games between 1999 and 2011?", ["Withdean Stadium", "The Goldstone Ground", "Gillingham", "Brighton Racecourse"], 0, "Withdean, a converted athletics track with temporary stands. Fans called it the Theatre of Trees."),
    (2, "The Brighton v Crystal Palace rivalry is named after what?", ["A motorway", "A railway line", "A river", "A shared manager"], 0, "The M23 motorway that links the two. The actual origin was a 1970s feud between the managers."),
    (2, "In which year was Brighton & Hove Albion founded?", ["1889", "1901", "1912", "1925"], 1, "1901, replacing a club called Brighton United that had gone bust."),
    (2, "What is Brighton's mascot called?", ["Gully", "Sammy the Seagull", "Albie", "Skipper"], 0, "Gully, a seagull, and a second one called Gully's Girl."),
    (2, "In which year did Brighton's Amex Stadium open?", ["2007", "2009", "2011", "2013"], 2, "2011, after a fourteen-year fight for planning permission. The first league game was a 2-1 win over Doncaster."),
]

PACKS = [
    ("club-arsenal", "Arsenal", ARSENAL),
    ("club-aston-villa", "Aston Villa", ASTON_VILLA),
    ("club-bournemouth", "AFC Bournemouth", BOURNEMOUTH),
    ("club-brentford", "Brentford", BRENTFORD),
    ("club-brighton", "Brighton & Hove Albion", BRIGHTON),
]
