# His Club packs: Chelsea, Coventry City, Crystal Palace, Everton, Fulham. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)

CHELSEA = [
    (1, "What is Chelsea's home ground called?", ["Stamford Bridge", "Craven Cottage", "Loftus Road", "The Bridge Arena"], 0,
     "Stamford Bridge, in Fulham, not Chelsea. The ground was built in 1877 for athletics; the football club was founded in 1905 to fill it.",
     "A club invented to fill an empty stadium is the best Chelsea fact there is.",
     "impress", "\"Stamford Bridge existed before Chelsea did. They started the club to fill it.\""),
    (1, "In which year was Chelsea founded?", ["1886", "1899", "1905", "1919"], 2,
     "1905, in a pub opposite the ground, the Rising Sun, now called the Butcher's Hook. You can drink where the club was born.",
     "A club founded in a pub you can visit is a date-night fact.",
     "say", "\"Chelsea were founded in that pub opposite the ground. It's there to this day, different name.\""),
    (1, "What colour are Chelsea's home shirts?", ["Royal blue", "Sky blue", "Red", "White"], 0,
     "Royal blue, since the early 1960s. Before that a paler blue, and for a while the fans were called the Pensioners after the war veterans who lived nearby.",
     "The Blues is the nickname; knowing they were once the Pensioners is the extra.",
     "impress", "\"Chelsea fans were the Pensioners until the sixties. After the old soldiers who live next door.\""),
    (2, "Which Russian billionaire owned Chelsea from 2003 to 2022?", ["Roman Abramovich", "Alisher Usmanov", "Dmitry Rybolovlev", "Mikhail Prokhorov"], 0,
     "Roman Abramovich, whose money turned a good club into a trophy machine: nineteen major trophies in nineteen years, and a lot of sacked managers. Forced to sell in 2022.",
     "Every Chelsea conversation splits into before and after Abramovich.",
     "ask", "Ask him: \"Would Chelsea have won anything without Abramovich's money?\""),
    (2, "In which year did Chelsea first win the Champions League?", ["2008", "2012", "2016", "2021"], 1,
     "2012, in Munich, on penalties against Bayern in Bayern's own stadium, after Drogba's late equaliser. They had lost the 2008 final on penalties to United.",
     "Munich 2012 is the night Chelsea fans of a certain age will talk about for the rest of their lives.",
     "ask", "Ask him: \"Munich 2012. Where were you when Drogba scored the penalty?\""),
    (2, "Who did Chelsea beat in the 2021 Champions League final?", ["Manchester City", "Real Madrid", "Bayern Munich", "Paris Saint-Germain"], 0,
     "Manchester City, 1-0 in Porto, with a goal from Kai Havertz. Their second European Cup, won by a manager appointed in January.",
     "An all-English final is a thing fans compare notes on. Chelsea won this one.",
     "say", "\"Chelsea beat City in the 2021 final. Havertz, one-nil.\""),
    (2, "Who is Chelsea's top scorer in the club's history?", ["Didier Drogba", "Frank Lampard", "Jimmy Greaves", "Bobby Tambling"], 1,
     "Frank Lampard, 211 goals, and he was a midfielder. Strikers would take that number. He later managed the club, less successfully.",
     "A midfielder as top scorer is the surprising Chelsea fact he will confirm proudly.",
     "impress", "\"Chelsea's top scorer ever is a midfielder. Lampard, 211 goals.\""),
    (2, "Which manager won Chelsea back-to-back league titles in 2005 and 2006?", ["Carlo Ancelotti", "José Mourinho", "Claudio Ranieri", "Antonio Conte"], 1,
     "José Mourinho, who arrived from Porto calling himself the Special One. First spell 2004 to 2007, second 2013 to 2015, another title in 2015.",
     "Mourinho is the manager Chelsea fans love and everyone else loves to hate. Know the name, know the era.",
     "ask", "Ask him: \"Was Mourinho's first Chelsea team the best they've ever had?\""),
    (3, "In which year did Chelsea win their first league title?", ["1905", "1955", "1970", "2005"], 1,
     "1955, then a fifty-year wait for the second in 2005. Older fans lived through the whole gap.",
     "Fifty years between titles explains why the older fans are a bit giddy.",
     "impress", "\"Chelsea won the league in 1955 and then not again until 2005. Fifty years.\""),
    (2, "Which centre-back captained Chelsea for over a decade and was called Captain, Leader, Legend?", ["John Terry", "Frank Lampard", "Marcel Desailly", "Gary Cahill"], 0,
     "John Terry, captain from 2004 to 2017, five league titles. The banner reads Captain, Leader, Legend. He also once wore a full kit to lift a trophy he hadn't played in.",
     "Terry divides opinion outside Chelsea and unites it inside. Both sides are worth hearing.",
     "ask", "Ask him: \"Terry: greatest Chelsea captain or a bit much?\""),
    (2, "Which Ivorian striker scored in four FA Cup finals for Chelsea?", ["Didier Drogba", "Salomon Kalou", "Nicolas Anelka", "Demba Ba"], 0,
     "Didier Drogba, who scored in every final he played for Chelsea, including the 2012 Champions League final. The definition of a big-game player.",
     "'Big-game player' is a phrase he uses. Drogba is the picture in his head.",
     "say", "\"He's a bit of a Drogba, saves it for the big games.\""),
    (3, "The Shed End is a stand at which ground?", ["Stamford Bridge", "Craven Cottage", "Upton Park", "The Den"], 0,
     "Stamford Bridge. The old covered terrace behind the south goal where the loudest fans stood, and where the noise comes from now.",
     "Stands with names are stands with reputations. The Shed is Chelsea's.",
     "say", "\"The Shed End. That's where the singing comes from.\""),
    (2, "Which Italian manager won the league and cup double with Chelsea in 2010, scoring 103 league goals?", ["Carlo Ancelotti", "Antonio Conte", "Roberto Di Matteo", "Gianluca Vialli"], 0,
     "Carlo Ancelotti, the calm one with the eyebrow. 103 goals was a Premier League season record at the time. Sacked the following year, in a corridor.",
     "Chelsea sacking title-winning managers is a running joke. Ancelotti is exhibit A.",
     "impress", "\"Ancelotti won the double and got sacked a year later. In a corridor.\""),
    (3, "Antonio Conte's title-winning Chelsea side of 2017 was famous for switching to which formation?", ["3-4-3", "4-4-2", "4-2-3-1", "5-3-2"], 0,
     "3-4-3, after a bad start. Three centre-backs, wing-backs flying forward. They won thirteen league games in a row and half the league copied it.",
     "If he says 'back three', this is where the modern fashion for it came from.",
     "impress", "\"Conte's 3-4-3 in 2017 started the whole back-three fashion. Everyone copied it.\""),
    (3, "Which manager led Chelsea Women to seven league titles before leaving in 2024?", ["Emma Hayes", "Sarina Wiegman", "Casey Stoney", "Hope Powell"], 0,
     "Emma Hayes, twelve years at the club, then off to coach the United States women's team, who won Olympic gold within months.",
     "Chelsea Women dominated for a decade. Knowing the manager's name is knowing the story.",
     "say", "\"Emma Hayes built Chelsea Women. Seven titles, then straight to Olympic gold with the USA.\""),
    (1, "What is Chelsea's nickname?", ["The Blues", "The Pensioners", "The Lions", "The Bridgers"], 0,
     "The Blues. The lion on the badge holds a staff, taken from the coat of arms of the local nobleman who was club president in the 1950s.",
     "Nickname and badge in one answer.",
     "say", "\"Come on you Blues.\" (The Chelsea version. Everton say the same, awkwardly.)"),
    (3, "Which Chelsea goalkeeper wore a protective headguard and saved a penalty in the 2012 final shootout?", ["Petr Čech", "Thibaut Courtois", "Carlo Cudicini", "Ross Turnbull"], 0,
     "Petr Čech, who wore the headguard after a fractured skull in 2006 and kept playing for a decade. He also saved a penalty in extra time that night.",
     "The keeper in the helmet is a visual he will remember instantly.",
     "say", "\"Čech, the one with the headguard. Saved two penalties in that final.\""),
    (2, "Who are Chelsea's nearest neighbours in the Premier League?", ["Fulham", "Brentford", "QPR", "Watford"], 0,
     "Fulham, under two miles away along the river. Stamford Bridge is actually in the borough of Fulham.",
     "West London derbies are gentle affairs, which he will deny.",
     "say", "\"The ground's technically in Fulham, not Chelsea. Don't tell him I said that.\""),
    (3, "Which Italian became Chelsea's player-manager in 1998?", ["Gianluca Vialli", "Gianfranco Zola", "Roberto Di Matteo", "Ruud Gullit"], 0,
     "Gianluca Vialli, who took over from Ruud Gullit and won two trophies within months while playing too. Chelsea of the late nineties were full of Italians.",
     "The Italian era, before the money, is what older fans mean when they say Chelsea were fun.",
     "ask", "Ask him: \"Were the Zola and Vialli years the fun Chelsea, before the money?\""),
    (2, "Eden Hazard left Chelsea in 2019 to join which club?", ["Real Madrid", "Barcelona", "Paris Saint-Germain", "Juventus"], 0,
     "Real Madrid, after seven seasons and two league titles. He scored twice in his final Chelsea game, the Europa League final, then barely played in Spain.",
     "Hazard is the player Chelsea fans of the 2010s adored above all. His decline in Madrid is a sad coda.",
     "ask", "Ask him: \"Was Hazard the best player you've watched at Chelsea?\""),
]

COVENTRY = [
    (1, "What is Coventry City's nickname?", ["The Sky Blues", "The Blues", "The Wasps", "The Bantams"], 0,
     "The Sky Blues, for the shirts, since a manager called Jimmy Hill changed the colours in 1962 and wrote a song to match.",
     "Nickname, kit and song all trace to one man in the sixties. Handy.",
     "say", "\"Sky Blues. The kit, the song and the nickname all came from Jimmy Hill.\""),
    (2, "In which year did Coventry City win the FA Cup?", ["1972", "1987", "1993", "2001"], 1,
     "1987, the club's one major trophy, beating Tottenham 3-2 after extra time. The city celebrated for a week.",
     "1987 is the year every Coventry fan's story comes back to.",
     "ask", "Ask him: \"Was anyone in your family at Wembley in 1987?\""),
    (2, "Who did Coventry beat in the 1987 FA Cup final?", ["Arsenal", "Tottenham Hotspur", "Everton", "Liverpool"], 1,
     "Tottenham, who had won every FA Cup final they had reached until that day. The winner was a Spurs own goal off Gary Mabbutt's knee in extra time.",
     "The own goal off a knee is the detail fans savour. A Coventry fanzine was named after the knee.",
     "impress", "\"Coventry won the cup with an own goal off a Spurs player's knee. There was a fanzine named after the knee.\""),
    (1, "What colour are Coventry's home shirts?", ["Sky blue", "Royal blue", "Claret", "Green"], 0,
     "Sky blue, since 1962. Before that they had played in nearly every colour going.",
     "Sky blue on the telly means Coventry or Manchester City. Worth knowing which.",
     "say", "\"Sky blue. Easy to mix up with City on a small screen.\""),
    (2, "Coventry City were founded in 1883 under what name?", ["Singers FC", "Coventry Rovers", "Rootes Athletic", "Godiva United"], 0,
     "Singers FC, the works team of a bicycle factory. Coventry made bikes, then cars; the club followed the city.",
     "A club that began as a bicycle works team says everything about the city.",
     "impress", "\"Coventry started as a bicycle factory's works team. Singers FC.\""),
    (3, "Which manager and TV presenter changed Coventry's kit to sky blue and wrote the fans' song?", ["Jimmy Hill", "Noel Cantwell", "John Sillett", "Bobby Gould"], 0,
     "Jimmy Hill, later the presenter of Match of the Day for decades, with the famous chin. He took Coventry from the third tier to the first in the 1960s.",
     "The man off the telly who built the club. Two facts for one.",
     "ask", "Ask him: \"Did you know Jimmy Hill off Match of the Day basically invented modern Coventry?\""),
    (2, "What was Coventry's home ground from 1899 to 2005?", ["Highfield Road", "The Ricoh Arena", "Butts Park", "Coundon Road"], 0,
     "Highfield Road, close to the city centre, for 106 years. It is housing now.",
     "Old grounds are where fans keep their childhood. Naming this one earns a story.",
     "ask", "Ask him: \"Did you ever go to Highfield Road?\""),
    (3, "In 1981 Highfield Road became the first English ground to be what?", ["All-seater", "Floodlit", "Covered on all sides", "Artificial turf"], 0,
     "All-seater, at Jimmy Hill's insistence. The fans hated sitting down and the terraces came back within a few years.",
     "Being first at something everyone now does, and having it rejected, is a great trivia shape.",
     "impress", "\"Coventry were the first all-seater ground in England, in 1981. Fans hated it so much they put terraces back.\""),
    (2, "When Coventry went down in 2001, how many consecutive seasons had they spent in the top flight?", ["14", "24", "34", "44"], 2,
     "Thirty-four seasons, from 1967 to 2001, escaping relegation on the final day more than once. Only a handful of clubs had a longer unbroken run at the time.",
     "Thirty-four years of survival is the club's proudest habit, and then the fall.",
     "impress", "\"Coventry spent thirty-four years in the top flight and kept surviving on the final day. Then they went down and kept going.\""),
    (2, "What is the stadium Coventry moved into in 2005 called now?", ["CBS Arena", "Ricoh Arena", "Highfield Road", "Sky Blue Park"], 0,
     "The CBS Arena, after a sponsor. It opened as the Ricoh Arena, and the club has twice been locked out of it in rent disputes.",
     "A club locked out of its own stadium twice is a story people struggle to believe.",
     "say", "\"They've been locked out of their own stadium twice. Rent rows.\""),
    (3, "In 2013-14 Coventry played home games in which town because of a rent dispute?", ["Northampton", "Leicester", "Birmingham", "Walsall"], 0,
     "Northampton, 35 miles away. Fans boycotted, crowds fell to two thousand, and people protested outside the empty Ricoh.",
     "The exile years are the wound. Knowing about them is knowing what the club survived.",
     "ask", "Ask him: \"Did you boycott the Northampton games or go anyway?\""),
    (3, "From 2019 to 2021 Coventry shared a ground with which club?", ["Birmingham City", "Aston Villa", "Leicester City", "Wolves"], 0,
     "Birmingham City, at St Andrew's, twenty miles away. They won promotion to the Championship while homeless, and many fans could not get there.",
     "Promotion while exiled is the kind of achievement only the fans who lived it can weigh.",
     "impress", "\"Coventry won promotion while playing home games at Birmingham. Fans couldn't even get in.\""),
    (2, "Which manager took Coventry from League Two to a Championship play-off final?", ["Mark Robins", "Tony Mowbray", "Steven Pressley", "Russell Slade"], 0,
     "Mark Robins, in charge 2017 to 2024, who had scored for the club as a player. Two promotions and a final while the club had no home.",
     "Robins is the name every Coventry fan says with gratitude.",
     "say", "\"Mark Robins took them from the fourth tier to a play-off final. With no home ground.\""),
    (3, "Coventry lost the 2023 Championship play-off final on penalties to which club?", ["Luton Town", "Sunderland", "Middlesbrough", "Millwall"], 0,
     "Luton Town, after a 1-1 draw at Wembley. One penalty from the Premier League. Three years later they made it anyway, as champions.",
     "The near miss makes the eventual promotion sweeter. He will want to tell you both halves.",
     "ask", "Ask him: \"Was the 2023 play-off final the worst day, or did it make 2026 better?\""),
    (2, "In which year were Coventry promoted back to the Premier League as Championship champions?", ["2024", "2025", "2026", "2027"], 2,
     "2026, with 95 points, their first top-flight season since 2001. Twenty-five years, a spell in the fourth tier and two exiles in between.",
     "This is the freshest joy in the fanbase. Ask about it and make his day.",
     "ask", "Ask him: \"Where were you when they went up as champions?\""),
    (1, "Coventry is in which region of England?", ["The North East", "The West Midlands", "East Anglia", "The South West"], 1,
     "The West Midlands, twenty miles from Birmingham. A car-making city with a cathedral rebuilt after the war.",
     "Map first, football second.",
     "say", "\"Coventry, West Midlands. Twenty minutes from Birmingham.\""),
    (2, "Which club is Coventry's main Midlands rival?", ["Birmingham City", "Nottingham Forest", "Derby County", "Stoke City"], 0,
     "Birmingham City, with Leicester and Aston Villa close behind. They also shared Birmingham's ground for two years, which helped nobody's mood.",
     "Sharing your rival's ground is a special humiliation. He will have views.",
     "ask", "Ask him: \"How weird was it playing home games at Birmingham's ground?\""),
    (3, "Which striker shared the Premier League Golden Boot in 1998 with eighteen goals for Coventry?", ["Dion Dublin", "Darren Huckerby", "Robbie Keane", "Peter Ndlovu"], 0,
     "Dion Dublin, level with Michael Owen and Chris Sutton. He later became a TV presenter and invented a percussion instrument called the Dube.",
     "A Golden Boot winner who invented a drum is the fact that wins the table.",
     "impress", "\"Dion Dublin won the Golden Boot at Coventry and then invented a drum. Called the Dube.\""),
    (3, "Which former England midfielder was appointed Coventry manager in November 2024 and took them up?", ["Frank Lampard", "Steven Gerrard", "Wayne Rooney", "Scott Parker"], 0,
     "Frank Lampard, after a difficult spell at Chelsea. Coventry were mid-table when he arrived and champions eighteen months later.",
     "Lampard rebuilding his reputation at Coventry is a redemption story fans of every club follow.",
     "ask", "Ask him: \"Has Lampard proved himself as a manager now, or was it the squad?\""),
    (3, "The Sky Blue Song is sung to the tune of what?", ["The Eton Boating Song", "Jerusalem", "Rule Britannia", "Land of Hope and Glory"], 0,
     "The Eton Boating Song, a rowing song from the posh school. Jimmy Hill wrote the football words in 1962 and fans have sung it ever since.",
     "Working-class fans singing an Eton rowing song is a lovely contradiction to have in your pocket.",
     "impress", "\"The Coventry song is the Eton Boating Song with new words. Jimmy Hill wrote it in 1962.\""),
]

CRYSTAL_PALACE = [
    (1, "What is Crystal Palace's home ground called?", ["Selhurst Park", "The Valley", "The Den", "Plough Lane"], 0,
     "Selhurst Park, in south London, since 1924. Old, cramped and loud, with the Holmesdale Road end full of drums and flags.",
     "Selhurst's atmosphere is the thing rival fans concede. Mention it and he lights up.",
     "say", "\"Selhurst on a night game. Best atmosphere in London, they say.\""),
    (1, "What is Crystal Palace's nickname?", ["The Eagles", "The Glaziers", "The Palace Boys", "The Hawks"], 0,
     "The Eagles, since 1973. Before that they were the Glaziers, after the glass palace the club is named for.",
     "Two nicknames, one club. The old one explains the name.",
     "say", "\"They were the Glaziers before the Eagles. Because of the glass palace.\""),
    (2, "Who are Crystal Palace's fiercest rivals?", ["Millwall", "Brighton & Hove Albion", "Charlton", "Wimbledon"], 1,
     "Brighton, forty miles down the M23. It began with two managers feuding in the 1970s and the fans took it on. Nobody outside quite understands it.",
     "The rivalry that makes no geographical sense is the one worth knowing about.",
     "ask", "Ask him: \"Why Brighton? They're forty miles away.\""),
    (1, "What colours are Palace's home shirts?", ["Red and blue stripes", "Claret and blue", "White", "Yellow and green"], 0,
     "Red and blue vertical stripes, copied from Barcelona in the 1970s by a manager who admired them.",
     "Barcelona's colours in south London is a fact that surprises people.",
     "impress", "\"Palace's stripes are copied from Barcelona. A manager just liked them in the seventies.\""),
    (2, "In which year was Crystal Palace founded?", ["1861", "1885", "1905", "1920"], 2,
     "1905, by workers at the Crystal Palace exhibition building in south London. They played in its grounds at first.",
     "The club is named after a building, and the building came first.",
     "say", "\"Palace are named after the actual Crystal Palace. Workers there started the club.\""),
    (2, "What is Crystal Palace named after?", ["A glass exhibition building", "A royal residence", "A pub", "A jeweller"], 0,
     "The Crystal Palace, the enormous glass hall built for the Great Exhibition of 1851 and moved to south London. It burned down in 1936. It is drawn on the badge.",
     "A club named after a building that no longer exists is a story people enjoy.",
     "impress", "\"The Crystal Palace burned down in 1936. The club's named after a building that isn't there.\""),
    (2, "Which former England manager took charge of Palace in 2017, the club he supported as a boy?", ["Roy Hodgson", "Sam Allardyce", "Alan Pardew", "Steve McClaren"], 0,
     "Roy Hodgson, who grew up in Croydon and watched Palace from the terraces. He kept them up four years running and came back for a second spell at 76.",
     "A boyhood fan managing the club at 70 is a warm story fans love telling.",
     "ask", "Ask him: \"Hodgson managing his boyhood club in his seventies, was that lovely or a bit much?\""),
    (2, "Palace lost FA Cup finals in 1990 and 2016 to the same club. Which?", ["Manchester United", "Liverpool", "Arsenal", "Chelsea"], 0,
     "Manchester United both times: after a replay in 1990, in extra time in 2016. Palace led in both.",
     "Two finals lost to the same club in the same way is the kind of pain that bonds fans.",
     "say", "\"United beat them in two cup finals, 1990 and 2016. Palace led in both.\""),
    (2, "Crystal Palace won their first major trophy in 2025. Which one?", ["The FA Cup", "The League Cup", "The Premier League", "The Europa League"], 0,
     "The FA Cup, beating Manchester City 1-0 at Wembley, 120 years after the club was founded. Croydon partied for a week.",
     "The first trophy is the freshest, happiest memory he has. Ask about it.",
     "ask", "Ask him: \"Where were you when Palace won the cup?\""),
    (3, "Who scored the winning goal in the 2025 FA Cup final?", ["Eberechi Eze", "Jean-Philippe Mateta", "Ismaïla Sarr", "Adam Wharton"], 0,
     "Eberechi Eze, a south London boy, in the first half. Goalkeeper Dean Henderson then saved a penalty and should probably have been sent off earlier.",
     "The scorer of the first trophy-winning goal is a name fans will hold onto for life.",
     "say", "\"Eze scored the goal that won Palace their first trophy. Local lad too.\""),
    (3, "Wilfried Zaha, who played over 450 games for Palace, left in 2023 for which club?", ["Galatasaray", "Arsenal", "Marseille", "Fenerbahçe"], 0,
     "Galatasaray in Turkey, after two spells and a decade as the club's talisman. An unhappy year at Manchester United sits in between.",
     "Zaha is the modern Palace hero. If he mentions one player from the 2010s, it is him.",
     "ask", "Ask him: \"Was Zaha the best player Palace have ever had?\""),
    (3, "Which striker scored twice off the bench in the 1990 FA Cup final for Palace?", ["Ian Wright", "Mark Bright", "Andy Gray", "John Salako"], 0,
     "Ian Wright, playing on a leg broken weeks earlier. The final was drawn 3-3; United won the replay. Wright later became an Arsenal legend and a TV presenter.",
     "Ian Wright off the telly was a Palace hero first. That surprises people.",
     "impress", "\"Ian Wright started at Palace. Scored twice in a cup final on a half-healed broken leg.\""),
    (3, "What was the name of the real eagle that flew around Selhurst Park before matches?", ["Kayla", "Eddie", "Percy", "Storm"], 0,
     "Kayla, an American bald eagle, who did a lap of the ground before kick-off from 2010 until her retirement. Fans miss her.",
     "A live eagle at a football match is the fact nobody believes until you show them.",
     "impress", "\"Palace had an actual eagle flying round the pitch before games. Called Kayla.\""),
    (1, "Crystal Palace are from which part of London?", ["North", "East", "South", "West"], 2,
     "South London, around Croydon and Selhurst. The other big south London clubs, Millwall and Charlton, are rivals too.",
     "London's football map is confusing. South is Palace territory.",
     "say", "\"Palace are south London. Croydon, basically.\""),
    (3, "Who scored the extra-time winner in Palace's 4-3 FA Cup semi-final against Liverpool in 1990?", ["Alan Pardew", "Ian Wright", "Mark Bright", "Geoff Thomas"], 0,
     "Alan Pardew, a midfielder who later came back to manage the club and took them to the 2016 final. Liverpool had beaten Palace 9-0 earlier that season.",
     "Beating Liverpool 4-3 months after losing 9-0 to them is a story fans tell in full.",
     "ask", "Ask him: \"Do Palace fans bring up the 4-3 against Liverpool in 1990?\""),
    (3, "Which former Arsenal captain managed Palace from 2021 to 2023?", ["Patrick Vieira", "Thierry Henry", "Tony Adams", "Cesc Fàbregas"], 0,
     "Patrick Vieira, who made Palace young and stylish for a season, then got sacked after twelve games without a win.",
     "Vieira's Palace was briefly the neutral's favourite. The ending was less romantic.",
     "say", "\"Vieira made Palace watchable for a year. Then twelve games without a win.\""),
    (3, "The fan group behind the drums and flags at Selhurst Park is called what?", ["The Holmesdale Fanatics", "The Eagles Ultras", "The Selhurst Boys", "The Glaziers"], 0,
     "The Holmesdale Fanatics, named after the stand they fill. They organise the displays, the drums and the songs, European-style.",
     "If he mentions 'the Fanatics', this is who he means.",
     "say", "\"That's the Holmesdale Fanatics with the drums. They run the atmosphere.\""),
    (3, "Palace won promotion to the Premier League in 2004 by beating which club in the play-off final?", ["West Ham", "Sunderland", "Ipswich", "Wigan"], 0,
     "West Ham, 1-0 in Cardiff, with a goal from Neil Shipperley. Palace had been near the bottom of the division at Christmas.",
     "Bottom at Christmas to promoted in May: the comeback fans measure others against.",
     "impress", "\"Palace were nearly bottom of the Championship at Christmas 2003 and got promoted that May.\""),
    (2, "Which Austrian manager won the FA Cup with Palace in 2025?", ["Oliver Glasner", "Ralph Hasenhüttl", "Ralf Rangnick", "Adi Hütter"], 0,
     "Oliver Glasner, who had already won the Europa League with Eintracht Frankfurt. He took Palace to their first trophy in his first full season.",
     "Glasner is the name on the first trophy. He will always be a Palace legend for it.",
     "say", "\"Glasner won them the cup. First trophy in a hundred and twenty years.\""),
    (2, "Palace beat which club in the 2025 FA Cup final?", ["Manchester City", "Manchester United", "Liverpool", "Aston Villa"], 0,
     "Manchester City, 1-0, at Wembley. City had won the cup two years earlier and were favourites by a distance.",
     "Beating City in a final is the giant-killing every small club dreams of. Palace did it.",
     "say", "\"They beat City in the final. Actual Man City, one-nil.\""),
]

EVERTON = [
    (1, "Which ground was Everton's home from 1892 to 2025?", ["Goodison Park", "Anfield", "Stanley Park", "Bramley-Moore Dock"], 0,
     "Goodison Park, the first purpose-built football stadium in England. Everton left it in 2025 for a new ground on the docks after 133 years.",
     "Leaving Goodison was emotional for every Everton fan. Knowing it shows you understand.",
     "ask", "Ask him: \"Did you go to Goodison before they left? What was it like?\""),
    (1, "What is Everton's nickname?", ["The Toffees", "The Blues", "The Reds", "The Scousers"], 0,
     "The Toffees, after a toffee shop near the ground. A woman in old-fashioned dress, the Toffee Lady, throws sweets into the crowd before home games.",
     "The Toffee Lady is the detail that makes rival fans smile too.",
     "impress", "\"The Toffee Lady throws sweets into the crowd before games. That's why they're the Toffees.\""),
    (1, "Who are Everton's rivals in the Merseyside derby?", ["Liverpool", "Tranmere Rovers", "Manchester United", "Wigan"], 0,
     "Liverpool, a short walk across a park. Called the friendly derby because families are split between the two, though it has produced more red cards than any other fixture.",
     "A friendly derby with the worst red-card count is the contradiction worth quoting.",
     "impress", "\"They call it the friendly derby, and it's had more red cards than any other fixture.\""),
    (2, "In which year was Everton founded?", ["1878", "1888", "1892", "1902"], 0,
     "1878, as St Domingo's, a church team. They renamed themselves Everton a year later and were founder members of the Football League in 1888.",
     "Everton were there at the start of league football. Fans are proud of the age.",
     "say", "\"Everton go back to 1878. Founder members of the league.\""),
    (1, "What colour are Everton's home shirts?", ["Royal blue", "Red", "White", "Sky blue"], 0,
     "Royal blue, since 1901. Before that they tried black with a red sash, and were nicknamed the Black Watch.",
     "Blue in Liverpool means Everton. Red means the other lot.",
     "say", "\"Blue half of Liverpool. Everton.\""),
    (2, "Who is Everton's top scorer in the club's history?", ["Dixie Dean", "Graeme Sharp", "Romelu Lukaku", "Bob Latchford"], 0,
     "Dixie Dean, 383 goals in the 1920s and 30s, a centre-forward famous for heading. His statue stands outside Goodison. He died at Goodison, watching a derby, in 1980.",
     "Dixie Dean is the name older Evertonians say like a saint's.",
     "say", "\"Dixie Dean. Sixty goals in one season. Nobody's touched it.\""),
    (3, "How many league goals did Dixie Dean score in the 1927-28 season?", ["40", "50", "60", "70"], 2,
     "Sixty, in 39 games, a figure no player in England has approached since. He got the sixtieth, a header, in the final match.",
     "Sixty in a season is a number that ends arguments about modern strikers.",
     "impress", "\"Sixty league goals in one season, 1928. Haaland's 36 looks modest next to that.\""),
    (2, "In which year did Everton win the league title, the ninth in the club's history?", ["1970", "1985", "1987", "1995"], 2,
     "1987, under Howard Kendall, two years after the eighth. Nine titles in total, more than every club except a handful.",
     "Nine titles is the number that makes Everton a big club, whatever recent years suggest.",
     "say", "\"Nine league titles. People forget how big Everton were.\""),
    (2, "Who managed Everton through their 1980s glory years?", ["Howard Kendall", "Harry Catterick", "Joe Royle", "Colin Harvey"], 0,
     "Howard Kendall: two league titles, an FA Cup and a European trophy between 1984 and 1987. Then the European ban after Heysel stopped the team going any further.",
     "The mid-eighties team is the one older fans mean when they say Everton were the best in England.",
     "ask", "Ask him: \"Would Kendall's Everton have won the European Cup if English clubs hadn't been banned?\""),
    (2, "Which European trophy did Everton win in 1985?", ["The Cup Winners' Cup", "The European Cup", "The UEFA Cup", "The Super Cup"], 0,
     "The Cup Winners' Cup, beating Rapid Vienna 3-1 in Rotterdam. Weeks later English clubs were banned from Europe for five years.",
     "Everton's one European trophy came just before the door shut. It shapes how fans see what might have been.",
     "impress", "\"Everton won in Europe in 1985 and then English clubs got banned for five years. Terrible timing.\""),
    (2, "In which year did Everton win the FA Cup, the club's fifth?", ["1984", "1995", "2004", "2009"], 1,
     "1995, beating Manchester United 1-0 at Wembley with a Paul Rideout header. Thirty years without a trophy followed.",
     "The trophy drought is the sore point. Handle with care and sympathy.",
     "say", "\"1995. Thirty years. Not that anyone's counting.\""),
    (2, "Wayne Rooney made his first-team debut for which club?", ["Everton", "Manchester United", "Liverpool", "Derby"], 0,
     "Everton, aged sixteen, in 2002. His first goal, against Arsenal, ended a thirty-game unbeaten run. He left for United two years later, which Evertonians did not enjoy.",
     "Rooney is Everton's best-known product and its sorest departure.",
     "ask", "Ask him: \"Do Everton fans forgive Rooney for leaving, or not?\""),
    (2, "Which Scottish manager had two spells at Everton, from 2002 to 2013 and again from 2025?", ["David Moyes", "Walter Smith", "Alex Ferguson", "Gordon Strachan"], 0,
     "David Moyes, who called Everton the People's Club on his first day and made them hard to beat for eleven years. Brought back in 2025 to steady the ship.",
     "'The People's Club' is a Moyes phrase Evertonians adopted. Use it and he'll know you did your homework.",
     "say", "\"The People's Club. That's Moyes's line from 2002.\""),
    (3, "Which club has spent the greatest number of seasons in England's top division?", ["Everton", "Arsenal", "Liverpool", "Manchester United"], 0,
     "Everton, relegated just twice in their history, in 1930 and 1951. Over 120 seasons at the top level.",
     "It is the stat Everton fans reach for when the club is struggling. And it is true.",
     "impress", "\"Everton have spent more seasons in the top flight than anyone. Relegated twice, ever.\""),
    (2, "Where does the nickname the Toffees come from?", ["A sweet shop", "The colour of the shirts", "A factory", "A brewery"], 0,
     "Mother Noblett's toffee shop near Goodison, which sold Everton Mints to the crowd. The club kept the name and the sweets.",
     "A nickname from a sweet shop is one of football's gentler origin stories.",
     "say", "\"The Toffees, from a sweet shop by the ground. You can buy Everton Mints to this day.\""),
    (2, "Everton's new stadium, opened in 2025, is built where?", ["Bramley-Moore Dock", "Stanley Park", "Kirkby", "Aintree"], 0,
     "Bramley-Moore Dock, on the Mersey waterfront north of the city centre. A filled-in dock, with the river behind one stand.",
     "The new ground is the big Everton topic of the decade. Knowing where it is shows you've kept up.",
     "ask", "Ask him: \"Have you been to the new ground yet? Is it as good as they say?\""),
    (3, "Where did Everton play before moving to Goodison Park in 1892?", ["Anfield", "Stanley Park", "Priory Road", "Walton Breck"], 0,
     "Anfield. A row over rent saw Everton walk out; the landlord kept the ground and started a new club to play there, called Liverpool.",
     "Liverpool only exist because Everton fell out with a landlord. Evertonians love this.",
     "impress", "\"Everton were at Anfield first. They left over rent and the landlord started Liverpool.\""),
    (2, "Tim Cahill, who punched the corner flag when he scored, came from which country?", ["Australia", "New Zealand", "Ireland", "South Africa"], 0,
     "Australia. Fifty-six goals for Everton, a lot of them headers, each celebrated by boxing the corner flag.",
     "The corner-flag celebration is a visual he can picture instantly.",
     "say", "\"Cahill. The one who used to box the corner flag.\""),
    (3, "In which position did Everton finish in 2005, earning a Champions League qualifying place?", ["Second", "Third", "Fourth", "Sixth"], 2,
     "Fourth, above Liverpool, who then went and won the Champions League that very season. Everton lost their qualifier and went out. Evertonians do not enjoy this story.",
     "The 2005 story is the purest example of Everton luck. Tell it gently.",
     "say", "\"Everton finished above Liverpool in 2005 and Liverpool won the Champions League anyway. Typical.\""),
    (3, "The Gwladys Street End was the home fans' stand at which ground?", ["Goodison Park", "Anfield", "Villa Park", "Elland Road"], 0,
     "Goodison Park. The team always tried to attack towards it in the second half, so the noise pushed them on.",
     "Stands with names carry memories. This one is now history.",
     "ask", "Ask him: \"Did you sit in the Gwladys Street? What was it like at the end?\""),
]

FULHAM = [
    (1, "What is Fulham's home ground called?", ["Craven Cottage", "Stamford Bridge", "Loftus Road", "Griffin Park"], 0,
     "Craven Cottage, on the bank of the Thames, with a real cottage in one corner where the players' families sit.",
     "The prettiest ground in London, and the cottage is real. Easy win.",
     "say", "\"Craven Cottage. There's an actual cottage in the corner. Families sit on the balcony.\""),
    (1, "What is Fulham's nickname?", ["The Cottagers", "The Whites", "The Lilywhites", "The Riversiders"], 0,
     "The Cottagers, after the cottage. Also, more plainly, the Whites.",
     "Nickname and ground are the same story here.",
     "say", "\"The Cottagers. It really is just because of the cottage.\""),
    (2, "In which year was Fulham founded?", ["1879", "1889", "1899", "1905"], 0,
     "1879, as a church team, making them London's oldest professional football club. Older than Arsenal, Chelsea and Spurs.",
     "'London's oldest club' is a title Fulham fans enjoy quietly.",
     "impress", "\"Fulham are London's oldest professional club. Older than Arsenal or Spurs.\""),
    (1, "What colours are Fulham's home kit?", ["White shirts and black shorts", "Red and white", "Blue and white", "All white"], 0,
     "White shirts, black shorts. Plain and old-fashioned, like the ground.",
     "Kit recognition, the everyday skill.",
     "say", "\"White with black shorts. That's Fulham, not Spurs.\""),
    (2, "Which Egyptian businessman owned Fulham from 1997 to 2013?", ["Mohamed Al-Fayed", "Roman Abramovich", "Naguib Sawiris", "Mohamed Mansour"], 0,
     "Mohamed Al-Fayed, who also owned Harrods. He took Fulham from the third tier to the Premier League and a European final, and put up a Michael Jackson statue.",
     "The Harrods owner and the Michael Jackson statue are the two Fulham facts everyone half-remembers.",
     "ask", "Ask him: \"Do you remember the Michael Jackson statue at Fulham? Was it as bad as it sounds?\""),
    (3, "A statue of which pop star stood outside Craven Cottage from 2011 to 2014?", ["Michael Jackson", "George Michael", "Elton John", "Robbie Williams"], 0,
     "Michael Jackson, a friend of Al-Fayed who had watched one match there. Fans were baffled; the next owner removed it and it ended up in a football museum.",
     "It is one of the strangest things ever to happen at a football ground. Enjoy it.",
     "impress", "\"Fulham had a Michael Jackson statue outside the ground for three years. He'd been to one game.\""),
    (2, "In which year did Fulham reach the Europa League final?", ["2006", "2010", "2014", "2018"], 1,
     "2010, losing 2-1 to Atlético Madrid in Hamburg in extra time. On the way they beat Juventus from 4-1 down on aggregate. A tiny club's greatest run.",
     "The 2010 run is the story Fulham fans tell above all others.",
     "ask", "Ask him: \"The 2010 Europa League run. Where were you for the Juventus game?\""),
    (2, "Who managed Fulham to the 2010 Europa League final?", ["Roy Hodgson", "Martin Jol", "Mark Hughes", "Chris Coleman"], 0,
     "Roy Hodgson, calm and clever, who was named manager of the year for it and then took the Liverpool job, which went badly.",
     "Hodgson at Fulham is the high point of a long career. Fans remember him fondly.",
     "say", "\"Hodgson got Fulham to a European final. Then Liverpool happened.\""),
    (2, "Which American businessman bought Fulham in 2013?", ["Shahid Khan", "Stan Kroenke", "John Henry", "Todd Boehly"], 0,
     "Shahid Khan, who also owns the Jacksonville Jaguars American football team and has a famous moustache. He rebuilt the riverside stand with a swimming pool on top.",
     "The owner with the moustache and the pool: two facts he will confirm.",
     "say", "\"The owner's the American with the moustache. Owns an NFL team too.\""),
    (1, "Craven Cottage sits beside which river?", ["The Thames", "The Lea", "The Wandle", "The Brent"], 0,
     "The Thames. Fans watch the rowers go past before kick-off, and the new riverside stand has a walkway along the water.",
     "A ground on the river is a day out. Suggest it.",
     "say", "\"It's right on the Thames. We could walk along the river before the game.\""),
    (3, "Fulham won the second tier as champions in 2001 under which French manager?", ["Jean Tigana", "Gérard Houllier", "Arsène Wenger", "Claude Puel"], 0,
     "Jean Tigana, with 101 points, playing passing football. It was Fulham's first season in the top flight since 1968.",
     "Tigana's team was the start of modern Fulham. The older fans light up at his name.",
     "ask", "Ask him: \"Was Tigana's Fulham the best team the club's had?\""),
    (2, "Which Portuguese manager won the Championship with Fulham in 2022?", ["Marco Silva", "Nuno Espírito Santo", "José Mourinho", "André Villas-Boas"], 0,
     "Marco Silva, with 90 points and a striker scoring goals for fun. Fulham had bounced between divisions for years; Silva made them stay.",
     "Silva ended the yo-yo years. That is why fans speak well of him.",
     "say", "\"Silva stopped them yo-yoing. First time in years they've stayed up comfortably.\""),
    (2, "Who are Fulham's main London rivals?", ["Chelsea", "Arsenal", "Tottenham", "West Ham"], 0,
     "Chelsea, under two miles away. Chelsea's ground is actually in Fulham, which Fulham fans mention. Brentford and QPR are the other local grudges.",
     "West London's rivalries are gentle by the standards of the game, and he will insist otherwise.",
     "say", "\"Stamford Bridge is in Fulham, you know. Don't tell a Chelsea fan.\""),
    (3, "Johnny Haynes, the first footballer paid £100 a week, spent his whole career at which club?", ["Fulham", "Chelsea", "Arsenal", "Brentford"], 0,
     "Fulham, 1952 to 1970, 658 games. A stand is named after him and his statue stands outside. He won no trophies and had no wish to leave.",
     "The first hundred-pound-a-week footballer is a fact that reaches beyond football.",
     "impress", "\"The first footballer to earn a hundred pounds a week played for Fulham. Johnny Haynes, 1961.\""),
    (3, "Which American scored the goal that knocked Juventus out of the 2010 Europa League for Fulham?", ["Clint Dempsey", "Brian McBride", "Carlos Bocanegra", "Eddie Johnson"], 0,
     "Clint Dempsey, with a chipped finish to complete a comeback from 4-1 down on aggregate. Fulham's greatest night by common agreement.",
     "The Dempsey chip is the goal Fulham fans replay in their heads.",
     "say", "\"Dempsey's chip against Juventus. That's the one they all talk about.\""),
    (1, "What stands in the corner of Fulham's ground?", ["A cottage", "A chapel", "A lighthouse", "A pub"], 0,
     "A cottage, built in 1905 as a pavilion and changing room. The players' families watch from its balcony on match days.",
     "The single loveliest detail of any London ground.",
     "say", "\"Look at the corner, there's the cottage. The players' families sit up there.\""),
    (3, "Fulham's Riverside Stand rebuild, finished in 2024, includes what unusual feature?", ["A rooftop swimming pool", "A cinema", "A bowling alley", "A helipad"], 0,
     "A rooftop swimming pool, alongside restaurants and a members' club, at prices that made ordinary fans wince.",
     "A pool at a football ground is a fact that stops a table.",
     "impress", "\"Fulham's new stand has a rooftop pool. At a football stadium.\""),
    (2, "Which Fulham striker scored 43 goals in the 2021-22 Championship season?", ["Aleksandar Mitrović", "Louis Saha", "Brian McBride", "Rodrigo Muniz"], 0,
     "Aleksandar Mitrović, a Serbian striker who scored like a machine in the second tier and celebrated every one like a final. He left for Saudi Arabia in 2023.",
     "Mitrović is the modern Fulham hero. His 43 is a number fans quote.",
     "say", "\"Mitrović got 43 in one Championship season. Forty-three.\""),
    (1, "Fulham are from which part of London?", ["South-west", "North", "East", "South-east"], 0,
     "South-west London, in the borough of Hammersmith and Fulham, on a bend of the Thames.",
     "Placing the club on the map is the basic courtesy.",
     "say", "\"South-west London, by the river. Nice part of town.\""),
    (2, "What is Fulham's mascot called?", ["Billy the Badger", "Freddie the Fox", "Cottage Cat", "Terry the Thames Otter"], 0,
     "Billy the Badger, who was once ordered off the pitch by a referee for breakdancing in the corner during a match.",
     "A mascot sent off for breakdancing is the ideal dull-match anecdote.",
     "impress", "\"Fulham's mascot got sent off once. For breakdancing during the game.\""),
]

PACKS = [
    ("club-chelsea", "Chelsea", CHELSEA),
    ("club-coventry", "Coventry City", COVENTRY),
    ("club-crystal-palace", "Crystal Palace", CRYSTAL_PALACE),
    ("club-everton", "Everton", EVERTON),
    ("club-fulham", "Fulham", FULHAM),
]
