# His Club packs: Arsenal, Aston Villa, Bournemouth, Brentford, Brighton. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)
# Finished, dated history only. No superlatives tied to now. Every question carries its use.

ARSENAL = [
    (1, "In which year was Arsenal founded?", ["1878", "1886", "1892"], 1,
     "1886, by workers at the Royal Arsenal, a munitions factory. That is where the cannon on the badge comes from.",
     "The badge, the nickname and the origin are one story. Knowing it makes the whole club make sense.",
     "impress", "\"Arsenal started as a works team at a weapons factory. Hence the cannon.\""),
    (2, "In which part of London did Arsenal begin life?", ["Islington", "Woolwich", "Hackney"], 1,
     "Woolwich, south of the river. In 1913 they moved north, a few miles from a rival's ground, uninvited. The neighbours took it as an invasion, and the derby grew from it.",
     "This is the root of the derby hatred, and plenty of fans only half know it.",
     "ask", "Ask him: \"Do you know why Arsenal's derby rivals actually hate them? It's about a house move.\""),
    (1, "Where did Arsenal play before the Emirates Stadium?", ["White Hart Lane", "Highbury", "Wembley"], 1,
     "Highbury, their home from 1913, with its art deco stands. The old ground is flats now, and the pitch is the residents' garden.",
     "Older Arsenal fans say Highbury with feeling. The flats detail is the bit they enjoy.",
     "say", "\"Highbury's flats now, isn't it? The pitch is the garden.\""),
    (1, "What is Arsenal's nickname?", ["The Gunners", "The Cannons", "The Hammers"], 0,
     "The Gunners, for the armaments works. The fans call themselves Gooners.",
     "Gooner is the word he uses for himself. Gunners is the word for the team. Mixing them up is noticed.",
     "say", "\"Come on you Gunners.\" (The chant. Sung before every match.)"),
    (1, "What colour are Arsenal's home shirts?", ["All red", "Red with white sleeves", "Red and white stripes"], 1,
     "Red body and white sleeves, since 1933. Before that, plain dark red. The change was the idea of the manager who made Arsenal a big club in the 1930s.",
     "The white sleeves are the club's signature. Knowing they were a manager's idea is a good extra.",
     "impress", "\"The white sleeves were a manager's idea in 1933. Before that they were plain red.\""),
    (3, "Which Arsenal manager got the local Tube station renamed after the club in 1932?", ["Herbert Chapman", "Tom Whittaker", "George Allison"], 0,
     "Herbert Chapman, manager 1925 to 1934: two titles, an FA Cup, and ideas like floodlights and numbered shirts. In 1932 Gillespie Road station became Arsenal.",
     "He is why there is a statue of a man in a suit outside the Emirates, and why the Tube stop says Arsenal.",
     "ask", "Ask him: \"Do you know why the Tube station is called Arsenal? A manager talked them into it.\""),
    (2, "In which season did Arsenal go the whole league campaign without losing?", ["1997-98", "2001-02", "2003-04"], 2,
     "2003-04: 38 games, 26 wins, 12 draws, no defeats. That team became known as the Invincibles.",
     "He will bring it up unprompted. Now you can bring it up first.",
     "say", "\"The Invincibles season. Thirty-eight games without losing.\""),
    (2, "Who managed the Invincibles?", ["George Graham", "Arsène Wenger", "Bruce Rioch"], 1,
     "Arsène Wenger, in charge for twenty-two years, 1996 to 2018. He changed English football's diet and training, and fans sang his name long after he left.",
     "Wenger divides Arsenal fans: genius, or stayed too long. It is a conversation he has had many times.",
     "ask", "Ask him: \"Was Wenger a genius, or did he stay about five years too long?\""),
    (2, "Who captained the Invincibles?", ["Tony Adams", "Patrick Vieira", "Thierry Henry"], 1,
     "Patrick Vieira, the tall French midfielder who ran the team. He later became a manager himself.",
     "Vieira is who he means by a proper midfielder. Every Arsenal midfielder since gets compared to him.",
     "say", "\"They've not had a midfielder like Vieira since.\" (Any time the midfield looks soft.)"),
    (2, "Which striker scored 228 goals for Arsenal between 1999 and 2012?", ["Ian Wright", "Thierry Henry", "Dennis Bergkamp"], 1,
     "Thierry Henry, across two spells: 1999 to 2007, and a short return in 2012. His statue outside the Emirates shows him sliding on his knees.",
     "Henry is the club's modern hero. If you know one Arsenal player, know him.",
     "ask", "Ask him: \"Did you ever see Henry play live?\" If yes, sit back for ten minutes."),
    (2, "How many league titles had Arsenal won by the end of the 2025-26 season?", ["Twelve", "Fourteen", "Sixteen"], 1,
     "Fourteen. The first came in 1931 and thirteen were won by 2004; then came a long wait for the fourteenth.",
     "The number he will quote against Liverpool and United fans. Have it ready.",
     "say", "\"Fourteen league titles. The fourteenth took them a while.\""),
    (2, "How many times had Arsenal won the FA Cup by 2020?", ["Eleven", "Fourteen", "Seventeen"], 1,
     "Fourteen, the 2020 win over Chelsea being the fourteenth. Manchester United had twelve at that point.",
     "The FA Cup is Arsenal's speciality. It is the trophy fans of other clubs mock them for loving.",
     "say", "\"Arsenal and the FA Cup. Fourteen of them by 2020.\""),
    (3, 'During the Second World War, Arsenal played their home games at which ground?', ['Wembley', 'White Hart Lane', 'Stamford Bridge'], 1,
     "White Hart Lane, Tottenham's ground. Arsenal's own was taken over for air-raid defence, so their north London rivals put them up for the war.",
     "The two clubs can't stand each other, which makes the wartime lodging a lovely detail.",
     'impress', '"Arsenal played at Spurs\' ground during the war. Imagine telling fans that now."'),
    (2, "In which year did Arsenal move to the Emirates Stadium?", ["2004", "2006", "2008"], 1,
     "2006. The stadium cost so much that the club went nine years without a trophy while paying for it. Fans called it the banter era.",
     "The trophy drought explains a decade of jokes at Arsenal's expense. He remembers every one.",
     "ask", "Ask him: \"Was the Emirates worth nine years without a trophy?\""),
    (2, "Which final did Arsenal reach in Paris in 2006, losing 2-1 to Barcelona?", ["The Champions League final", "The UEFA Cup final", "The League Cup final"], 0,
     "The Champions League final. Their goalkeeper was sent off after eighteen minutes, they led anyway, and lost to two late goals. Arsenal fans blamed the referee for years.",
     "European finals are rare for Arsenal, so each one is a story he can tell in detail.",
     "ask", "Ask him: \"Paris 2006. Was Lehmann's red card the end of it, or would they have lost anyway?\""),
    (2, "Tony Adams captained Arsenal to league titles in how many different decades?", ["Two", "Three", "Four"], 1,
     "Three: 1989 and 1991, 1998, and 2002. A centre-back who played for Arsenal for his entire career and has a statue outside the ground.",
     "Mr Arsenal, fans call him. Three decades as captain is the fact to have.",
     "impress", "\"Adams captained them to titles in three different decades. Mr Arsenal.\""),
    (2, "Who managed Arsenal to the league titles of 1989 and 1991?", ["Terry Neill", "George Graham", "Bruce Rioch"], 1,
     "George Graham, an ex-Arsenal player whose teams defended first and won 1-0 a lot. Rivals sang 'boring, boring Arsenal'; Arsenal fans answered 'one-nil to the Arsenal'.",
     "'Boring Arsenal' was the taunt for a decade, and the club's identity through the early nineties.",
     "impress", "\"'One-nil to the Arsenal' was a real chant. They won a lot of games that way under Graham.\""),
    (1, "What is the name of Arsenal's dinosaur mascot?", ["Gunnersaurus", "Rex the Gunner", "Arsenalodon"], 0,
     "Gunnersaurus Rex, designed by a young fan in 1993. The club made him redundant in 2020 to save money and reinstated him after an outcry led by a player.",
     "The mascot being sacked and un-sacked is a story that gets a laugh every time.",
     "say", "\"They sacked Gunnersaurus in 2020 and had to bring him back. Fans revolted.\""),
    (3, "Which Dutch striker from the Invincibles team has a statue outside the Emirates?", ["Dennis Bergkamp", "Robin van Persie", "Marc Overmars"], 0,
     "Dennis Bergkamp, nicknamed the Non-Flying Dutchman because he refused to travel by plane. His statue went up in 2014.",
     "Two statues, one argument he will enjoy: which of the two strikers was better.",
     "ask", "Ask him: \"Henry or Bergkamp?\" Then just listen."),
    (2, "In which season did Arsenal win the league with 85 points, after three second places in a row?", ["2023-24", "2024-25", "2025-26"], 2,
     "2025-26, seven points clear of Manchester City. Their first league title since the Invincibles.",
     "It is the freshest happy memory he has. Asking about it is a gift.",
     "ask", "Ask him: \"Where were you when they finally won it?\""),
]

ASTON_VILLA = [
    (1, "What is Aston Villa's home ground called?", ["Villa Park", "Villa Road", "Villa Fields"], 0,
     "Villa Park, their home since 1897, in the Aston district. It hosted games at the 1966 World Cup and dozens of FA Cup semi-finals.",
     "Villa Park is one of the grand old grounds, and fans say the name with pride.",
     "say", "\"Villa Park's one of the proper old grounds, isn't it?\""),
    (1, "What colours do Aston Villa play in?", ["Red and white", "Claret and blue", "Blue and white"], 1,
     "Claret and blue. Villa had it first; West Ham and Burnley copied it. A common quiz argument.",
     "Three clubs share the colours and Villa fans want credit for being first.",
     "ask", "Ask him: \"Who had claret and blue first, Villa or West Ham?\" He will say Villa, and he is right."),
    (2, "In which year was Aston Villa founded?", ["1866", "1874", "1888"], 1,
     "1874, by members of a chapel cricket team looking for something to do in winter. One of England's oldest clubs.",
     "Villa fans feel the club's history is undervalued. Knowing its age is a way in.",
     "say", "\"Villa are one of the oldest clubs in the country. 1874.\""),
    (2, "Aston Villa were founder members of which competition in 1888?", ["The FA Cup", "The Football League", "The Premier League"], 1,
     "The Football League, the first league anywhere in the world. A Villa director, William McGregor, wrote the letter that proposed it.",
     "The league itself was a Villa man's idea. That is a genuinely impressive fact.",
     "impress", "\"A Villa director invented the Football League. Literally wrote the letter proposing it.\""),
    (2, "In which year did Aston Villa win the European Cup?", ["1977", "1982", "1999"], 1,
     "1982, beating Bayern Munich 1-0 in Rotterdam. The European Cup is what the Champions League used to be called.",
     "People forget Villa are European champions. Villa fans do not, and love being reminded.",
     "impress", "\"Villa are European champions. 1982, beat Bayern. People always forget.\""),
    (3, "Who scored the winning goal when Aston Villa won the European Cup?", ["Gary Shaw", "Peter Withe", "Tony Morley"], 1,
     "Peter Withe, off his shin from close range, from a Tony Morley cross. Villa's goalkeeper had gone off injured early on, and his young replacement kept a clean sheet.",
     "A scrappy winner and a stand-in keeper: the details proper fans love.",
     "impress", "\"Villa won the European Cup with a goal off Withe's shin and their reserve keeper in goal.\""),
    (2, "How many English league titles had Aston Villa won by 2025?", ["Three", "Seven", "Nine"], 1,
     "Seven, six of them before 1911 and the seventh in 1981. For a spell around 1900 they were the dominant club in England.",
     "It is the number that explains why Villa fans think of themselves as a big club.",
     "say", "\"Seven league titles. They were the Manchester United of the 1890s.\""),
    (2, "Who managed Aston Villa to the league title in 1981?", ["Ron Saunders", "Graham Taylor", "Ron Atkinson"], 0,
     "Ron Saunders, a strict manager who used just fourteen players all season. He had arrived in 1974, with Villa in the second tier.",
     "Fourteen players for a whole season is a fact that stops modern fans in their tracks.",
     "impress", "\"They won the 1981 title using fourteen players. Fourteen, all season.\""),
    (2, "Who are Aston Villa's city rivals?", ["Wolves", "Birmingham City", "West Brom"], 1,
     "Birmingham City. The Second City derby, played only when the two are in the same division. To Villa fans, 'the Blues' means Birmingham, not Chelsea.",
     "If he says 'the Blues' with contempt, this is who he means.",
     "say", "\"Second City derby. Villa fans think they're the bigger club, and they usually are.\""),
    (1, "What is Aston Villa's nickname?", ["The Villans", "The Clarets", "The Brummies"], 0,
     "The Villans, spelt with an a. Rival fans prefer the other spelling.",
     "Spelling it right in a text is a small win.",
     "say", "\"Come on you Villans.\" (With an a. He will notice.)"),
    (2, "Which animal is on the Aston Villa badge?", ["A lion", "An eagle", "A bull"], 0,
     "A lion rampant, borrowed from the Scottish royal standard as a nod to the Scots who ran the early club. The club motto is Prepared.",
     "Badge stories are the easiest way to show you looked properly.",
     "impress", "\"The lion on the badge is Scottish. The men who ran the early club were Scots.\""),
    (2, "Jack Grealish left Aston Villa in 2021 to join which club?", ["Manchester United", "Manchester City", "Chelsea"], 1,
     "Manchester City, for £100 million, a British record at the time. He was Villa's captain and a local boy, which made it hurt.",
     "The local hero who left for money is a Villa sore point and a good conversation.",
     "ask", "Ask him: \"Do Villa fans forgive Grealish, or is he a traitor for life?\""),
    (2, "After relegation in 2016, in which year did Villa return to the Premier League?", ["2018", "2019", "2020"], 1,
     "2019, beating Derby in the play-off final at Wembley. Three seasons in the Championship for a club that considers itself a giant.",
     "The Championship years are the low point he measures everything against.",
     "ask", "Ask him: \"How bad were the Championship years? Did you keep going?\""),
    (2, 'Which goalkeeper was playing for Villa when he won the 2022 World Cup with Argentina?', ['Franco Armani', 'Emi Martínez', 'Gerónimo Rulli'], 1,
     'Emiliano Martínez, who also won the award for best goalkeeper at the tournament and celebrated it in a way that upset a lot of people.',
     'A World Cup winner between the posts is a bragging right few clubs have.',
     'say', '"Villa had a World Cup winner in goal. Not many clubs can say that."'),
    (2, "In which competition did Aston Villa play in 2024-25 for the first time in over forty years?", ["The Europa League", "The Champions League", "The Conference League"], 1,
     "The Champions League, after finishing fourth in 2023-24. They reached the quarter-finals and went out to Paris Saint-Germain.",
     "Villa in the Champions League was the feel-good story of 2024. He will remember the anthem.",
     "ask", "Ask him: \"What was it like hearing the Champions League anthem at a Villa home game?\""),
    (3, "Which striker left Villa for Manchester United in 1998 and won the treble the next year?", ["Dwight Yorke", "Stan Collymore", "Savo Milošević"], 0,
     "Dwight Yorke, from Trinidad and Tobago, always smiling. Villa fans watched him win everything the season after he left.",
     "Selling your best player and watching him win the treble is a specific kind of pain. It explains a lot.",
     "say", "\"Villa sold Yorke and he won the treble the next year. Typical.\""),
    (3, "Villa beat Manchester United in the 1994 League Cup final under which manager?", ["Brian Little", "Ron Atkinson", "Graham Taylor"], 1,
     "Ron Atkinson, who had managed United himself. The win stopped United doing a domestic treble that year, which Villa fans enjoy more than the cup.",
     "Stopping a rival's treble is worth more than a trophy to some fans. This is the example.",
     "impress", "\"Villa stopped United's treble in 1994. With United's old manager in charge.\""),
    (2, "Which member of the royal family is a well-known Aston Villa fan?", ["Prince William", "Prince Harry", "King Charles III"], 0,
     "Prince William, who has said he picked Villa as a schoolboy rather than one of the usual big clubs. He has turned up for their big European nights.",
     "A royal fan is the fact that comes up at every dinner party. Villa fans are quietly proud of it.",
     "impress", "\"Prince William's a Villa fan. He picked them as a schoolboy.\""),
    (2, "What is the name of Aston Villa's famous stand behind one goal?", ["The Holte End", "The Kop", "The Stretford End"], 0,
     "The Holte End, named after the Holte Hotel, a pub next to the ground. It is where the noise comes from.",
     "'The Holte End' is a phrase he will use. Now you know it is a stand, not a person.",
     "say", "\"The Holte End's loud today.\""),
    (2, 'Which Spanish manager replaced Steven Gerrard at Aston Villa in October 2022?', ['Unai Emery', 'Rafael Benítez', 'Mikel Arteta'], 0,
     "Unai Emery, who had won the Europa League four times elsewhere. Gerrard left Villa 17th, and Emery's team finished seventh that season.",
     'The Emery turnaround is the Villa story of the 2020s.',
     'say', '"Gerrard left them seventeenth. Emery had them seventh by May."'),
]

BOURNEMOUTH = [
    (1, "What is Bournemouth's home ground called?", ["Vitality Stadium", "St Mary's", "Fratton Park"], 0,
     "The Vitality Stadium, also known by its old name, Dean Court. In 2025 it held about 11,300, tiny by Premier League standards.",
     "The tiny ground is the first thing anyone mentions about Bournemouth. Get there first.",
     "say", "\"Eleven thousand. You could fit their whole crowd in a corner of Old Trafford.\""),
    (1, "What is Bournemouth's nickname?", ["The Cherries", "The Saints", "The Seasiders"], 0,
     "The Cherries, for the cherry-red shirts and the cherry orchards that used to stand near the ground.",
     "Nicknames turn up in every commentary. This one has a pleasant story.",
     "say", "\"The Cherries. There were orchards by the old ground.\""),
    (1, "What colours are Bournemouth's home shirts?", ["Red and black stripes", "Red and white stripes", "All red"], 0,
     "Red and black stripes, copied from AC Milan in the early 1970s because the manager admired them.",
     "A small English club in Milan's colours is a neat fact for a match on telly.",
     "impress", "\"Bournemouth's stripes are copied from AC Milan. A manager just liked the look.\""),
    (2, "In which year did Bournemouth first reach the Premier League?", ["2013", "2015", "2018"], 1,
     "2015, as Championship winners. It was the club's first season in the top flight in 116 years of existence.",
     "The rise is the whole Bournemouth story. Everything else is footnotes.",
     "say", "\"First time in the top flight in 2015, after 116 years. Mad.\""),
    (2, "Which manager took Bournemouth from the fourth tier to the Premier League?", ["Eddie Howe", "Harry Redknapp", "Scott Parker"], 0,
     "Eddie Howe, a former Bournemouth defender who became manager at 31. Two spells in charge and three promotions.",
     "Howe is the name Bournemouth fans say with love.",
     "ask", "Ask him: \"Is Eddie Howe the best thing that ever happened to Bournemouth?\""),
    (3, "In which year did Bournemouth go into administration and nearly cease to exist?", ["2008", "2012", "2016"], 0,
     "2008. They began the next season on minus 17 points as a punishment and avoided relegation anyway.",
     "From nearly dead to the Premier League. It is the fact that explains the club.",
     "impress", "\"Bournemouth once started a season on minus seventeen points. And stayed up.\""),
    (2, 'Dominic Solanke left Bournemouth in 2024 for which club?', ['Chelsea', 'Tottenham Hotspur', 'Aston Villa'], 1,
     'Tottenham, for a fee that could reach £65 million, after 19 Premier League goals the season before. Bournemouth had paid Liverpool about £19 million for him.',
     'Selling a striker for three times what you paid is how a small club keeps going.',
     'say', '"They sold Solanke to Spurs for about sixty-five million. Not bad for a small club."'),
    (2, "Bournemouth won on the final day of 2019-20 and went down anyway. Who did they beat?", ["Everton", "Watford", "Aston Villa"], 0,
     "Everton, 3-1 at Goodison Park, with no fans in because of Covid. Aston Villa drew at West Ham and stayed up by a single point.",
     "Winning on the final day and going down anyway is a special kind of football pain.",
     "say", "\"They won on the final day in 2020 and went down anyway. By one point.\""),
    (2, "After relegation in 2020, in which year did Bournemouth return to the Premier League?", ["2021", "2022", "2023"], 1,
     "2022, finishing second in the Championship under Scott Parker, who was sacked four games into the new season.",
     "Sacking the manager who got you promoted is a football classic. This is a clean example.",
     "impress", "\"They sacked the manager who got them promoted after four games. Four.\""),
    (2, "Bournemouth's first ever Premier League win came 4-3 away at which club?", ["West Ham", "Southampton", "Chelsea"], 0,
     "West Ham, at Upton Park in August, in their third Premier League game. Their centre-forward scored a hat-trick.",
     "First wins at a new level get retold for years. This one had seven goals.",
     "ask", "Ask him: \"Do you remember Bournemouth's first Premier League win? Seven goals at West Ham?\""),
    (2, "What does Bournemouth's badge show?", ["A cherry tree above the sea", "A footballer heading a ball", "A pier and a seagull"], 1,
     "A player heading the ball, in profile. It was drawn in the 1970s and has barely changed.",
     "Badge spotting is a low-stakes way to show attention.",
     "say", "\"Their badge is a bloke heading a ball. Nice and literal.\""),
    (2, "Who are Bournemouth's south-coast rivals?", ["Portsmouth", "Southampton", "Brighton"], 1,
     "Southampton, thirty miles east. Historically the bigger club by far, which Bournemouth fans enjoy pointing out has changed.",
     "Rivalries are where fans get funny. This one has a recent role reversal.",
     "ask", "Ask him: \"Are Bournemouth bigger than Southampton now? Be honest.\""),
    (3, "Which striker left Bournemouth for Newcastle in 2020?", ["Callum Wilson", "Joshua King", "Dominic Solanke"], 0,
     "Callum Wilson, their main striker in the Premier League years, sold after relegation. He kept scoring at Newcastle.",
     "Losing your striker after relegation is the price of going down. Wilson is the example.",
     "say", "\"They had to sell Wilson when they went down. That's what relegation costs.\""),
    (3, "Andoni Iraola, appointed Bournemouth manager in 2023, comes from which country?", ["Portugal", "Spain", "Italy"], 1,
     "Spain, from the Basque Country. He had made Rayo Vallecano in Madrid play thrilling football on no money, and did the same at Bournemouth.",
     "Iraola made Bournemouth a team neutral fans watched on purpose. That is rare for a small club.",
     "ask", "Ask him: \"Did Iraola's Bournemouth actually play the best football in the league for a while?\""),
    (2, 'Eddie Howe won the League Cup in 2025 as manager of which club?', ['Newcastle', 'Everton', 'Crystal Palace'], 0,
     "Newcastle United, beating Liverpool 2-1 at Wembley. It was the club's first major domestic trophy since 1955.",
     "A former manager winning a trophy elsewhere is a story his old club's fans share.",
     'say', '"Howe won Newcastle their first domestic trophy in seventy years. Bournemouth fans were chuffed for him."'),
    (3, 'Why did Bournemouth put AFC at the front of their name in 1971?', ['To top alphabetical lists', 'To match Ajax of Amsterdam', 'To mark a club merger'], 0,
     'To come first in alphabetical lists of league clubs, ahead of Aldershot and Arsenal. AFC stands for Athletic Football Club.',
     'The alphabetical trick is a perfect pub fact: small, true and slightly ridiculous.',
     'impress', '"They put AFC at the front so they\'d come first in alphabetical lists. Genius, really."'),
    (3, "What was Bournemouth called before 1971?", ["Bournemouth Rovers", "Bournemouth & Boscombe Athletic", "Boscombe & Southbourne Wanderers"], 1,
     "Bournemouth & Boscombe Athletic, from 1923. Boscombe is the suburb where the ground is, and plenty of locals call the ground Dean Court.",
     "Old names come up on old shirts and old photos. He may not know this one himself.",
     "ask", "Ask him: \"Did you know they used to be Bournemouth and Boscombe Athletic?\""),
    (3, "In which division were Bournemouth fighting relegation in 2009?", ["League One", "League Two", "National League"], 1,
     "League Two, the fourth tier, and in danger of dropping out of the Football League altogether. Within a few years they were playing Manchester United.",
     "Knowing how low they sank makes the rise land properly.",
     "impress", "\"Fourth division in 2009. Imagine telling those fans what came next.\""),
    (2, "Bournemouth's first ever Premier League season ended in which position?", ["Twelfth", "Sixteenth", "Nineteenth"], 1,
     "Sixteenth, comfortably safe. Everyone had tipped them to go straight back down, and they stayed up playing passing football.",
     "Staying up in year one is the achievement small clubs are judged on. Bournemouth passed.",
     "say", "\"Everyone said they'd go straight back down. They finished sixteenth, easy.\""),
    (2, "Where does the name Dean Court, Bournemouth's ground, come from?", ['A local landowner', 'A former player', 'A church'], 0,
     "The Cooper-Dean family, local landowners who gave the club the land in 1910. The stadium sponsor changes; the fans' name for the place does not.",
     'Fans use the old name, sponsors use the new one. Knowing both is knowing the club.',
     'say', '"Dean Court\'s named after the family that gave the club the land."'),
]

BRENTFORD = [
    (1, "What is Brentford's nickname?", ["The Bees", "The Hornets", "The Wasps"], 0,
     "The Bees. In the 1890s students cheering a friend in the team shouted 'buck up Bs', and the local papers wrote it down as Bees.",
     "It is a friendly nickname with a daft origin story.",
     "say", "\"The Bees. It started as a student chant the papers misheard.\""),
    (1, "What is Brentford's home ground called?", ["Brentford Riverside Stadium", "Gtech Community Stadium", "Craven Cottage"], 1,
     "The Gtech Community Stadium, their home since 2020, squeezed between railway lines near the Thames.",
     "New grounds take years to feel like home. He may use the old ground's name by habit.",
     "say", "\"The Gtech. Sounds more like a gadget shop than a football ground.\""),
    (2, "What was the name of Brentford's old ground, famous for having a pub on every corner?", ["Griffin Park", "Plough Lane", "Boleyn Ground"], 0,
     "Griffin Park, home from 1904 to 2020. Four corners, four pubs. Away fans planned their day around it.",
     "The four pubs are the fact every fan knows and loves. It works every time.",
     "impress", "\"Griffin Park had a pub on all four corners. Best away day in the country.\""),
    (2, "Which club did Brentford beat in the 2021 play-off final to reach the Premier League?", ["Swansea", "Fulham", "Bournemouth"], 0,
     "Swansea City, 2-0, a year after Brentford lost the 2020 final to Fulham. Bournemouth were beaten in the semi-final on the way.",
     "Losing a play-off final then winning the next one is a story with a happy ending. He will tell it if asked.",
     "ask", "Ask him: \"Was 2021 sweeter because they'd lost the final the year before?\""),
    (1, "What colours are Brentford's home shirts?", ["Red and white stripes", "Blue and white stripes", "All red"], 0,
     "Red and white stripes with black shorts. Easy to confuse with Sunderland on a small screen.",
     "Kit recognition is how you follow a match without the commentary.",
     "say", "\"Red and white stripes, black shorts. That's Brentford, not Sunderland.\""),
    (2, "Which Danish manager took Brentford into the Premier League and kept them there?", ["Thomas Frank", "Kasper Hjulmand", "Michael Laudrup"], 0,
     "Thomas Frank, in charge from 2018 to 2025, then off to Tottenham. Calm, funny, and adored by Brentford fans.",
     "Frank was the model of a small-club manager. His move to Spurs is a talking point in itself.",
     "ask", "Ask him: \"Was Thomas Frank right to leave for Spurs?\""),
    (3, "Brentford's owner made his fortune in what?", ['Sports betting', 'Property', 'Television'], 0,
     "Sports betting. Matthew Benham, a lifelong fan, built a gambling business on statistics and ran the club the same way. In 2014 he bought Denmark's Midtjylland too.",
     "The maths club is Brentford's identity. Knowing why is knowing them.",
     'impress', '"Brentford\'s owner made his money gambling on statistics, and built the club the same way."'),
    (1, "Brentford is in which part of London?", ["North", "West", "South"], 1,
     "West London, by the Thames, out towards Heathrow. A small corner of a big city.",
     "London has a dozen clubs. Placing them is the first skill.",
     "say", "\"Brentford's out west. Proper west London.\""),
    (3, "When Brentford went up in 2021, how many years had passed since their previous top-flight season?", ["44 years", "74 years", "94 years"], 1,
     "Seventy-four years. Their previous top-flight season was 1946-47, just after the war.",
     "Seventy-four years of waiting puts every other club's complaints in perspective.",
     "impress", "\"Brentford waited seventy-four years to get back to the top flight. Since 1947.\""),
    (3, "Ivan Toney left Brentford in 2024 to play in which country?", ["Italy", "Saudi Arabia", "Turkey"], 1,
     "Saudi Arabia, joining Al-Ahli for around £40 million. He had been their top scorer in three of his four seasons and served a betting ban in 2023.",
     "Players leaving for Saudi money is a live debate. Toney is a name he will bring up.",
     "ask", "Ask him: \"Can you blame Toney for taking the Saudi money?\""),
    (1, "Who are Brentford's nearest rivals?", ["Fulham and QPR", "Chelsea and Arsenal", "Watford and Luton"], 0,
     "Fulham and Queens Park Rangers, a couple of miles away. Low-key as derbies go, and he wants them won all the same.",
     "Small derbies matter as much to the fans in them as the big ones do.",
     "say", "\"Local derby. Nobody else cares, everyone in Brentford does.\""),
    (2, "Brentford sold Bryan Mbeumo in 2025 to which club?", ["Manchester United", "Tottenham Hotspur", "Newcastle United"], 0,
     "Manchester United, for around £70 million, after six seasons in Brentford's attack. They had signed him from French football for a fraction of that.",
     "Buying cheap and selling big is how Brentford pays its way.",
     "say", "\"Brentford sold Mbeumo to United for seventy million. That's their whole model.\""),
    (3, "In 2016 Brentford closed their youth academy and replaced it with what?", ["A B team", "A partnership with Chelsea", "A women's team"], 0,
     "A B team, for players released by bigger clubs aged 17 to 20. Cheaper than an academy, and several of them made the first team.",
     "Brentford doing things differently is their whole appeal to football hipsters.",
     "impress", "\"Brentford shut their academy and signed rejects from other clubs instead. It worked.\""),
    (3, "Brentford's first ever Premier League match in 2021 was a 2-0 home win over which club?", ["Arsenal", "Chelsea", "Liverpool"], 0,
     "Arsenal, on the opening Friday night of the season, live on television. A perfect way to arrive.",
     "First-night wins get retold forever. This one was against a giant.",
     "say", "\"Their first ever Premier League game was beating Arsenal. Friday night, on telly.\""),
    (2, "Christian Eriksen joined Brentford in 2022 after collapsing on the pitch at which tournament?", ["Euro 2020", "2018 World Cup", "Euro 2016"], 0,
     "Euro 2020, played in 2021, where his heart stopped during a Denmark match. Fitted with a defibrillator, he returned to football at Brentford early in 2022.",
     "Eriksen's comeback is one of the truly moving football stories of the decade, and Brentford made it possible.",
     "say", "\"Eriksen came back from a cardiac arrest at Brentford. The whole league was cheering him.\""),
    (3, "Brentford's stadium sits next to which London landmark?", ["Kew Bridge", "Tower Bridge", "Hammersmith Bridge"], 0,
     "Kew Bridge, over the Thames, a walk from the botanical gardens. The stadium is wedged between two railway lines.",
     "Knowing where the ground is turns a fixture into a day out.",
     "say", "\"It's right by Kew Gardens. Football and a walk round the gardens.\""),
    (1, "At which stadium did Brentford win the 2021 play-off final?", ["Wembley", "Old Trafford", "Villa Park"], 0,
     "Wembley, in front of a crowd limited by the pandemic. It was Brentford's first promotion to the top flight since 1935.",
     "Play-off finals are the happiest and saddest day in a fan's year. This one was the happy kind.",
     "ask", "Ask him: \"What was Wembley like with the crowd capped by Covid?\""),
    (2, "In which year was Brentford founded?", ["1875", "1889", "1901"], 1,
     "1889, by members of a rowing club looking for a winter sport. They voted between football and rugby, and football won by a few votes.",
     "A club that nearly became a rugby team is a fact worth having.",
     "impress", "\"Brentford voted on whether to play football or rugby in 1889. Football won narrowly.\""),
    (3, "Brentford's captain Christian Nørgaard left in the summer of 2025 for which club?", ["Arsenal", "Tottenham Hotspur", "Manchester United"], 0,
     "Arsenal. The same summer Brentford lost their manager and their top scorer too, and plenty expected them to collapse. They finished ninth in 2025-26.",
     "The summer of 2025 is the moment Brentford fans feared the project was over.",
     "ask", "Ask him: \"Did you think Brentford were finished in the summer of 2025?\""),
    (2, "Brentford's mascot is called what?", ["Buzz Bee", "Billy Bee", "Sting"], 0,
     "Buzz Bee. Not a complicated club when it comes to naming things.",
     "Mascots are small talk gold when the match is dull.",
     "say", "\"Buzz Bee. They didn't overthink that one.\""),
]

BRIGHTON = [
    (1, "What is Brighton's nickname?", ["The Seagulls", "The Shrimpers", "The Mariners"], 0,
     "The Seagulls. It started in the 1970s as a chant to answer Crystal Palace fans singing 'Eagles', and became the official nickname.",
     "A nickname invented to annoy a rival is the best kind. And it explains the Palace thing.",
     "impress", "\"Brighton only became the Seagulls to wind up Palace fans. Seagulls versus Eagles.\""),
    (1, "What is Brighton's home ground commonly called?", ["The Amex", "The Goldstone", "The Dell"], 0,
     "The Amex, after the sponsor, at Falmer on the edge of the South Downs. Officially the American Express Stadium.",
     "\"At the Amex\" is how every Brighton home game is described.",
     "say", "\"They're at the Amex. Lovely ground, middle of nowhere.\""),
    (2, "The Brighton v Crystal Palace feud took off in the 1970s because of a clash between which two?", ["The two managers", "The two chairmen", "The two captains"], 0,
     "The managers, Alan Mullery at Brighton and Terry Venables at Palace, whose teams met again and again in 1976-77 with bad blood each time. The fans took it on and kept it.",
     "It is the rivalry that makes no geographical sense, so knowing the real reason marks you as informed.",
     "ask", "Ask him: \"Why do Brighton and Palace hate each other? They're forty miles apart.\""),
    (2, "In which year were Brighton promoted to the Premier League for the first time?", ["2015", "2017", "2019"], 1,
     "2017, after thirty-four years out of the top flight, under Chris Hughton. Twenty years earlier they had nearly dropped out of the league altogether.",
     "The 2017 promotion is the moment the modern club began. He will have a memory of it.",
     "ask", "Ask him: \"Where were you when they went up in 2017?\""),
    (1, "What colours are Brighton's home shirts?", ["Blue and white stripes", "Red and white stripes", "All blue"], 0,
     "Blue and white stripes, with white shorts. Easy to spot, easy to confuse with Sheffield Wednesday.",
     "Kit recognition is the fastest way to follow a match.",
     "say", "\"Blue and white stripes. That's Brighton.\""),
    (3, "Brighton's owner, Tony Bloom, made his money how?", ['Professional gambling', 'Nightclubs and casinos', 'Property development'], 0,
     'Professional gambling and a betting-data company. A lifelong fan known at the poker table as the Lizard, he uses his data to find players nobody else has spotted.',
     "Brighton's whole business model, buy cheap and sell for a fortune, comes from this one man.",
     'impress', '"Brighton\'s owner made his fortune gambling. He built the whole club on his betting data."'),
    (2, "Which Italian manager took Brighton into European football for the first time?", ["Roberto De Zerbi", "Roberto Mancini", "Carlo Ancelotti"], 0,
     "Roberto De Zerbi, who took them to sixth in 2023, playing football neutral fans tuned in for.",
     "De Zerbi's Brighton is the team neutral fans fell for in 2023.",
     "ask", "Ask him: \"Was De Zerbi's Brighton the best football you've seen from a small club?\""),
    (3, "Which ground did Brighton lose in 1997, leaving them homeless for two years?", ["The Goldstone Ground", "Withdean Stadium", "The Dell"], 0,
     "The Goldstone Ground, sold by the owners to developers. Brighton played home games seventy miles away in Gillingham for two seasons while fans fought to save the club.",
     "The Goldstone is the trauma every Brighton fan over forty carries. Knowing it shows respect.",
     "ask", "Ask him: \"Did you go through the Goldstone years? Playing home games in Gillingham?\""),
    (3, "Brighton reached the FA Cup final in 1983 and lost the replay to which club?", ["Manchester United", "Liverpool", "Tottenham Hotspur"], 0,
     "Manchester United, 4-0 in a replay after a 2-2 draw. Gordon Smith could have won the first game late on. 'And Smith must score,' said the commentator. He didn't.",
     "'And Smith must score' is a Brighton fanzine title and a phrase fans use for any big miss.",
     "impress", "\"'And Smith must score' comes from Brighton's 1983 cup final. He didn't. There's a fanzine named after it.\""),
    (2, "Graham Potter left Brighton in 2022 to manage which club?", ["Chelsea", "Arsenal", "Manchester United"], 0,
     "Chelsea, who paid Brighton over £20 million for him. He was sacked within seven months, and Brighton got better without him.",
     "Managers leaving for big clubs and flopping is a genre. This is the textbook case.",
     "say", "\"Chelsea paid twenty million for Potter and sacked him in seven months. Brighton just carried on.\""),
    (3, "Brighton sold Moisés Caicedo to Chelsea in 2023 for roughly how much?", ["£75 million", "£115 million", "£150 million"], 1,
     "About £115 million, a British record at the time, for a player they had bought for around £4 million from Ecuador two years earlier.",
     "Buy for four, sell for a hundred and fifteen. That is the Brighton model in one transfer.",
     "impress", "\"Brighton bought Caicedo for four million and sold him for a hundred and fifteen. In two years.\""),
    (1, "Brighton is in which county?", ["Kent", "Sussex", "Hampshire"], 1,
     "Sussex, on the south coast, an hour from London. The ground is on the edge of the South Downs, next to a university.",
     "The seaside city with a football club: useful context for the away-day chat.",
     "say", "\"Brighton. Sussex, seaside, students and a football club on the Downs.\""),
    (2, "Which Brighton midfielder moved to Liverpool in 2023, months after winning the World Cup?", ["Alexis Mac Allister", "Marc Cucurella", "Yves Bissouma"], 0,
     "Alexis Mac Allister, a World Cup winner with Argentina in December 2022 while a Brighton player. Sold to Liverpool for about £35 million.",
     "A World Cup winner in a Brighton shirt is a fact that surprises people.",
     "impress", "\"Brighton had a World Cup winner in their team. Mac Allister, before Liverpool bought him.\""),
    (2, "In which competition did Brighton play their first European campaign, in 2023-24?", ["The Champions League", "The Europa League", "The Conference League"], 1,
     "The Europa League. They beat Ajax and Marseille and went out to Roma in the round of sixteen. A club that had been homeless twenty-five years earlier.",
     "From Gillingham to Amsterdam in one lifetime is the arc Brighton fans live for.",
     "say", "\"Brighton beat Ajax in Europe. Twenty-five years after nearly going out of business.\""),
    (3, "Where did Brighton play home games after returning from Gillingham in 1999?", ["Withdean Stadium", "Hove Park", "Brighton Racecourse"], 0,
     "Withdean, a converted athletics ground with temporary stands and a running track between the fans and the pitch. They stayed until the new ground was ready.",
     "Years on an athletics track, then European nights. The contrast is the story.",
     "impress", "\"They played on an athletics track for years. Running track round the pitch and all.\""),
    (2, "The Brighton v Crystal Palace rivalry takes its name from what?", ["A motorway", "A railway line", "A shared manager"], 0,
     "The M23 motorway that links the two, so it gets called the M23 derby. Nobody outside the two clubs quite gets it.",
     "A derby named after a road is a detail that makes people laugh.",
     "say", "\"It's called the M23 derby. After the motorway. Very romantic.\""),
    (2, "In which year was Brighton & Hove Albion founded?", ["1889", "1901", "1912"], 1,
     "1901, replacing a club called Brighton United that had gone bust. Albion is an old poetic name for Britain.",
     "The 'Albion' in the name puzzles people. Now you can explain it.",
     "say", "\"Albion just means Britain. It's the old poetic name.\""),
    (2, "What is Brighton's mascot called?", ['Gully', 'Squawk', 'Skipper'], 0,
     'Gully, who by the 2020s had a matchday partner at the Amex called Sally.',
     'Mascot names are a safe question when the match is dull.',
     'say', '"Gully. And there\'s a Sally too."'),
    (2, "In which year did Brighton move into their new stadium at Falmer?", ["2009", "2011", "2013"], 1,
     "2011, after a fourteen-year fight for planning permission that went to a public inquiry twice. The first league game there was a 2-1 win over Doncaster.",
     "Fourteen years to build a ground. Fans remember every planning meeting.",
     "ask", "Ask him: \"Fourteen years to get the new ground built. Did you ever think it wouldn't happen?\""),
    (2, "How old was Fabian Hürzeler when Brighton appointed him manager in 2024?", ["Twenty-nine", "Thirty-one", "Thirty-four"], 1,
     "Thirty-one, a German who had just won promotion with St Pauli. He was younger than some of his own players.",
     "Brighton appointing a 31-year-old is the kind of bold move that makes fans of other clubs jealous.",
     "impress", "\"Brighton hired a 31-year-old manager. Younger than some of the players.\""),
]

PACKS = [
    ("club-arsenal", "Arsenal", ARSENAL),
    ("club-aston-villa", "Aston Villa", ASTON_VILLA),
    ("club-bournemouth", "AFC Bournemouth", BOURNEMOUTH),
    ("club-brentford", "Brentford", BRENTFORD),
    ("club-brighton", "Brighton & Hove Albion", BRIGHTON),
]
