# His Club packs: Hull City, Ipswich Town, Leeds United, Liverpool, Manchester City. Rewritten 2026-09-08.
# (difficulty, question, options, answer_index, explanation, why, useType, use)

HULL = [
    (1, "What is Hull City's nickname?", ["The Tigers", "The Lions", "The Codheads"], 0,
     "The Tigers, a name from the club's first years. Commentators use it as often as the club's real name.",
     "Hear 'the Tigers' on the telly and you'll know it's his lot.",
     "say", "\"The Tigers. Easy one to remember.\""),
    (1, "What is Hull City's home ground called?", ["MKM Stadium", "Kingston Park", "Craven Park"], 0,
     "The MKM Stadium, since 2002, shared with the rugby league club Hull FC. It opened as the KC Stadium; sponsors change, the building doesn't.",
     "Ground names change with sponsors. Knowing that stops you sounding out of date either way.",
     "say", "\"The MKM. Used to be the KC. Same place.\""),
    (1, "What colours are Hull's home shirts?", ["Amber and black", "Red and white", "Blue and white"], 0,
     "Amber and black stripes, worn since the club's earliest days.",
     "Kit recognition on a small screen is the skill that lets you follow along.",
     "say", "\"Amber and black. That's Hull.\""),
    (2, "In which year was Hull City founded?", ["1888", "1904", "1919"], 1,
     "1904. Hull was a rugby league city and the football club took decades to catch on. It took them 104 years to reach the top division.",
     "A football club in a rugby town explains a lot about Hull's history.",
     "impress", "\"Hull's a rugby city. The football club took a hundred and four years to reach the top flight.\""),
    (3, "Which club did Hull beat at Wembley in the 2008 play-off final?", ["Bristol City", "Watford", "Crystal Palace"], 0,
     "Bristol City, 1-0, in front of about 86,000. It took Hull into the top division for the first time in their history.",
     "2008 is Hull's year zero. Every fan over thirty has a story about it.",
     "ask", "Ask him: \"Where were you for the 2008 play-off final?\""),
    (3, "Who scored the winning goal in Hull's 2008 play-off final?", ["Dean Windass", "Nick Barmby", "Ian Ashbee"], 0,
     "Dean Windass, a 39-year-old born in Hull who had been released by the club as a teenager, with a volley from the edge of the box. He wept on the pitch.",
     "A local boy, 39, released as a kid, scoring the goal that took his hometown up. The perfect football story.",
     "impress", "\"The winner in 2008 was scored by a 39-year-old from Hull who the club had released as a teenager.\""),
    (2, "Which manager took Hull into the Premier League in 2008?", ["Phil Brown", "Steve Bruce", "Peter Taylor"], 0,
     "Phil Brown, remembered for his suntan, his headset and one very public team talk. He sang to the fans on the pitch when they stayed up.",
     "Brown is a character. Fans of other clubs mock him; Hull fans mostly love him.",
     "say", "\"Phil Brown. The one with the tan and the headset.\""),
    (3, "In 2008 Hull's manager gave a half-time team talk on the pitch. At which club's ground?", ['Manchester City', 'Manchester United', 'Chelsea'], 0,
     "Manchester City's, on Boxing Day, 4-0 down at the break. He sat the players on the grass and lectured them. It finished 5-1; later he said he'd change nothing.",
     'The on-pitch team talk is one of the strangest sights in Premier League history. Worth knowing the details.',
     'impress', '"Hull\'s manager once did the half-time team talk on the pitch, in front of the fans. Sat them all down. They lost 5-1."'),
    (2, "Hull reached the FA Cup final in 2014 and lost to which club?", ["Arsenal", "Chelsea", "Liverpool"], 0,
     "Arsenal, 3-2 after extra time, and Hull had led 2-0 inside eight minutes. It was the club's first FA Cup final.",
     "Two-nil up in a cup final and losing is the kind of pain fans carry for life.",
     "ask", "Ask him: \"2014, two-nil up at Wembley after eight minutes. Do you ever think about it?\""),
    (2, "Who managed Hull in the 2014 FA Cup final?", ["Steve Bruce", "Phil Brown", "Nigel Adkins"], 0,
     "Steve Bruce, the former Manchester United captain. Because the winners were already in the Champions League, losing the final put Hull into Europe for the first time.",
     "Losing a final and qualifying for Europe anyway is a quirk fans enjoy explaining.",
     "impress", "\"Hull got into Europe by losing a cup final. The winners were already qualified.\""),
    (3, "In 2013 Hull's owners tried to rename the club. The FA refused. What did they want to drop?", ["The word 'City'", "The letters 'AFC'", "The word 'Hull'"], 0,
     "'City'. The owners called the word common. Fans marched, the FA said no, and the row with the owners ran on for years.",
     "Fans fighting their own owners over the club's name is a story every supporter understands.",
     'ask', 'Ask him: "Were you part of the protests when the owners tried to take \'City\' out of the name?"'),
    (2, "What was Hull's home ground before 2002?", ["Boothferry Park", "Craven Park", "Anlaby Road"], 0,
     "Boothferry Park, from 1946, which had its own railway station and, by the end, a supermarket built into one stand.",
     "A ground with a supermarket in it is a fact people remember.",
     "impress", "\"Hull's old ground had a supermarket built into one of the stands. Boothferry Park.\""),
    (1, "Hull is in which historic county?", ["Yorkshire", "Lincolnshire", "Lancashire"], 0,
     "Yorkshire, the East Riding. The city's full name is Kingston upon Hull, and it sits where the River Hull meets the Humber.",
     "Yorkshire loyalty runs deep. Getting the county right matters.",
     "say", "\"Hull's Yorkshire. East Riding, on the Humber.\""),
    (2, "Which club do Hull fans regard as their main rivals?", ["Leeds United", "Stoke City", "Norwich City"], 0,
     "Leeds United, the big club sixty miles west. Grimsby, over the Humber, is the older, smaller grudge.",
     "Rivalries tell you who he shouts at. Leeds is the answer here.",
     "say", "\"Hull and Leeds. Two cities, one long grudge.\""),
    (3, "Which Portuguese manager led Hull in the Premier League in 2016-17?", ["Marco Silva", "Paulo Fonseca", "Carlos Carvalhal"], 0,
     "Marco Silva, in his first English job. Hull went down anyway, but his reputation survived and he went on to manage Watford, Everton and Fulham.",
     "Silva is a name he will know from bigger clubs. Hull is where England first saw him.",
     "say", "\"Marco Silva started in England at Hull. Didn't keep them up, but everyone noticed him.\""),
    (3, "After relegation from the Premier League in 2017, Hull dropped to League One in which year?", ["2019", "2020", "2021"], 1,
     "2020, finishing bottom of the Championship in the pandemic season. Two relegations in three years.",
     "The fall to the third tier is the low point fans measure the current club against.",
     "ask", "Ask him: \"How bad was the League One year? Did you keep going?\""),
    (3, "Who managed Hull to the League One title?", ["Grant McCann", "Nigel Adkins", "Liam Rosenior"], 0,
     "Grant McCann, a Northern Irish former midfielder, who took them up as champions at the first attempt.",
     "Bouncing straight back is the happy half of the story. Fans like being reminded.",
     "say", "\"Grant McCann took them straight back up as champions. Didn't hang about.\""),
    (3, "Which Turkish television personality bought Hull City in 2022?", ["Acun Ilıcalı", "Fatih Terim", "Cem Yılmaz"], 0,
     "Acun Ilıcalı, the face of Turkey's version of Survivor, who built his own TV network. He promised the Premier League and, in the end, delivered it.",
     "A Turkish TV star buying an English club is a fact that stops a conversation.",
     "impress", "\"Hull were bought by the man behind Survivor in Turkey. Basically Turkish Ant and Dec.\""),
    (2, "In which year did Hull return to the Premier League for the first time since 2017?", ["2024", "2025", "2026"], 2,
     "2026, through the play-offs after finishing sixth in the Championship. Nine years away, including one in the third tier.",
     "The 2026 promotion is the one fans will talk about for years. Ask about it.",
     "ask", "Ask him: \"Where were you when they went up through the play-offs this time?\""),
    (2, "What is Hull City's mascot called?", ['Humber', 'Roary', 'Stripes'], 1,
     'Roary, a tiger in the club kit, who works the touchline before kick-off and at half-time.',
     'Mascots are safe ground when the match goes quiet.',
     'say', '"Roary. Of course the tiger\'s called Roary."'),
]

IPSWICH = [
    (1, "What is Ipswich Town's home ground called?", ["Portman Road", "Carrow Road", "Layer Road"], 0,
     "Portman Road, the club's home since 1884, a short walk from the town centre and the railway station.",
     "A ground in the middle of town makes match day easy. Handy if he ever takes you.",
     "say", "\"Portman Road. They've played there since 1884.\""),
    (1, "What is Ipswich Town's nickname?", ["The Tractor Boys", "The Canaries", "The Farmers"], 0,
     "The Tractor Boys. Rival fans meant it as a jibe about the farming county around the town; Ipswich fans adopted it and put it on scarves.",
     "The best nicknames began as insults. This is the textbook example.",
     "say", "\"Tractor Boys started as an insult. Ipswich just took it and ran.\""),
    (2, 'Ipswich beat Norwich 3-1 in October 2025. It was their first derby win in how many years?', ['Six', 'Sixteen', 'Twenty-six'], 1,
     'Sixteen. They won at Carrow Road in April 2026 too, their first league double over Norwich since 1992-93.',
     'Rivalries tell you who he shouts at. That season he shouted happily.',
     'ask', 'Ask him: "Sixteen years without beating Norwich. How good was that season?"'),
    (2, "In which year was Ipswich Town founded?", ["1878", "1888", "1898"], 0,
     "1878, though they stayed amateur until 1936 and joined the Football League in 1938. Late starters who then went all the way to the top.",
     "From amateur club to champions in a generation is a remarkable arc.",
     "impress", "\"Ipswich were amateurs until 1936. Within a generation they were champions of England.\""),
    (2, "In which year did Ipswich win the league title?", ["1962", "1972", "1982"], 0,
     "1962, in their very first season in the top division, a year after winning the second tier.",
     "Winning the league in your first top-flight season is a fact rival fans struggle to top.",
     "impress", "\"Ipswich won the title in their first ever season in the top division. 1962.\""),
    (2, "Which future England manager took Ipswich from the third tier to league champions?", ["Alf Ramsey", "Don Revie", "Graham Taylor"], 0,
     "Alf Ramsey, who arrived in 1955 with the club in the third tier and went on to win the World Championship with England. His statue stands outside the ground.",
     "Ipswich gave England the manager who won the 1966 World Championship. A national-level fact.",
     "impress", "\"Alf Ramsey made England world champions in 1966. He learned how at Ipswich.\""),
    (2, "In which year did Ipswich win the FA Cup?", ["1968", "1978", "1988"], 1,
     "1978, beating Arsenal 1-0 at Wembley. The scorer was so overcome he had to be substituted straight afterwards.",
     "A goalscorer subbed off for fainting with emotion is a story worth the telling.",
     "impress", "\"The guy who scored Ipswich's cup final winner had to come off straight after. Overcome.\""),
    (2, "Which European trophy did Ipswich win in 1981?", ["The UEFA Cup", "The Cup Winners' Cup", "The European Cup"], 0,
     "The UEFA Cup, over a two-legged final, 5-4 on aggregate, with a side that played lovely football.",
     "A town club winning a European trophy is the kind of thing that sounds made up.",
     "impress", "\"Ipswich won a European trophy in 1981. And it's a town, not even a city.\""),
    (2, "Which manager led Ipswich from 1969 to 1982, then took the England job?", ["Bobby Robson", "George Burley", "Joe Royle"], 0,
     "Bobby Robson, who went on to manage England, Barcelona and Newcastle. His statue stands outside the ground.",
     "Robson is one of English football's best-loved figures. Knowing where he started is a kindness.",
     "say", "\"Bobby Robson learned his trade at Ipswich. Thirteen years before England.\""),
    (2, "Which Northern Irish manager took Ipswich from League One to the Premier League in 2023 and 2024?", ["Kieran McKenna", "Brendan Rodgers", "Martin O'Neill"], 0,
     "Kieran McKenna, back-to-back promotions in his first two full seasons, after 22 years out of the top flight. Big clubs came calling and he stayed.",
     "Two promotions in a row is rare. McKenna is the name Ipswich fans thank for it.",
     "say", "\"McKenna took them from the third tier to the Premier League in two seasons.\""),
    (3, "Who did Ipswich beat in their 1981 European final?", ["AZ Alkmaar", "Feyenoord", "Cologne"], 0,
     "AZ Alkmaar, 3-0 at home and 2-4 away. John Wark, a midfielder, scored 14 goals in the competition that season.",
     "The Alkmaar detail separates fans who know from fans who think they know.",
     "impress", "\"They beat AZ Alkmaar in the 1981 final. Their midfielder scored fourteen European goals that year.\""),
    (1, "What colours are Ipswich Town's home shirts?", ["Blue and white", "Yellow and green", "Red and white"], 0,
     "Blue shirts and white shorts. Norwich are yellow and green, which makes the derby easy to follow.",
     "Kit colours are the first thing you need on match day.",
     "say", "\"Blue and white is Ipswich. Yellow and green is Norwich. Two different worlds.\""),
    (3, 'Who scored the winner when Ipswich beat Arsenal in an FA Cup final?', ['Roger Osborne', 'Paul Mariner', 'Kevin Beattie'], 0,
     'Roger Osborne, a local lad, in the 77th minute. He collapsed with emotion and exhaustion and was substituted moments later.',
     "Cup final goalscorers become immortal at small clubs. Osborne is Ipswich's.",
     'say', '"Roger Osborne. Scored the cup final winner and had to be taken off in tears."'),
    (1, "Ipswich is in which county?", ["Suffolk", "Norfolk", "Essex"], 0,
     "Suffolk, on the east coast. Norwich, in Norfolk, is forty miles north and the source of all the trouble.",
     "Suffolk versus Norfolk is the whole East Anglian rivalry in two words.",
     "say", "\"Suffolk. Norwich are Norfolk. That's the whole derby.\""),
    (2, "What animal is on the Ipswich Town badge?", ["A bull", "A horse", "A lion"], 1,
     "A carthorse, the county's own heavy farm breed. Norwich have a canary; Ipswich chose a horse.",
     "Badge stories are a low-cost way to show attention.",
     "say", "\"It's a farm horse on the badge. They lean into it.\""),
    (3, "Ipswich were founder members of the Premier League in which season?", ["1992-93", "1994-95", "1996-97"], 0,
     "1992-93, having won the second tier the previous year. They were relegated in 1995 after a 9-0 defeat at Manchester United.",
     "Being there at the start of the Premier League is a small badge of honour.",
     "impress", "\"Ipswich were in the very first Premier League season. Then lost 9-0 at Old Trafford and went down.\""),
    (3, "Where did Ipswich finish in 2000-01, their first Premier League season back up?", ["Third", "Fifth", "Seventh"], 1,
     "Fifth, under George Burley, which took them into Europe. Burley was voted manager of the year.",
     "Fifth in the Premier League is the season fans bring up when hopes are high.",
     "say", "\"They finished fifth in 2001. Above Chelsea. Different times.\""),
    (3, "What tongue-in-cheek name is given to the Ipswich v Norwich derby?", ["The Old Farm derby", "The Turnip derby", "The Broads derby"], 0,
     "The Old Farm derby, a joke on the Old Firm, Glasgow's Celtic against Rangers. Both sets of fans use it.",
     "A pun both sets of fans use is rare. This is one.",
     "say", "\"Old Farm derby. Even the fans call it that.\""),
    (2, "Ipswich went straight back down in 2025. Which two clubs went down with them?", ["Leicester and Southampton", "Sheffield United and Luton", "Watford and Norwich"], 0,
     "Leicester and Southampton, the other two promoted clubs. It was the second season running that all three promoted sides went straight back down.",
     "The yo-yo is the story of the club's mid-2020s. He will have views on which drop hurt more.",
     "ask", "Ask him: \"Was going down in 2025 worse because of how good 2024 had felt?\""),
    (2, "How did Ipswich win promotion back to the Premier League in 2026?", ["Finishing second", "Winning the play-offs", "Winning the Championship"], 0,
     "Second in the Championship, behind Coventry, which means automatic promotion with no play-offs. One season down, straight back up.",
     "The bounce back is the fresh good news. Lead with it.",
     "say", "\"Second in the Championship. Straight back up, no play-offs needed.\""),
]

LEEDS = [
    (1, "What is Leeds United's home ground called?", ["Elland Road", "Headingley", "Roundhay Park"], 0,
     "Elland Road, famous for being loud and hostile to visitors. Leeds fans consider that a compliment.",
     "'Elland Road under the lights' is a phrase he will say with feeling.",
     "say", "\"Elland Road on a night game. Properly hostile.\""),
    (1, "What colour do Leeds United play in?", ["All white", "Blue and white", "White and green"], 0,
     "All white, shirts, shorts and socks, since 1961. Before that Leeds wore blue and gold.",
     "All white is the quickest way to spot Leeds on a small screen.",
     "say", "\"All white. Shirts, shorts, socks. That's Leeds.\""),
    (2, "In which year was Leeds United founded?", ["1904", "1919", "1925"], 1,
     "1919, after the previous club, Leeds City, was expelled from the league for illegal payments to players. A fresh start with a new name.",
     "A club born from a scandal is a good origin story.",
     "impress", "\"Leeds United only exist because the old club got kicked out of the league for paying players illegally.\""),
    (2, "Which manager built the great Leeds team of the 1960s and 70s?", ["Don Revie", "Brian Clough", "Jimmy Armfield"], 0,
     "Don Revie, manager 1961 to 1974: two league titles, an FA Cup and a reputation for being brilliant, ruthless and hard to like. Left to manage England.",
     "Revie is the founding father of modern Leeds. His statue stands outside the ground.",
     "ask", "Ask him: \"Was Revie's Leeds dirty, or just better than everyone and hated for it?\""),
    (2, "In which year did Leeds win the league title, the third in the club's history?", ["1974", "1992", "2001"], 1,
     "1992, the final season before the Premier League began. Three titles in total: 1969, 1974 and 1992.",
     "Leeds fans point out they were champions the year before the Premier League began. A favourite line.",
     "say", "\"Leeds were the champions the year before the Premier League started. They like reminding people.\""),
    (2, 'Who managed Leeds to their third league title?', ['Howard Wilkinson', "David O'Leary", 'George Graham'], 0,
     'Howard Wilkinson, known as Sergeant Wilko. By 2026 no English manager had won the top division since.',
     'That fact comes up whenever an English manager gets a big job.',
     'ask', 'Ask him: "Is it true no English manager has won the league since Howard Wilkinson?"'),
    (2, "In which year did Leeds reach the semi-finals of the Champions League?", ["1975", "1992", "2001"], 2,
     "2001, losing to Valencia, with a young team that had beaten Deportivo and drawn with Barcelona. Then the money ran out.",
     "The 2001 run is the peak before the fall. Fans tell both halves together.",
     "ask", "Ask him: \"Do you remember the 2001 Champions League team? Before it all went wrong?\""),
    (3, "By which year had Leeds fallen to League One, the third tier, after their financial collapse?", ["2004", "2007", "2010"], 1,
     "2007, three years after leaving the Premier League. They had spent money they expected from the Champions League and it stopped coming. The phrase is 'doing a Leeds'.",
     "'Doing a Leeds' is a warning used about every over-spending club. He will know the phrase.",
     "impress", "\"'Doing a Leeds' means spending money you haven't got. They went from a Champions League semi to the third tier in a few years.\""),
    (2, "Which Argentine manager took Leeds back to the Premier League in 2020?", ["Marcelo Bielsa", "Diego Simeone", "Jorge Sampaoli"], 0,
     "Marcelo Bielsa, who sat on a blue bucket, ran the players into the ground and was adored. He ended sixteen years out of the top flight.",
     "Bielsa is a cult figure across football. Leeds fans think he is theirs.",
     "ask", "Ask him: \"Bielsa: greatest thing that ever happened to Leeds, or did he burn them out?\""),
    (2, "Who are Leeds United's fiercest rivals?", ["Manchester United", "Sheffield United", "Huddersfield Town"], 0,
     "Manchester United, in the Roses rivalry, named after the Wars of the Roses, fought five hundred years before football.",
     "A derby with a medieval origin is the one to know.",
     "impress", "\"Leeds and Man United is the Roses rivalry. It goes back to an actual war in the 1400s.\""),
    (3, "Which captain of the 1969 and 1974 title teams has a statue outside the ground?", ["Billy Bremner", "Jack Charlton", "Johnny Giles"], 0,
     "Billy Bremner, the small, red-haired Scottish midfielder who was afraid of nobody. The statue went up in 1999.",
     "The statue is the meeting point outside the ground. Knowing who it is helps.",
     "say", "\"That's Billy Bremner. The old captain. Tiny and terrifying.\""),
    (2, "Which old Leeds nickname came from a pub near the ground?", ["The Peacocks", "The Blades", "The Owls"], 0,
     "The Peacocks, after the Old Peacock pub across the road from the ground. The Blades and the Owls are the two Sheffield clubs.",
     "An obscure nickname impresses more than the obvious one.",
     "impress", "\"Leeds used to be called the Peacocks, after a pub by the ground. Hardly anyone says it now.\""),
    (2, "Why did Leeds switch to their famous kit in 1961?", ["To copy Real Madrid", "Sponsors demanded it", "To match the city's coat of arms"], 0,
     "The new manager changed it to copy Real Madrid, winners of the first five European Cups, hoping his players would carry themselves like champions.",
     "The kit as a psychological trick is a great story about ambition.",
     "say", "\"They changed the kit to copy Real Madrid. Then they started winning.\""),
    (3, 'Leeds lost the 1975 European Cup final to which club?', ['Bayern Munich', 'Ajax', 'Juventus'], 0,
     'Bayern Munich, 2-0 in Paris, after a Leeds goal was ruled out and two penalty shouts refused. Fans rioted and Leeds were banned from Europe.',
     'The 1975 final is the great Leeds grievance. Knowing it earns you a long, passionate story.',
     'ask', 'Ask him: "Paris 1975. Were Leeds robbed, honestly?"'),
    (3, "Leeds returned to the Premier League in 2025 as Championship champions with how many points?", ["90", "95", "100"], 2,
     "One hundred, level with Burnley, decided on the final day. Both went up, and Leeds took the title on goal difference.",
     "A hundred points is a number he will quote. Have it ready.",
     "say", "\"A hundred points and it came down to goal difference on the final day.\""),
    (2, "What is the name of the Leeds United club song?", ["Marching On Together", "Glory Glory Leeds", "Yorkshire Forever"], 0,
     "Marching On Together, released as a single for the 1972 FA Cup final and sung at every game since. The words are on the wall outside the ground.",
     "He knows every word. You can know the title.",
     "say", "\"Marching On Together. That's the one they all sing.\""),
    (3, "Leeds won the FA Cup in 1972 by beating which club?", ["Arsenal", "Chelsea", "Sunderland"], 0,
     "Arsenal, 1-0 in the centenary final, with an Allan Clarke diving header. By 2026 it was the club's one FA Cup win.",
     "One FA Cup, by 2026, is a stat that surprises people about a club this big.",
     "impress", "\"Leeds won the FA Cup in 1972. The centenary final, with a diving header.\""),
    (1, "Leeds is in which county?", ["Yorkshire", "Lancashire", "Derbyshire"], 0,
     "West Yorkshire. The white rose on the badge is the county's symbol.",
     "Yorkshire is not a county to Yorkshire people; it is a nationality. Get it right.",
     "say", "\"Yorkshire. Don't say 'up north' to a Leeds fan, say Yorkshire.\""),
    (3, "Which player did Leeds sell to Manchester United in the 1990s, a deal they came to regret?", ["Eric Cantona", "Lee Chapman", "David Batty"], 0,
     "Eric Cantona, in November 1992, for about £1.2 million. He won four titles in five years at Old Trafford.",
     "Selling Cantona is the transfer Leeds fans wince at.",
     "impress", "\"Leeds sold Cantona to Man United for about a million. Then he won four titles for them.\""),
    (2, "Which German manager led Leeds to promotion in 2025?", ["Daniel Farke", "Jesse Marsch", "Thomas Tuchel"], 0,
     "Daniel Farke, who had already taken Norwich up twice, in 2019 and 2021. He knew the Championship inside out.",
     "Farke is the name on the 2025 promotion. Fans judge him on what came after.",
     "ask", "Ask him: \"Was Farke the man for the Premier League, or just brilliant in the Championship?\""),
]

LIVERPOOL = [
    (1, "What is Liverpool's home ground called?", ["Anfield", "Goodison Park", "Stanley Park"], 0,
     "Anfield, since 1892. It was Everton's ground first, until a rent row saw Everton leave and the landlord start a new club to play there.",
     "Liverpool exist because of a landlord dispute. Evertonians love telling this; get in first.",
     "impress", "\"Liverpool were founded because Everton fell out with their landlord over rent at Anfield.\""),
    (1, "Which song do Liverpool fans sing before every home match?", ["You'll Never Walk Alone", "Blue Moon", "Marching On Together"], 0,
     "You'll Never Walk Alone, a show tune from the musical Carousel, adopted in 1963 after a Liverpool band had a hit with it. The words are on the gates at the ground.",
     "A football anthem that began life as a Broadway ballad.",
     "impress", "\"You'll Never Walk Alone is from a musical. Carousel, 1945. They took it from a pop cover.\""),
    (2, "Liverpool's league title in 2025 was the club's how-manyth?", ["Eighteenth", "Nineteenth", "Twentieth"], 2,
     "Twentieth, drawing level with Manchester United. The nineteenth had ended a thirty-year wait.",
     "Twenty versus United's twenty is the count he keeps. Know the number.",
     "say", "\"Twenty titles by 2025. Level with United. That's the argument at every family dinner.\""),
    (2, "How many times had Liverpool won the European Cup or Champions League by 2025?", ["Four", "Five", "Six"], 2,
     "Six: 1977, 1978, 1981, 1984, 2005 and 2019. By 2025 no other English club had as many, which Liverpool fans mention regularly.",
     "Six European Cups is the number that ends arguments with United fans.",
     "say", "\"Six European Cups. Ask a United fan how many they've got.\""),
    (1, 'Liverpool came back from 3-0 down to win the 2005 Champions League final against which club?', ['AC Milan', 'Juventus', 'Real Madrid'], 0,
     'AC Milan, in Istanbul: 3-0 down at half-time, three goals in six minutes early in the second half, then won on penalties. The miracle of Istanbul.',
     'Istanbul is the comeback every football fan knows. Every Liverpool fan can tell you where they were.',
     'ask', 'Ask him: "Istanbul 2005. Where were you at half-time?"'),
    (1, "Which German managed Liverpool from 2015 to 2024?", ["Jürgen Klopp", "Thomas Tuchel", "Ralf Rangnick"], 0,
     "Jürgen Klopp: hugs, heavy-metal football, a Champions League and a league title after thirty years. He left as one of the best-loved managers the club had known.",
     "Klopp is the manager she has probably heard of even without football. He is the reference point.",
     "say", "\"Klopp. Nine years, everyone loved him, then he just left on his own terms.\""),
    (2, "In which year did Liverpool end their thirty-year wait for a league title?", ["2019", "2020", "2022"], 1,
     "2020, during the pandemic, with seven games to spare and an empty stadium. Fans celebrated outside the ground anyway.",
     "Thirty years of waiting then no crowd to celebrate is the bittersweet note in the story.",
     "ask", "Ask him: \"Winning it in lockdown with no fans in. Did it feel real?\""),
    (3, "Which striker scored 346 goals for Liverpool across two spells in the 1980s and 90s?", ["Ian Rush", "Roger Hunt", "Robbie Fowler"], 0,
     "Ian Rush, a Welsh striker with a moustache and a knack for scoring against Everton. By 2025 nobody had scored more for the club.",
     "Rush is the name older fans reach for whenever goalscorers come up.",
     "ask", "Ask him: \"Will anyone ever catch Ian Rush's 346?\""),
    (1, "Which two clubs are Liverpool's main rivals?", ["Everton and Man United", "Everton and Leeds", "Manchester City and Chelsea"], 0,
     "Everton, across the park, in the Merseyside derby; and Manchester United, thirty miles away, a rivalry built on decades of fighting over trophies.",
     "Two rivals, two different kinds of hate. Knowing which is which matters.",
     "say", "\"Everton's the local one. United's the real one.\""),
    (3, "The Kop, Anfield's famous stand, is named after what?", ["A hill in the Boer War", "A Liverpool docker", "A Norwegian word for stand"], 0,
     "Spion Kop, a hill in South Africa where many soldiers from Liverpool died in a battle in 1900. The steep terrace reminded people of it.",
     "The name has a war behind it. That is worth knowing before you shout it.",
     "impress", "\"The Kop's named after a hill in the Boer War where Liverpool soldiers died.\""),
    (2, "Which Scot managed Liverpool from 1959 to 1974 and has a statue outside Anfield?", ["Bill Shankly", "Bob Paisley", "Kenny Dalglish"], 0,
     "Bill Shankly, who took them up from the second division and built the modern club. The Shankly Gates went up in his honour in 1982, and his quotes turn up everywhere.",
     "Shankly quotes get used at every Liverpool occasion. Know the man behind them.",
     "say", "\"Shankly said football's more important than life and death. He was joking. Mostly.\""),
    (3, 'Which Liverpool manager won three European Cups between 1977 and 1981?', ['Bob Paisley', 'Joe Fagan', 'Kenny Dalglish'], 0,
     'Bob Paisley, the quiet assistant who stepped up in 1974 and turned out to be even more successful: six league titles and three European Cups in nine years.',
     'The quiet assistant who out-won his famous boss is a lovely twist to know.',
     'impress', '"Paisley won three European Cups. Nobody talks about him because he didn\'t do quotes."'),
    (3, "Steven Gerrard's long-range equaliser in the 2006 FA Cup final came against which club?", ["West Ham", "Chelsea", "Arsenal"], 0,
     "West Ham, in the final minute, from 35 yards, with cramp. Liverpool won on penalties. People call it the Gerrard final.",
     "A final named after one player tells you what he meant to them.",
     "say", "\"The Gerrard final. Thirty-five yards, last minute, cramp in both legs.\""),
    (2, "Mohamed Salah joined Liverpool in 2017 from which club?", ["Roma", "Chelsea", "Fiorentina"], 0,
     "Roma, for about £37 million, after Chelsea had given up on him. He scored 44 goals in his first season.",
     "Chelsea letting Salah go is the transfer regret rivals enjoy raising.",
     "ask", "Ask him: \"Is Salah the best signing Liverpool have ever made?\""),
    (3, "Virgil van Dijk joined Liverpool in 2018 from which club?", ["Southampton", "Celtic", "Ajax"], 0,
     "Southampton, for £75 million, a world record for a defender at the time. Liverpool reached the next two Champions League finals with him.",
     "Van Dijk changed Liverpool overnight. The fee looked mad and then looked cheap.",
     "say", "\"Seventy-five million for a defender looked mad. Then they won everything.\""),
    (2, "Who took over at Liverpool in 2024 and won the title in his first season?", ["Arne Slot", "Xabi Alonso", "Ruben Amorim"], 0,
     "Arne Slot, from Feyenoord. Calm where his predecessor was loud, and champion within a year.",
     "Following a legend and winning the league immediately is rare. Slot did it.",
     "ask", "Ask him: \"Did Slot win that title, or was it the team he inherited?\""),
    (2, "Who did Liverpool beat in the 2019 Champions League final?", ["Tottenham Hotspur", "Manchester City", "Real Madrid"], 0,
     "Tottenham, 2-0 in Madrid, with a penalty in the second minute, a year after losing the final to Real Madrid.",
     "An all-English final is the kind of night that gets relived. He will remember the penalty.",
     "say", "\"Madrid 2019. Penalty in the second minute and that was that.\""),
    (3, "In the 2019 comeback against Barcelona, who took the quick corner for the winning goal?", ["Trent Alexander-Arnold", "Alex Oxlade-Chamberlain", "Xherdan Shaqiri"], 0,
     "Trent Alexander-Arnold, a local lad, while Barcelona's defenders were not looking. Divock Origi tapped it in to complete a 4-0 win from 3-0 down.",
     "'Corner taken quickly' is a phrase Liverpool fans say as a catchphrase. This is why.",
     "impress", "\"'Corner taken quickly, Origi.' That's the commentary from the Barcelona game. Fans quote it.\""),
    (1, "What bird is on the Liverpool badge?", ["The liver bird", "A magpie", "A cockerel"], 0,
     "The liver bird, the city's symbol, a cormorant with a sprig of seaweed in its beak. It is on the town hall and the Liver Building too.",
     "Reading the badge is knowing the city.",
     "say", "\"That's the liver bird. It's all over the city, not just the club.\""),
    (3, "Kenny Dalglish joined Liverpool in 1977 from which club?", ["Celtic", "Rangers", "Aberdeen"], 0,
     "Celtic, for £440,000, to replace Kevin Keegan. He became a club great, then its manager, and won the league in both roles.",
     "King Kenny is the name older fans say with reverence. A stand at the ground carries his name.",
     "say", "\"King Kenny. Player, manager, won the league as both. There's a stand named after him.\""),
]

MAN_CITY = [
    (1, "What is Manchester City's home ground called?", ["Etihad Stadium", "Old Trafford", "Emirates Stadium"], 0,
     "The Etihad Stadium, built for the 2002 Commonwealth Games and converted for football. Officially the City of Manchester Stadium.",
     "An athletics stadium turned football ground is a good bit of context.",
     "say", "\"The Etihad was built for the Commonwealth Games. City moved in after.\""),
    (2, "Where did Manchester City play before they moved grounds in 2003?", ["Maine Road", "Hyde Road", "Old Trafford"], 0,
     "Maine Road, in Moss Side, from 1923 to 2003. In 1934 it held 84,569 for an FA Cup game against Stoke.",
     "Older City fans get misty about Maine Road. It is where the club's soul lived before the money.",
     "ask", "Ask him: \"Did you ever go to Maine Road? Everyone says it was a different club then.\""),
    (1, "What colour are Manchester City's home shirts?", ["Sky blue", "Red", "Navy blue"], 0,
     "Sky blue, since the 1890s. The fans' song is Blue Moon, sung slowly and sadly, which suited the club for much of its history.",
     "Blue Moon before every game is one of football's odder rituals. Knowing why it is sad helps.",
     "say", "\"Blue Moon. They sing it slow, from when City were rubbish. It stuck.\""),
    (1, "Which Spanish manager took charge of Manchester City in 2016?", ["Pep Guardiola", "Roberto Mancini", "Mikel Arteta"], 0,
     "Pep Guardiola, who had won everything at Barcelona and Bayern. Six league titles in his first eight seasons at City and a treble in 2023.",
     "Guardiola is the manager every other manager is compared to. His City years are the benchmark.",
     "ask", "Ask him: \"Is Guardiola the best manager there's ever been, or did the money do it?\""),
    (2, "In which year was Manchester City bought by Abu Dhabi's Sheikh Mansour?", ["2003", "2008", "2012"], 1,
     "2008, on the final day of the transfer window. They signed Robinho the same afternoon and the modern City began.",
     "Everything about City splits into before and after 2008.",
     "say", "\"2008. Before that they were a joke club. After that, well.\""),
    (2, "In which year did Manchester City win their first Premier League title?", ["2010", "2012", "2014"], 1,
     "2012, with Agüero's goal in the final seconds of the final game against QPR, to beat United on goal difference. Their first title since 1968.",
     "The Agüero moment is the one every football fan remembers, City or not.",
     "say", "\"Agüerooo. Last kick of the season. Even neutrals remember where they were.\""),
    (2, "Which English club won the league, FA Cup and European Cup treble before City did in 2023?", ["Manchester United", "Liverpool", "Nottingham Forest"], 0,
     "Manchester United, in 1999, under Alex Ferguson. City matching United's treble was a big part of the joy.",
     "The treble is the peak of the Guardiola era, and the United comparison is half the fun.",
     "say", "\"2023 treble. United had done it in 1999, and City loved matching it.\""),
    (2, "Who did Manchester City beat in the 2023 Champions League final?", ["Inter Milan", "Real Madrid", "Bayern Munich"], 0,
     "Inter Milan, 1-0 in Istanbul, with a goal from Rodri. Their first European Cup, after years of trying.",
     "The first European Cup is the trophy City fans waited longest for.",
     "say", "\"Rodri scored the goal in Istanbul. First European Cup, finally.\""),
    (2, "How many goals did Erling Haaland score in the 2022-23 Premier League season?", ["34", "36", "40"], 1,
     "Thirty-six, in his first season in England, beating a mark that had stood since 1994. Also 52 in all competitions.",
     "Thirty-six is the number he will quote when defending Haaland in any argument.",
     "say", "\"Thirty-six league goals in his first season. In England. At 22.\""),
    (2, "In 2024 City became the first English club to win how many consecutive league titles?", ["Three", "Four", "Five"], 1,
     "Four in a row, 2021 to 2024. Nobody had done more than three before.",
     "Four in a row is the argument for that City side being the best England had produced.",
     "impress", "\"Four titles in a row. Nobody had ever done that in England.\""),
    (2, "What did Alex Ferguson call City in 2009, after the money arrived?", ["The noisy neighbours", "The poor relations", "The small club down the road"], 0,
     "The noisy neighbours, a jibe from United's manager once City started spending big. City fans took it as a compliment.",
     "The derby decides who owns Manchester that week, and this line is part of the story.",
     "say", "\"The noisy neighbours. Ferguson's line. Aged badly for him.\""),
    (3, "In the 1999 play-off final against Gillingham, who scored City's 95th-minute equaliser?", ["Paul Dickov", "Shaun Goater", "Kevin Horlock"], 0,
     "Paul Dickov, at Wembley, with City 2-0 down and in the third tier. They won on penalties. Fans talk about it as the goal that saved the club.",
     "City in the third division in 1999 is the fact that makes the modern club astonishing.",
     "impress", "\"City were in the third division in 1999. Hard to believe now, isn't it?\""),
    (3, "In which year did Manchester City win the European Cup Winners' Cup?", ["1956", "1970", "1976"], 1,
     "1970, beating Górnik Zabrze of Poland in Vienna. Their one European trophy until 2023.",
     "City fans of a certain age had one European trophy to cling to for fifty years. This is it.",
     "impress", "\"City won a European trophy in 1970 and then nothing in Europe until 2023.\""),
    (3, "The Colin Bell Stand at City's ground is named after a 1960s midfielder nicknamed what?", ["Nijinsky", "The King", "The Engine"], 0,
     "Nijinsky, after a famous racehorse, because he could run all day. A stand is named after him, the sign of a true club great.",
     "A footballer nicknamed after a horse is a fact worth having on hand.",
     "impress", "\"Colin Bell was nicknamed after a racehorse. Nijinsky. Because he ran all day.\""),
    (3, "Which Spanish playmaker, nicknamed El Mago, has a statue outside City's ground?", ["David Silva", "Sergio Agüero", "Vincent Kompany"], 0,
     "David Silva, the magician, ten seasons and four titles, with a statue alongside Agüero's and Kompany's. Small, left-footed, impossible to tackle.",
     "Three statues outside the ground; knowing all three names is the full set.",
     "say", "\"Silva, Agüero, Kompany. The three statues. That's the team that started it.\""),
    (2, "In which year did Manchester City beat Manchester United 6-1 at Old Trafford?", ["2011", "2014", "2019"], 0,
     "2011, in October. Balotelli scored and lifted his shirt to reveal the words 'Why always me?'",
     "6-1 at Old Trafford is the scoreline City fans bring to every derby argument.",
     "say", "\"Six-one at Old Trafford. 'Why always me?' That whole day was ridiculous.\""),
    (2, "What is Manchester City's nickname?", ["The Citizens", "The Moonrakers", "The Mancs"], 0,
     "The Citizens, though fans mostly just say City. Cityzens, with a z, is what the club calls its members.",
     "Nicknames are how fans refer to their own. Get this one right and he notices.",
     "say", "\"City. Nobody actually says the Citizens.\""),
    (2, "What did many fans call City's new ground at first, after the area it was built in?", ["Eastlands", "Salford Quays", "Didsbury"], 0,
     "Eastlands, old industrial land in east Manchester that was rebuilt around the stadium, with a training campus and an arena added later.",
     "Knowing where the ground is turns a match into a day out.",
     "say", "\"People used to call it Eastlands. East Manchester, all rebuilt around the ground.\""),
    (3, "Which Chilean manager won the Premier League with Manchester City in 2014?", ["Manuel Pellegrini", "Roberto Mancini", "Mark Hughes"], 0,
     "Manuel Pellegrini, the first manager from outside Europe to win the Premier League. Quiet, polite, and gone by 2016.",
     "The manager between two bigger names is the one everyone forgets. Remembering him is the trick.",
     "impress", "\"Pellegrini won City a title in 2014 and nobody ever mentions him. First non-European to win it.\""),
    (3, "In which year did Manchester City win their first league title?", ["1904", "1937", "1968"], 1,
     "1937. They were relegated the very next season while scoring more goals than anyone in the division. 'Typical City', fans said for decades.",
     "'Typical City' is what older fans say about any self-inflicted disaster. This is where it comes from.",
     "impress", "\"City won the league in 1937 and got relegated the next year. That's where 'typical City' comes from.\""),
]

PACKS = [
    ("club-hull", "Hull City", HULL),
    ("club-ipswich", "Ipswich Town", IPSWICH),
    ("club-leeds", "Leeds United", LEEDS),
    ("club-liverpool", "Liverpool", LIVERPOOL),
    ("club-man-city", "Manchester City", MAN_CITY),
]
