# The four general packs, rewritten 2026-09-08 (CONTENT_PRINCIPLES.md).
# (difficulty, question, options, answer_index, explanation, why, useType, use)
# No superlatives tied to the present. Every question carries its use.

BASICS = [
    (1, "How many points does a team get for winning a match?", ["One", "Two", "Three", "Four"], 2,
     "Three for a win, one for a draw, nothing for a loss. Add them up and that is the whole league table.",
     "Every conversation about the table is a conversation about points. This is the currency.",
     "say", "\"Ugly win, but three points is three points.\""),
    (1, "How many clubs are in the Premier League?", ["16", "18", "20", "24"], 2,
     "Twenty clubs. Each plays the other nineteen twice, home and away, which makes 38 games a season.",
     "It tells you how long the season is and why one bad month is not the end of the world.",
     "say", "\"It's 38 games. One bad month doesn't decide it.\""),
    (1, "How many clubs go down to the Championship at the end of a season?", ["One", "Two", "Three", "Four"], 2,
     "The bottom three are relegated and three come up to replace them. Relegation costs a club a fortune and its best players.",
     "Come spring, half the league is talking about nothing else.",
     "ask", "Ask him: \"Who do you think goes down this year?\" He has a list."),
    (1, "How long is a match, before any added time?", ["60 minutes", "80 minutes", "90 minutes", "120 minutes"], 2,
     "Two halves of 45 minutes. Added time on top makes up for stoppages, so it usually runs closer to 100.",
     "So you know when it is actually over, and why \"two minutes left\" takes ten.",
     "say", "\"Ninety minutes plus whatever he adds. Could be a while.\""),
    (1, "How many players does each team have on the pitch at kick-off?", ["Nine", "Ten", "Eleven", "Twelve"], 2,
     "Eleven a side, one of them the goalkeeper. Lose a player to a red card and it is ten men.",
     "\"Down to ten men\" is meaningless unless you know it started at eleven.",
     "say", "\"Ten men now. They'll sit back and defend.\""),
    (1, "Which colour card means a player is sent off?", ["Yellow", "Red", "Blue", "Black"], 1,
     "Red means off. Yellow is a warning, and two yellows in one game add up to a red.",
     "The sofa reacts to a red card before the commentator does. You want to be in on it.",
     "say", "\"That's a red. Early bath for him.\""),
    (1, "Which player is allowed to handle the ball inside their own penalty area?", ["The captain", "The goalkeeper", "Any defender", "Nobody"], 1,
     "The goalkeeper, and only inside the box. Step outside it and the same rules apply as for everyone else.",
     "Half of all shouting at the telly is about handball. Knowing the one exception makes you sound sure.",
     "say", "\"Keeper's outside his box, he can't pick that up.\""),
    (2, "How far from goal is a penalty kick taken?", ["Eight yards", "Ten yards", "Twelve yards", "Eighteen yards"], 2,
     "Twelve yards, straight in front of goal, only the keeper to beat. Around three in four go in.",
     "A penalty is the tensest moment in a match and he will want company for it.",
     "say", "\"Twelve yards, keeper to beat. Don't look at me, I can't watch either.\""),
    (1, "What does VAR stand for?", ["Video Assistant Referee", "Visual Analysis Review", "Video Appeal Rule", "Verified Action Replay"], 0,
     "Video Assistant Referee: a team in a room checking goals, penalties and red cards on replay while everyone waits.",
     "\"VAR is checking\" happens every single match and stops the room dead. Knowing why buys you the pause.",
     "say", "\"VAR's checking it. Don't celebrate yet.\""),
    (2, "Since 2022, how many substitutions can a Premier League team make in a match?", ["Three", "Four", "Five", "Seven"], 2,
     "Five, in three separate stoppages plus half-time. It was three for decades before the rule changed in 2022.",
     "Substitutions are where he judges the manager. Knowing the limit lets you join the judging.",
     "ask", "Ask him: \"He's used all five already? Bit early for that?\""),
    (1, "What happens when a league match ends level?", ["Extra time", "A penalty shootout", "Both teams get a point", "A replay"], 2,
     "A draw: one point each. Extra time and penalties only happen in cup games that must have a winner.",
     "So you know a league draw is over at the whistle, and a cup draw is just getting started.",
     "say", "\"It's the league, so that's it. Point each.\""),
    (1, "What is a clean sheet?", ["A win by three goals", "Letting in no goals", "No yellow cards", "A new kit"], 1,
     "Letting in nothing. The goalkeeper's favourite statistic, and the defence's bragging right.",
     "It is the compliment that makes him think you watched the whole match.",
     "say", "\"Another clean sheet. The defence has been solid.\""),
    (1, "A hat-trick is how many goals by one player in one match?", ["Two", "Three", "Four", "Five"], 1,
     "Three. Two is a brace. There is no word for four, which tells you how rare it is. The player keeps the match ball.",
     "He will say brace and hat-trick without explaining them. Now you do not need him to.",
     "say", "\"Two already. One more and it's a hat-trick.\""),
    (1, "Which division sits directly below the Premier League?", ["League One", "The Championship", "The National League", "The Conference"], 1,
     "The Championship, confusingly named: winning it makes you promoted, not champions of much.",
     "\"They'll be in the Championship next year\" is the insult of choice in spring.",
     "ask", "Ask him: \"Which of the clubs that came up do you think stays up?\""),
    (2, "How do the three promoted clubs get out of the Championship?", ["All three via play-offs", "Top two plus a play-off winner", "Top three automatically", "A vote"], 1,
     "The top two go up automatically. The next four play a mini knockout for the third place; its final is called the richest game in football.",
     "Late May, the play-off final is on and he knows someone whose club is in it.",
     "say", "\"Play-off final. One game for a hundred million pounds.\""),
    (2, "When two teams finish level on points, what usually separates them?", ["Goals scored", "Goal difference", "Head-to-head", "Alphabetical order"], 1,
     "Goal difference: goals scored minus goals let in. It is why a 4-0 win matters more than a 1-0 win late in a season.",
     "Title races and relegation fights come down to it, and it is the bit he loves explaining.",
     "impress", "\"They're level on points, so it's on goal difference. Every goal counts now.\""),
    (1, "When can clubs buy and sell players?", ["Any time", "Summer and January", "Only in summer", "Only at Christmas"], 1,
     "Two transfer windows: the summer, and the month of January. Outside them, nothing moves, whatever the newspapers say.",
     "Transfer rumours are half of what he reads. Knowing when they can actually happen is the filter.",
     "say", "\"Window's shut. That rumour can't happen until January.\""),
    (2, "How long is each half of extra time in a cup match?", ["Ten minutes", "Fifteen minutes", "Twenty minutes", "Thirty minutes"], 1,
     "Two halves of fifteen minutes, played when a cup match is level after ninety. If it is level after that, it is penalties.",
     "Cup nights run late. This is how you know exactly how late.",
     "say", "\"Extra time. Thirty more minutes, then penalties. Put the kettle on.\""),
    (2, "In a penalty shootout, how many kicks does each side take before sudden death?", ["Three", "Five", "Seven", "Ten"], 1,
     "Five each, alternating. If it is level after that, one each until somebody misses. England fans have suffered here.",
     "The one moment he cannot look at the screen. You can be the one who knows the format.",
     "say", "\"Five each, then sudden death. Who's taking the fifth?\""),
    (2, "Which is the oldest cup competition in the world?", ["The League Cup", "The Champions League", "The FA Cup", "The World Cup"], 2,
     "The FA Cup, first played in 1871. Every club in England can enter, so a village team can end up playing Liverpool.",
     "January cup weekends are about small clubs beating big ones. That is the whole charm, and now you know why.",
     "ask", "Ask him: \"Any giant-killings this weekend?\""),
    (1, "What is a match between two local rivals called?", ["A classic", "A derby", "A final", "A friendly"], 1,
     "A derby, pronounced darby. Manchester, Merseyside, North London: same city, decades of grudges.",
     "Derby week changes his mood for a fortnight. Naming it correctly is the least you can do.",
     "ask", "Ask him: \"It's the derby this weekend, isn't it? Are you nervous?\""),
    (2, "Which body runs the Champions League?", ["FIFA", "UEFA", "The FA", "The Premier League"], 1,
     "UEFA, European football's governing body. FIFA runs the World Cup. Neither is loved.",
     "Midweek European nights are a separate mood. Knowing who runs them is the first step.",
     "say", "\"UEFA night. Different anthem, different vibe.\""),
    (2, "Over two legs, what decides which team goes through?", ["The second-leg score only", "The aggregate score", "A coin toss", "The home team's score"], 1,
     "The aggregate: add the two scores together. Win the first leg 2-0 and lose the second 1-0, you go through 2-1 overall.",
     "European knockout nights are impossible to follow without this. With it, you are ahead of half the pub.",
     "ask", "Ask him: \"So what's the aggregate? Who's actually ahead?\""),
    (1, "What is nil in football?", ["A draw", "Zero", "An injury", "A foul"], 1,
     "Zero. A goalless draw is nil-nil, a 2-0 win is two-nil. Football has its own word for nothing.",
     "Saying \"two-zero\" marks you as a newcomer faster than anything else.",
     "say", "\"Two-nil. Comfortable, that.\""),
    (1, "Which two domestic cup competitions do English clubs enter?", ["The FA Cup and the League Cup", "The FA Cup and the Europa League", "The League Cup and the play-offs", "The FA Cup and the Champions League"], 0,
     "The FA Cup and the League Cup (Carabao Cup). Both are knockouts run alongside the league; the European competitions are separate again.",
     "He will switch between three competitions in a single week and assume you know which is which.",
     "ask", "Ask him: \"Is this the league or one of the cups?\""),
    (1, "What happens to a team that loses a cup match?", ["They are out of that competition", "They drop a division", "They lose three points", "They play a replay next week"], 0,
     "Cups are knockouts: lose once and that competition is finished for the season. In the league a defeat costs points and you carry on.",
     "It explains why a cup defeat lands harder than a league one, even against a small club.",
     "say", "\"That's them out, then. No second chance in the cup.\""),
    (1, "What is Wembley?", ["England's national stadium", "A London club's training ground", "The Premier League trophy", "A cup competition"], 0,
     "England's national stadium, in north London. Both domestic cup finals are played there, along with the FA Cup semi-finals and England's home games.",
     "\"A trip to Wembley\" is how fans describe a cup run that has gone deep, and it comes up every spring.",
     "ask", "Ask him: \"Have you ever been to a game at Wembley?\""),
    (2, "Why do big clubs often pick a weaker side in the early League Cup rounds?", ["To rest players for bigger games", "It is a rule of the competition", "Their best players are banned", "To save money on wages"], 0,
     "Rotation. With league games and European nights stacked up, a manager rests his first-choice players and hands the young ones a game instead.",
     "It stops a weak line-up looking like a disaster and gets you into the argument about priorities.",
     "impress", "\"He's rotated for this. The league game at the weekend is the priority.\""),
    (2, "Which is Europe's third club competition, below the Europa League?", ["The Conference League", "The Championship", "The Community Shield", "The Super Cup"], 0,
     "The Conference League, played on Thursday nights like the Europa League. Smaller trophy, same format, and a European away day either way.",
     "European nights come in three varieties and he will not say which one he means.",
     "ask", "Ask him: \"Is that the Europa League or the Conference League?\""),
    (2, "In a two-legged cup round, where is the second leg played?", ["At the other team's ground", "At a neutral ground", "At the same ground as the first", "Wherever the winner chooses"], 0,
     "One match at each ground, so both sides get a home game. The two scores are added together and the aggregate decides who goes through.",
     "European knockout nights make no sense until you know that both matches count as one.",
     "say", "\"Second leg at home. They just need to keep it tight.\""),
]

LEGENDS = [
    (1, "Alan Shearer retired in 2006 with how many Premier League goals?", ["160", "200", "260", "300"], 2,
     "260, for Blackburn and Newcastle. Nobody had passed it by 2024, and he has been on Match of the Day ever since.",
     "His name comes up every time a striker scores a lot. Now you know why he is the yardstick.",
     "impress", "\"Nobody's near Shearer's 260, are they? Kane didn't get there.\""),
    (1, "Thierry Henry is a legend at which club?", ["Chelsea", "Arsenal", "Liverpool", "Manchester United"], 1,
     "Arsenal, where he scored 228 goals and has a statue outside the ground. Elegant, quick, French, and adored.",
     "He is the player Arsenal fans of a certain age measure everyone against.",
     "ask", "Ask him: \"Henry or Bergkamp, who was better?\" Then sit back."),
    (1, "Who managed Manchester United from 1986 to 2013?", ["José Mourinho", "Sir Alex Ferguson", "Arsène Wenger", "Sir Bobby Robson"], 1,
     "Sir Alex Ferguson: thirteen league titles, two Champions Leagues, and a stand named after him. Every manager since is compared to him.",
     "Half of football's phrases are his: Fergie time, the hairdryer, squeaky bum time.",
     "say", "\"Nobody's matched Ferguson's thirteen titles. Nobody's going to.\""),
    (2, "Who scored the injury-time goal that won Manchester City the title in 2012?", ["Sergio Agüero", "Edin Džeko", "Yaya Touré", "Mario Balotelli"], 0,
     "Sergio Agüero, in the 94th minute of the final game, against QPR, to snatch the title from United on goal difference. The commentary is just 'Agüerooo'.",
     "It is the moment fans use to explain why football is worth the stress.",
     "say", "\"Agüerooo. That's why people put themselves through this.\""),
    (1, "Steven Gerrard spent almost his whole career at which club?", ["Everton", "Liverpool", "Chelsea", "Leeds"], 1,
     "Liverpool, 1998 to 2015, as captain. He dragged them to the 2005 Champions League from 3-0 down. Then he became a manager, less happily.",
     "The one-club captain is a type he admires. Gerrard is the template.",
     "say", "\"Gerrard was Liverpool. You don't get one-club players like that now.\""),
    (1, "Which Frenchman managed Arsenal from 1996 to 2018?", ["Gérard Houllier", "Arsène Wenger", "Didier Deschamps", "Claude Puel"], 1,
     "Arsène Wenger. Three titles, the unbeaten 2003-04 season, and he changed how English clubs ate and trained. Fans sing his name to this day.",
     "Wenger is the reason Arsenal fans talk about football as an art form.",
     "ask", "Ask him: \"Was Wenger a genius or did he stay too long?\" Both answers are strongly held."),
    (2, "Frank Lampard scored 211 goals for which club, more than any striker in its history?", ["West Ham", "Chelsea", "Manchester City", "Everton"], 1,
     "Chelsea, over thirteen years. Two hundred and eleven goals from midfield is absurd; strikers would take it.",
     "He is the answer to \"which midfielder scored like a striker\", a debate he has had.",
     "impress", "\"Lampard got 211 for Chelsea from midfield. From midfield.\""),
    (2, "Harry Kane passed Jimmy Greaves in 2023 to become the top scorer in the history of which club?", ["Arsenal", "Tottenham Hotspur", "Manchester United", "Leicester"], 1,
     "Tottenham. Kane then left for Bayern Munich, chasing the trophies he had not won at Spurs.",
     "Kane is the polite, decent superstar every fan respects, even rivals.",
     "ask", "Ask him: \"Was Kane right to leave Spurs for Bayern?\""),
    (2, "Peter Schmeichel kept goal for which club in the 1990s?", ["Liverpool", "Manchester United", "Arsenal", "Aston Villa"], 1,
     "Manchester United, five league titles, a huge Dane in a green jersey. His son Kasper won the league with Leicester in 2016.",
     "Father and son both won the league. That is the fun fact, and it is yours.",
     "impress", "\"Schmeichel and his son both won the league. Different clubs, twenty years apart.\""),
    (2, "Eric Cantona kicked a fan in 1995 while playing for which club?", ["Leeds United", "Manchester United", "Chelsea", "Arsenal"], 1,
     "Manchester United, at Crystal Palace. He was banned for eight months, then came back and won the double. Collar up, always.",
     "Cantona is the reference for any moody genius footballer. Now you get the reference.",
     "say", "\"Bit of a Cantona moment, that.\" (When a player loses his temper spectacularly.)"),
    (2, "Which Welsh winger won thirteen league titles with Manchester United?", ["Gareth Bale", "Ryan Giggs", "Mark Hughes", "Aaron Ramsey"], 1,
     "Ryan Giggs, one club for his whole career, 1991 to 2014. Thirteen titles with one team.",
     "He is the standard for loyalty and longevity. Any long-serving player gets compared to him.",
     "impress", "\"Giggs won thirteen titles at one club. Twenty-three years.\""),
    (2, "Gianfranco Zola, a Chelsea favourite of the late 1990s, came from which country?", ["Spain", "Italy", "Argentina", "Portugal"], 1,
     "Italy. Small, brilliant, and voted Chelsea's greatest ever player by fans in 2003, before the money arrived.",
     "Older Chelsea fans light up at his name. It is a kindness to know it.",
     "ask", "Ask him: \"Did you ever see Zola play? Everyone says he was magic.\""),
    (2, "Roy Keane, the fierce captain known as Keano, led which club in the 1990s and 2000s?", ["Liverpool", "Manchester United", "Celtic", "Leeds"], 1,
     "Manchester United, and Ireland. Terrifying midfielder, now a pundit who is terrifying to other pundits.",
     "He is on TV every week saying something brutal. Knowing his history explains the tone.",
     "say", "\"Roy Keane wouldn't have stood for that.\" (When a player looks like he isn't trying.)"),
    (1, "Which Liverpool forward is nicknamed the Egyptian King?", ["Sadio Mané", "Mohamed Salah", "Roberto Firmino", "Luis Díaz"], 1,
     "Mohamed Salah, who joined from Roma in 2017 and scored 32 league goals in his first season, a new high for a 38-game campaign at the time.",
     "The song fans sing about him is one he will know all the words to.",
     "ask", "Ask him: \"Is Salah the best signing Liverpool ever made?\""),
    (2, "Didier Drogba scored the winning penalty in the 2012 Champions League final for which club?", ["Arsenal", "Chelsea", "Manchester United", "Liverpool"], 1,
     "Chelsea, in Bayern Munich's own stadium. He had also scored the late equaliser. The man for the big occasion, and he knew it.",
     "\"Big-game player\" is a phrase he uses. Drogba is who he means.",
     "say", "\"He's a bit of a Drogba. Only turns up for the big ones.\""),
    (2, "Wayne Rooney's overhead kick in the 2011 Manchester derby was scored for which club?", ["Everton", "Manchester City", "Manchester United", "England"], 2,
     "Manchester United. Voted the best goal in the first twenty years of the Premier League. He started at Everton and ended as United's top scorer.",
     "It is the goal that gets replayed whenever anyone scores an overhead kick.",
     "say", "\"Rooney against City. That's the overhead kick everyone means.\""),
    (2, "Who captained Manchester City to their first Premier League title in 2012?", ["Vincent Kompany", "David Silva", "Joe Hart", "Carlos Tevez"], 0,
     "Vincent Kompany, the Belgian centre-back with a statue outside the Etihad. He later became a manager and won the Bundesliga with Bayern.",
     "Kompany is the answer when City fans get misty about the club before the trophies were routine.",
     "ask", "Ask him: \"Kompany or Rodri, who mattered more to City?\""),
    (3, "Who scored a hat-trick in under three minutes for Southampton in 2015?", ["Sadio Mané", "Jamie Vardy", "Robbie Fowler", "Sergio Agüero"], 0,
     "Sadio Mané, 2 minutes 56 seconds against Aston Villa. He later won everything at Liverpool alongside Salah.",
     "The fastest-hat-trick pub question. Having the answer ready is pure impress.",
     "impress", "\"Mané did a hat-trick in under three minutes once. Under three minutes.\""),
    (2, "Who managed Leicester City to the 2016 Premier League title?", ["Brendan Rodgers", "Claudio Ranieri", "Nigel Pearson", "Craig Shakespeare"], 1,
     "Claudio Ranieri, the Italian nobody expected anything from. Leicester had started the season as 5000-1 outsiders. Sacked nine months later.",
     "Leicester 2016 is the fairy tale every small club fan mentions. It is the proof that it can happen.",
     "say", "\"Leicester won it at 5000-1. Anything can happen.\" (When his team are underdogs.)"),
    (2, "Robin van Persie left Arsenal in 2012 to join which club?", ["Chelsea", "Manchester United", "Manchester City", "Barcelona"], 1,
     "Manchester United, where he won the title in his first season. Arsenal fans consider it a betrayal, United fans a masterstroke.",
     "Players leaving for rivals is the sorest subject in football. This is the classic case.",
     "ask", "Ask him: \"Worst betrayal in football: Van Persie or Sol Campbell?\""),
    (1, "Which Belgian midfielder was Manchester City's playmaker for a decade from 2015?", ["Eden Hazard", "Kevin De Bruyne", "Romelu Lukaku", "Vincent Kompany"], 1,
     "Kevin De Bruyne: passes nobody else saw, six league titles, and Chelsea let him go for almost nothing first.",
     "He is the modern example of a playmaker, the word you will hear in every tactical chat.",
     "say", "\"De Bruyne saw passes nobody else did. That's what a playmaker is.\""),
    (2, "David Beckham scored from the halfway line in 1996 playing for which club?", ["England", "Manchester United", "Real Madrid", "Preston North End"], 1,
     "Manchester United, against Wimbledon, on the opening day of the season. It made him famous overnight. Then came Posh.",
     "Beckham is the crossover celebrity; this goal is where it started.",
     "impress", "\"That's where Beckham started. Halfway line, first game of the season, 1996.\""),
]

CLUBS_RIVALRIES = [
    (1, "The North London derby is between Arsenal and which club?", ["Chelsea", "Tottenham Hotspur", "West Ham", "Fulham"], 1,
     "Tottenham. Four miles apart, and the grudge dates to 1913, when Arsenal moved north into Spurs' patch uninvited.",
     "If he supports either club, this fixture decides his mood for a fortnight.",
     "ask", "Ask him: \"Do you actually know why Arsenal and Spurs hate each other?\" Plenty of fans don't."),
    (1, "Which two clubs play the Merseyside derby?", ["Liverpool and Everton", "Liverpool and Man Utd", "Everton and Tranmere", "Liverpool and Leeds"], 0,
     "Liverpool and Everton, whose grounds were a short walk apart across a park. Families in the city are split down the middle.",
     "It is called the friendly derby because relatives sit together. It has more red cards than any other fixture.",
     "impress", "\"The friendly derby, and it's had more red cards than any other. Bit ironic.\""),
    (1, "The Manchester derby is City against whom?", ["Liverpool", "Manchester United", "Leeds United", "Bolton"], 1,
     "Manchester United. City spent decades in United's shadow; United fans called them the noisy neighbours. The noise has got louder.",
     "The derby is a status contest as much as a match. Knowing the history explains the heat.",
     "say", "\"Noisy neighbours. That's what Ferguson called City.\""),
    (2, "Which two clubs contest the M23 derby?", ["Brighton and Crystal Palace", "Southampton and Portsmouth", "Reading and Oxford", "Watford and Luton"], 0,
     "Brighton and Crystal Palace, forty miles apart along the M23. It began as a feud between two managers in the 1970s and simply carried on.",
     "Nobody outside the two clubs understands it, so knowing about it marks you as someone who pays attention.",
     "ask", "Ask him: \"Why do Brighton and Palace hate each other? They're miles apart.\""),
    (2, "The Tyne-Wear derby is Newcastle against which club?", ["Middlesbrough", "Sunderland", "Leeds", "Hull"], 1,
     "Sunderland. Two rivers, twelve miles, and well over a century of mutual dislike. When both are in the Premier League, the region stops.",
     "It is the fixture northern fans mention when southerners talk about derbies.",
     "say", "\"Tyne-Wear derby. That one's properly nasty.\""),
    (1, "Which club is nicknamed the Gunners?", ["Chelsea", "Arsenal", "West Ham", "Aston Villa"], 1,
     "Arsenal, founded by workers at the Royal Arsenal munitions factory in 1886. Hence the cannon on the badge.",
     "Nicknames come up in every match: the Gunners, the Reds, the Blues. This one has the best story.",
     "impress", "\"They're the Gunners because the club started at a weapons factory. Hence the cannon.\""),
    (2, "Which club is known as the Toffees?", ["Everton", "Liverpool", "Leeds", "Bolton"], 0,
     "Everton, after a toffee shop near the ground. Before home games a woman in old-fashioned dress throws sweets into the crowd, to this day.",
     "The Toffee Lady is the kind of detail that makes a fan grin. It is yours now.",
     "impress", "\"Everton have a Toffee Lady who throws sweets to the crowd. That's why they're the Toffees.\""),
    (1, "Which club is nicknamed the Magpies?", ["Newcastle United", "Sunderland", "Fulham", "Brentford"], 0,
     "Newcastle, for the black and white stripes. The fans are the Toon Army, and they are loud.",
     "\"The Toon\" is what he will call Newcastle without explaining. Now it needs no explaining.",
     "say", "\"The Toon are at home. St James' will be bouncing.\""),
    (2, "Which club is nicknamed the Cherries?", ["Southampton", "AFC Bournemouth", "Brentford", "Nottingham Forest"], 1,
     "Bournemouth, for the cherry-red shirts and the cherry orchards that stood near the old ground.",
     "A small club with a smaller ground and a nice story. Good to have when they come up in conversation.",
     "say", "\"The Cherries. Tiny ground, about eleven thousand.\""),
    (2, "Which club is nicknamed the Bees?", ["Watford", "Brentford", "Barnet", "Burnley"], 1,
     "Brentford, in west London. The badge is a bee, the fans chant 'buzz', and the club runs on statistics rather than money.",
     "Brentford are the club clever fans admire. Knowing them is a signal.",
     "impress", "\"Brentford scrapped their academy and built a team on data. And it worked.\""),
    (2, "Which club is nicknamed the Seagulls?", ["Brighton & Hove Albion", "Bournemouth", "Southampton", "Portsmouth"], 0,
     "Brighton. The name started as a chant to wind up Crystal Palace fans, who sing 'Eagles'. Rivalry gave them their identity.",
     "Two seaside birds, one grudge. It is a good line and it is true.",
     "impress", "\"Brighton only became the Seagulls to annoy Palace. Eagles versus Seagulls.\""),
    (2, "Which club is nicknamed the Villans?", ["Aston Villa", "West Ham", "Wolves", "Birmingham City"], 0,
     "Aston Villa, spelt with an a. One of the oldest clubs in England, founder members of the Football League in 1888, and European champions in 1982.",
     "Villa fans feel undervalued. Knowing they won the European Cup is the way to their heart.",
     "impress", "\"Villa won the European Cup in 1982. People forget that.\""),
    (2, "Which club is nicknamed the Cottagers?", ["Fulham", "Chelsea", "Brentford", "QPR"], 0,
     "Fulham, whose ground, Craven Cottage, has an actual cottage in one corner. London's oldest professional club, from 1879.",
     "The prettiest ground in London, on the Thames. Good for a day out, good for a line.",
     "say", "\"Craven Cottage. There's an actual cottage in the corner of the ground.\""),
    (2, "Which club is nicknamed the Black Cats?", ["Newcastle", "Sunderland", "Hull City", "Swansea"], 1,
     "Sunderland. A black cat was the club's lucky mascot at a cup final in 1937, and fans voted the name official in 2000.",
     "Sunderland fans are famously loyal through misery. The Netflix series about them is the reference.",
     "ask", "Ask him: \"Did you watch Sunderland 'Til I Die? Was it as painful as it looked?\""),
    (2, "Which club plays in claret and blue and has Birmingham City as its city rival?", ["West Ham", "Aston Villa", "Burnley", "Scunthorpe"], 1,
     "Aston Villa. West Ham and Burnley borrowed the claret and blue from Villa. The Birmingham fixture is the Second City derby.",
     "Three clubs, one colour scheme. He may not know who had it first.",
     "ask", "Ask him: \"Who had claret and blue first, Villa or West Ham?\" It was Villa."),
    (2, "Which two clubs contest the East Anglian derby?", ["Ipswich and Norwich", "Ipswich and Colchester", "Norwich and Peterborough", "Cambridge and Ipswich"], 0,
     "Ipswich Town and Norwich City, forty miles apart. Fans joke it is the Old Farm derby, a pun on Glasgow's Old Firm.",
     "The pun alone is worth knowing. It always gets a laugh from the right crowd.",
     "say", "\"The Old Farm derby. Ipswich and Norwich. It's a farming joke.\""),
    (3, "Leeds United's rivalry with Manchester United is known as what?", ["The War of the Pennines", "The Roses rivalry", "The Northern derby", "The M62 derby"], 1,
     "The Roses rivalry: Yorkshire's white rose against Lancashire's red, from a war fought five hundred years before football existed.",
     "It is the one derby with a medieval origin story. Perfect impress material.",
     "impress", "\"Leeds and United is the Roses rivalry. It goes back to an actual war in the 1400s.\""),
    (2, "Who are Chelsea's nearest neighbours in the Premier League?", ["Fulham", "QPR", "Brentford", "Watford"], 0,
     "Fulham. Stamford Bridge and Craven Cottage are under two miles apart, both in the same borough.",
     "West London derbies are lower-key, and he wants them won all the same.",
     "say", "\"Chelsea and Fulham are basically neighbours. Two miles apart.\""),
    (2, "Which club is nicknamed the Sky Blues?", ["Manchester City", "Coventry City", "Lazio", "Wycombe"], 1,
     "Coventry City. A 1960s manager, Jimmy Hill, changed the kit to sky blue and wrote the fans' song to go with it.",
     "Coventry are the romantic story: a big-city club that fell to the fourth tier and climbed all the way back.",
     "impress", "\"Coventry were in the fourth division in 2018. Now look at them.\""),
    (2, "Which club is nicknamed the Tractor Boys?", ["Norwich", "Ipswich Town", "Lincoln", "Peterborough"], 1,
     "Ipswich Town, from Suffolk farming country. Rival fans meant it as an insult; Ipswich fans adopted it and put it on scarves.",
     "The best nicknames were insults first. This is a good example to have ready.",
     "say", "\"Tractor Boys started as an insult from other fans. Ipswich just took it.\""),
    (2, "Which club is nicknamed the Eagles?", ["Crystal Palace", "Brighton", "Watford", "Charlton"], 0,
     "Crystal Palace, in south London. For years a real bald eagle called Kayla flew round the ground before matches.",
     "A live eagle at a football match is a fact people do not believe. Enjoy telling it.",
     "impress", "\"Palace used to have an actual eagle flying round the pitch before games.\""),
    (1, "Which club's fans sing You'll Never Walk Alone before every home game?", ["Manchester United", "Liverpool", "Celtic", "Everton"], 1,
     "Liverpool, since the 1960s. It is a show tune from a musical, and the words are over the gates at Anfield.",
     "It is the one football song everyone has heard. Knowing whose it is matters.",
     "say", "\"You'll Never Walk Alone. Every Liverpool game, scarves up. Gets me every time.\""),
]

BADGES_GROUNDS = [
    (1, "Which club plays at the Emirates Stadium?", ["Chelsea", "Arsenal", "West Ham", "Spurs"], 1,
     "Arsenal, since 2006. Before that they played at Highbury, a few hundred yards away, which is now flats with the pitch as a garden.",
     "\"At the Emirates\" is how he will say Arsenal are at home. It also has a fun afterlife story.",
     "impress", "\"Highbury's flats now. The old pitch is the communal garden.\""),
    (1, "Anfield is the home of which club?", ["Everton", "Liverpool", "Manchester United", "Leeds"], 1,
     "Liverpool. It was Everton's ground first, until a rent row in 1892 sent Everton across the park and left the landlord to start Liverpool.",
     "Liverpool only exist because of a landlord dispute. That is a genuinely good story.",
     "impress", "\"Liverpool were founded because Everton fell out with their landlord over rent.\""),
    (1, "Old Trafford is the home of which club?", ["Manchester City", "Manchester United", "Bolton", "Blackburn"], 1,
     "Manchester United, since 1910. Bobby Charlton called it the Theatre of Dreams and the name stuck.",
     "The nickname turns up in every United broadcast. Knowing who coined it is the extra step.",
     "say", "\"Theatre of Dreams. Bobby Charlton's line, wasn't it?\""),
    (1, "Stamford Bridge is the home of which club?", ["Fulham", "Chelsea", "QPR", "Brentford"], 1,
     "Chelsea. The stadium existed before the club: it was built in 1877 and Chelsea were founded in 1905 to fill it, in a pub over the road.",
     "A club invented to fill an empty stadium is the kind of fact that flips a conversation.",
     "impress", "\"Chelsea were founded in a pub to fill a stadium that was already there.\""),
    (2, "Which club's badge shows a cockerel standing on a football?", ["Tottenham Hotspur", "Arsenal", "Aston Villa", "Norwich"], 0,
     "Spurs. The cockerel has been on the badge and the roof since 1909, and it wears spurs on its legs, which is the pun.",
     "He has looked at that badge a thousand times without noticing the spurs. You can be the one who did.",
     "ask", "Ask him: \"Have you noticed the cockerel on the Spurs badge is wearing spurs?\""),
    (2, "Which club's badge features the liver bird?", ["Everton", "Liverpool", "Leeds", "Birmingham"], 1,
     "Liverpool. The liver bird is the city's symbol, a cormorant holding seaweed in its beak, on the town hall and the badge.",
     "Badge stories are how you show you looked properly.",
     "say", "\"That's the liver bird. It's on the buildings all over the city too.\""),
    (2, "Villa Park is the home of which club?", ["Aston Villa", "West Ham", "Birmingham City", "Wolves"], 0,
     "Aston Villa, since 1897. The huge stand behind one goal is the Holte End, and the ground has hosted more FA Cup semi-finals than any other.",
     "Villa Park is a ground fans of every club have visited for a semi-final. He will have a memory of it.",
     "ask", "Ask him: \"Have you ever been to Villa Park? Everyone seems to have a semi-final story.\""),
    (2, "Goodison Park was for over a century the home of which club?", ["Liverpool", "Everton", "Tranmere", "Preston"], 1,
     "Everton, from 1892 until they moved to a new stadium on the docks in 2025. Goodison was the first purpose-built football ground in England.",
     "Grounds closing is an emotional subject. Knowing this one shows you understand why.",
     "ask", "Ask him: \"Did you ever go to Goodison before they left? People say it was special.\""),
    (1, "St James' Park is the home of which club?", ["Sunderland", "Newcastle United", "Exeter City", "Leeds"], 1,
     "Newcastle. Right in the city centre; you can see the stands from the shops. Fans in the top tier are famously far from the pitch.",
     "It is the ground people mean when they say a stadium is part of the city.",
     "say", "\"St James' is right in the middle of town. You can walk from the shops.\""),
    (2, "Which club's badge shows a red devil holding a trident?", ["Manchester United", "Liverpool", "Nottingham Forest", "Sunderland"], 0,
     "Manchester United. Matt Busby borrowed the Red Devils name from a Salford rugby team in the 1960s, and the devil joined the badge in 1970.",
     "Even United fans rarely know the devil came from rugby. That is the point of knowing it.",
     "impress", "\"The Red Devils name came from a rugby league team in Salford. Busby nicked it.\""),
    (1, "Which club has a cannon on its badge?", ["Arsenal", "Portsmouth", "Sunderland", "Chelsea"], 0,
     "Arsenal, for the Royal Arsenal weapons works in Woolwich where the club began. The cannon has pointed in different directions over the years.",
     "Badge, nickname and origin story all in one. Efficient.",
     "say", "\"Cannon on the badge, Gunners as the nickname. It all comes from the weapons factory.\""),
    (2, "Which club's badge is a bee?", ["Brentford", "Barnet", "Watford", "Burnley"], 0,
     "Brentford. Red and white stripes and a bee, for the Bees. Their old ground, Griffin Park, had a pub on every corner.",
     "Four pubs, four corners is a fact he may already love. If not, he will now.",
     "impress", "\"Brentford's old ground had a pub on every corner. All four.\""),
    (2, "Which club's badge shows an eagle perched on a football?", ["Crystal Palace", "Brighton", "Bournemouth", "Coventry"], 0,
     "Crystal Palace. Below the eagle is a drawing of the actual Crystal Palace, the giant glass exhibition hall the club is named after. It burned down in 1936.",
     "The club is named after a building that no longer exists. Good to know why.",
     "impress", "\"Palace are named after a glass palace that burned down in 1936. It's on the badge.\""),
    (2, "Craven Cottage is the home of which club?", ["Chelsea", "Fulham", "Brentford", "QPR"], 1,
     "Fulham, on the bank of the Thames. There is a real cottage in one corner, and the stand finished in 2024 has a rooftop swimming pool.",
     "A stadium with a swimming pool is a fact worth having.",
     "impress", "\"Fulham's new stand has a rooftop pool. At a football ground.\""),
    (2, "The City Ground is the home of which club?", ["Manchester City", "Nottingham Forest", "Coventry", "Bristol City"], 1,
     "Nottingham Forest, on the River Trent. Notts County's ground is three hundred yards away across the water, the closest two grounds in England.",
     "Two league grounds you can see from each other. Nobody expects that fact.",
     "impress", "\"Forest and Notts County's grounds are 300 yards apart. You can see one from the other.\""),
    (2, "Which club plays at the Stadium of Light?", ["Benfica", "Sunderland", "Newcastle", "Everton"], 1,
     "Sunderland, since 1997. It was built on a coal mine, and the name honours the miners' lamps. Benfica's ground in Lisbon has the same name.",
     "Two Stadiums of Light is a decent pub question, and the coal mine is the better half of the answer.",
     "impress", "\"The Stadium of Light's built on an old coal mine. The name's for the miners' lamps.\""),
    (2, "Elland Road is the home of which club?", ["Leeds United", "Sheffield United", "Huddersfield", "Bradford"], 0,
     "Leeds United, since 1919. Known for being loud and hostile to visiting teams, which Leeds fans consider a compliment.",
     "\"Elland Road on a night game\" is a phrase he will use with feeling.",
     "say", "\"Elland Road under the lights. Proper hostile.\""),
    (1, "Which club plays at the smallest ground in Premier League history, holding about 11,000?", ["AFC Bournemouth", "Brighton", "Brentford", "Luton"], 0,
     "Bournemouth, at the Vitality Stadium, also called Dean Court. Some Championship grounds are three times the size.",
     "Ground size is a bragging point. Knowing the smallest gives you a comparison for everything.",
     "say", "\"Bournemouth's ground holds eleven thousand. That's smaller than some rugby clubs.\""),
    (2, "Which club plays at the ground known as the Amex?", ["Brighton & Hove Albion", "Bournemouth", "Brentford", "Burnley"], 0,
     "Brighton, at Falmer on the edge of the Downs. It took fourteen years of planning fights to build; before that they played on an athletics track.",
     "Brighton's rise from homeless to European football is a story fans respect.",
     "impress", "\"Brighton played on an athletics track for twelve years before the Amex. Now they're in Europe.\""),
    (3, "Which club's badge shows a ship above three diagonal stripes for the city's rivers?", ["Liverpool", "Manchester City", "Sunderland", "Hull City"], 1,
     "Manchester City. The ship is for the Ship Canal and the city's trade, the stripes for its three rivers, and the red rose is for Lancashire.",
     "Reading a badge like a map is a small party trick. This is the best badge for it.",
     "impress", "\"City's badge is a map: the ship's the canal, the stripes are the three rivers.\""),
    (2, "Portman Road is the home of which club?", ["Norwich", "Ipswich Town", "Colchester", "Southend"], 1,
     "Ipswich Town, since 1884, their home for the club's entire history. Two managers who went on to run England have statues outside.",
     "Ipswich are a small club with a big history. The statues are the proof.",
     "impress", "\"Two England managers came from Ipswich. Ramsey and Robson, both have statues outside.\""),
    (2, "Which club's badge features a tree?", ["Nottingham Forest", "Norwich", "Leeds", "Sherwood Rangers"], 0,
     "Nottingham Forest. A tree above wavy lines for the River Trent, designed by a fan in a competition in 1973.",
     "Forest are the club with two European Cups and a badge drawn by a supporter. Both are worth knowing.",
     "impress", "\"Forest's badge was designed by a fan in a competition. And they've won two European Cups.\""),
]

PACKS = [
    ("the-basics", "The Basics", BASICS),
    ("legends", "Legends", LEGENDS),
    ("clubs-rivalries", "Clubs & Rivalries", CLUBS_RIVALRIES),
    ("badges-grounds", "Badges & Grounds", BADGES_GROUNDS),
]
