# The four general packs, rewritten 2026-09-08 (CONTENT_PRINCIPLES.md).
# (difficulty, question, options, answer_index, explanation, why, useType, use)
# No superlatives tied to the present. Every question carries its use.

BASICS = [
    (1, "How many points does a team get for winning a match?", ["One", "Two", "Three"], 2,
     "Three for a win, one for a draw, nothing for a loss. Add them up and that is the whole league table.",
     "Every conversation about the table is a conversation about points. This is the currency.",
     "say", "\"Ugly win, but three points is three points.\""),
    (1, "How many clubs are in the Premier League?", ["18", "20", "24"], 1,
     "Twenty clubs. Each plays the other nineteen twice, home and away, which makes 38 games a season.",
     "It tells you how long the season is and why one bad month is not the end of the world.",
     "say", "\"It's 38 games. One bad month doesn't decide it.\""),
    (1, "How many clubs go down to the Championship at the end of a season?", ["One", "Two", "Three"], 2,
     "The bottom three are relegated and three come up to replace them. Relegation costs a club a fortune and its best players.",
     "Come spring, half the league is talking about nothing else.",
     "ask", "Ask him: \"Who do you think goes down this year?\" He has a list."),
    (1, "How long is a match, before any added time?", ["80 minutes", "90 minutes", "120 minutes"], 1,
     "Two halves of 45 minutes. Added time on top makes up for stoppages, so it usually runs closer to 100.",
     "So you know when it is actually over, and why \"two minutes left\" takes ten.",
     "say", "\"Ninety minutes plus whatever he adds. Could be a while.\""),
    (1, "How many players does each team have on the pitch at kick-off?", ["Ten", "Eleven", "Twelve"], 1,
     "Eleven a side, one of them the goalkeeper. Lose a player to a red card and it is ten men.",
     "\"Down to ten men\" is meaningless unless you know it started at eleven.",
     "say", "\"Ten men now. They'll sit back and defend.\""),
    (1, "Which colour card means a player is sent off?", ["Yellow", "Red", "Blue"], 1,
     "Red means off. Yellow is a warning, and two yellows in one game add up to a red.",
     "The sofa reacts to a red card before the commentator does. You want to be in on it.",
     "say", "\"That's a red. Early bath for him.\""),
    (1, "Which player is allowed to handle the ball inside their own penalty area?", ["The captain", "The goalkeeper", "Any defender"], 1,
     "The goalkeeper, and only inside the box. Step outside it and the same rules apply as for everyone else.",
     "Half of all shouting at the telly is about handball. Knowing the one exception makes you sound sure.",
     "say", "\"Keeper's outside his box, he can't pick that up.\""),
    (2, "How far from goal is a penalty kick taken?", ["Ten yards", "Twelve yards", "Eighteen yards"], 1,
     "Twelve yards, straight in front of goal, only the keeper to beat. Around three in four go in.",
     "A penalty is the tensest moment in a match and he will want company for it.",
     "say", "\"Twelve yards, keeper to beat. Don't look at me, I can't watch either.\""),
    (1, "What does VAR stand for?", ["Video Assistant Referee", "Visual Analysis Review", "Verified Action Replay"], 0,
     "Video Assistant Referee: a team in a room checking goals, penalties and red cards on replay while everyone waits.",
     "\"VAR is checking\" happens every single match and stops the room dead. Knowing why buys you the pause.",
     "say", "\"VAR's checking it. Don't celebrate yet.\""),
    (2, "Since 2022, how many substitutions can a Premier League team make in a match?", ["Three", "Four", "Five"], 2,
     "Five, in three separate stoppages plus half-time. It was three for decades before the rule changed in 2022.",
     "Substitutions are where he judges the manager. Knowing the limit lets you join the judging.",
     "ask", "Ask him: \"He's used all five already? Bit early for that?\""),
    (1, "What happens when a league match ends level?", ["Extra time", "A penalty shootout", "A point each"], 2,
     "A draw: one point each. Extra time and penalties only happen in cup games that must have a winner.",
     "So you know a league draw is over at the whistle, and a cup draw is just getting started.",
     "say", "\"It's the league, so that's it. Point each.\""),
    (1, "What is a clean sheet?", ["Winning by three goals", "Letting in no goals", "No yellow cards"], 1,
     "Letting in nothing. The goalkeeper's favourite statistic, and the defence's bragging right.",
     "It is the compliment that makes him think you watched the whole match.",
     "say", "\"Another clean sheet. The defence has been solid.\""),
    (1, "A hat-trick is how many goals by one player in one match?", ["Two", "Three", "Four"], 1,
     "Three. Two is a brace. There is no word for four, which tells you how rare it is. The player keeps the match ball.",
     "He will say brace and hat-trick without explaining them. Now you do not need him to.",
     "say", "\"Two already. One more and it's a hat-trick.\""),
    (1, "Which division sits directly below the Premier League?", ["League One", "The Championship", "The National League"], 1,
     "The Championship, confusingly named: winning it makes you promoted, not champions of much.",
     "\"They'll be in the Championship next year\" is the insult of choice in spring.",
     "ask", "Ask him: \"Which of the clubs that came up do you think stays up?\""),
    (2, 'How do the three promoted clubs get out of the Championship?', ['All three through the play-offs', 'Top two plus a play-off winner', 'Top three automatically'], 1,
     'The top two go up automatically. The next four play a mini knockout for the third promotion place, with a final at Wembley worth well over £100 million.',
     'Late May, the play-off final is on and he knows someone whose club is in it.',
     'say', '"Play-off final. One game worth over a hundred million pounds."'),
    (2, "When two teams finish level on points, what usually separates them?", ["Goals scored", "Goal difference", "Head-to-head"], 1,
     "Goal difference: goals scored minus goals let in. It is why a 4-0 win matters more than a 1-0 win late in a season.",
     "Title races and relegation fights come down to it, and it is the bit he loves explaining.",
     "impress", "\"They're level on points, so it's on goal difference. Every goal counts now.\""),
    (1, "When can clubs buy and sell players?", ["Any time", "Summer and January", "Only in summer"], 1,
     "Two transfer windows: the summer, and the month of January. Outside them, nothing moves, whatever the newspapers say.",
     "Transfer rumours are half of what he reads. Knowing when they can actually happen is the filter.",
     "say", "\"Window's shut. That rumour can't happen until January.\""),
    (2, "How long is each half of extra time in a cup match?", ["Fifteen minutes", "Twenty minutes", "Thirty minutes"], 0,
     "Two halves of fifteen minutes, played when a cup match is level after ninety. If it is level after that, it is penalties.",
     "Cup nights run late. This is how you know exactly how late.",
     "say", "\"Extra time. Thirty more minutes, then penalties. Put the kettle on.\""),
    (2, "In a penalty shootout, how many kicks does each side take before sudden death?", ["Three", "Five", "Seven"], 1,
     "Five each, alternating. If it is level after that, one each until somebody misses. England fans have suffered here.",
     "The one moment he cannot look at the screen. You can be the one who knows the format.",
     "say", "\"Five each, then sudden death. Who's taking the fifth?\""),
    (2, "Which is the oldest cup competition in the world?", ["The League Cup", "The FA Cup", "The World Cup"], 1,
     "The FA Cup, first played in 1871. Hundreds of clubs enter, so a village team can end up playing Liverpool.",
     "January cup weekends are about small clubs beating big ones. That is the whole charm, and now you know why.",
     "ask", "Ask him: \"Any giant-killings this weekend?\""),
    (1, "What is a match between two local rivals called?", ["A classic", "A derby", "A friendly"], 1,
     "A derby, pronounced darby. Manchester, Merseyside, North London: same city, decades of grudges.",
     "Derby week changes his mood for a fortnight. Naming it correctly is the least you can do.",
     "ask", "Ask him: \"It's the derby this weekend, isn't it? Are you nervous?\""),
    (2, "Which body runs the Champions League?", ["FIFA", "UEFA", "England's FA"], 1,
     "UEFA, European football's governing body. FIFA runs the World Cup. Neither is loved.",
     "Midweek European nights are a separate mood. Knowing who runs them is the first step.",
     "say", "\"UEFA night. Different anthem, different vibe.\""),
    (2, "Over two legs, what decides which team goes through?", ["The second-leg score only", "The aggregate score", "The home team's score"], 1,
     "The aggregate: add the two scores together. Win the first leg 2-0 and lose the second 1-0, you go through 2-1 overall.",
     "European knockout nights are impossible to follow without this. With it, you are ahead of half the pub.",
     "ask", "Ask him: \"So what's the aggregate? Who's actually ahead?\""),
    (1, "What is nil in football?", ["A draw", "Zero", "A foul"], 1,
     "Zero. A goalless draw is nil-nil, a 2-0 win is two-nil. Football has its own word for nothing.",
     "Saying \"two-zero\" marks you as a newcomer faster than anything else.",
     "say", "\"Two-nil. Comfortable, that.\""),
    (1, "Which two domestic cup competitions do English clubs enter?", ["The FA Cup and the League Cup", "The FA Cup and the Europa League", "The FA Cup and the Champions League"], 0,
     "The FA Cup and the League Cup (Carabao Cup). Both are knockouts run alongside the league; the European competitions are separate again.",
     "He will switch between three competitions in a single week and assume you know which is which.",
     "ask", "Ask him: \"Is this the league or one of the cups?\""),
    (1, "What happens to a team that loses a cup match?", ["They are out of that competition", "They lose three points", "They play a replay next week"], 0,
     "Cups are knockouts: lose once and that competition is finished for the season. In the league a defeat costs points and you carry on.",
     "It explains why a cup defeat lands harder than a league one, even against a small club.",
     "say", "\"That's them out, then. No second chance in the cup.\""),
    (1, "What is Wembley?", ["England's national stadium", "A London club's training ground", "A cup competition"], 0,
     "England's national stadium, in north London. Both domestic cup finals are played there, along with the FA Cup semi-finals and England's home games.",
     "\"A trip to Wembley\" is how fans describe a cup run that has gone deep, and it comes up every spring.",
     "ask", "Ask him: \"Have you ever been to a game at Wembley?\""),
    (2, "Why do big clubs often pick a weaker side in the early League Cup rounds?", ["To rest players for bigger games", "It is a rule of the competition", "To save money on wages"], 0,
     "Rotation. With league games and European nights stacked up, a manager rests his first-choice players and hands the young ones a game instead.",
     "It stops a weak line-up looking like a disaster and gets you into the argument about priorities.",
     "impress", "\"He's rotated for this. The league game at the weekend is the priority.\""),
    (2, "Which is Europe's third club competition, below the Europa League?", ["The Conference League", "The Community Shield", "The Super Cup"], 0,
     "The Conference League, played on Thursday nights like the Europa League. Smaller trophy, same format, and a European away day either way.",
     "European nights come in three varieties and he will not say which one he means.",
     "ask", "Ask him: \"Is that the Europa League or the Conference League?\""),
    (2, "In a two-legged cup round, where is the second leg played?", ["At the other team's ground", "At a neutral ground", "At the same ground as the first"], 0,
     "One match at each ground, so both sides get a home game. Whoever is at home second has their own crowd behind them for the finish.",
     "European knockout nights make more sense once you know each side gets a home leg.",
     "say", "\"Second leg at home. They just need to keep it tight.\""),
]

LEGENDS = [
    (1, "Alan Shearer retired in 2006 with how many Premier League goals?", ["200", "260", "300"], 1,
     "260, for Blackburn and Newcastle. By 2024 nobody had passed it; Harry Kane left for Germany in 2023 on 213.",
     "His name comes up every time a striker scores a lot. Now you know why he is the yardstick.",
     "impress", "\"Shearer got 260 in the Premier League. Kane left for Bayern on 213.\""),
    (1, "Thierry Henry is a legend at which club?", ["Chelsea", "Arsenal", "Liverpool"], 1,
     "Arsenal, where he scored 228 goals and has a statue outside the ground. Elegant, quick, French, and adored.",
     "He is the player Arsenal fans of a certain age measure everyone against.",
     "ask", "Ask him: \"Henry or Bergkamp, who was better?\" Then sit back."),
    (1, "Who managed Manchester United from 1986 to 2013?", ["Sir Alex Ferguson", "Arsène Wenger", "Sir Bobby Robson"], 0,
     "Sir Alex Ferguson: thirteen league titles, two Champions Leagues, and a stand named after him. Every manager since is compared to him.",
     "Half of football's phrases are his: Fergie time, the hairdryer, squeaky bum time.",
     "say", "\"Thirteen titles in 27 years. No wonder every United manager gets compared to Fergie.\""),
    (2, "Who scored the injury-time goal that won Manchester City the title in 2012?", ["Sergio Agüero", "Edin Džeko", "Mario Balotelli"], 0,
     "Sergio Agüero, in the 94th minute of the final game, against QPR, to snatch the title from United on goal difference. The commentary is just 'Agüerooo'.",
     "It is the moment fans use to explain why football is worth the stress.",
     "say", "\"Agüerooo. That's why people put themselves through this.\""),
    (1, "Steven Gerrard spent almost his whole career at which club?", ["Everton", "Liverpool", "Chelsea"], 1,
     "Liverpool, 1998 to 2015, as captain. He dragged them to the 2005 Champions League from 3-0 down. Then he became a manager, less happily.",
     "The one-club captain is a type he admires. Gerrard is the template.",
     "say", "\"Gerrard was Liverpool. You don't get one-club players like that now.\""),
    (1, "Which Frenchman managed Arsenal from 1996 to 2018?", ["Gérard Houllier", "Arsène Wenger", "Didier Deschamps"], 1,
     "Arsène Wenger. Three titles, the unbeaten 2003-04 season, and he changed how English clubs ate and trained. His statue went up at the Emirates in 2023.",
     "Wenger is the reason Arsenal fans talk about football as an art form.",
     "ask", "Ask him: \"Was Wenger a genius or did he stay too long?\" Both answers are strongly held."),
    (2, "Frank Lampard scored 211 goals from midfield for which club?", ["West Ham", "Chelsea", "Manchester City"], 1,
     "Chelsea, over thirteen years, 2001 to 2014. Two hundred and eleven goals from midfield is absurd; strikers would take it.",
     "He is the answer to \"which midfielder scored like a striker\", a debate he has had.",
     "impress", "\"Lampard got 211 for Chelsea from midfield. From midfield.\""),
    (2, "Harry Kane passed Jimmy Greaves in 2023 to become the top scorer in the history of which club?", ["Arsenal", "Tottenham Hotspur", "Manchester United"], 1,
     "Tottenham. Kane then left for Bayern Munich, chasing the trophies he had not won at Spurs.",
     "Kane is the polite, decent superstar every fan respects, even rivals.",
     "ask", "Ask him: \"Was Kane right to leave Spurs for Bayern?\""),
    (2, "Peter Schmeichel kept goal for which club in the 1990s?", ["Liverpool", "Manchester United", "Nottingham Forest"], 1,
     "Manchester United, five league titles, a huge Dane in a green jersey. His son Kasper won the league with Leicester in 2016.",
     "Father and son both won the league. That is the fun fact, and it is yours.",
     "impress", "\"Schmeichel and his son both won the league. Different clubs, twenty years apart.\""),
    (2, "Eric Cantona kicked a fan in 1995 while playing for which club?", ["Leeds United", "Manchester United", "Chelsea"], 1,
     "Manchester United, at Crystal Palace. He was banned for eight months, then came back and won the double. Collar up, always.",
     "Cantona is the reference for any moody genius footballer. Now you get the reference.",
     "say", "\"Bit of a Cantona moment, that.\" (When a player loses his temper spectacularly.)"),
    (2, "Which Welsh winger won thirteen league titles with Manchester United?", ["Gareth Bale", "Ryan Giggs", "Mark Hughes"], 1,
     "Ryan Giggs, one club for his whole career, 1991 to 2014. Thirteen titles with one team.",
     "He is the standard for loyalty and longevity. Any long-serving player gets compared to him.",
     "impress", "\"Giggs won thirteen titles at one club. Twenty-three years.\""),
    (2, "In 2003, Chelsea fans voted which Italian their greatest ever player?", ["Gianluca Vialli", "Gianfranco Zola", "Roberto Di Matteo"], 1,
     "Gianfranco Zola, small and brilliant, at Chelsea from 1996 to 2003. Vialli and Di Matteo were Italian heroes there in the same years.",
     "Older Chelsea fans light up at his name. It is a kindness to know it.",
     "ask", "Ask him: \"Did you ever see Zola play? Everyone says he was magic.\""),
    (2, "Roy Keane, the fierce captain known as Keano, led which club in the 1990s and 2000s?", ["Nottingham Forest", "Manchester United", "Leeds United"], 1,
     "Manchester United, and Ireland. A terrifying midfielder who became a pundit, terrifying to other pundits.",
     "He is on TV every week saying something brutal. Knowing his history explains the tone.",
     "say", "\"Roy Keane wouldn't have stood for that.\" (When a player looks like he isn't trying.)"),
    (2, "How many league goals did Mohamed Salah score in his first Liverpool season, 2017-18?", ["22", "32", "42"], 1,
     "32, after joining from Roma, a high for a 38-game Premier League season at the time. Fans named him the Egyptian King and wrote him a song.",
     "The song fans sing about him is one he will know all the words to.",
     "ask", "Ask him: \"Was Salah the best signing Liverpool made in your lifetime?\""),
    (2, "Didier Drogba scored the winning penalty in the 2012 Champions League final for which club?", ["Arsenal", "Chelsea", "Liverpool"], 1,
     "Chelsea, in Bayern Munich's own stadium. He had also scored the late equaliser. The man for the big occasion, and he knew it.",
     "\"Big-game player\" is a phrase he uses. Drogba is who he means.",
     "say", "\"He's a bit of a Drogba. Only turns up for the big ones.\""),
    (2, "Wayne Rooney's overhead kick in the 2011 Manchester derby was scored for which club?", ["Everton", "Manchester City", "Manchester United"], 2,
     "Manchester United. Voted the best goal in the first twenty years of the Premier League. He started at Everton and ended as United's top scorer.",
     "It is the goal that gets replayed whenever anyone scores an overhead kick.",
     "say", "\"Rooney against City. That's the overhead kick everyone means.\""),
    (2, "Who captained Manchester City to their first Premier League title in 2012?", ["Vincent Kompany", "David Silva", "Carlos Tevez"], 0,
     "Vincent Kompany, the Belgian centre-back with a statue outside the Etihad. He became a manager and won the Bundesliga with Bayern in 2025.",
     "Kompany is the answer when City fans get misty about the club before the trophies were routine.",
     "ask", "Ask him: \"Kompany or David Silva, who mattered more to City?\""),
    (3, "Who scored a hat-trick in under three minutes for Southampton in 2015?", ["Sadio Mané", "Jamie Vardy", "Sergio Agüero"], 0,
     "Sadio Mané, 2 minutes 56 seconds against Aston Villa. He later won everything at Liverpool alongside Salah.",
     "The fastest-hat-trick pub question. Having the answer ready is pure impress.",
     "impress", "\"Mané did a hat-trick in under three minutes once. Under three minutes.\""),
    (2, "Who managed Leicester City to the 2016 Premier League title?", ["Brendan Rodgers", "Claudio Ranieri", "Nigel Pearson"], 1,
     "Claudio Ranieri, the Italian nobody expected anything from. Leicester had started the season as 5000-1 outsiders. Sacked nine months later.",
     "Leicester 2016 is the fairy tale every small club fan mentions. It is the proof that it can happen.",
     "say", "\"Leicester won it at 5000-1. Anything can happen.\" (When his team are underdogs.)"),
    (2, "Robin van Persie left Arsenal in 2012 to join which club?", ["Chelsea", "Manchester United", "Manchester City"], 1,
     "Manchester United, where he won the title in his first season. Arsenal fans consider it a betrayal, United fans a masterstroke.",
     "Players leaving for rivals is the sorest subject in football. This is the classic case.",
     "ask", "Ask him: \"Worst betrayal in football: Van Persie or Sol Campbell?\""),
    (1, "Which Belgian midfielder was Manchester City's playmaker for a decade from 2015?", ['Eden Hazard', 'Kevin De Bruyne', 'Marouane Fellaini'], 1,
     'Kevin De Bruyne: passes nobody else saw, six league titles, and Chelsea had sold him to Wolfsburg first.',
     'He is the modern example of a playmaker, the word you will hear in every tactical chat.',
     'say', '"De Bruyne saw passes nobody else did. That\'s what a playmaker is."'),
    (2, "David Beckham scored from the halfway line in 1996 playing for which club?", ["Manchester United", "Real Madrid", "Preston North End"], 0,
     "Manchester United, against Wimbledon, on the opening day of the season. It made him famous overnight. Then came Posh.",
     "Beckham is the crossover celebrity; this goal is where it started.",
     "impress", "\"That's where Beckham started. Halfway line, first game of the season, 1996.\""),
]

CLUBS_RIVALRIES = [
    (1, "The North London derby is between Arsenal and which club?", ["Queens Park Rangers", "Tottenham Hotspur", "West Ham United"], 1,
     "Tottenham. Four miles apart, and the grudge dates to 1913, when Arsenal moved north into Spurs' patch uninvited.",
     "If he supports either club, this fixture decides his mood for a fortnight.",
     "ask", "Ask him: \"Do you actually know why Arsenal and Spurs hate each other?\" Plenty of fans don't."),
    (1, "Which two clubs play the Merseyside derby?", ["Liverpool and Everton", "Liverpool and Man Utd", "Everton and Tranmere"], 0,
     "Liverpool and Everton, whose grounds were a short walk apart across a park. Families in the city are split down the middle.",
     "It is called the friendly derby because relatives sit together. It is also famous for its red cards.",
     "impress", "\"They call it the friendly derby, and it's famous for red cards. Bit ironic.\""),
    (2, 'In the Steel City derby, Sheffield United are the Blades. What are Sheffield Wednesday called?', ['The Millers', 'The Owls', 'The Tykes'], 1,
     "The Owls, from Owlerton, the district around their Hillsborough ground. The Blades take their name from Sheffield's steel and cutlery.",
     'Sheffield is where club football started, in 1857. The derby between its two clubs is a big deal in that city.',
     'impress', '"Wednesday are the Owls because of Owlerton, the area. Nothing to do with the bird."'),
    (2, "Which two clubs contest the M23 derby?", ["Brighton and Crystal Palace", "Southampton and Portsmouth", "Watford and Luton"], 0,
     "Brighton and Crystal Palace, forty miles apart along the M23. It began as a feud between two managers in the 1970s and simply carried on.",
     "Nobody outside the two clubs understands it, so knowing about it marks you as someone who pays attention.",
     "ask", "Ask him: \"Why do Brighton and Palace hate each other? They're miles apart.\""),
    (2, "The Tyne-Wear derby is Newcastle against which club?", ["Middlesbrough", "Sunderland", "Leeds"], 1,
     "Sunderland. Two rivers, twelve miles, and well over a century of mutual dislike. When both are in the Premier League, the region stops.",
     "It is the fixture northern fans mention when southerners talk about derbies.",
     "say", "\"Tyne-Wear derby. That one's properly nasty.\""),
    (1, "Which nickname do Arsenal go by?", ["The Cannons", "The Gunners", "The Soldiers"], 1,
     "The Gunners. The club was founded by workers at the Royal Arsenal munitions factory in 1886, hence the cannon on the badge.",
     "Nicknames come up in every match: the Gunners, the Reds, the Blues. This one has the best story.",
     "impress", "\"They're the Gunners because the club started at a weapons factory. Hence the cannon.\""),
    (2, "Which club is known as the Toffees?", ["Everton", "Liverpool", "Bolton"], 0,
     "Everton, after a toffee shop near where the club began. For decades a Toffee Lady in old-fashioned dress has thrown sweets into the crowd before home games.",
     "The Toffee Lady is the kind of detail that makes a fan grin. It is yours now.",
     "impress", "\"Everton have a Toffee Lady who throws sweets to the crowd. That's why they're the Toffees.\""),
    (1, "Which club is nicknamed the Magpies?", ["Newcastle United", "Sunderland", "Sheffield Wednesday"], 0,
     "Newcastle, for the black and white stripes. The fans are the Toon Army, and they are loud.",
     "\"The Toon\" is what he will call Newcastle without explaining. Now it needs no explaining.",
     "say", "\"The Toon are at home. St James' will be bouncing.\""),
    (2, "Which club is nicknamed the Cherries?", ["Southampton", "AFC Bournemouth", "Nottingham Forest"], 1,
     "Bournemouth, for the cherry-red shirts and the cherry orchards that stood near the old ground.",
     "A small club with a smaller ground and a nice story. Good to have when they come up in conversation.",
     "say", "\"The Cherries. Tiny ground, about eleven thousand.\""),
    (2, "Which club, promoted to the Premier League in 2021, is nicknamed the Bees?", ["Watford", "Brentford", "Norwich City"], 1,
     "Brentford, from west London, with a bee on the badge. Going up in 2021 put them in the top flight for the first time since 1947.",
     "Brentford are the club clever fans admire, built on statistics rather than money. Knowing them is a signal.",
     "impress", "\"Brentford scrapped their academy in 2016 and built a team on data. And it worked.\""),
    (2, "Which club is nicknamed the Seagulls?", ["Brighton", "Bournemouth", "Southampton"], 0,
     "Brighton, the seaside club. The name began as a terrace chant in the 1970s, and the gull was on the badge by the end of the decade.",
     "Seaside clubs love a seaside bird, and he may not know the fans picked this one themselves.",
     "impress", "\"The Seagulls started as a chant in the 1970s. The fans named their own club.\""),
    (2, 'The Black Country derby is Wolves against which club?', ['Birmingham City', 'West Bromwich Albion', 'Stoke City'], 1,
     'West Brom. Both come from the Black Country, the old industrial area just west of Birmingham, usually said to be named for the soot of its mines and foundries.',
     'Not every big derby is in the Premier League. To the people in this one, it matters just as much.',
     'say', '"The Black Country derby. Wolves and West Brom. Proper old-school one, that."'),
    (2, "Which club is nicknamed the Cottagers?", ["Fulham", "Chelsea", "Brentford"], 0,
     "Fulham, whose ground, Craven Cottage, has an actual cottage in one corner. The club was founded in 1879.",
     "The prettiest ground in London, on the Thames. Good for a day out, good for a line.",
     "say", "\"Craven Cottage. There's an actual cottage in the corner of the ground.\""),
    (2, "Which club is nicknamed the Black Cats?", ["Newcastle", "Sunderland", "Hull City"], 1,
     "Sunderland. A black cat was the club's lucky mascot at a cup final in 1937, and fans voted the name official in 2000.",
     "Sunderland fans are famously loyal through misery. The Netflix series about them is the reference.",
     "ask", "Ask him: \"Did you watch Sunderland 'Til I Die? Was it as painful as it looked?\""),
    (2, "Which club plays in claret and blue and has Birmingham City as its city rival?", ["West Ham", "Aston Villa", "Burnley"], 1,
     "Aston Villa. West Ham and Burnley borrowed the claret and blue from Villa. The Birmingham fixture is the Second City derby.",
     "Three clubs, one colour scheme. He may not know who had it first.",
     "ask", "Ask him: \"Who had claret and blue first, Villa or West Ham?\" It was Villa."),
    (2, "Which two clubs contest the East Anglian derby?", ["Ipswich and Norwich", "Ipswich and Colchester", "Cambridge and Ipswich"], 0,
     "Ipswich Town and Norwich City, forty miles apart. Fans joke it is the Old Farm derby, a pun on Glasgow's Old Firm.",
     "The pun alone is worth knowing. It always gets a laugh from the right crowd.",
     "say", "\"The Old Farm derby. Ipswich and Norwich. It's a farming joke.\""),
    (3, "Leeds United's rivalry with Manchester United is known as what?", ['The Roses rivalry', 'The Tudor rivalry', 'The Crown derby'], 0,
     "The Roses rivalry: Yorkshire's white rose against Lancashire's red, from a war fought four hundred years before football existed.",
     'A derby with a medieval origin story. Perfect impress material.',
     'impress', '"Leeds and United is the Roses rivalry. It goes back to an actual war in the 1400s."'),
    (2, "Which club's ground is about a mile and a half from Chelsea's?", ['Fulham', 'QPR', 'Brentford'], 0,
     'Fulham. The two grounds are about a mile and a half apart, both in the London borough of Hammersmith and Fulham.',
     'West London derbies are lower-key, and he wants them won all the same.',
     'say', '"Chelsea and Fulham are basically neighbours. A mile and a half apart."'),
    (2, "Which club is nicknamed the Sky Blues?", ["Blackburn Rovers", "Coventry City", "Wycombe"], 1,
     "Coventry City. A 1960s manager, Jimmy Hill, changed the kit to sky blue and wrote the fans' song to go with it.",
     "Coventry are the romantic story: a big-city club that fell to the fourth tier and climbed all the way back.",
     "impress", "\"Coventry were in the fourth tier in 2018 and in the Premier League by 2026.\""),
    (2, "Which club is nicknamed the Tractor Boys?", ["Norwich", "Ipswich Town", "Peterborough"], 1,
     "Ipswich Town, from Suffolk farming country. Rival fans meant it as an insult; Ipswich fans adopted it and put it on scarves.",
     "The best nicknames were insults first. This is a good example to have ready.",
     "say", "\"Tractor Boys started as an insult from other fans. Ipswich just took it.\""),
    (2, "Which club is nicknamed the Eagles?", ["Crystal Palace", "Brighton", "Charlton Athletic"], 0,
     "Crystal Palace, in south London. For years a real bald eagle called Kayla flew round the ground before matches.",
     "A live eagle at a football match is a fact people do not believe. Enjoy telling it.",
     "impress", "\"Palace used to have an actual eagle flying round the pitch before games.\""),
    (1, "Which English club's fans sing You'll Never Walk Alone before every home game?", ["Manchester United", "Liverpool", "Everton"], 1,
     "Liverpool, since the 1960s. It is a show tune from a musical, and the words are over the gates at Anfield. Celtic fans sing it too.",
     "It is the football song everyone has heard. Knowing whose it is matters.",
     "say", "\"You'll Never Walk Alone. Every Liverpool game, scarves up. Gets me every time.\""),
]

BADGES_GROUNDS = [
    (1, "Which club plays at the Emirates Stadium?", ["Chelsea", "Arsenal", "West Ham"], 1,
     "Arsenal, since 2006. Before that they played at Highbury, a few hundred yards away, which is now flats with the pitch as a garden.",
     "\"At the Emirates\" is how he will say Arsenal are at home. It also has a fun afterlife story.",
     "impress", "\"Highbury's flats now. The old pitch is the communal garden.\""),
    (1, "Anfield is the home of which club?", ["Everton", "Liverpool", "Manchester United"], 1,
     "Liverpool. It was Everton's ground first, until a rent row in 1892 sent Everton across the park and left the landlord to start Liverpool.",
     "Liverpool only exist because of a landlord dispute. That is a genuinely good story.",
     "impress", "\"Liverpool were founded because Everton fell out with their landlord over rent.\""),
    (1, "Old Trafford is the home of which club?", ["Manchester City", "Manchester United", "Blackburn"], 1,
     "Manchester United, since 1910. Bobby Charlton called it the Theatre of Dreams and the name stuck.",
     "The nickname turns up in every United broadcast. Knowing who coined it is the extra step.",
     "say", "\"Theatre of Dreams. Bobby Charlton's line, wasn't it?\""),
    (1, "Stamford Bridge is the home of which club?", ["Fulham", "Chelsea", "Brentford"], 1,
     "Chelsea. The stadium existed before the club: it was built in 1877 and Chelsea were founded in 1905 to fill it, in a pub over the road.",
     "A club invented to fill an empty stadium is the kind of fact that flips a conversation.",
     "impress", "\"Chelsea were founded in a pub to fill a stadium that was already there.\""),
    (2, "Which club's badge shows a cockerel standing on a football?", ["Tottenham Hotspur", "Aston Villa", "Norwich"], 0,
     "Spurs. A cockerel first went up on the stand roof in 1909, and it wears spurs on its legs, which is the pun.",
     "He has looked at that badge a thousand times without noticing the spurs. You can be the one who did.",
     "ask", "Ask him: \"Have you noticed the cockerel on the Spurs badge is wearing spurs?\""),
    (2, "Which club's badge shows a bird with seaweed in its beak?", ["Brighton", "Liverpool", "Newcastle"], 1,
     "Liverpool. It is the liver bird, the city's symbol, on the Royal Liver Building by the river as well as the badge.",
     "Badge stories are how you show you looked properly.",
     "say", "\"That's the liver bird. It's on the buildings all over the city too.\""),
    (2, "Villa Park is the home of which club?", ["Aston Villa", "West Ham", "Birmingham City"], 0,
     "Aston Villa, since 1897. The huge stand behind one goal is the Holte End, and for decades it staged FA Cup semi-finals, until they moved to Wembley in 2008.",
     "Villa Park is a ground fans of every club have visited for a semi-final. He will have a memory of it.",
     "ask", "Ask him: \"Have you ever been to Villa Park? Everyone seems to have a semi-final story.\""),
    (2, "Goodison Park was for over a century the home of which club?", ["Liverpool", "Everton", "Tranmere"], 1,
     "Everton, from 1892 until they moved to a new stadium on the docks in 2025. Goodison was the first purpose-built football ground in England.",
     "Grounds closing is an emotional subject. Knowing this one shows you understand why.",
     "ask", "Ask him: \"Did you ever go to Goodison before they left? People say it was special.\""),
    (1, "Which north-east club plays at St James' Park?", ["Sunderland", "Newcastle", "Middlesbrough"], 1,
     "Newcastle. Right in the city centre; you can see the stands from the shops. Fans in the top tier are famously far from the pitch.",
     "It is the ground people mean when they say a stadium is part of the city.",
     "say", "\"St James' is right in the middle of town. You can walk from the shops.\""),
    (2, "Which club's badge shows a red devil holding a trident?", ["Manchester United", "Liverpool", "Nottingham Forest"], 0,
     "Manchester United. Matt Busby borrowed the Red Devils name from a Salford rugby team in the 1960s, and the devil joined the badge in 1970.",
     "Even United fans rarely know the devil came from rugby. That is the point of knowing it.",
     "impress", "\"The Red Devils name came from a rugby league team in Salford. Busby nicked it.\""),
    (2, "Which club's badge shows a fox?", ["Wolves", "Leicester", "Huddersfield"], 1,
     "Leicester City, the Foxes. Leicestershire was famous fox-hunting country, and the fox has been the club's emblem for generations.",
     "Leicester's 2016 title is the fairy tale every underdog fan quotes, and the Foxes is how he will say it.",
     "say", "\"The Foxes. Leicester, like the 2016 fairy tale.\""),
    (2, "Which club's badge shows a round stone tower?", ["Everton", "Aston Villa", "Leeds United"], 0,
     "Everton. It is Prince Rupert's Tower, built in 1787 as a lock-up for the district's drunks. The club is named after the same district.",
     "A badge with a jail for drunks on it is the kind of fact that makes a fan laugh.",
     "impress", "\"The tower on Everton's badge was a lock-up for drunks. In 1787.\""),
    (2, 'The Valley is the home of which London club?', ['Millwall', 'Charlton Athletic', 'QPR'], 1,
     'Charlton Athletic, in south-east London. They left in 1985, shared other grounds for seven years, and a fan campaign brought them home in 1992.',
     'Charlton getting their ground back is a great fan story. It comes up whenever a club talks of moving.',
     'ask', 'Ask him: "Is it true Charlton fans started a political party to get their ground back?"'),
    (2, "Which club moved into the London Stadium, built for the 2012 Olympics?", ["Tottenham", "West Ham", "Leyton Orient"], 1,
     "West Ham, in 2016, after 112 years at Upton Park. Tottenham had bid for the stadium too.",
     "Moving grounds is an emotional subject, and West Ham's move is one every fan has a view on.",
     "ask", "Ask him: \"Do West Ham fans actually like the London Stadium?\" He'll have views."),
    (2, "The City Ground is the home of which club?", ["Manchester City", "Nottingham Forest", "Bristol City"], 1,
     "Nottingham Forest, on the River Trent. Notts County's ground, Meadow Lane, is about three hundred yards away across the water.",
     "Two league grounds you can see from each other. Nobody expects that fact.",
     "impress", "\"Forest and Notts County's grounds are 300 yards apart. You can see one from the other.\""),
    (2, "Which English club plays at the Stadium of Light?", ["Sunderland", "Newcastle", "Everton"], 0,
     "Sunderland, since 1997. It was built on a coal mine, and the name honours the miners' lamps. Benfica's ground in Lisbon has the same name.",
     "Two Stadiums of Light is a decent pub question, and the coal mine is the better half of the answer.",
     "impress", "\"The Stadium of Light's built on an old coal mine. The name's for the miners' lamps.\""),
    (2, "Elland Road is the home of which club?", ["Leeds United", "Sheffield United", "Huddersfield"], 0,
     "Leeds United, since 1919. Known for being loud and hostile to visiting teams, which Leeds fans consider a compliment.",
     "\"Elland Road on a night game\" is a phrase he will use with feeling.",
     "say", "\"Elland Road under the lights. Proper hostile.\""),
    (1, "Which club played the 2025-26 Premier League season at a ground holding about 11,000?", ["Bournemouth", "Brentford", "Nottingham Forest"], 0,
     "Bournemouth, at Dean Court, also called the Vitality Stadium. Brentford's holds about 17,000 and Forest's about 30,000.",
     "Ground size is a bragging point. Knowing the tiny one gives you a comparison for everything.",
     "say", "\"Bournemouth's ground holds eleven thousand. That's smaller than some rugby clubs.\""),
    (2, "Which club plays at the ground known as the Amex?", ["Brighton", "Bournemouth", "Brentford"], 0,
     "Brighton, at Falmer on the edge of the Downs. It took fourteen years of planning fights to build; before that they played on an athletics track.",
     "Brighton's rise from homeless to European football is a story fans respect.",
     "impress", "\"Brighton played on an athletics track for twelve years before the Amex. By 2023 they were in Europe.\""),
    (3, "Which club's badge shows a ship above three diagonal stripes for the city's rivers?", ["Liverpool", "Manchester City", "Sunderland"], 1,
     "Manchester City. The ship is for the Ship Canal and the city's trade, the stripes for its three rivers, and the red rose is for Lancashire.",
     "Reading a badge like a map is a small party trick. This is the best badge for it.",
     "impress", "\"City's badge is a map: the ship's the canal, the stripes are the three rivers.\""),
    (2, 'Portman Road is the home of which club?', ['Norwich', 'Ipswich', 'Colchester'], 1,
     'Ipswich Town, their home since 1884. Two managers who went on to run England have statues outside.',
     'Ipswich are a small club with a big history. The statues are the proof.',
     'impress', '"Two England managers came from the Ipswich job. Ramsey and Robson, both have statues outside."'),
    (2, "Which club has a canary on its badge?", ["Watford", "Norwich", "Burnley"], 1,
     "Norwich City, the Canaries. Flemish weavers who settled in the city centuries ago bred canaries, and the club took the bird and the yellow shirts in the early 1900s.",
     "The yellow shirts make sense once you know the bird came first. It is a nice bit of city history.",
     "ask", "Ask him: \"Did you know Norwich are the Canaries because of weavers who bred them?\""),
]

PACKS = [
    ("the-basics", "The Basics", BASICS),
    ("legends", "Legends", LEGENDS),
    ("clubs-rivalries", "Clubs & Rivalries", CLUBS_RIVALRIES),
    ("badges-grounds", "Badges & Grounds", BADGES_GROUNDS),
]
