# The four general packs. (difficulty, question, options, answer_index, explanation)
# Finished history only — nothing that a season, a transfer or a sacking can make wrong.

BASICS = [
    (1, "How many points does a team get for winning a match?", ["One", "Two", "Three", "Four"], 2, "Three for a win, one for a draw, nothing for a loss. That is the whole table."),
    (1, "How many clubs are in the Premier League?", ["16", "18", "20", "24"], 2, "Twenty clubs, each playing the others twice. 38 games a season."),
    (1, "How many clubs are relegated at the end of a Premier League season?", ["One", "Two", "Three", "Four"], 2, "The bottom three go down to the Championship and three come up."),
    (1, "How long is a match, before any added time?", ["60 minutes", "80 minutes", "90 minutes", "120 minutes"], 2, "Two halves of 45. Added time on top is for stoppages."),
    (1, "How many players does each team have on the pitch at kick-off?", ["Nine", "Ten", "Eleven", "Twelve"], 2, "Eleven a side, one of them the goalkeeper."),
    (1, "Which colour card means a player is sent off?", ["Yellow", "Red", "Blue", "Black"], 1, "Red is off. Yellow is a warning, and two yellows make a red."),
    (1, "Who is the only player allowed to handle the ball inside their own penalty area?", ["The captain", "The goalkeeper", "Any defender", "Nobody"], 1, "Only the keeper, and only inside the box. Outside it, same rules as everyone."),
    (2, "How far from goal is a penalty kick taken?", ["Eight yards", "Ten yards", "Twelve yards", "Eighteen yards"], 2, "Twelve yards, straight in front of goal, with only the keeper to beat."),
    (1, "What does VAR stand for?", ["Video Assistant Referee", "Visual Analysis Review", "Video Appeal Rule", "Verified Action Replay"], 0, "Video Assistant Referee. A team in a room checking the big decisions on replay."),
    (2, "How many substitutions can a Premier League team make in a match?", ["Three", "Four", "Five", "Seven"], 2, "Five, in three stopped moments, plus half-time. It was three until 2022."),
    (1, "What happens when a league match ends level?", ["Extra time", "A penalty shootout", "Both teams get a point", "A replay"], 2, "A draw. One point each. Extra time and penalties are for cups."),
    (1, "Two yellow cards in one match equals what?", ["A fine", "A penalty", "A red card", "A one-match ban later"], 2, "Two yellows make a red, and the player is off."),
    (1, "What is a clean sheet?", ["A win by three goals", "Not conceding a goal", "No yellow cards", "A new kit"], 1, "Letting in nothing. The goalkeeper's favourite statistic."),
    (1, "A hat-trick is how many goals by one player in one match?", ["Two", "Three", "Four", "Five"], 1, "Three. Two is a brace. The player traditionally keeps the match ball."),
    (1, "Which division sits directly below the Premier League?", ["League One", "The Championship", "The National League", "The Conference"], 1, "The Championship. Confusingly named, since winning it is not really a championship."),
    (2, "How many clubs are promoted from the Championship each season?", ["One", "Two", "Three", "Four"], 2, "Three: the top two automatically, and one more through the play-offs."),
    (2, "When two teams finish level on points, what usually separates them?", ["Goals scored", "Goal difference", "Head-to-head", "Alphabetical order"], 1, "Goal difference first: goals scored minus goals conceded."),
    (1, "When are the two transfer windows?", ["Autumn and spring", "Summer and January", "Christmas and Easter", "Any time"], 1, "The summer, and the whole of January. Outside those, clubs cannot buy."),
    (2, "How long is each half of extra time in a cup match?", ["Ten minutes", "Fifteen minutes", "Twenty minutes", "Thirty minutes"], 1, "Two halves of fifteen. If it is still level after that, penalties."),
    (2, "In a penalty shootout, how many kicks does each side take before it goes to sudden death?", ["Three", "Five", "Seven", "Ten"], 1, "Five each. Then one at a time until somebody misses."),
    (1, "Who takes a corner kick?", ["The defending team", "The attacking team", "The goalkeeper", "The referee decides"], 1, "The attackers, after the defending side put the ball out behind their own goal."),
    (2, "Which is the oldest cup competition in the world?", ["The League Cup", "The Champions League", "The FA Cup", "The World Cup"], 2, "The FA Cup, first played in 1871. Every club in England can enter."),
    (1, "What is a match between two local rivals called?", ["A classic", "A derby", "A final", "A friendly"], 1, "A derby, pronounced darby. Manchester, Merseyside, North London — all derbies."),
    (2, "Which body runs the Champions League?", ["FIFA", "UEFA", "The FA", "The Premier League"], 1, "UEFA, European football's governing body. FIFA runs the World Cup."),
    (2, "Over two legs, what decides which team goes through?", ["The second-leg score only", "The aggregate score", "A coin toss", "The home team's score"], 1, "Add the two scores together. That total is the aggregate."),
    (1, "What is nil in football?", ["A draw", "Zero", "An injury", "A foul"], 1, "Zero. A goalless draw is nil-nil, and it always will be."),
    (2, "What is added time?", ["Extra time in a cup", "Minutes added for stoppages", "Time added for a red card", "The half-time break"], 1, "Minutes tacked on at the end of each half to make up for stoppages."),
    (3, "How many yards is the penalty area from the goal line?", ["Twelve", "Sixteen", "Eighteen", "Twenty-two"], 2, "Eighteen yards deep, which is why it is also called the eighteen-yard box."),
]

LEGENDS = [
    (1, "Who has scored the most Premier League goals of all time?", ["Alan Shearer", "Wayne Rooney", "Harry Kane", "Thierry Henry"], 0, "Alan Shearer, 260. Nobody has got close since."),
    (3, "Who has made the most Premier League appearances?", ["Ryan Giggs", "Gareth Barry", "Frank Lampard", "James Milner"], 1, "Gareth Barry, 653 games for Villa, City, Everton and West Brom."),
    (1, "Thierry Henry is a legend at which club?", ["Chelsea", "Arsenal", "Liverpool", "Manchester United"], 1, "Arsenal. There is a statue of him outside the Emirates."),
    (1, "Who managed Manchester United for 26 years until 2013?", ["José Mourinho", "Sir Alex Ferguson", "Arsène Wenger", "Sir Bobby Robson"], 1, "Sir Alex Ferguson. Thirteen league titles. The stand at Old Trafford is named after him."),
    (2, "Who scored the injury-time goal that won Manchester City the title in 2012?", ["Sergio Agüero", "Edin Džeko", "Yaya Touré", "Mario Balotelli"], 0, "Agüero, 94th minute against QPR. The commentator's 'Agüerooo' is still quoted."),
    (1, "Steven Gerrard spent almost his whole career at which club?", ["Everton", "Liverpool", "Chelsea", "Leeds"], 1, "Liverpool, from 1998 to 2015. Captain, and a Champions League winner in 2005."),
    (1, "Which Frenchman managed Arsenal from 1996 to 2018?", ["Gérard Houllier", "Arsène Wenger", "Didier Deschamps", "Claude Puel"], 1, "Arsène Wenger. Three league titles and the unbeaten 2003-04 season."),
    (2, "Frank Lampard became the all-time record goalscorer of which club?", ["West Ham", "Chelsea", "Manchester City", "Everton"], 1, "Chelsea, 211 goals. A midfielder, which makes it odder."),
    (2, "Who is Tottenham Hotspur's all-time record goalscorer?", ["Gareth Bale", "Jimmy Greaves", "Harry Kane", "Teddy Sheringham"], 2, "Harry Kane passed Jimmy Greaves in 2023 before leaving for Bayern Munich."),
    (2, "Peter Schmeichel kept goal for which Premier League club in the 1990s?", ["Liverpool", "Manchester United", "Arsenal", "Aston Villa"], 1, "Manchester United, five titles. His son Kasper won the league with Leicester in 2016."),
    (2, "Eric Cantona was banned for kicking a fan in 1995 while playing for which club?", ["Leeds United", "Manchester United", "Chelsea", "Arsenal"], 1, "Manchester United, at Selhurst Park. He had joined from Leeds in 1992."),
    (2, "Which Welsh winger won thirteen Premier League titles with Manchester United?", ["Gareth Bale", "Ryan Giggs", "Mark Hughes", "Aaron Ramsey"], 1, "Ryan Giggs, one club for his whole career. Nobody else has thirteen."),
    (2, "Dennis Bergkamp, famous for a 1998 World Cup goal, played his club football in England for whom?", ["Chelsea", "Arsenal", "Newcastle", "Spurs"], 1, "Arsenal, 1995 to 2006. He would not fly, so he missed away games in Europe."),
    (2, "Gianfranco Zola, a Chelsea favourite in the late 1990s, came from which country?", ["Spain", "Italy", "Argentina", "Portugal"], 1, "Italy. Small, brilliant, and voted Chelsea's greatest ever player by fans in 2003."),
    (2, "Who captained both Manchester United and Ireland and is known as Keano?", ["Robbie Keane", "Roy Keane", "Denis Irwin", "Paul McGrath"], 1, "Roy Keane. Fierce midfielder, now a fiercer pundit."),
    (2, "Who is Manchester City's all-time record goalscorer?", ["Erling Haaland", "Sergio Agüero", "Carlos Tevez", "Raheem Sterling"], 1, "Sergio Agüero, 260 goals in all competitions between 2011 and 2021."),
    (1, "Which Liverpool forward is nicknamed the Egyptian King?", ["Sadio Mané", "Mohamed Salah", "Roberto Firmino", "Luis Díaz"], 1, "Mohamed Salah, who joined from Roma in 2017 and broke the 38-game scoring record."),
    (2, "Didier Drogba scored the winning penalty in the 2012 Champions League final for which club?", ["Arsenal", "Chelsea", "Manchester United", "Liverpool"], 1, "Chelsea, against Bayern Munich in Munich. He had also scored the late equaliser."),
    (2, "Wayne Rooney's famous overhead kick in a 2011 Manchester derby was for which club?", ["Everton", "Manchester City", "Manchester United", "England"], 2, "Manchester United, at Old Trafford. Voted the best goal in twenty years of the Premier League."),
    (2, "Who captained Manchester City to their first Premier League title in 2012?", ["Vincent Kompany", "David Silva", "Joe Hart", "Carlos Tevez"], 0, "Vincent Kompany, the Belgian centre-back who later became a manager."),
    (3, "Who scored the fastest Premier League hat-trick, in under three minutes for Southampton in 2015?", ["Sadio Mané", "Jamie Vardy", "Robbie Fowler", "Sergio Agüero"], 0, "Sadio Mané, two minutes and 56 seconds against Aston Villa."),
    (3, "Jamie Vardy set a record in 2015 by scoring in how many consecutive Premier League matches?", ["Eight", "Nine", "Eleven", "Thirteen"], 2, "Eleven in a row for Leicester, beating Ruud van Nistelrooy's ten."),
    (2, "Who managed Leicester City to the 2016 Premier League title?", ["Brendan Rodgers", "Claudio Ranieri", "Nigel Pearson", "Craig Shakespeare"], 1, "Claudio Ranieri. Leicester started the season as 5000-1 outsiders."),
    (2, "Robin van Persie left Arsenal in 2012 to join which club?", ["Chelsea", "Manchester United", "Manchester City", "Barcelona"], 1, "Manchester United, where he won the title and the Golden Boot in his first season."),
    (1, "Which Belgian midfielder was Manchester City's playmaker for a decade from 2015?", ["Eden Hazard", "Kevin De Bruyne", "Romelu Lukaku", "Vincent Kompany"], 1, "Kevin De Bruyne. Passes nobody else saw, and six league titles."),
    (2, "David Beckham scored from the halfway line in 1996 against Wimbledon playing for whom?", ["England", "Manchester United", "Real Madrid", "Preston North End"], 1, "Manchester United, on the opening day of the season. It made him famous overnight."),
    (2, "Which Arsenal team went a whole Premier League season unbeaten?", ["1997-98", "2001-02", "2003-04", "2007-08"], 2, "2003-04. 26 wins, 12 draws, no defeats. They are called the Invincibles."),
    (3, "Who was the first player to score 100 Premier League goals?", ["Ian Wright", "Alan Shearer", "Les Ferdinand", "Andy Cole"], 1, "Alan Shearer, in 1995 for Blackburn Rovers, who won the title that year."),
]

CLUBS_RIVALRIES = [
    (1, "The North London derby is between Arsenal and which club?", ["Chelsea", "Tottenham Hotspur", "West Ham", "Fulham"], 1, "Spurs. Four miles apart and about as friendly as it sounds."),
    (1, "Which two clubs play the Merseyside derby?", ["Liverpool and Everton", "Liverpool and Man Utd", "Everton and Tranmere", "Liverpool and Leeds"], 0, "Liverpool and Everton, whose grounds were a short walk apart across Stanley Park."),
    (1, "The Manchester derby is City against whom?", ["Liverpool", "Manchester United", "Leeds United", "Bolton"], 1, "Manchester United. City fans spent decades in United's shadow, which is why it matters so much now."),
    (2, "Which two clubs contest the M23 derby?", ["Brighton and Crystal Palace", "Southampton and Portsmouth", "Reading and Oxford", "Watford and Luton"], 0, "Brighton and Crystal Palace, named after the motorway between them. Genuinely bitter."),
    (2, "The Tyne-Wear derby is Newcastle against which club?", ["Middlesbrough", "Sunderland", "Leeds", "Hull"], 1, "Sunderland. Two rivers, twelve miles, over a century of not getting on."),
    (1, "Which club is nicknamed the Gunners?", ["Chelsea", "Arsenal", "West Ham", "Aston Villa"], 1, "Arsenal, founded by workers at a royal armaments factory in Woolwich."),
    (2, "Which club is known as the Toffees?", ["Everton", "Liverpool", "Leeds", "Bolton"], 0, "Everton. Named after a toffee shop near the ground; a Toffee Lady still throws sweets to the crowd."),
    (1, "Which club is nicknamed the Magpies?", ["Newcastle United", "Sunderland", "Fulham", "Brentford"], 0, "Newcastle, for the black and white stripes."),
    (2, "Which club is nicknamed the Cherries?", ["Southampton", "AFC Bournemouth", "Brentford", "Nottingham Forest"], 1, "Bournemouth. Cherry-red shirts, and cherry orchards near the old ground."),
    (2, "Which club is nicknamed the Bees?", ["Watford", "Brentford", "Barnet", "Burnley"], 1, "Brentford. The badge is a bee and the fans chant 'buzz'."),
    (2, "Which club is nicknamed the Seagulls?", ["Brighton & Hove Albion", "Bournemouth", "Southampton", "Portsmouth"], 0, "Brighton. It started as a chant to wind up Palace fans, who sing 'Eagles'."),
    (2, "Which club is nicknamed the Villans?", ["Aston Villa", "West Ham", "Wolves", "Birmingham City"], 0, "Aston Villa. Villa, Villans. Not villains, though rivals disagree."),
    (2, "Which club is nicknamed the Cottagers?", ["Fulham", "Chelsea", "Brentford", "QPR"], 0, "Fulham, whose ground is Craven Cottage, with an actual cottage in the corner."),
    (2, "Which club is nicknamed the Black Cats?", ["Newcastle", "Sunderland", "Hull City", "Swansea"], 1, "Sunderland. A black cat was a lucky mascot at a cup final over a century ago."),
    (2, "Which club plays in claret and blue and has Birmingham City as its city rival?", ["West Ham", "Aston Villa", "Burnley", "Scunthorpe"], 1, "Aston Villa. The Second City derby, when Birmingham are in the same division."),
    (2, "Which two clubs contest the East Anglian derby?", ["Ipswich and Norwich", "Ipswich and Colchester", "Norwich and Peterborough", "Cambridge and Ipswich"], 0, "Ipswich Town and Norwich City. Forty miles apart and it is the biggest game of either club's year."),
    (3, "Leeds United's rivalry with Manchester United is known as which war?", ["The War of the Pennines", "The Roses rivalry", "The Northern derby", "The M62 derby"], 1, "The Roses rivalry, Yorkshire's white rose against Lancashire's red. Older than football."),
    (2, "Who are Chelsea's closest West London neighbours in the Premier League?", ["Fulham", "QPR", "Brentford", "Watford"], 0, "Fulham. Stamford Bridge and Craven Cottage are under two miles apart."),
    (2, "Which club is nicknamed the Sky Blues?", ["Manchester City", "Coventry City", "Lazio", "Wycombe"], 1, "Coventry City. Sky blue shirts since the 1960s, and the fans' nickname since then too."),
    (2, "Which club is nicknamed the Tractor Boys?", ["Norwich", "Ipswich Town", "Lincoln", "Peterborough"], 1, "Ipswich Town. Suffolk farming country. Started as an insult from rival fans and got adopted."),
    (2, "Which club is nicknamed the Tigers?", ["Hull City", "Castleford", "Wolves", "Leicester"], 0, "Hull City, for the amber and black stripes."),
    (2, "Which club is nicknamed the Eagles?", ["Crystal Palace", "Brighton", "Watford", "Charlton"], 0, "Crystal Palace. An actual eagle used to be flown around Selhurst Park before games."),
    (1, "Which club's fans sing 'You'll Never Walk Alone' before every home game?", ["Manchester United", "Liverpool", "Celtic", "Everton"], 1, "Liverpool, since the 1960s. The words are over the gates at Anfield."),
    (3, "Nottingham Forest's fiercest rivalry is with which club?", ["Leicester City", "Derby County", "Notts County", "Sheffield United"], 1, "Derby County. Fifteen miles apart, and Brian Clough managed both."),
    (1, "Spurs is short for which club?", ["Tottenham Hotspur", "Sheffield Spurs", "Southampton Spurs", "Stoke Hotspur"], 0, "Tottenham Hotspur, named after Harry Hotspur, a medieval knight from Shakespeare."),
    (2, "Which club is nicknamed the Red Devils?", ["Liverpool", "Manchester United", "Nottingham Forest", "Bristol City"], 1, "Manchester United. Matt Busby liked the name in the 1960s and it stuck."),
    (2, "Which club is nicknamed the Whites?", ["Leeds United", "Fulham", "Spurs", "Real Madrid"], 0, "Leeds United, who switched to all-white in the 1960s to copy Real Madrid."),
    (2, "Which club is nicknamed the Tricky Trees?", ["Nottingham Forest", "Sherwood", "Norwich", "Derby"], 0, "Nottingham Forest. The badge is a tree; the trickiness is aspirational."),
]

BADGES_GROUNDS = [
    (1, "Which club plays at the Emirates Stadium?", ["Chelsea", "Arsenal", "West Ham", "Spurs"], 1, "Arsenal, since 2006. Before that, Highbury, a few hundred yards away."),
    (1, "Anfield is the home of which club?", ["Everton", "Liverpool", "Manchester United", "Leeds"], 1, "Liverpool. Originally Everton's ground, until a rent row in 1892."),
    (1, "Old Trafford is the home of which club?", ["Manchester City", "Manchester United", "Bolton", "Blackburn"], 1, "Manchester United, since 1910. Nicknamed the Theatre of Dreams."),
    (1, "Stamford Bridge is the home of which club?", ["Fulham", "Chelsea", "QPR", "Brentford"], 1, "Chelsea. The club was founded in 1905 to fill a stadium that already existed."),
    (2, "Which club's badge shows a cockerel standing on a football?", ["Tottenham Hotspur", "Arsenal", "Aston Villa", "Norwich"], 0, "Spurs. There has been a cockerel on the badge and the stadium roof since 1909."),
    (2, "Which club's badge features the liver bird?", ["Everton", "Liverpool", "Leeds", "Birmingham"], 1, "Liverpool. The liver bird is the city's symbol, a cormorant with seaweed in its beak."),
    (2, "Villa Park is the home of which club?", ["Aston Villa", "West Ham", "Birmingham City", "Wolves"], 0, "Aston Villa, since 1897. It has hosted more FA Cup semi-finals than any other ground."),
    (2, "Goodison Park was for over a century the home of which club?", ["Liverpool", "Everton", "Tranmere", "Preston"], 1, "Everton, from 1892 until they moved to a new stadium on the docks in 2025."),
    (1, "St James' Park is the home of which club?", ["Sunderland", "Newcastle United", "Exeter City", "Leeds"], 1, "Newcastle. Right in the city centre; the stadium looks over the shops."),
    (2, "Which club's badge shows a red devil holding a trident?", ["Manchester United", "Liverpool", "Nottingham Forest", "Sunderland"], 0, "Manchester United. The devil has been on the badge since 1970."),
    (1, "Which club has a cannon on its badge?", ["Arsenal", "Portsmouth", "Sunderland", "Chelsea"], 0, "Arsenal, for the Royal Arsenal armaments works where the club began."),
    (2, "Which club's badge is a bee?", ["Brentford", "Barnet", "Watford", "Burnley"], 0, "Brentford. Red and white stripes, and a bee."),
    (2, "Which club's badge shows an eagle perched on a football?", ["Crystal Palace", "Brighton", "Bournemouth", "Coventry"], 0, "Crystal Palace, above a drawing of the original glass palace the club is named after."),
    (2, "Craven Cottage is the home of which club?", ["Chelsea", "Fulham", "Brentford", "QPR"], 1, "Fulham, on the Thames. Oldest professional football ground in London."),
    (2, "The City Ground is the home of which club?", ["Manchester City", "Nottingham Forest", "Coventry", "Bristol City"], 1, "Nottingham Forest, on the banks of the River Trent."),
    (2, "Which club plays at the Stadium of Light?", ["Benfica", "Sunderland", "Newcastle", "Everton"], 1, "Sunderland, since 1997. Benfica's ground in Lisbon has the same name."),
    (2, "Elland Road is the home of which club?", ["Leeds United", "Sheffield United", "Huddersfield", "Bradford"], 0, "Leeds United, since 1919. Famous for its noise."),
    (1, "The Vitality Stadium is the home of which club?", ["AFC Bournemouth", "Brighton", "Southampton", "Portsmouth"], 0, "Bournemouth. Its old name is Dean Court; it holds barely 11,000."),
    (2, "Which club plays at the ground known as the Amex?", ["Brighton & Hove Albion", "Bournemouth", "Brentford", "Burnley"], 0, "Brighton, at Falmer, on the edge of the South Downs."),
    (3, "Which club's badge shows a ship above three diagonal stripes for the city's rivers?", ["Liverpool", "Manchester City", "Sunderland", "Hull City"], 1, "Manchester City. The ship is for trade on the Manchester Ship Canal, with a red rose for Lancashire."),
    (2, "Portman Road is the home of which club?", ["Norwich", "Ipswich Town", "Colchester", "Southend"], 1, "Ipswich Town, since 1884."),
    (2, "Selhurst Park is the home of which club?", ["Crystal Palace", "Charlton", "Millwall", "Wimbledon"], 0, "Crystal Palace, in South London. Wimbledon and Charlton have both shared it."),
    (3, "The Gtech Community Stadium is the home of which club?", ["Brentford", "Barnet", "Watford", "Wycombe"], 0, "Brentford, since 2020, replacing Griffin Park, the ground with a pub on every corner."),
    (3, "Which club plays at the MKM Stadium?", ["Milton Keynes Dons", "Hull City", "Middlesbrough", "Millwall"], 1, "Hull City, since 2002. It was the KC Stadium before a sponsor changed its name."),
    (2, "Which club's badge features a tree?", ["Nottingham Forest", "Norwich", "Leeds", "Sherwood Rangers"], 0, "Nottingham Forest. A tree with wavy lines for the River Trent, designed by a fan in 1973."),
    (3, "Which club's badge has a white rose above the shield?", ["Leeds United", "Lancaster", "Manchester United", "York City"], 0, "Leeds United. The white rose of Yorkshire."),
    (2, "Which ground is nicknamed the Theatre of Dreams?", ["Wembley", "Old Trafford", "Anfield", "The Emirates"], 1, "Old Trafford. Bobby Charlton coined it."),
    (1, "Where do England play their home matches?", ["Old Trafford", "Wembley", "The Emirates", "Villa Park"], 1, "Wembley, in north-west London. The arch is visible from across the city."),
]

PACKS = [
    ("the-basics", "The Basics", BASICS),
    ("legends", "Legends", LEGENDS),
    ("clubs-rivalries", "Clubs & Rivalries", CLUBS_RIVALRIES),
    ("badges-grounds", "Badges & Grounds", BADGES_GROUNDS),
]
